table Formules

	measure Orderbedrag = ```
			
			    SUM('Project eenmalige orderregels'[TotaalRegelbedrag Excl. BTW])
			
			
			```
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Eenmalige orders

		annotation PBI_FormatHint = {"currencyCulture":"nl-NL"}

	measure 'Definitieve kostprijs' = ```
			
			var result = 
			CALCULATE(
			    SUM('Project kosten en geboekte uren'[Kostprijs]),
			    'Project kosten en geboekte uren'[Kostenstatus] = "Definitief"
			)
			
			return
			    result
			
			
			
			```
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

		annotation PBI_FormatHint = {"currencyCulture":"nl-NL"}

	measure 'Onverwerkte verrekenprijs' = ```
			
			CALCULATE(
			    SUM('Project kosten en geboekte uren'[Verrekenprijs]),
			    'Project kosten en geboekte uren'[Kostenstatus] = "Nog te verwachten"
			)
			
			
			```
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

		annotation PBI_FormatHint = {"currencyCulture":"nl-NL"}

	measure 'Totaal kosten (verrekenprijs onverwerkt, kostprijs definitief)' = ```
			
			[Definitieve kostprijs]+[Onverwerkte verrekenprijs]
			
			```
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

		annotation PBI_FormatHint = {"currencyCulture":"nl-NL"}

	measure 'Project omzet' =
			
			var result=
			CALCULATE(
			    SUM('Project omzet'[Bedrag])
			    ,'Project omzet'[Opbrengststatus] = "Definitief"
			)
			
			
			return
			    result
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project omzet

		annotation PBI_FormatHint = {"currencyCulture":"nl-NL"}

	measure 'Projectgebonden uren' =
			
			CALCULATE(
			    SUM('Project kosten en geboekte uren'[Aantal])
			     ,'NR - Taakgroepen DQ'[Taakgroep] = "Projectgebonden"
			)
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid

	measure 'Montage uren' = ```
			
			VAR werkuren_urenstaat =
			    CALCULATE(
			    SUM('Project kosten en geboekte uren'[Aantal])
			    ,'NR - Taakgroepen DQ'[Taakgroep] = "Montage"
			)
			
			VAR result = werkuren_urenstaat 
			
			RETURN
			result
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid

	measure 'Definitieve kostprijs arbeid' =
			
			CALCULATE(
			    SUM('Project kosten en geboekte uren'[Kostprijs])
			    ,'Project kosten en geboekte uren'[Kostenstatus] = "Definitief"
			    ,Kostensoorten[Categorie] = "Arbeid"
			)
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

		annotation PBI_FormatHint = {"currencyCulture":"nl-NL"}

	measure 'Projectgebonden uren NOT BLANK' =
			
			IF(
			    ISBLANK([Projectgebonden uren]),
			    "-",
			    [Projectgebonden uren]
			)
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid

	measure 'Totale kosten cum. (verrekenprijs onverwerkt, kostprijs definitief)' = ```
			
			CALCULATE (
			    SUM ( 'Project kosten en geboekte uren'[Kostprijs] ),
			    FILTER (
			        ALL ( 'Kalender'[Datum]),
			        'Kalender'[Datum] <= MAX ( 'Kalender'[Datum] )
			    )
			)
			
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

	measure 'Project omzet cum.' = ```
			
			CALCULATE(
			    SUM( 'Project omzet'[Bedrag] ),
			    FILTER( ALL( 'Kalender'[Datum] ), 'Kalender'[Datum] <= MAX( 'Kalender'[Datum] ) )
			    , 'Project omzet'[Opbrengststatus] = "Definitief"
			)
			
			
			```
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project omzet

		annotation PBI_FormatHint = {"currencyCulture":"nl-NL"}

	measure 'Orderbedrag Niet gefactureerd' = ```
			
			    Sum('Project eenmalige orderregels'[Nog te factureren excl. BTW])
			```
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Eenmalige orders

		annotation PBI_FormatHint = {"currencyCulture":"nl-NL"}

	measure 'Project resultaat' = [Project omzet]-[Definitieve kostprijs]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat

	measure 'Project marge' = ```
			
			 DIVIDE([Project resultaat],[Project omzet])
			```
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Ratios

	measure 'Montage uren cumulatief' = ```
			
			CALCULATE (
			    SUM('Project kosten en geboekte uren'[Aantal])
			    ,'NR - Taakgroepen DQ'[Taakgroep] = "Montage"
			    ,FILTER (
			        ALL ( 'Kalender'[Datum]),
			        'Kalender'[Datum] <= MAX ( 'Kalender'[Datum] )
			    )
			)
			
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Projectgebonden uren cumulatief' = ```
			
			CALCULATE (
			    [Projectgebonden uren],
			    FILTER (
			        ALL ( 'Kalender'[Datum]),
			        'Kalender'[Datum] <= MAX ( 'Kalender'[Datum] )
			    )
			)
			
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Hoofdproject Einddatum' = ```
			
			    CALCULATE(
			        FIRSTDATE(Projecten[Einddatum]),
			        Projecten[Niveau] = 1
			    )
			```
		formatString: Short Date
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectselectie

	measure 'Hoofdproject Startdatum' = ```
			
			    CALCULATE(
			        FIRSTDATE(Projecten[Startdatum]),
			        Projecten[Niveau] = 1
			    )
			```
		formatString: Short Date
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectselectie

	measure 'Eerste boekdatum' = ```
			
			    // startdatum op basis van eerste kosten en/of opbrengsten
			    if(
			        MIN ('Project kosten en geboekte uren'[Boekdatum]) > MIN ('Project omzet'[Boekdatum]),
			        MIN ('Project kosten en geboekte uren'[Boekdatum]),
			        MIN ('Project omzet'[Boekdatum])
			        )
			
			```
		formatString: General Date
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Meldingen

	measure 'Laatste boekdatum' = ```
			
			    // einddatum op basis van laatste kosten en/of opbrengsten
			   MAX(Kalender[Datum])
			
			```
		formatString: Short Date
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Meldingen

	measure projectduur = ```
			
			    DATEDIFF([Hoofdproject Startdatum],[Hoofdproject Einddatum],DAY)
			```
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Meldingen

	measure 'Werkelijke duur %' =
			
			// Werkelijke duur % ten opzichte van de projectduur.
			    DIVIDE([Werkelijke duur],[projectduur])
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Ratios

	measure 'Werkelijke duur' =
			
			DATEDIFF([Hoofdproject Startdatum],Today(),DAY)
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Ratios

	measure 'Onverwerkte verrekenprijs inkoop' = ```
			
			CALCULATE(
			    SUM('Project kosten en geboekte uren'[Verrekenprijs])
			    ,'Project kosten en geboekte uren'[Kostenstatus] = "Nog te verwachten"
			    , Kostensoorten[Categorie] <> "Arbeid"
			)
			
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

	measure 'Totale uren cumulatief' = ```
			
			CALCULATE (
			    SUM('Geboekte uren'[Aantal])
			    ,'Geboekte uren'[verlofsaldoboeking] = "Nee"
			    ,FILTER (
			        ALL ( 'Kalender'[Datum]),
			        'Kalender'[Datum] <= MAX ( 'Kalender'[Datum] )
			    )
			)
			
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Gerealiseerde uren

	measure 'Nog te facturen (te laat)' = ```
			
			    CALCULATE(
			        SUM('Project eenmalige orderregels'[Nog te factureren excl. BTW])
			        ,'Project eenmalige orderregels'[FactureerDatum]<TODAY()
			    )
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project omzet

	measure 'Nog te factureren (komende 7 dagen)' = ```
			
			var NTF =
			  CALCULATE(
			        SUM('Project eenmalige orderregels'[Nog te factureren excl. BTW])
			        ,'Project eenmalige orderregels'[FactureerDatum]>=today() && 'Project eenmalige orderregels'[FactureerDatum] <= TODAY()+7
			    )
			return
			IF(
			    NOT(ISBLANK([Orderbedrag]))
			    ,IF(
			        ISBLANK(NTF)
			        ,0
			        ,NTF
			        )
			    ,BLANK()
			)        
			
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project omzet

	measure 'Nog te factureren (toekomstig)' = ```
			
			var NTF =
			  CALCULATE(
			        SUM('Project eenmalige orderregels'[Nog te factureren excl. BTW])
			        ,'Project eenmalige orderregels'[FactureerDatum]>today()+7
			    )
			return
			IF(
			    NOT(ISBLANK([Orderbedrag]))
			    ,IF(
			        ISBLANK(NTF)
			        ,0
			        ,NTF
			        )
			    ,BLANK()
			)        
			
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project omzet

	measure 'Onverwerkte opbrengstregels via orders' =
			
			SUM('Project eenmalige orderregels'[Opbrengst nog te verwachten])
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project omzet

	measure 'Prognose factureerdatum' = ```
			
			 IF (
			        HASONEVALUE('Project eenmalige orderregels'[OrderregelKey])
			        ,MIN('Project eenmalige orderregels'[Factureerdatum])
			 )
			```
		formatString: dd-mm-yy
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Nog te factureren - Totaal' = ```
			
			    sum('Project eenmalige orderregels'[Nog te factureren excl. BTW])
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project omzet

	measure 'Onverwerkte opbrengstregels' =
			
			CALCULATE(
			    SUM('Project omzet'[Bedrag])
			    ,'Project omzet'[Opbrengststatus] = "Nog te verwachten"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project omzet

	measure 'Geselecteerd hoofdproject' =
			
			SELECTEDVALUE(Projecten[Hoofdproject]
			    ,"LET OP: Selecteer één hoofdproject op tabblad Projectselectie!")
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectselectie

		changedProperty = IsHidden

	measure 'Project resultaat incl. kosten in bestelling' = ```
			
			    [Project omzet]-[Definitieve kostprijs]-[Onverwerkte verrekenprijs inkoop]
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat

	measure 'Huidige gebruiker' =
			
			USERPRINCIPALNAME()
		displayFolder: 1. Semantisch model\1.99 Overig\Algemeen

		changedProperty = IsHidden

	measure 'Calculatie montage uren' = ```
			
			          CALCULATE(
			            SUM('Calculatie kostenregels'[Aantal])
			            ,NOT(ISBLANK('Calculatie kostenregels'[TaakKey]))
			            //,'NR - DirecteTaken'[ProjectTaakType] = "Montage"
			            ,'NR - Taakgroepen DQ'[Taakgroep] = "Montage"
			            ,'Calculatie kostenregels'[Calculatiestatus] = "Opdracht"
			            )   
			```
		formatString: #,##0.0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Calculatie kostprijs inkoop' =
			
			CALCULATE(
			    SUM('Calculatie kostenregels'[Kostprijs])
			    ,Kostensoorten[Categorie] <> "Arbeid"
			    ,'Calculatie kostenregels'[Calculatiestatus] = "Opdracht"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie

	measure 'Calculatie montage uren NOT BLANK' =
			
			IF(
			    ISBLANK([Calculatie montage uren])
			    ,0
			    ,[Calculatie montage uren]
			)
		formatString: #,##0.0
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Calculatie kostprijs inkoop NOT BLANK' = ```
			
			var kostprijs_inkoop =
			CALCULATE(
			    SUM('Calculatie kostenregels'[Kostprijs])
			    ,ISBLANK('Calculatie kostenregels'[TaakKey])
			)
			return  
			IF(
			    ISBLANK(kostprijs_inkoop)
			    ,0
			    ,kostprijs_inkoop
			)
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie

		changedProperty = IsHidden

	measure 'verrekenprijs inkoop NOT BLANK' =
			
			var verrekenprijs_inkoop =
			    CALCULATE(
			        SUM('Project kosten en geboekte uren'[Verrekenprijs]),
			        Kostensoorten[Categorie] <> "Arbeid"
			        )
			return
			IF(
			    isblank(verrekenprijs_inkoop)
			    ,0
			    ,verrekenprijs_inkoop
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

	measure 'kostprijs inkoop NOT BLANK' =
			
			var kostprijs_inkoop =
			    CALCULATE(
			        SUM('Project kosten en geboekte uren'[Kostprijs]),
			        Kostensoorten[Categorie] <> "Arbeid"
			        )
			return
			IF(
			    isblank(kostprijs_inkoop)
			    ,0
			    ,kostprijs_inkoop
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

	measure 'Definitieve kostprijs inkoop' =
			
			CALCULATE(
			    SUM('Project kosten en geboekte uren'[Kostprijs])
			    ,'Project kosten en geboekte uren'[Kostenstatus] = "Definitief"
			    , Kostensoorten[Categorie] <> "Arbeid"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

	measure 'Totale kosten inkoop (verrekenprijs onverwerkt, kostprijs definitief)' =
			
			[Onverwerkte verrekenprijs inkoop] + [Definitieve kostprijs inkoop]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

	measure 'Totale kosten inkoop cum. (verrekenprijs onverwerkt, kostprijs definitief)' =
			
			CALCULATE (
			    [Totale kosten inkoop (verrekenprijs onverwerkt, kostprijs definitief)],
			    FILTER (
			        ALL ( 'Kalender'[Datum]),
			        'Kalender'[Datum] <= MAX ( 'Kalender'[Datum] )
			    )
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Calculatie projectgebonden uren cum.' = ```
			
			CALCULATE (
			        [Calculatie projectgebonden uren],
			        FILTER (
			            ALL ( 'Kalender'[Datum]),
			            'Kalender'[Datum] <= MAX ( 'Kalender'[Datum] )
			        )
			    )
			
			```
		formatString: #,##0.0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Projectfase = ```
			VAR __projectniveau =
			 CALCULATE(
			    MIN( Projecten[Niveau] )
			    , ALLEXCEPT( Projecten,Projecten[Hoofdproject],Projecten[Niveau 2 Project],Projecten[Niveau 3 Project] )
			)
			
			VAR __inscope= 
			     ISINSCOPE(Projecten[Hoofdproject])
			     
			VAR result =
			    IF(
			    __inscope
			    , SWITCH(
			        __projectniveau
			        , 1, MAX( Projecten[Hoofdprojectfase] )
			        , 2, MAX( Projecten[Niveau 2 projectfase] )
			        , 3, MAX( Projecten[Niveau 3 projectfase] )
			        , BLANK()
			    )
			)
			
			RETURN 
			    result
			```
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectselectie

		changedProperty = IsHidden

	measure Projectstatus = ```
			VAR __projectniveau =
			 CALCULATE(
			    MIN( Projecten[Niveau] )
			    , ALLEXCEPT( Projecten,Projecten[Hoofdproject],Projecten[Niveau 2 Project],Projecten[Niveau 3 Project] )
			)
			
			VAR __inscope= 
			     ISINSCOPE(Projecten[Hoofdproject])
			
			VAR result =
			IF(
			    __inscope
			    , SWITCH(
			        __projectniveau
			        , 1, MAX( Projecten[Hoofdprojectstatus] )
			        , 2, MAX( Projecten[Niveau 2 projectstatus] )
			        , 3, MAX( Projecten[Niveau 3 projectstatus] )
			        , BLANK()
			    )
			)
			
			RETURN
			    result
			```
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectselectie

		changedProperty = IsHidden

	measure Factureerwijze =
			
			IF(
			    MIN(Projecten[Niveau])=1
			    ,MAX(Projecten[Hoofdproject factureerwijze])
			    ,IF(
			        MIN(Projecten[Niveau])=2
			        ,max(Projecten[Niveau 2 factureerwijze])
			        ,blank()
			    )
			)
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Meldingen

		changedProperty = IsHidden

	measure 'Calculatie kostprijs NOT BLANK' =
			
			var kostprijs =
			CALCULATE(
			    SUM('Calculatie kostenregels'[Kostprijs])
			)
			return
			IF(
			    ISBLANK(kostprijs)
			    ,0
			    ,kostprijs)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie

		changedProperty = IsHidden

	measure 'Calculatie projectgebonden uren NOT BLANK' =
			
			if(
			    ISBLANK([Calculatie projectgebonden uren])
			    ,0
			    ,[Calculatie projectgebonden uren])
		formatString: #,##0.0
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Gerealiseerde marge incl ontverwerkte kosten' = ```
			
			 DIVIDE([Project resultaat incl. kosten in bestelling],[Project omzet])
			```
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat

	measure 'Budget resultaat' = ```
			VAR _budgetresultaat =
			[Budget omzet o.b.v. methode budgetomzet]-[Calculatie kostprijs]
			
			VAR _budgetresultaat_generieke_marge =
			[Budget omzet o.b.v. methode budgetomzet]*[Generieke marge geselecteerd]
			 
			VAR Result = 
			IF(
			   [Methode ID verwachte marge geselecteerd] = 1
			   ,_budgetresultaat
			   ,_budgetresultaat_generieke_marge
			)
			
			RETURN
			    result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Budget

	measure 'Budget marge' = ```
			VAR _budgetrendement= DIVIDE([Budget resultaat],[Budget omzet o.b.v. methode budgetomzet],0)
			VAR _budgetrendement_generieke__marge = [Generieke marge geselecteerd]
			
			VAR Result = 
			IF(
			   [Methode ID verwachte marge geselecteerd] = 1
			   ,_budgetrendement
			   ,_budgetrendement_generieke__marge
			)
			
			RETURN
			    result
			
			```
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Budget

	measure logo = ```
			//Voor gebruiker demo@bisqq.nl
			var hier_uw_logo=
			    CALCULATE(
			        MAX('NR  - StandaardLogos'[Logo])
			        ,'NR  - StandaardLogos'[LogoKey] = 103)
			
			/*Logo wordt voor klant via instellingen App ingeladen in notificaRAAS database en daarna naar klant DWH overgehaald.*/ 
			var App_logo_basis =
			CALCULATE(
			    MAX( 'NR - LogoPerAdministratie DQ'[Logo] )
			    ,'NR - LogoPerAdministratie DQ'[Basislogo_JN]="J"
			)
			
			var App_logo_administratie = 
			   CALCULATE( 
			     MAX( 'NR - LogoPerAdministratie DQ'[Logo] )
			    ,'NR - LogoPerAdministratie DQ'[UniekeAdministratieID]=SELECTEDVALUE(Administraties[UniekeAdministratieID])
			   )
			
			var App_logo_tussenstap=
			IF(
			    count(administraties[Administratie])=1
			    ,If(
			        ISBLANK(App_logo_administratie)
			        ,App_logo_basis
			        ,App_logo_administratie )
			    ,App_logo_basis
			)
			var App_logo = /*Als er geen logo is toegevoegd dan wordt er standaard naar [hier_uw_logo] verwezen. */
			IF(
			    ISBLANK(App_logo_tussenstap)
			    ,hier_uw_logo
			    ,App_logo_tussenstap)
			
			VAR result =
			IF(
			    USERPRINCIPALNAME()="demo@bisqq.nl"
			    ,hier_uw_logo
			    ,App_logo
			)
			
			Return
			    result
			
			
			```
		displayFolder: 1. Semantisch model\1.99 Overig\Algemeen
		dataCategory: ImageUrl

		changedProperty = IsHidden

	measure 'Verschil calculatie - realisatie' = [Calculatie kostprijs] - [Definitieve kostprijs]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat

	measure 'Calculatie uren' = ```
			
			          CALCULATE(
			            SUM('Calculatie kostenregels'[Aantal])
			            ,NOT(ISBLANK('Calculatie kostenregels'[TaakKey]))
			            ,'Calculatie kostenregels'[Calculatiestatus] = "Opdracht"
			            )   
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Verschil calculatie - realisatie uren' =
			
			[Calculatie uren] - [Gerealiseerde uren]
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Debet = ```
			
			sum(Journaalregels[Debetbedrag])
			
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual

		changedProperty = IsHidden

	measure Credit = ```
			
			sum(Journaalregels[Creditbedrag])
			
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual

		changedProperty = IsHidden

	measure 'Verzoek Kosten' = ```
			
			VAR result = 
			CALCULATE(
			     SUM('NR - Projectbudgetverzoekregels DQ'[Kostprijs])
			    ,'NR - Projectbudgetverzoekregels DQ'[Categorie] <> "Omzet"
			    ,ALL(Kalender)
			) 
			    
			RETURN
			    result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budgetverzoek o.b.v. Budget Verzoek App

	measure 'Verzoek omzet' = ```
			
			VAR result = 
			CALCULATE(
			    SUM('NR - Projectbudgetverzoekregels DQ'[Kostprijs])
			    ,'NR - Projectbudgetverzoekregels DQ'[Categorie] = "Omzet"
			)
			
			RETURN
			    result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budgetverzoek o.b.v. Budget Verzoek App

	measure 'Verzoek projectgebonden uren' =
			
			VAR result =
			CALCULATE(
			    SUM('NR - Projectbudgetverzoekregels DQ'[AantalUur])
			    ,'NR - Taakgroepen DQ'[Taakgroep] = "Projectgebonden"
			)
			
			RETURN
			    result
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budgetverzoek o.b.v. Budget Verzoek App

	measure 'Verzoek projectgebonden uren NOT BLANK' =
			
			if(
			    ISBLANK([Verzoek projectgebonden uren])
			    ,0
			    ,[Verzoek projectgebonden uren])
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budgetverzoek o.b.v. Budget Verzoek App

	measure 'Verzoek uren' =
			
			VAR result =
			    SUM('NR - Projectbudgetverzoekregels DQ'[AantalUur])
			
			RETURN
			    result
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budgetverzoek o.b.v. Budget Verzoek App

	measure 'Verzoek montage uren' = ```
			
			VAR result =
			CALCULATE(
			     SUM('NR - Projectbudgetverzoekregels DQ'[AantalUur])
			     ,'NR - Taakgroepen DQ'[Taakgroep] = "Montage"
			)  
			
			RETURN
			    result
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budgetverzoek o.b.v. Budget Verzoek App

	measure 'Verzoek montage uren NOT BLANK' =
			
			IF(
			    ISBLANK([Verzoek montage uren])
			    ,0
			    ,[Verzoek montage uren]
			)
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budgetverzoek o.b.v. Budget Verzoek App

	measure 'Prognose kostprijs o.b.v. methode wachte marge' = ```
			VAR _prognosekosten = [Budget kostprijs o.b.v. geselecteerde verwachte marge] + [Verzoek Kosten]
			
			VAR _prognosekosten_generieke_marge = [Prognose omzet o.b.v. methode verwachte marge] - [Prognose resultaat] 
			
			
			VAR Result = 
			IF(
			   [Methode ID verwachte marge geselecteerd] = 1
			   ,_prognosekosten 
			   ,_prognosekosten_generieke_marge
			)
			
			
			return
			    result
			
			
			
			
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Prognose

	measure 'Prognose omzet o.b.v. methode verwachte marge' = ```
			
			VAR _prog_omzet = [Budget omzet o.b.v. methode budgetomzet]+ [Verzoek omzet]
			
			VAR _prog_omzet_generieke_marge =
			IF(
			    [Methode ID verwachte marge geselecteerd] = 3
			    , DIVIDE( [Definitieve kostprijs (t/m standdatum)], 1 - [Generieke marge geselecteerd] )
			    , IF(
			        ISBLANK( [Orderbedrag] )
			        , DIVIDE( [Definitieve kostprijs (t/m standdatum)], 1 - [Generieke marge geselecteerd] )
			        , [Orderbedrag]
			    )
			)    
			
			VAR Result = 
			IF(
			   [Methode ID verwachte marge geselecteerd] = 1
			   ,_prog_omzet 
			   ,_prog_omzet_generieke_marge
			)
			
			return
			   _prog_omzet 
			
			
			
			
			
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Prognose

	measure 'Prognose projectgebonden uren' = ```
			/*
			18-6-2023; impact van methode verwachte marge: Generieke marge vooralsnog onbekend. Nu alleen Budget omzet, budget kostprijs, budget resultaat en budget rendement aangepast. 
			*/
			[Budget projectgebonden uren] +[Verzoek projectgebonden uren]
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Prognose o.b.v. calculatiekostprijs en order

	measure 'Prognose montage uren' = [Budget montage uren]+[Verzoek montage uren]
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Prognose o.b.v. calculatiekostprijs en order

	measure 'Prognose projectbebonden uren NOT BLANK' =
			
			if(
			    ISBLANK([Prognose projectgebonden uren])
			    ,0
			    ,[Prognose projectgebonden uren])
		formatString: 0
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Prognose o.b.v. calculatiekostprijs en order

	measure 'Prognose montage uren NOT BLANK' =
			
			if(
			    ISBLANK([Prognose montage uren])
			    ,0
			    ,[Prognose montage uren])
		formatString: 0
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Prognose o.b.v. calculatiekostprijs en order

	measure 'Prognose kostprijs o.b.v. methode wachte marge NOT BLANK' =
			
			if(
			    ISBLANK([Prognose kostprijs o.b.v. methode wachte marge])
			    ,0
			    ,[Prognose kostprijs o.b.v. methode wachte marge])
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Prognose

	measure 'Prognose omzet o.b.v. methode verwachte marge NOT BLANK' =
			
			if(
			    ISBLANK([Prognose omzet o.b.v. methode verwachte marge])
			    ,0
			    ,[Prognose omzet o.b.v. methode verwachte marge])
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Prognose

	measure 'Prognose resultaat' = ```
			
			VAR _prognoseresultaat =
			[Prognose omzet o.b.v. methode verwachte marge] - ( [Budget kostprijs o.b.v. geselecteerde verwachte marge]+ [Verzoek Kosten] )
			
			VAR _prognoseresultaat_generieke_marge =
			[Prognose omzet o.b.v. methode verwachte marge]*[Generieke marge geselecteerd]
			 
			VAR Result = 
			IF(
			   [Methode ID verwachte marge geselecteerd] = 1
			   ,_prognoseresultaat 
			   ,_prognoseresultaat_generieke_marge
			)
			
			RETURN
			    _prognoseresultaat
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Prognose

	measure 'Prognose marge' = ```
			VAR _prognoserendement= DIVIDE([Prognose resultaat],[Prognose omzet o.b.v. methode verwachte marge],0)
			VAR _prognoserendement_generieke__marge = [Generieke marge geselecteerd]
			
			VAR Result = 
			IF(
			   [Methode ID verwachte marge geselecteerd] = 1
			   ,_prognoserendement
			   ,_prognoserendement_generieke__marge
			)
			
			RETURN
			   _prognoserendement
			```
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Prognose

	measure 'Aantal budgetverzoeken' = ```
			
			VAR result =
			
			    COUNT( 'NR - Projectbudgetverzoeken DQ'[BudgetverzoekKey] )
			 
			RETURN
			    result
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budgetverzoek o.b.v. Budget Verzoek App

	measure 'Budget handhaven' =
			
			IF(
			    ISINSCOPE('NR - Projectbudgetverzoeken DQ'[BudgetverzoekKey])
			    ,IF(
			        MIN('NR - Projectbudgetverzoeken DQ'[Budget_handhaven_JN])= "J"
			        ,"Ja"
			        ,IF(
			            MIN('NR - Projectbudgetverzoeken DQ'[Budget_handhaven_JN])= "N"
			            ,"Nee"
			            ,blank()
			        )
			    )
			    ,blank()
			)
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Meldingen

		changedProperty = IsHidden

	measure 'melding 1 hoofdproject selecteren' =
			
			IF(
			    ISBLANK(SELECTEDVALUE(Projecten[Hoofdproject]))
			    ,1
			    ,0
			    )
		formatString: 0
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectselectie

		changedProperty = IsHidden

	measure 'Aantal budgetverzoeken voor handhaven budget' = ```
			
			VAR result =    
			CALCULATE(
			    COUNT('NR - Projectbudgetverzoeken DQ'[BudgetverzoekKey])
			    ,'NR - Projectbudgetverzoeken DQ'[Budget_handhaven_JN] = "J"
			)  
			
			
			RETURN
			    result
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budgetverzoek o.b.v. Budget Verzoek App

	measure 'Ouderdom laatste budgetverzoek' = DATEDIFF([laatste budgetverzoek],TODAY(),DAY)
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budgetverzoek o.b.v. Budget Verzoek App

	measure KlantnummerDWH = max('1_klantnummer'[1_klantnummer])
		formatString: 0
		displayFolder: 1. Semantisch model\1.99 Overig\Algemeen

		changedProperty = FormatString

		changedProperty = IsHidden

	measure Opdrachtgever = ```
			VAR __projectniveau =
			 CALCULATE(
			    MIN( Projecten[Niveau] )
			    , ALLEXCEPT( Projecten,Projecten[Hoofdproject],Projecten[Niveau 2 Project],Projecten[Niveau 3 Project] )
			)
			
			VAR __inscope= 
			     ISINSCOPE(Projecten[Hoofdproject])
			
			VAR result =
			IF(
			    __inscope
			    , SWITCH(
			        __projectniveau
			        , 1, MAX( Projecten[Hoofdproject opdrachtgever] )
			        , 2, MAX( Projecten[Niveau 2 opdrachtgever] )
			        , 3, MAX( Projecten[Niveau 3 opdrachtgever] )
			        , BLANK()
			    )
			    ,blank()
			)
			
			RETURN 
			    result
			```
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectselectie

		changedProperty = DisplayFolder

	measure Projectleider = ```
			VAR __projectniveau =
			 CALCULATE(
			    MIN( Projecten[Niveau] )
			    , ALLEXCEPT( Projecten,Projecten[Hoofdproject],Projecten[Niveau 2 Project],Projecten[Niveau 3 Project] )
			)
			
			VAR __inscope= 
			     ISINSCOPE(Projecten[Hoofdproject])
			
			VAR result =
			IF(
			    __inscope
			    ,SWITCH(
			        __projectniveau
			        , 1, MAX( Projecten[Hoofdproject projectleider] )
			        , 2, MAX( Projecten[Niveau 2 projectleider] )
			        , 3, MAX( Projecten[Niveau 3 projectleider] )
			        , BLANK()
			    )
			)
			
			RETURN 
			    result
			```
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectselectie

		changedProperty = DisplayFolder

	measure 'Calculatie verkoopprijs' =
			
			CALCULATE(
			    SUM( 'Calculaties met verkoopprijzen'[Verkoopprijs incl. staart] )
			    ,'Calculaties met verkoopprijzen'[Calculatiestatus] = "Opdracht"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie

	measure 'Toegevoegde Waarde op calculatie (TWC)' = ```
			[Calculatie omzet]-[Calculatie verrekenprijs exclusief arbeid]
			   
			
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Toegevoegde waarde

	measure 'Calculatie verrekenprijs exclusief arbeid' =
			CALCULATE(
			    SUM( 'Calculatie kostenregels'[Verrekenprijs] ),
			    'Calculatie kostenregels'[Calculatiestatus] = "Opdracht"
			    ,ISBLANK('Calculatie kostenregels'[TaakKey])
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie

	measure 'Toegevoegde Waarde op calculatie per uur (TWC\u)' = ```
			VAR TWCu =
			DIVIDE([Toegevoegde Waarde op calculatie (TWC)],[Calculatie montage uren])
			
			VAR TWC_hoofdproject =
			SUMX(
			    SUMMARIZE('Projecten'
			        ,'Projecten'[Hoofdproject]
			        ,"x", 
			            IF(
			                ISBLANK( [Calculatie montage uren] )
			                , 0
			                , [Toegevoegde Waarde op calculatie (TWC)]
			            )
			            ),[x]
			)
			VAR cal_werkuren_hoofdproject =
			SUMX(
			    SUMMARIZE('Projecten'
			        ,'Projecten'[Hoofdproject]
			        ,"y", 
			            IF(
			                ISBLANK( [Calculatie montage uren] )
			                , 0
			                , [Calculatie montage uren]
			            )
			            ),[y]
			)
			
			VAR TWCu_per_project = DIVIDE( TWC_hoofdproject, cal_werkuren_hoofdproject )
			
			VAR result = TWCu_per_project
			
			RETURN 
			result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Toegevoegde waarde

	measure 'Toegevoegde Waarde op Realisatie (TWR)' = ```
			
			CALCULATE(
			    [Project omzet] - [Verrekenprijs exclusief arbeid]
			)
			
			
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Toegevoegde waarde

	measure 'Verrekenprijs exclusief arbeid' =
			/*
			Verrekenprijs exclusief arbeid is in de basis de kostenregels zonder een taak. Echter uren van inleners die direct via inkoopfacturen worden geboekt moeten ook niet worden
			berekend. Het uren-aantal van deze regels wordt opgeteld bij de werkuren en de kosten ervan mogen daarom niet als inkoop worden beschouwd.
			
			Voorwaarde voor inleners via inkoopfacturen is dat 1) er een kostensoort [Arbeid] wordt gebruikt en 2) de eenheid [u/Uur]
			met internationale code 570410.
			
			*/
			VAR verrekenprijs_met_inleen =
			CALCULATE(
			    SUM('Project kosten en geboekte uren'[Verrekenprijs] )
			    ,ISBLANK('Project kosten en geboekte uren'[TaakKey])
			)
			
			VAR verrekenprijs_inleners =
			CALCULATE(
			    SUM('Project kosten en geboekte uren'[Verrekenprijs])
			    ,'Kostensoorten'[Categorie] = "Arbeid"
			    ,'Project kosten en geboekte uren'[Kostenbron] = "Inkoop"
			    --,'Kosten'[Kostenstatus] = "Definitief"
			    ,'Project kosten en geboekte uren'[internationale code] = "570410"
			)
			
			VAR result = verrekenprijs_met_inleen - verrekenprijs_inleners
			
			
			RETURN
			result
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Toegevoegde waarde

	measure 'Toegevoegde Waarde op realisatie per montage uur (TWR\u, zonder datumfilter)' = ```
			
			VAR TWR_hoofdproject =
			SUMX(
			    SUMMARIZE('Projecten'
			        ,'Projecten'[Hoofdproject]
			        ,"x", 
			            IF(
			                ISBLANK( [Montage uren zonder datumfilter]+[Inleenuren via inkoop zonder datumfilter] )
			                , 0
			                , [Toegevoegde Waarde op Realisatie (TWR)]
			            )
			            ),[x]
			)
			VAR werkuren_hoofdproject =
			SUMX(
			    SUMMARIZE('Projecten'
			        ,'Projecten'[Hoofdproject]
			        ,"y", 
			            IF(
			                ISBLANK([Montage uren zonder datumfilter]+[Inleenuren via inkoop zonder datumfilter])
			                , 0
			                ,IF([Montage uren zonder datumfilter]+[Inleenuren via inkoop zonder datumfilter]   < 1
			                    ,0
			                    ,[Montage uren zonder datumfilter]+[Inleenuren via inkoop zonder datumfilter] 
			                )
			            )
			            ),[y]
			)
			
			VAR TWRu_per_project = DIVIDE( TWR_hoofdproject, werkuren_hoofdproject )
			
			VAR result = TWRu_per_project
			
			RETURN 
			result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Toegevoegde waarde\Zonder datumfilter

		changedProperty = FormatString

	measure 'Aantal actuele hoofdprojecten' =
			CALCULATE(
			    DISTINCTCOUNT(Projecten[HoofdProjectKey])
			    ,'Projecten'[Hoofdprojectstatus]="Actueel"
			)
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectselectie

	measure 'Calculatie montage uren TWC' = ```
			
			VAR Calc_werkuren =
			    CALCULATE(
			        SUM('Calculatie kostenregels'[Aantal])
			        ,NOT(ISBLANK('Calculatie kostenregels'[TaakKey]))
			        //,'NR - DirecteTaken'[ProjectTaakType] = "Montage"
			        ,'NR - Taakgroepen DQ'[Taakgroep] = "Montage"
			        ,'Calculatie kostenregels'[Calculatiestatus] = "Opdracht"
			        )   
			VAR result = Calc_werkuren
			RETURN
			result
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Toegevoegde waarde

	measure 'Calculatie omzet' = ```
			
			/*
			IF(
			    VALUE(MAX('Methode Omzet TWC'[ID])) = 1
			    ,[Orderbedrag]
			    ,[Calculatie verkoopprijs]
			)*/
			[Orderbedrag]
			
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Toegevoegde waarde

	measure 'Hoofdproject percentage gereed' =
			
			AVERAGE(Projecten[Hoofdproject percentage gereed])/100
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectselectie

	measure 'Onverwerkte verrekenprijs arbeid' = ```
			
			CALCULATE(
			    SUM('Project kosten en geboekte uren'[Verrekenprijs])
			    ,'Project kosten en geboekte uren'[Kostenstatus] = "Nog te verwachten"
			    ,Kostensoorten[Categorie] = "Arbeid"
			)
			
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

	measure 'calculatie kostprijs inkoop cum.' = ```
			
			CALCULATE (
			    [Calculatie kostprijs inkoop],
			    FILTER (
			        ALL ( 'Kalender'[Datum]),
			        'Kalender'[Datum] <= MAX ( 'Kalender'[Datum] )
			    )
			)
			
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Betreft alle creditboekigen op doorbelasting rubrieken van het type "Winst & Verlies". Doorbelasting boekingen zijn niet projectgebonden.
	measure 'Doorbelasting projectkosten' = ```
			
			CALCULATE(
			    SUM(Journaalregels[Creditbedrag])
			    ,Rubrieken[Type] = "W"
			    ,'Rubrieken'[Toepassing] = "Doorbelasting OHW"
			    ,'Journaalregels'[BoxNummer] = "2"
			)
			
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Projectjournalisering zonder projectrelatie\Enterprise

		changedProperty = DisplayFolder

		changedProperty = IsHidden

	/// Betreft alle debetboekigen op doorbelastingrubrieken van het type "Winst & Verlies". Doorbelasting boekingen zijn niet projectgebonden.
	measure 'Doorbelasting projectopbrengsten' = ```
			
			CALCULATE(
			    SUM(Journaalregels[Debetbedrag])
			    ,Rubrieken[Type] = "W"
			    ,'Rubrieken'[Toepassing] = "Doorbelasting OHW"
			    ,'Journaalregels'[BoxNummer] = "2" 
			)
			
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Projectjournalisering zonder projectrelatie\Enterprise

		changedProperty = DisplayFolder

		changedProperty = IsHidden

	measure 'Melding filter op projecten\meerdere boekjaren' =
			IF(
			    ISFILTERED('Projecten')
			    ,"LET OP: er is gefiltered op projecten en/of meerdere boekjaren."
			    ,""
			)
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Meldingen

		changedProperty = IsHidden

	measure 'filter op projecten' =
			IF(
			    ISFILTERED('Projecten')
			    ,1
			    ,0
			)
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectselectie

	measure 'Melding periode YTD' =
			
			"Periode: "
			&FORMAT(MIN('Kalender'[Datum]),"dd-mm-yyyy")
			&" t/m "
			&FORMAT(MAX('Kalender'[Datum]),"dd-mm-yyyy")
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Meldingen

		changedProperty = IsHidden

	/// Reservering van dekking t.b.v. overhead vanuit projectkosten. Betreft de werkelijke journaalregels; deze hebben geen verwijzing naar projecten.
	measure Dekkingen = ```
			
			VAR _debet = 
			 CALCULATE(
			    SUM(Journaalregels[Debetbedrag])
			    ,Rubrieken[Type] = "W"
			    ,'Journaalregels'[BoxNummer] = "2"
			    ,'Rubrieken'[Toepassing] = "Grootboek"
			)
			
			
			VAR _credit = 
			 CALCULATE(
			    SUM(Journaalregels[Creditbedrag])
			    ,Rubrieken[Type] = "W"
			    ,'Journaalregels'[BoxNummer] = "2"
			    ,'Rubrieken'[Toepassing] = "Grootboek"
			)
			
			VAR result = -_credit
			RETURN
			result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Projectjournalisering zonder projectrelatie\Enterprise

	/// [OHW eindstand]-[OHW beginstand]
	measure 'OHW mutatie in balans' = ```
			
			VAR _credit = 
			CALCULATE(
			    SUM('Project journaalregels'[bedrag] )
			    ,'Project journaalregels'[Debet/Credit] = "C"
			    ,Rubrieken[Type] = "B"
			    ,'Rubrieken'[Toepassing]="Doorbelasting OHW"
			    ,'Journaalregels'[BoxNummer] = "2"
			    ,Journaalregels[TypePeriode]<>"Openingsperiode"
			)
			
			VAR _debet = 
			CALCULATE(
			    SUM('Project journaalregels'[bedrag] )
			    ,'Project journaalregels'[Debet/Credit] = "D"
			    ,Rubrieken[Type] = "B"
			    ,'Rubrieken'[Toepassing]="Doorbelasting OHW"
			    ,'Journaalregels'[BoxNummer] = "2"
			    ,Journaalregels[TypePeriode]<>"Openingsperiode"
			
			)
			
			VAR result = _credit-_debet
			
			
			RETURN
			result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering

	measure 'Definitieve verrekenprijs' = ```
			
			CALCULATE(
			    SUM('Project kosten en geboekte uren'[Verrekenprijs])
			    ,'Project kosten en geboekte uren'[Kostenstatus] = "Definitief"
			)
			
			```
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

		annotation PBI_FormatHint = {"currencyCulture":"nl-NL"}

	/// Telt het aantal unieke Administraties.
	measure 'aantal geselecteerde administraties' =
			
			count(Administraties[AdministratieKey])
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Meldingen

	measure 'Verschil opbrengsten' = ```
			
			VAR _verschil = [Projectjournalisering opbrengsten]-[Project omzet]
			VAR result =
			 IF(
			     _verschil > - 1 && _verschil < 1
			     , BLANK()
			     , _verschil
			 )
			 
			 RETURN 
			     result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\aansluiting hoofd- en subadministratie

	measure 'Verschil kosten' = ```
			
			VAR _verschil = [Projectjournalisering kosten]-[Definitieve verrekenprijs]
			VAR result =
			 IF(
			     _verschil > - 1 && _verschil < 1
			     , BLANK()
			     , _verschil
			 )
			 
			 RETURN 
			     result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\aansluiting hoofd- en subadministratie

	measure 'Verschil totaal' = [Verschil kosten]+[Verschil opbrengsten]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\aansluiting hoofd- en subadministratie

	/// Doorbelasting van kosten en opbrengsten naar balans.
	measure 'OHW doorbelasting' = ```
			
			VAR _credit = 
			CALCULATE(
			    SUM('Project journaalregels'[bedrag] )
			    ,'Project journaalregels'[Debet/Credit] = "C"
			    --,Rubrieken[Type] = "B"
			    ,'Rubrieken'[Toepassing]="Doorbelasting OHW"
			    ,'Journaalregels'[BoxNummer] = "2"
			    ,Journaalregels[TypePeriode]<>"Openingsperiode"
			)
			
			VAR _debet = 
			CALCULATE(
			    SUM('Project journaalregels'[bedrag] )
			    ,'Project journaalregels'[Debet/Credit] = "D"
			    --,Rubrieken[Type] = "B"
			    ,'Rubrieken'[Toepassing]="Doorbelasting OHW"
			    ,'Journaalregels'[BoxNummer] = "2"
			    ,Journaalregels[TypePeriode]<>"Openingsperiode"
			
			)
			
			VAR result = _credit-_debet
			
			
			RETURN
			result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering

	measure 'Project resultaat historisch' = [Historische omzet (t/m standdatum)]-[Definitieve kostprijs (t/m standdatum)]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat

	measure 'Geselecteerde standdatum' = "Op basis van geselecteerde standdatum worden actuals tot en met "& FORMAT( MAX( 'Kalender standdatums'[Standdatum] ), "dd-mm-yyyy" )&" berekend en de forecast na "& FORMAT( MAX('Kalender standdatums'[Standdatum]), "dd-mm-yyyy" )
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Cashflow forecast

	/// [%gefactureerd/budget omzet] - [%NC/ calculatie kosten]. Hiermee kan de voortgang van de facturatie t.o.v. gemaakte kosten worden bepaald. 
	measure 'Voortgang facturatie o.b.v. budget' = [POC omzet o.b.v. budget]-[POC kostprijs o.b.v. budget]
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat

	/// [%gefactureerd/prognose omzet] - [%NC/ calculatie kosten]. Hiermee kan de voortgang van de facturatie t.o.v. gemaakte kosten worden bepaald. 
	measure 'Voortgang facturatie o.b.v. prognose' = [POC omzet o.b.v. prognose]-[POC kostprijs o.b.v. prognose]
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat

	measure 'Budget kostprijs o.b.v. geselecteerde verwachte marge' = ```
			VAR _budgetkosten = [Calculatie kostprijs]
			
			VAR _budgetkosten_generieke_marge = [Budget omzet o.b.v. methode budgetomzet] - [Budget resultaat] 
			
			
			VAR Result = 
			IF(
			   [Methode ID verwachte marge geselecteerd] = 1
			   ,_budgetkosten 
			   ,_budgetkosten_generieke_marge
			)
			
			
			return
			   _budgetkosten 
			
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Budget

	measure 'Budget kostprijs inkoop' = ```
			/*
			18-6-2023; impact van methode verwachte marge: Generieke marge vooralsnog onbekend. Nu alleen Budget omzet, budget kostprijs, budget resultaat en budget rendement aangepast. 
			*/
			
			[Calculatie kostprijs inkoop]
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budget o.b.v. calculatiekostprijs en order

	measure 'Budget kostprijs inkoop cum.' = ```
			/*
			18-6-2023; impact van methode verwachte marge: Generieke marge vooralsnog onbekend. Nu alleen Budget omzet, budget kostprijs, budget resultaat en budget rendement aangepast. 
			*/
			
			[calculatie kostprijs inkoop cum.]
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budget o.b.v. calculatiekostprijs en order

	measure 'Budget montage uren' = ```
			/*
			18-6-2023; impact van methode verwachte marge: Generieke marge vooralsnog onbekend. Nu alleen Budget omzet, budget kostprijs, budget resultaat en budget rendement aangepast. 
			*/
			
			[Calculatie montage uren]
			```
		formatString: #,##0.0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budget o.b.v. calculatiekostprijs en order

	measure 'Budget montage uren cum.' = ```
			/*
			18-6-2023; impact van methode verwachte marge: Generieke marge vooralsnog onbekend. Nu alleen Budget omzet, budget kostprijs, budget resultaat en budget rendement aangepast. 
			*/
			
			[Calculatie montage uren cum.]
			```
		formatString: #,##0.0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budget o.b.v. calculatiekostprijs en order

	measure 'Budget projectgebonden uren' =
			
			[Calculatie projectgebonden uren]
		formatString: #,##0.0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budget o.b.v. calculatiekostprijs en order

	measure 'Budget projectgebonden uren cum.' = ```
			/*
			18-6-2023; impact van methode verwachte marge: Generieke marge vooralsnog onbekend. Nu alleen Budget omzet, budget kostprijs, budget resultaat en budget rendement aangepast. 
			*/
			
			[Calculatie projectgebonden uren cum.]
			```
		formatString: #,##0.0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budget o.b.v. calculatiekostprijs en order

	measure 'Budget uren' = [Calculatie uren]
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budget o.b.v. calculatiekostprijs en order

	measure 'Melding laatste verversdatum/-tijd' = "Laatste vernieuwing: "&FORMAT(MAX('Laatste verversdatum'[Date Last Refreshed]),"dd-MM-yyyy hh:MM")
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Meldingen

	measure 'Project marge historisch' = DIVIDE([Project resultaat historisch],[Historische omzet (t/m standdatum)])
		formatString: #,##0 %
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Ratios

	measure Projectsoort = ```
			VAR __projectniveau =
			 CALCULATE(
			    MIN( Projecten[Niveau] )
			    , ALLEXCEPT( Projecten,Projecten[Hoofdproject],Projecten[Niveau 2 Project],Projecten[Niveau 3 Project] )
			)
			
			VAR __inscope= 
			     ISINSCOPE(Projecten[Hoofdproject])
			
			VAR result =
			IF(
			    __inscope
			    , SWITCH(
			        __projectniveau
			        , 1, MAX( Projecten[Hoofdproject Soort] )
			        , 2, MAX( Projecten[Niveau 2 projectsoort] )
			        , 3, MAX( Projecten[Niveau 3 projectsoort] )
			        , BLANK()
			    )
			)
			
			RETURN 
			    result
			```
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectselectie

		changedProperty = IsHidden

	measure 'Test filter projecten' =
			CALCULATE(
			    MIN( Projecten[Niveau] )
			    , ALLEXCEPT( Projecten,Projecten[Hoofdproject],Projecten[Niveau 2 Project],Projecten[Niveau 3 Project] )
			)
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectselectie

	measure 'Service order' = ```
			SUM( 'Project service orders prognose'[Factureerbedrag excl. BTW] ) 
			+ 
			CALCULATE(
			    SUM( 'Project omzet'[Bedrag] )
			    ,'Project omzet'[projectsoort] = "Periodiek"
			)
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Periodieke orders

	measure 'Verzoek Kostprijs (kosten en omzet)' = ```
			
			VAR result =
			CALCULATE(
			     SUM('NR - Projectbudgetverzoekregels DQ'[Kostprijs])
			)     
			
			RETURN
			    result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budgetverzoek o.b.v. Budget Verzoek App

	measure 'Prognose uren' = ```
			/*
			18-6-2023; impact van methode verwachte marge: Generieke marge vooralsnog onbekend. Nu alleen Budget omzet, budget kostprijs, budget resultaat en budget rendement aangepast. 
			*/
			[Budget uren]+[Verzoek uren]
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Prognose o.b.v. calculatiekostprijs en order

	measure 'Prognose uren NOT BLANK' =
			
			if(
			    ISBLANK([Prognose uren])
			    ,0
			    ,[Prognose uren])
		formatString: 0
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Prognose o.b.v. calculatiekostprijs en order

	/// --Omschrijving--
	/// Gerealiseerde uren tot en met geselecteerde standdatum. 
	/// 
	/// LET OP; kan in combinatie met kalender tabel/filter ook gefilterd zijn.
	/// 
	/// 
	/// --DAX--
	/// CALCULATE(
	///     [Montage uren]
	///     ,'Geboekte Uren'[Arbeid uitvoeringsdatum]<=MAX('Standdatums'[standdatum])
	/// )
	measure 'Montage uren historisch' =
			
			CALCULATE(
			    [Montage uren]
			    ,'Project kosten en geboekte uren'[Arbeid uitvoeringsdatum]<=MAX(kalender[standdatum])
			)
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid

		annotation PBI_FormatHint = {"isDecimal":true}

	/// --Omschrijving--
	/// Gerealiseerde support uren tot en met geselecteerde standdatum. 
	/// 
	/// LET OP; kan in combinatie met kalender tabel/filter ook gefilterd zijn.
	/// 
	/// 
	/// --DAX--
	/// CALCULATE(
	///     [Supporturen]
	///     ,'Geboekte Uren'[Arbeid uitvoeringsdatum]<=MAX('Standdatums'[standdatum])
	/// )
	measure 'Projectgebonden uren historisch' =
			
			CALCULATE(
			    [Projectgebonden uren]
			    ,'Project kosten en geboekte uren'[Arbeid uitvoeringsdatum]<=MAX(kalender[standdatum])
			)
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Hide Visual' =
			IF(
			      1=2,
			      1,
			      0
			   )
		formatString: 0
		displayFolder: 1. Semantisch model\1.99 Overig\Algemeen

	measure 'Verzoek Kosten arbeid' = ```
			
			VAR result = 
			CALCULATE(
			     SUM('NR - Projectbudgetverzoekregels DQ'[Kostprijs])
			    ,'NR - Projectbudgetverzoekregels DQ'[Categorie] = "Arbeid"
			) 
			    
			RETURN
			    result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budgetverzoek o.b.v. Budget Verzoek App

	measure 'Verzoek Kosten inkoop' = ```
			
			VAR result = 
			CALCULATE(
			     SUM('NR - Projectbudgetverzoekregels DQ'[Kostprijs])
			    ,NOT( 'NR - Projectbudgetverzoekregels DQ'[Categorie] ) IN {"Omzet","Arbeid"}  
			) 
			    
			RETURN
			    result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budgetverzoek o.b.v. Budget Verzoek App

	measure 'Verzoek Kosten materiaal' = ```
			VAR result = 
			CALCULATE(
			     SUM('NR - Projectbudgetverzoekregels DQ'[Kostprijs])
			    ,'NR - Projectbudgetverzoekregels DQ'[Categorie] = "Materiaal"
			) 
			    
			RETURN
			    result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budgetverzoek o.b.v. Budget Verzoek App

	measure 'Verzoek Kosten materieel' = ```
			
			VAR result = 
			CALCULATE(
			     SUM('NR - Projectbudgetverzoekregels DQ'[Kostprijs])
			    ,'NR - Projectbudgetverzoekregels DQ'[Categorie] = "Materieel"
			) 
			    
			RETURN
			    result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budgetverzoek o.b.v. Budget Verzoek App

	measure 'Verzoek Kosten overig' = ```
			VAR result = 
			CALCULATE(
			     SUM('NR - Projectbudgetverzoekregels DQ'[Kostprijs])
			    ,'NR - Projectbudgetverzoekregels DQ'[Categorie] = "Overig"
			) 
			    
			RETURN
			    result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budgetverzoek o.b.v. Budget Verzoek App

	measure 'Calculatie kostprijs arbeid' =
			
			CALCULATE(
			    SUM('Calculatie kostenregels'[Kostprijs])
			    ,Kostensoorten[Categorie] = "Arbeid"
			    ,'Calculatie kostenregels'[Calculatiestatus] = "Opdracht"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie

	measure 'Calculatie kostprijs materiaal' =
			
			CALCULATE(
			    SUM('Calculatie kostenregels'[Kostprijs])
			    ,Kostensoorten[Categorie] = "Materiaal"
			    ,'Calculatie kostenregels'[Calculatiestatus] = "Opdracht"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie

	measure 'Calculatie kostprijs materieel' =
			
			CALCULATE(
			    SUM('Calculatie kostenregels'[Kostprijs])
			    ,Kostensoorten[Categorie] = "Materieel"
			    ,'Calculatie kostenregels'[Calculatiestatus] = "Opdracht"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie

	measure 'Calculatie kostprijs overig' =
			
			CALCULATE(
			    SUM('Calculatie kostenregels'[Kostprijs])
			    ,Kostensoorten[Categorie] = "Overig"
			    ,'Calculatie kostenregels'[Calculatiestatus] = "Opdracht"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie

	measure 'Budget kostprijs arbeid' = [Calculatie kostprijs arbeid]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budget o.b.v. calculatiekostprijs en order

	measure 'Budget kostprijs materiaal' = [Calculatie kostprijs materiaal]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budget o.b.v. calculatiekostprijs en order

	measure 'Budget kostprijs materieel' = [Calculatie kostprijs materieel]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budget o.b.v. calculatiekostprijs en order

	measure 'Budget kostprijs overig' = [Calculatie kostprijs overig]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budget o.b.v. calculatiekostprijs en order

	measure 'Prognose kostprijs arbeid' = [Budget kostprijs arbeid] + [Verzoek Kosten arbeid]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Prognose o.b.v. calculatiekostprijs en order

	measure 'Prognose kostprijs inkoop' = [Budget kostprijs inkoop] + [Verzoek Kosten inkoop]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Prognose o.b.v. calculatiekostprijs en order

	measure 'Prognose kostprijs materiaal' = [Budget kostprijs materiaal] + [Verzoek Kosten materiaal]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Prognose o.b.v. calculatiekostprijs en order

	measure 'Prognose kostprijs materieel' = [Budget kostprijs materieel] + [Verzoek Kosten materieel]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Prognose o.b.v. calculatiekostprijs en order

	measure 'Prognose kostprijs overig' = [Budget kostprijs overig] + [Verzoek Kosten overig]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Prognose o.b.v. calculatiekostprijs en order

	measure 'Definitieve kostprijs materiaal' =
			
			CALCULATE(
			    SUM('Project kosten en geboekte uren'[Kostprijs]),
			    'Project kosten en geboekte uren'[Kostenstatus] = "Definitief",
			    Kostensoorten[Categorie] = "Materiaal"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

	measure 'Definitieve kostprijs materieel' =
			
			CALCULATE(
			    SUM('Project kosten en geboekte uren'[Kostprijs]),
			    'Project kosten en geboekte uren'[Kostenstatus] = "Definitief",
			    Kostensoorten[Categorie] = "Materieel"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

	measure 'Definitieve kostprijs overig' =
			
			CALCULATE(
			    SUM('Project kosten en geboekte uren'[Kostprijs]),
			    'Project kosten en geboekte uren'[Kostenstatus] = "Definitief",
			    Kostensoorten[Categorie] = "Overig"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

	measure 'Toegevoegde Waarde op prognose (TWP)' = [Prognose omzet o.b.v. methode verwachte marge]-[Prognose kostprijs inkoop]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Toegevoegde waarde

	measure 'Toegevoegde Waarde op prognose per uur (TWP\u)' = ```
			
			VAR TWPu =
			DIVIDE([Toegevoegde Waarde op prognose (TWP)],[Prognose montage uren])
			
			VAR TWP_hoofdproject =
			SUMX(
			    SUMMARIZE('Projecten'
			        ,'Projecten'[Hoofdproject]
			        ,"x", 
			            IF(
			                ISBLANK( [Prognose montage uren] )
			                , 0
			                , [Toegevoegde Waarde op prognose (TWP)]
			            )
			            ),[x]
			)
			VAR prog_werkuren_hoofdproject =
			SUMX(
			    SUMMARIZE('Projecten'
			        ,'Projecten'[Hoofdproject]
			        ,"y", 
			            IF(
			                ISBLANK( [Prognose montage uren] )
			                , 0
			                , [Prognose montage uren]
			            )
			            ),[y]
			)
			
			VAR TWPu_per_project = DIVIDE( TWP_hoofdproject, prog_werkuren_hoofdproject )
			
			VAR result = TWPu_per_project
			
			RETURN 
			result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Toegevoegde waarde

	measure Startdatum = ```
			
			VAR __projectniveau =
			 CALCULATE(
			    MIN( Projecten[Niveau] )
			    , ALLEXCEPT( Projecten,Projecten[Hoofdproject],Projecten[Niveau 2 Project],Projecten[Niveau 3 Project] )
			)
			
			VAR __inscope= 
			     ISINSCOPE(Projecten[Hoofdproject])
			     
			VAR result =
			    IF(
			    __inscope
			    , SWITCH(
			        __projectniveau
			        , 1, MAX( Projecten[Hoofdproject startdatum] )
			        , 2, MAX( Projecten[Niveau 2 startdatum] )
			        , 3, MAX( Projecten[Niveau 3 startdatum] )
			        , BLANK()
			    )
			)
			
			RETURN 
			    result
			```
		formatString: dd-mm-yyyy
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectselectie

		changedProperty = IsHidden

	measure Einddatum = ```
			
			VAR __projectniveau =
			 CALCULATE(
			    MIN( Projecten[Niveau] )
			    , ALLEXCEPT( Projecten,Projecten[Hoofdproject],Projecten[Niveau 2 Project],Projecten[Niveau 3 Project] )
			)
			
			VAR __inscope= 
			     ISINSCOPE(Projecten[Hoofdproject])
			     
			VAR result =
			    IF(
			    __inscope
			    , SWITCH(
			        __projectniveau
			        , 1, MAX( Projecten[Hoofdproject einddatum] )
			        , 2, MAX( Projecten[Niveau 2 einddatum] )
			        , 3, MAX( Projecten[Niveau 3 einddatum] )
			        , BLANK()
			    )
			)
			
			RETURN 
			    result
			```
		formatString: dd-mm-yyyy
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectselectie

		changedProperty = IsHidden

	measure EBIT = ```
			
			VAR result = 
			    CALCULATE(
			      sum(Journaalregels[Creditbedrag])  - sum(Journaalregels[Debetbedrag])
			      ,'NR - CoA schema'[Code]<111001
			      ,Rubrieken[Type] = "W"
			    )
			
			RETURN
			    result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA rekeningschema

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Verschil opbrengsten - kosten eliminatie' = [Eliminatie opbrengsten]-[Eliminatie inkoopkosten]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Eliminatie posten

	measure 'Debet eliminatie Resultaatrekening' =
			
			CALCULATE(
			    SUM( 'Eliminatie journaalregels'[Debet] )
			    , 'Eliminatie journaalregels'[Rubriektype] = "W"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Eliminatie posten

	measure 'Debet eliminatie Balans' =
			
			CALCULATE(
			    SUM( 'Eliminatie journaalregels'[Debet] )
			    , 'Eliminatie journaalregels'[Rubriektype] = "B"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Eliminatie posten

	measure 'Debet eliminatie' = SUM('Eliminatie journaalregels'[Debet])
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Eliminatie posten

	measure 'Credit eliminatie Resultaatrekening' =
			
			CALCULATE(
			    SUM( 'Eliminatie journaalregels'[Credit] )
			    , 'Eliminatie journaalregels'[Rubriektype] = "W"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Eliminatie posten

	measure 'Credit eliminatie Balans' =
			
			CALCULATE(
			    SUM( 'Eliminatie journaalregels'[Credit] )
			    , 'Eliminatie journaalregels'[Rubriektype] = "B"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Eliminatie posten

	measure 'Credit eliminatie' = SUM('Eliminatie journaalregels'[Credit])
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Eliminatie posten

	measure 'Titel verkoopfacturen' =
			
			var _aantal_select_adm =
			    DISTINCTCOUNT('Eliminatie journaalregels'[Administratie -> Relatie])
			
			return
			if(
			    _aantal_select_adm = 1
			   , "Verkoopfacturen bij ["&max('Eliminatie journaalregels'[Versturende Administratie])&"] aan ["&max('Eliminatie journaalregels'[Ontvangende Administratie])&"]"
			   , "Verkoopfacturen"
			   )
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Meldingen

	measure 'Melding gekoppelde inkoopfactuur' = ```
			
			VAR result = 
			            IF(
			                ISINSCOPE('Eliminatie journaalregels'[Document])
			                ,IF(
			                    NOT(ISBLANK([Eliminatie opbrengsten]))
			                    , IF(
			                        MIN( 'Eliminatie journaalregels'[Heeft inkoopfactuur] ) = "Nee" 
			                        ,"Geen inkoopfactuur"
			                        ,IF(
			                            ROUND( [Eliminatie opbrengsten] - [Eliminatie inkoopkosten van de opbrengsten], 0 ) <> 0
			                            ,"Verschil in bedrag"
			                            ,""
			                        )
			                    )
			                    ,blank()
			                )
			                ,blank()
			            )
			
			return
			    result
			```
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Controle

	measure 'Eliminatie opbrengsten' =
			
			Calculate(
			    SUM('Eliminatie journaalregels'[Credit])
			    ,'Eliminatie journaalregels'[Document bron] = "Verkoopfactuur"
			   ,'Rubrieken'[Toepassing] IN {"Balansboeking","Omzetrekening"}
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Eliminatie posten\Opbrengsten

	measure 'Eliminatie inkoopkosten van de opbrengsten' =
			
			Calculate(
			    MIN('Eliminatie journaalregels'[inkoopkosten])
			    ,'Eliminatie journaalregels'[Document bron] = "Verkoopfactuur"
			   ,'Rubrieken'[Toepassing] IN {"Balansboeking","Omzetrekening"}
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Eliminatie posten\Opbrengsten

	measure 'Controle opbrengsten gelijk aan gekoppelde inkoopkosten' = ```
			
			IF(
			    ROUND( [Eliminatie opbrengsten] - [Eliminatie inkoopkosten van de opbrengsten], 0 ) = 0
			    ,0
			    ,1 
			)
			```
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Controle

	measure 'Verkoopfactuur buiten datumselectie' = ```
			
			VAR _startdatum = min('Kalender'[Datum])
			VAR _einddatum = max('Kalender'[Datum])
			VAR _sel_vkf_boekdatum = 
			    max('Eliminatie journaalregels'[Verkoopfactuur boekdatum])
			
			
			    VAR result = 
			            IF(
			                ISINSCOPE('Eliminatie journaalregels'[Document])
			                ,IF(
			                    NOT(ISBLANK([Eliminatie inkoopkosten]))
			                    ,IF(
			                        ISBLANK(_sel_vkf_boekdatum)
			                        ,-1
			                        ,IF(
			                            _sel_vkf_boekdatum >=_startdatum && _sel_vkf_boekdatum <=_einddatum
			                            ,1
			                            ,0
			                        )
			                    )
			                    ,blank()
			                )
			                ,blank()
			            )
			
			return
			    result
			```
		formatString: #,##0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Meldingen

	measure 'Titel inkoopfacturen' =
			
			var _aantal_select_adm =
			    DISTINCTCOUNT('Eliminatie journaalregels'[Administratie -> Relatie])
			
			return
			if(
			    _aantal_select_adm = 1
			   , "Inkoopfacturen bij ["&max('Eliminatie journaalregels'[Ontvangende Administratie])&"] van ["&max('Eliminatie journaalregels'[Versturende Administratie])&"]"
			   , "Inkoopfacturen"
			   )
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Meldingen

	measure 'Melding gekoppelde verkoopfactuur' = ```
			
			VAR _startdatum = min('Kalender'[Datum])
			VAR _einddatum = max('Kalender'[Datum])
			VAR _sel_vkf_boekdatum = 
			    max('Eliminatie journaalregels'[Verkoopfactuur boekdatum])
			
			
			    VAR result = 
			            IF(
			                ISINSCOPE('Eliminatie journaalregels'[Document])
			                ,IF(
			                    NOT(ISBLANK([Eliminatie inkoopkosten]))
			                    ,IF(
			                        ISBLANK(_sel_vkf_boekdatum)
			                        ,"Geen verkoopfactuur"
			                        ,IF(
			                            _sel_vkf_boekdatum >=_startdatum && _sel_vkf_boekdatum <=_einddatum && ROUND( [Eliminatie inkoopkosten] - [Eliminatie opbrengsten van de inkoopkosten], 0 ) =0
			                            ,""
			                            ,IF(
			                                _sel_vkf_boekdatum >=_startdatum && _sel_vkf_boekdatum <=_einddatum && ROUND( [Eliminatie inkoopkosten] - [Eliminatie opbrengsten van de inkoopkosten], 0 )<>0
			                                ,"Verschil in bedrag"
			                                ,IF(
			                                    _sel_vkf_boekdatum >= _startdatum && _sel_vkf_boekdatum <= _einddatum
			                                    ,""
			                                    ,"Verkoopfactuur buiten selectie"
			                                )
			                                
			                            )
			                        )
			                    )
			                    ,blank()
			                )
			                ,blank()
			            )
			
			return
			    result
			```
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Meldingen

	measure 'Eliminatie opbrengsten van de inkoopkosten' =
			
			Calculate(
			   MIN('Eliminatie journaalregels'[opbrengstbedrag])
			    ,'Eliminatie journaalregels'[Document bron] <> "Verkoopfactuur"
			    ,'Rubrieken'[Toepassing] IN {"Balansboeking","Kostenrekening","Magazijn"}
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Eliminatie posten\Inkoopkosten

	measure 'Eliminatie inkoopkosten' =
			
			Calculate(
			    SUM('Eliminatie journaalregels'[Debet])
			    ,'Eliminatie journaalregels'[Document bron] <> "Verkoopfactuur"
			   ,'Rubrieken'[Toepassing] IN {"Balansboeking","Kostenrekening","Magazijn"}
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Eliminatie posten\Inkoopkosten

	measure 'Controle inkoopkosten gelijk aan gekoppelde opbrengsten' = ```
			
			IF(
			    ROUND( [Eliminatie inkoopkosten] - [Eliminatie opbrengsten van de inkoopkosten], 0 ) = 0
			    ,0
			    ,1 
			)
			```
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Controle

	measure 'Mutatie budget per dag' =
			
			var debet =
			CALCULATE(
			    SUM ('Budget per dag'[Bedrag per dag])
			    ,'Budget per dag'[Debet/Credit] = "D"
			    ,Rubrieken[Type] = "W"
			)
			var credit =
			CALCULATE(
			    SUM ('Budget per dag'[Bedrag per dag])
			    ,'Budget per dag'[Debet/Credit] = "C"
			    ,Rubrieken[Type] = "W"
			)
			
			return
			credit-debet
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Budget\Bron - Syntess

	measure 'Budget YTD' =
			
			var geselecteerde_einddatum = MAX('Kalender'[Datum])
			var StartOfYear_geselecteerde_einddatum = Date(YEAR(geselecteerde_einddatum),1,1)
			var debet =
			CALCULATE(
			    SUM ('Budget per dag'[Bedrag per dag])
			    ,'Budget per dag'[Debet/Credit] = "D"
			    ,FILTER(
			        ALL('Kalender')
			        ,'Kalender'[Datum]>=StartOfYear_geselecteerde_einddatum &&
			        'Kalender'[Datum]<=geselecteerde_einddatum
			    )
			    ,Rubrieken[Type] = "W"
			)
			var credit =
			CALCULATE(
			    SUM ('Budget per dag'[Bedrag per dag])
			    ,'Budget per dag'[Debet/Credit] = "C"
			    ,FILTER(
			        ALL('Kalender')
			        ,'Kalender'[Datum]>=StartOfYear_geselecteerde_einddatum &&
			        'Kalender'[Datum]<=geselecteerde_einddatum
			    )
			    ,Rubrieken[Type] = "W"
			)
			
			return
			credit-debet
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Budget\Bron - Syntess

	measure '% YTD t.o.v. YTD budget' = DIVIDE([Delta actual - budget],[CoA mutatie])
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Ratio

	measure '% YTD t.o.v. YTD LY' = DIVIDE([Delta actual - actual-LY],[CoA mutatie])
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA rekeningschema

	measure 'CoA Actual LY' =
			
			CALCULATE(
			    [CoA mutatie]
			    ,SAMEPERIODLASTYEAR('Kalender'[Datum])
			)
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA rekeningschema

	measure 'CoA lege regel' = ```
			
			IF(
			    SELECTEDVALUE('NR - CoA schema'[Classificatie type]) = "Blank" 
			    , 0
			    , BLANK()
			)
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		isHidden
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA rekeningschema

	measure 'CoA mutatie' = ```
			
			VAR _classification         = SELECTEDVALUE('NR - CoA schema'[Classificatie type])
			VAR _is_subtotaal           = _classification = "Subtotaal"
			VAR _is_geen_omzet          = _classification <> "Omzet" 
			VAR _correctSubtotalLevel   = _is_subtotaal                && ISINSCOPE('NR - CoA schema'[Niveau1]) && NOT(ISINSCOPE('NR - CoA schema'[Niveau2]))
			VAR _is_legeregel           = _classification = "Leeg"    && ISINSCOPE('NR - CoA schema'[Niveau1]) && NOT(ISINSCOPE('NR - CoA schema'[Niveau2]))
			
			VAR _credit_eliminatie_Resultaatrekening = 
			CALCULATE(
			    SUM( 'Eliminatie journaalregels'[Credit] )
			    , 'Eliminatie journaalregels'[Rubriektype] = "W"
			    ,NOT ( ISBLANK('NR - CoA mapping DQ'[CoA_code] ) )
			)
			
			VAR _debet_eliminatie_Resultaatrekening = 
			CALCULATE(
			    SUM( 'Eliminatie journaalregels'[Debet] )
			    , 'Eliminatie journaalregels'[Rubriektype] = "W"
			    ,NOT ( ISBLANK('NR - CoA mapping DQ'[CoA_code] ) )
			)
			
			VAR _credit_exploitatie     = CALCULATE(SUM( 'Journaalregels'[Creditbedrag] ),'Rubrieken'[Type] = "W",NOT ( ISBLANK('NR - CoA mapping DQ'[CoA_code] ) )) - _credit_eliminatie_Resultaatrekening
			VAR _debet_exploitatie      = CALCULATE(SUM( 'Journaalregels'[Debetbedrag] ), 'Rubrieken'[Type] = "W",NOT ( ISBLANK('NR - CoA mapping DQ'[CoA_code]) )) - _debet_eliminatie_Resultaatrekening
			VAR _mutatie_eploitatie     = _credit_exploitatie - _debet_exploitatie -- Reguliere mutaties op rubriek--
			
			VAR _subtotaalWaarde =
			    CALCULATE(
			        [Mutatie resultaat met mapping]
			        , FILTER(
			            ALL( 'NR - CoA schema' )
			            , 'NR - CoA schema'[Niveau2_sortering] <= MAX( 'NR - CoA schema'[Niveau2_sortering] )
			        )
			    )
			
			VAR result =
			    SWITCH(
			        TRUE
			        ,_is_legeregel,0
			        ,NOT(_is_subtotaal) && _is_geen_omzet,-_mutatie_eploitatie
			        ,NOT(_is_subtotaal),_mutatie_eploitatie
			        ,_correctSubtotalLevel,_subtotaalWaarde
			    )/1000
			    
			    
			RETURN
			   result
			```
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA rekeningschema

	measure 'CoA mutatie budget' = ```
			
			VAR _classification         = SELECTEDVALUE('NR - CoA schema'[Classificatie type])
			VAR _is_subtotaal           = _classification = "Subtotaal"
			VAR _is_geen_omzet          = _classification <> "Omzet" 
			VAR _correctSubtotalLevel   = _is_subtotaal                && ISINSCOPE('NR - CoA schema'[Niveau1]) && NOT(ISINSCOPE('NR - CoA schema'[Niveau2]))
			VAR _is_legeregel           = _classification = "Leeg"    && ISINSCOPE('NR - CoA schema'[Niveau1]) && NOT(ISINSCOPE('NR - CoA schema'[Niveau2]))
			 
			VAR _credit_exploitatie     
			= CALCULATE(
			    SUM ('Budget per dag'[Bedrag per dag])
			    ,'Budget per dag'[Debet/Credit] = "C"
			    ,Rubrieken[Type] = "W"
			)
			VAR _debet_exploitatie      
			= CALCULATE(
			    SUM ('Budget per dag'[Bedrag per dag])
			    ,'Budget per dag'[Debet/Credit] = "D"
			    ,Rubrieken[Type] = "W"
			)
			
			VAR _mutatie_eploitatie     
			= _credit_exploitatie - _debet_exploitatie -- Reguliere mutaties op rubriek--
			
			VAR _subtotaalWaarde =
			    CALCULATE(
			        [Mutatie budget per dag]
			        , FILTER(
			            ALL( 'NR - CoA schema' )
			            , 'NR - CoA schema'[Niveau2_sortering] <= MAX( 'NR - CoA schema'[Niveau2_sortering] )
			        )
			    )
			
			VAR result =
			    SWITCH(
			        TRUE
			        ,_is_legeregel,0
			        ,NOT(_is_subtotaal) && _is_geen_omzet,-_mutatie_eploitatie
			        ,NOT(_is_subtotaal),_mutatie_eploitatie
			        ,_correctSubtotalLevel,_subtotaalWaarde
			    )/1000
			    
			    
			RETURN
			   result
			```
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Syntess budget

	measure 'CoA resultaat' = ( [Mutatie resultaat] + [CoA lege regel] + [CoA subtotaal waardes] )/1000
		formatString: #,##0;(#,##0);
		isHidden
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA rekeningschema

	measure 'CoA subtotaal waardes' = ```
			
			VAR _marge =
			CALCULATE(
			    [Mutatie resultaat]
			    , FILTER(
			        ALL( 'NR - CoA schema' )
			        , 'NR - CoA schema'[Niveau2_sortering] <= MAX( 'NR - CoA schema'[Niveau2_sortering] )
			        
			    )
			)
			VAR result = 
			    IF(
			        SELECTEDVALUE('NR - CoA schema'[Classificatie type]) = "Subtotaal"
			        ,_marge
			        ,BLANK()
			    )
			
			RETURN
			    result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		isHidden
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA rekeningschema

	measure 'CoA YTD rendement' = ```
			
			VAR _classification         = SELECTEDVALUE('NR - CoA schema'[Classificatie type])
			VAR _is_subtotaal           = _classification = "Subtotaal"
			VAR _is_omzet               = _classification = "Omzet" 
			VAR _correctSubtotalLevel   = _is_subtotaal               && ISINSCOPE('NR - CoA schema'[Niveau1]) && NOT(ISINSCOPE('NR - CoA schema'[Niveau2]))
			VAR _is_legeregel           = _classification = "Leeg"    && ISINSCOPE('NR - CoA schema'[Niveau1]) && NOT(ISINSCOPE('NR - CoA schema'[Niveau2]))
			 
			VAR _omzetwaarde =
			    CALCULATE(
			        [Mutatie resultaat]
			        ,FILTER(
			            ALL( 'NR - CoA schema' )
			            , 'NR - CoA schema'[Classificatie type] = "Omzet"
			        )
			    )
			    
			VAR _subtotaalWaarde =
			    CALCULATE(
			        [Mutatie resultaat]
			        , FILTER(
			            ALL( 'NR - CoA schema' )
			            , 'NR - CoA schema'[Niveau2_sortering] <= MAX( 'NR - CoA schema'[Niveau2_sortering] )
			        )
			    )
			
			VAR result =
			    SWITCH(
			        TRUE
			        ,_is_legeregel,BLANK()
			        ,NOT(_is_subtotaal),BLANK()
			        ,_correctSubtotalLevel,DIVIDE( _subtotaalWaarde, _omzetwaarde )
			    )
			    
			    
			RETURN
			   result
			```
		formatString: 0%;-0%;
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA rekeningschema

	measure 'CoA YTD rendement budget' = ```
			
			VAR _classification         = SELECTEDVALUE('NR - CoA schema'[Classificatie type])
			VAR _is_subtotaal           = _classification = "Subtotaal"
			VAR _is_omzet               = _classification = "Omzet" 
			VAR _correctSubtotalLevel   = _is_subtotaal               && ISINSCOPE('NR - CoA schema'[Niveau1]) && NOT(ISINSCOPE('NR - CoA schema'[Niveau2]))
			VAR _is_legeregel           = _classification = "Leeg"    && ISINSCOPE('NR - CoA schema'[Niveau1]) && NOT(ISINSCOPE('NR - CoA schema'[Niveau2]))
			 
			VAR _omzetwaarde =
			    CALCULATE(
			        [Mutatie resultaat budget]
			        ,FILTER(
			            ALL( 'NR - CoA schema' )
			            , 'NR - CoA schema'[Classificatie type] = "Omzet"
			        )
			    )
			    
			VAR _subtotaalWaarde =
			    CALCULATE(
			        [Mutatie resultaat budget]
			        , FILTER(
			            ALL( 'NR - CoA schema' )
			            , 'NR - CoA schema'[Niveau2_sortering] <= MAX( 'NR - CoA schema'[Niveau2_sortering] )
			        )
			    )
			
			VAR result =
			    SWITCH(
			        TRUE
			        ,_is_legeregel,BLANK()
			        ,NOT(_is_subtotaal),BLANK()
			        ,_correctSubtotalLevel,DIVIDE( _subtotaalWaarde, _omzetwaarde )
			    )
			    
			    
			RETURN
			   result
			```
		formatString: 0%;-0%;
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Syntess budget

	measure 'CoA YTD rendement LY' = ```
			
			VAR _classification         = SELECTEDVALUE('NR - CoA schema'[Classificatie type])
			VAR _is_subtotaal           = _classification = "Subtotaal"
			VAR _is_omzet               = _classification = "Omzet" 
			VAR _correctSubtotalLevel   = _is_subtotaal               && ISINSCOPE('NR - CoA schema'[Niveau1]) && NOT(ISINSCOPE('NR - CoA schema'[Niveau2]))
			VAR _is_legeregel           = _classification = "Leeg"    && ISINSCOPE('NR - CoA schema'[Niveau1]) && NOT(ISINSCOPE('NR - CoA schema'[Niveau2]))
			 
			VAR _omzetwaarde =
			    CALCULATE(
			        [Mutatie resultaat LY]
			        ,FILTER(
			            ALL( 'NR - CoA schema' )
			            , 'NR - CoA schema'[Classificatie type] = "Omzet"
			        )
			    )
			    
			VAR _subtotaalWaarde =
			    CALCULATE(
			       [Mutatie resultaat LY]
			        , FILTER(
			            ALL( 'NR - CoA schema' )
			            , 'NR - CoA schema'[Niveau2_sortering] <= MAX( 'NR - CoA schema'[Niveau2_sortering] )
			        )
			    )
			
			VAR result =
			    SWITCH(
			        TRUE
			        ,_is_legeregel,BLANK()
			        ,NOT(_is_subtotaal),BLANK()
			        ,_correctSubtotalLevel,DIVIDE( _subtotaalWaarde, _omzetwaarde )
			    )
			    
			    
			RETURN
			   result
			```
		formatString: 0%;-0%;
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA rekeningschema

	measure 'Delta actual - actual-LY' = [CoA mutatie]-[CoA Actual LY]
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA rekeningschema

	measure 'Delta actual - budget' = [CoA mutatie]-[CoA mutatie budget]
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Ratio

	measure 'Geselecteerde classificatie' =
			
			IF(
			    MAX( 'NR - CoA schema'[Classificatie type] ) = "Subtotaal"
			    , 1
			    , 0
			)
		formatString: #,##0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA rekeningschema

	measure 'Melding resultaat rubrieken zijn niet gekoppeld' =
			
			IF(
			    ISBLANK([Mutatie resultaat zonder mapping])
			    ,"Alle rubrieken zijn gekoppeld onder de huidige filter instellingen."
			    ,"Er zijn rubrieken zonder koppeling."
			)
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA rekeningschema

	measure 'Mutatie resultaat' = ```
			
			VAR _credit = 
			CALCULATE(
			    SUM( 'Journaalregels'[Creditbedrag] )
			    ,'Rubrieken'[Type] = "W"
			)
			-[Credit eliminatie Resultaatrekening]
			VAR _debet = 
			CALCULATE(
			    SUM( 'Journaalregels'[Debetbedrag] )
			    , 'Rubrieken'[Type] = "W"
			)-[Debet eliminatie Resultaatrekening]
			
			VAR result = _credit - _debet
			
			RETURN
			    result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA rekeningschema

	measure 'Mutatie resultaat budget' = ```
			
			VAR _credit = 
			CALCULATE(
			    SUM ('Budget per dag'[Bedrag per dag])
			    ,'Budget per dag'[Debet/Credit] = "C"
			    ,Rubrieken[Type] = "W"
			)
			
			VAR _debet = 
			CALCULATE(
			    SUM ('Budget per dag'[Bedrag per dag])
			    ,'Budget per dag'[Debet/Credit] = "D"
			    ,Rubrieken[Type] = "W"
			)
			
			VAR result = _credit - _debet
			
			RETURN
			    result
			```
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Syntess budget

	measure 'Mutatie resultaat LY' =
			
			CALCULATE(
			    [Mutatie resultaat]
			    ,SAMEPERIODLASTYEAR('Kalender'[Datum])
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA rekeningschema

	measure 'Mutatie resultaat met mapping' = ```
			
			VAR _credit = 
			CALCULATE(
			    SUM( 'Journaalregels'[Creditbedrag] )
			    ,'Rubrieken'[Type] = "W"
			    ,NOT ( ISBLANK( 'NR - CoA mapping DQ'[CoA_code] ) )
			)
			
			VAR _credit_eliminatie =
			CALCULATE(
			    SUM( 'Eliminatie journaalregels'[Credit] )
			    , 'Eliminatie journaalregels'[Rubriektype] = "W"
			    ,NOT ( ISBLANK('NR - CoA mapping DQ'[CoA_code]) )
			)
			
			VAR _debet = 
			CALCULATE(
			    SUM( 'Journaalregels'[Debetbedrag] )
			    , 'Rubrieken'[Type] = "W"
			    ,NOT ( ISBLANK('NR - CoA mapping DQ'[CoA_code]) )
			)
			
			VAR _debet_eliminatie =
			CALCULATE(
			    SUM( 'Eliminatie journaalregels'[Debet] )
			    , 'Eliminatie journaalregels'[Rubriektype] = "W"
			    ,NOT ( ISBLANK('NR - CoA mapping DQ'[CoA_code]))
			)
			
			VAR result = (_credit - _credit_eliminatie) - (_debet - _debet_eliminatie)
			
			RETURN
			    result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA rekeningschema

	measure 'Mutatie resultaat zonder mapping' = ```
			
			VAR _credit = 
			CALCULATE(
			    SUM( 'Journaalregels'[Creditbedrag] )
			    ,'Rubrieken'[Type] = "W"
			    ,ISBLANK('NR - CoA mapping DQ'[CoA_code]) 
			)
			
			VAR _credit_eliminatie =
			CALCULATE(
			    SUM( 'Eliminatie journaalregels'[Credit] )
			    , 'Eliminatie journaalregels'[Rubriektype] = "W"
			    ,ISBLANK('NR - CoA mapping DQ'[CoA_code]) 
			)
			
			VAR _debet = 
			CALCULATE(
			    SUM( 'Journaalregels'[Debetbedrag] )
			    , 'Rubrieken'[Type] = "W"
			    ,ISBLANK('NR - CoA mapping DQ'[CoA_code] ) 
			)
			
			VAR _debet_eliminatie =
			CALCULATE(
			    SUM( 'Eliminatie journaalregels'[Debet] )
			    , 'Eliminatie journaalregels'[Rubriektype] = "W"
			    ,ISBLANK('NR - CoA mapping DQ'[CoA_code] )
			)
			
			
			VAR result = (_credit - _credit_eliminatie) - (_debet - _debet_eliminatie)
			
			RETURN
			    result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA rekeningschema

	measure 'Waardemelding resultaat rubrieken zijn niet gekoppeld' =
			
			IF(
			    ISBLANK([Mutatie resultaat zonder mapping])
			    ,1
			    ,0
			)
		formatString: #,##0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA rekeningschema

	measure 'Actual YTD exploitatierekening' =
			
			var geselecteerde_einddatum = MAX('Kalender'[Datum])
			var StartOfYear_geselecteerde_einddatum = Date(YEAR(geselecteerde_einddatum),1,1)
			var debet =
			CALCULATE(
			    SUM(Journaalregels[Debetbedrag])
			    ,FILTER(
			        ALL('Kalender')
			        ,'Kalender'[Datum]>=StartOfYear_geselecteerde_einddatum &&
			        'Kalender'[Datum]<=geselecteerde_einddatum
			    )
			    ,Rubrieken[Type] = "W"
			)
			var credit =
			CALCULATE(
			    SUM(Journaalregels[Creditbedrag])
			    ,FILTER(
			        ALL('Kalender')
			        ,'Kalender'[Datum]>=StartOfYear_geselecteerde_einddatum &&
			        'Kalender'[Datum]<=geselecteerde_einddatum
			    )
			    ,Rubrieken[Type] = "W"
			)
			
			return
			credit-debet
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Exploitatie

	measure 'Actual mutatie exploitatierekening' =
			
			var debet =
			CALCULATE(
			    SUM(Journaalregels[Debetbedrag])
			    ,Rubrieken[Type] = "W"
			)
			var credit =
			CALCULATE(
			    SUM(Journaalregels[Creditbedrag])
			    ,Rubrieken[Type] = "W"
			)
			
			var exploitatie =
			CALCULATE(
			    credit-debet
			    ,Journaalregels[TypePeriode]<>"Openingsperiode"
			)
			return
			IF(
			    exploitatie >-0.1 && exploitatie <0.1
			    ,BLANK()
			    ,exploitatie
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Exploitatie

	measure 'Mutatie Balans YTD (debet-credit)' = [Actual debet-YTD Balans]-[Actual credit-YTD Balans]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Balans

	measure 'Mutatie Balans (debet-credit)' = [Actual debet-mutatie Balans]-[Actual credit-mutatie Balans]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Balans

	/// [Actual debet-YTD Balans]-[Actual credit-YTD Balans] indien groter dan 1 andere leeg.
	measure 'Debet balans' =
			
			var debet_min_credit =
			    [Actual debet-YTD Balans]-[Actual credit-YTD Balans]
			return
			IF(
			    debet_min_credit>1
			    ,debet_min_credit
			    ,blank()
			    )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Balans

	/// [Actual credit-YTD Balans]- [Actual debet-YTD Balans] indien groter dan 1 andere leeg.
	measure 'Credit balans' =
			
			var credit_min_debet =
			   [Actual credit-YTD Balans]- [Actual debet-YTD Balans]
			return
			IF(
			    credit_min_debet>1
			    ,credit_min_debet
			    ,blank()
			    )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Balans

	/// Debet boekingen op balans rekeningen vanaf 1 januari (van het jaar van de geselecteerde einddatum) tot en met  geselecteerde einddatum.
	measure 'Actual debet-YTD Balans' =
			
			var geselecteerde_einddatum = MAX('Kalender'[Datum])
			var StartOfYear_geselecteerde_einddatum = Date(YEAR(geselecteerde_einddatum),1,1)
			return
			CALCULATE(
			    SUM('Journaalregels'[Debetbedrag])
			    ,FILTER(
			        ALL('Kalender')
			        ,'Kalender'[Datum]>=StartOfYear_geselecteerde_einddatum &&
			        'Kalender'[Datum]<=geselecteerde_einddatum
			    )
			    ,Rubrieken[Type] = "B"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Balans

	/// Debet boekingen op balans rekeningen in geselecteerde periode.
	measure 'Actual debet-mutatie Balans' =
			
			var debet_balans =
			CALCULATE(
			    SUM('Journaalregels'[Debetbedrag])
			    ,Rubrieken[Type] = "B"
			    ,Journaalregels[TypePeriode]<>"Openingsperiode"
			)
			
			return
			IF(
			    debet_balans >-0.1 && debet_balans <0.1
			    ,BLANK()
			    ,debet_balans
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Balans

	/// Credit boekingen op balans rekeningen vanaf 1 januari (van het jaar van de geselecteerde einddatum) tot en met  geselecteerde einddatum.
	measure 'Actual credit-YTD Balans' =
			
			var geselecteerde_einddatum = MAX('Kalender'[Datum])
			var StartOfYear_geselecteerde_einddatum = Date(YEAR(geselecteerde_einddatum),1,1)
			return
			CALCULATE(
			    SUM('Journaalregels'[Creditbedrag])
			    ,FILTER(
			        ALL('Kalender')
			        ,'Kalender'[Datum]>=StartOfYear_geselecteerde_einddatum &&
			        'Kalender'[Datum]<=geselecteerde_einddatum
			    )
			    ,Rubrieken[Type] = "B"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Balans

	/// Credit boekingen op balans rekeningen in geselecteerde periode.
	measure 'Actual credit-mutatie Balans' =
			
			var credit_balans =
			CALCULATE(
			    SUM('Journaalregels'[Creditbedrag])
			    ,Rubrieken[Type] = "B"
			    ,Journaalregels[TypePeriode]<>"Openingsperiode"
			)
			
			return
			IF(
			    credit_balans >-0.1 && credit_balans <0.1
			    ,BLANK()
			    ,credit_balans
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Balans

	measure 'Actual credit-mutatie Balans CoA' =
			
			var credit_balans =
			CALCULATE(
			    SUM('Journaalregels'[Creditbedrag])
			    ,Rubrieken[Type] = "B"
			    ,Journaalregels[TypePeriode]<>"Openingsperiode"
			)
			-[Credit eliminatie Balans]
			
			return
			IF(
			    credit_balans >-0.1 && credit_balans <0.1
			    ,BLANK()
			    ,credit_balans
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA Balans

	measure 'Actual credit-YTD Balans CoA' =
			
			var geselecteerde_einddatum = MAX('Kalender'[Datum])
			var StartOfYear_geselecteerde_einddatum = Date(YEAR(geselecteerde_einddatum),1,1)
			VAR credit_YTD =
			CALCULATE(
			    SUM('Journaalregels'[Creditbedrag])
			    ,FILTER(
			        ALL('Kalender')
			        ,'Kalender'[Datum]>=StartOfYear_geselecteerde_einddatum &&
			        'Kalender'[Datum]<=geselecteerde_einddatum
			    )
			    ,Rubrieken[Type] = "B"
			)
			VAR credit_YTD_eliminatie =
			CALCULATE(
			    SUM( 'Eliminatie journaalregels'[Credit] )
			    ,FILTER(
			        ALL('Kalender')
			        ,'Kalender'[Datum]>=StartOfYear_geselecteerde_einddatum &&
			        'Kalender'[Datum]<=geselecteerde_einddatum
			    )
			    , 'Eliminatie journaalregels'[Rubriektype] = "B"
			)
			
			VAR result = credit_YTD - credit_YTD_eliminatie
			
			
			
			RETURN
			    result
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA Balans

	measure 'Actual debet-mutatie Balans CoA' =
			
			var debet_balans =
			CALCULATE(
			    SUM('Journaalregels'[Debetbedrag])
			    ,Rubrieken[Type] = "B"
			    ,Journaalregels[TypePeriode]<>"Openingsperiode"
			)
			-[Debet eliminatie Balans]
			return
			IF(
			    debet_balans >-0.1 && debet_balans <0.1
			    ,BLANK()
			    ,debet_balans
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA Balans

	measure 'Actual debet-YTD Balans CoA' =
			
			var geselecteerde_einddatum = MAX('Kalender'[Datum])
			var StartOfYear_geselecteerde_einddatum = Date(YEAR(geselecteerde_einddatum),1,1)
			return
			CALCULATE(
			    SUM('Journaalregels'[Debetbedrag])
			    ,FILTER(
			        ALL('Kalender')
			        ,'Kalender'[Datum]>=StartOfYear_geselecteerde_einddatum &&
			        'Kalender'[Datum]<=geselecteerde_einddatum
			    )
			    ,Rubrieken[Type] = "B"
			)
			-[Debet eliminatie Balans]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA Balans

	measure 'CoA balans YTD' = ```
			
			VAR _classification      = SELECTEDVALUE('NR - CoA balans schema'[Classificatie_type])
			VAR _Is_subtotaal        = _classification = "Subtotaal"
			VAR _is_activa           = _classification = "Activa"
			VAR _is_passiva          = _classification = "Passiva"
			
			VAR _correctSubtotalLevel_activa   = SELECTEDVALUE('NR - CoA balans schema'[Niveau1]) = "Activa" && ISINSCOPE('NR - CoA balans schema'[Niveau1]) && NOT(ISINSCOPE('NR - CoA balans schema'[Niveau2]))
			VAR _correctSubtotalLevel_passiva  = SELECTEDVALUE('NR - CoA balans schema'[Niveau1]) = "Passiva" && ISINSCOPE('NR - CoA balans schema'[Niveau1]) && NOT(ISINSCOPE('NR - CoA balans schema'[Niveau2]))
			
			VAR _is_legeregel           = _classification  = "Leeg" && ISINSCOPE('NR - CoA balans schema'[Niveau1]) && NOT(ISINSCOPE('NR - CoA balans schema'[Niveau2]))
			 
			VAR _stand_Balans         = [Verschil debet-credit balans CoA] -- Reguliere mutaties op rubriek--
			
			VAR _subtotaalWaarde_activa =
			    CALCULATE(
			        [Verschil debet-credit balans CoA]
			        , FILTER(
			            ALL( 'NR - CoA balans schema' )
			            , 'NR - CoA balans schema'[Classificatie_type] = "Activa"
			        )
			    )
			 
			VAR _subtotaalWaarde_passiva =
			    CALCULATE(
			        [Verschil credit-debet balans CoA]
			        , FILTER(
			            ALL( 'NR - CoA balans schema' )
			            , 'NR - CoA balans schema'[Classificatie_type] = "Passiva"
			        )
			    ) 
			
			VAR result =   
			SWITCH(
			        TRUE
			        ,_is_legeregel,0
			        ,NOT ( _is_subtotaal ) && _is_activa,[Verschil debet-credit balans CoA]
			        ,NOT ( _is_subtotaal ) && _is_passiva,[Verschil credit-debet balans CoA]
			        ,_correctSubtotalLevel_activa ,_subtotaalWaarde_activa
			        ,_correctSubtotalLevel_passiva,_subtotaalWaarde_passiva 
			    )
			
			VAR result2 =   
			IF(
			    _is_legeregel
			    , 0
			    , IF(
			        NOT ( _is_subtotaal )
			        , _stand_Balans
			        , IF(
			            _correctSubtotalLevel_activa
			            , _subtotaalWaarde_activa
			            , IF(
			                _correctSubtotalLevel_passiva
			                , _subtotaalWaarde_passiva
			            )
			        )
			    )
			)
			
			RETURN
			    result
			```
		formatString: "€"\ #,0;("€"\ #,0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA Balans

	measure 'Credit balans YTD CoA' =
			
			var credit_min_debet =
			   [Actual credit-YTD Balans]- [Actual debet-YTD Balans]
			return
			IF(
			    credit_min_debet>1
			    ,credit_min_debet
			    ,blank()
			    )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA Balans

	measure 'Debet balans YTD CoA' =
			
			var debet_min_credit =
			    [Actual debet-YTD Balans]-[Actual credit-YTD Balans]
			return
			IF(
			    debet_min_credit>1
			    ,debet_min_credit
			    ,blank()
			    )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA Balans

	measure 'Melding balans rubrieken zijn niet gekoppeld' =
			
			IF(
			    ISBLANK([Mutatie balans zonder mapping])
			    ,"Alle rubrieken zijn gekoppeld onder de huidige filter instellingen."
			    ,"Er zijn rubrieken zonder koppeling."
			)
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA Balans

	measure 'Mutatie balans met mapping' = ```
			
			VAR _credit = 
			CALCULATE(
			    SUM( 'Journaalregels'[Creditbedrag] )
			    ,'Rubrieken'[Type] = "B"
			    ,NOT ( ISBLANK( 'NR - CoA mapping balans DQ'[CoA_code_balans] ) )
			)
			
			VAR _credit_eliminatie =
			CALCULATE(
			    SUM( 'Eliminatie journaalregels'[Credit] )
			    , 'Eliminatie journaalregels'[Rubriektype] = "B"
			    ,NOT ( ISBLANK( 'NR - CoA mapping balans DQ'[CoA_code_balans]  ) )
			)
			
			VAR _debet = 
			CALCULATE(
			    SUM( 'Journaalregels'[Debetbedrag] )
			    , 'Rubrieken'[Type] = "B"
			    ,NOT ( ISBLANK( 'NR - CoA mapping balans DQ'[CoA_code_balans]  ) )
			)
			
			VAR _debet_eliminatie =
			CALCULATE(
			    SUM( 'Eliminatie journaalregels'[Debet] )
			    , 'Eliminatie journaalregels'[Rubriektype] = "B"
			    ,NOT ( ISBLANK('NR - CoA mapping balans DQ'[CoA_code_balans]  ) )
			)
			
			VAR result = _debet - _debet_eliminatie - _credit + _credit_eliminatie
			
			RETURN
			    result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA Balans

	measure 'Mutatie balans zonder mapping' = ```
			
			VAR _credit = 
			CALCULATE(
			    SUM( 'Journaalregels'[Creditbedrag] )
			    ,'Rubrieken'[Type] = "B"
			    ,ISBLANK('NR - CoA mapping balans DQ'[CoA_code_balans] )
			)
			
			VAR _credit_eliminatie =
			CALCULATE(
			    SUM( 'Eliminatie journaalregels'[Credit] )
			    , 'Eliminatie journaalregels'[Rubriektype] = "B"
			    ,ISBLANK( 'NR - CoA mapping balans DQ'[CoA_code_balans] )
			)
			
			VAR _debet = 
			CALCULATE(
			    SUM( 'Journaalregels'[Debetbedrag] )
			    , 'Rubrieken'[Type] = "B"
			    ,ISBLANK( 'NR - CoA mapping balans DQ'[CoA_code_balans]  )
			)
			
			VAR _debet_eliminatie =
			CALCULATE(
			    SUM( 'Eliminatie journaalregels'[Debet] )
			    , 'Eliminatie journaalregels'[Rubriektype] = "B"
			    ,ISBLANK( 'NR - CoA mapping balans DQ'[CoA_code_balans]  )
			)
			
			VAR result = _debet - _debet_eliminatie - _credit + _credit_eliminatie
			
			RETURN
			    result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA Balans

	measure 'resultaat W&V CoA Balans' =
			
			[Actual mutatie exploitatierekening]
			-[Debet eliminatie Balans]+[Credit eliminatie Balans]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA Balans

	measure 'Selected classificatie type subtotaal' =
			
			IF(
			    SELECTEDVALUE('NR - CoA balans schema'[Classificatie_type]) = "Subtotaal"
			    ,1
			    ,0
			)
		formatString: #,##0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA Balans

	measure 'Stand Balans CoA' = [Debet balans YTD CoA]+[Credit balans YTD CoA]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA Balans

	measure 'Verschil credit-debet balans CoA' = [Actual credit-YTD Balans CoA]-[Actual debet-YTD Balans CoA]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA Balans

	measure 'Verschil debet-credit balans CoA' = [Actual debet-YTD Balans CoA]-[Actual credit-YTD Balans CoA]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA Balans

	measure 'Waardemelding balans rubrieken zijn niet gekoppeld' =
			
			IF(
			    ISBLANK([Mutatie balans zonder mapping])
			    ,1
			    ,0
			)
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA Balans

	measure 'Projectjournalisering projectwaarderingen' = ```
			
			VAR _credit =
			CALCULATE(
			    SUM('Project journaalregels'[Bedrag])
			    ,'Project journaalregels'[Debet/Credit] = "C"
			    ,Rubrieken[Type] = "W"
			    ,'Rubrieken'[Toepassing] = "Projectwaardering"
			    ,'Project journaalregels'[BoxNummer] = "2" 
			)
			
			VAR _debet =
			CALCULATE(
			    SUM( 'Project journaalregels'[Bedrag] )
			    , 'Project journaalregels'[Debet/Credit] = "D"
			    , Rubrieken[Type] = "W"
			    , 'Rubrieken'[Toepassing] = "Projectwaardering"
			    , 'Project journaalregels'[BoxNummer] = "2"
			)
			
			
			VAR Result = _credit-_debet
			
			RETURN
			Result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering

	measure 'Projectjournalisering werkresultaat' = ```
			
			VAR _credit =
			CALCULATE(
			    SUM('Project journaalregels'[Bedrag])
			    ,'Project journaalregels'[Debet/Credit] = "C"
			    ,Rubrieken[Type] = "W"
			    ,'Rubrieken'[Toepassing] = "Werkresultaat"
			    ,'Project journaalregels'[BoxNummer] = "2"
			)
			
			VAR _debet =
			CALCULATE(
			    SUM('Project journaalregels'[Bedrag])
			    ,'Project journaalregels'[Debet/Credit] = "D"
			
			    ,Rubrieken[Type] = "W"
			    ,'Rubrieken'[Toepassing] = "Werkresultaat"
			    ,'Project journaalregels'[BoxNummer] = "2" 
			)
			
			
			VAR Result = _credit-_debet
			
			RETURN
			Result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering

	measure 'Projectjournalisering projectwaarderingen en werkresultaat' = ```
			
			VAR _credit =
			CALCULATE(
			    SUM('Project journaalregels'[Bedrag])
			    ,'Project journaalregels'[Debet/Credit] = "C"
			    ,Rubrieken[Type] = "W"
			    ,'Rubrieken'[Toepassing] in { "Projectwaardering", "Werkresultaat" }
			    ,'Project journaalregels'[BoxNummer] = "2" 
			)
			
			VAR _debet =
			CALCULATE(
			    SUM( 'Project journaalregels'[Bedrag] )
			    , 'Project journaalregels'[Debet/Credit] = "D"
			    , Rubrieken[Type] = "W"
			    , 'Rubrieken'[Toepassing] in { "Projectwaardering", "Werkresultaat" }
			    , 'Project journaalregels'[BoxNummer] = "2"
			)
			
			
			VAR Result = _credit-_debet
			
			RETURN
			Result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering

	measure 'Project resultaat incl. omzet correctie' = ```
			
			/*
			MCH 20230917;
			Omzet correctie is nog niet beschikbaar in DWH. Met 'Omzet correctie app', die gelijk aan de projectwaardering app, de gebruiker de mogelijkheid moet bieden 
			om de omzet correctie vast te leggen is dit wel mogelijk. De omzetcorrectie kan dan als feitentabel worden opgehaald en onder de projecten worden gekoppeld.
			
			Ter info; de projectwaarderingen die via de projectwaardering app worden gemaakt hoeven niet als aparte tabel te worden gekoppeld. De projectwaarderingen kunnen in Syntess 
			als boeking per project via memoriaal worden ingeboekt. Dit verloopt hierdoor al via de journaalregels.
			
			LET OP; omdat omzet correctie in Professional niet op projectniveau kan worden ingevoerd is het gewenst om dit wel op administratie niveau te doen. Dit moet dan wel aansluiten met 
			de vastgelegde omzetcorrectieregels in de omzet correctie app! De gebruiker kan hier van afwijken (het totaal uit de omzet correctie app en de uiteindelijke ingeboekte 
			omzet correctie in Syntess) waardoor er geen aansluiting is. 
			
			*/
			
			
			[Project omzet]-[Definitieve kostprijs]
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Ratios

	measure 'Montage en reis uren incl. inleen via inkoopdactuur' = ```
			
			/*
			Werkuren vanuit de urenstaten plus werkuren van inleners die direct via inkoopfacturen op projecten worden geboekt.
			Voorwaarde voor inleners via inkoopfacturen is dat 1) er een kostensoort [Arbeid] wordt gebruikt en 2) de eenheid [u/Uur]
			met internationale code 570410.
			*/
			VAR werkuren_urenstaat =
			    CALCULATE(
			    SUM('Project kosten en geboekte uren'[Aantal])
			    ,'NR - Taakgroepen DQ'[Taakgroep] = "Montage"
			)
			VAR inleenuren_via_inkoop =
			CALCULATE(
			    SUM('Project kosten en geboekte uren'[Aantal])
			    ,'Kostensoorten'[Categorie] = "Arbeid"
			    ,'Project kosten en geboekte uren'[Kostenbron] = "Inkoop"
			    --,'Kosten'[Kostenstatus] = "Definitief"
			    ,'Project kosten en geboekte uren'[internationale code] = "570410"
			)
			VAR reisuren_op_projecten = 
			CALCULATE(
			    SUM('Project kosten en geboekte uren'[Aantal])
			    ,'NR - Taakgroepen DQ'[Taakgroep] = "Reizen"
			)
			VAR result = werkuren_urenstaat + inleenuren_via_inkoop + reisuren_op_projecten
			
			RETURN
			result
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid

	measure 'Reis uren op projecten' = ```
			
			VAR reisuren_op_projecten = 
			CALCULATE(
			    SUM('Project kosten en geboekte uren'[Aantal])
			    ,'NR - Taakgroepen DQ'[Taakgroep] = "Reizen"
			)
			VAR result = reisuren_op_projecten
			
			RETURN
			result
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid

	measure 'Toegevoegde Waarde op realisatie per montage + reis uur (TWR\u)' = ```
			
			VAR TWR_hoofdproject =
			SUMX(
			    SUMMARIZE('Projecten'
			        ,'Projecten'[Hoofdproject]
			        ,"x", 
			            IF(
			                ISBLANK( [Montage en reis uren incl. inleen via inkoopdactuur]+[Inleenuren via inkoop]  )
			                , 0
			                , [Toegevoegde Waarde op Realisatie (TWR)]
			            )
			            ),[x]
			)
			VAR werkuren_hoofdproject =
			SUMX(
			    SUMMARIZE('Projecten'
			        ,'Projecten'[Hoofdproject]
			        ,"y", 
			            IF(
			                ISBLANK(  [Montage en reis uren incl. inleen via inkoopdactuur]+[Inleenuren via inkoop]    )
			                , 0
			                ,IF([Montage en reis uren incl. inleen via inkoopdactuur]+[Inleenuren via inkoop]   < 1
			                    ,0
			                    ,[Montage en reis uren incl. inleen via inkoopdactuur]+[Inleenuren via inkoop] 
			                )
			            )
			            ),[y]
			)
			
			VAR TWRu_per_project = DIVIDE( TWR_hoofdproject, werkuren_hoofdproject )
			
			VAR result = TWRu_per_project
			
			RETURN 
			result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Toegevoegde waarde

		changedProperty = FormatString

	measure 'Gerealiseerde uren MPS monteurs' = ```
			
			/*
			Totaal gerealiseerde uren van medewerkers die tot de MPS functiegroe 'monteurs'
			behoren 
			
			*/
			
			CALCULATE(
			    SUM('Geboekte uren'[Aantal])
			    ,'Geboekte uren'[verlofsaldoboeking] = "Nee"
			    ,'NR - MPS functies DQ'[MPS omschrijving] IN { "Project monteurs", "S&O monteurs" }
			)
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Gerealiseerde uren

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Montage uren t.o.v. totale uren eigen MPS monteurs (projecten en S&O)' = DIVIDE([Montage uren eigen MPS monteurs (projecten en S&O)],[Gerealiseerde uren eigen MPS monteurs])
		formatString: #,##0 %
		displayFolder: 1. Semantisch model\1.02 HR\Ratios

	measure 'Montage uren MPS functie monteurs (projecten en S&O)' = ```
			
			VAR werkuren_urenstaat =
			    CALCULATE(
			    SUM('Project kosten en geboekte uren'[Aantal])
			    ,'NR - Taakgroepen DQ'[Taakgroep] = "Montage"
			    ,'NR - MPS functies DQ'[MPS omschrijving] IN { "Project monteurs", "S&O monteurs" }
			)
			
			VAR result = werkuren_urenstaat 
			
			RETURN
			result
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid

	measure 'Montage uren niet MPS functie monteurs (projecten en S&O)' =
			
			VAR werkuren_urenstaat =
			    CALCULATE(
			    SUM('Project kosten en geboekte uren'[Aantal])
			    ,'NR - Taakgroepen DQ'[Taakgroep] = "Montage"
			    ,NOT( 'NR - MPS functies DQ'[MPS omschrijving] )  IN { "Project monteurs", "S&O monteurs" }
			)
			
			
			VAR result = werkuren_urenstaat
			
			RETURN
			result
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid

	measure 'Inleenuren via inkoop' =
			
			/*
			Werkuren vanuit de urenstaten plus werkuren van inleners die direct via inkoopfacturen op projecten worden geboekt.
			Voorwaarde voor inleners via inkoopfacturen is dat 1) er een kostensoort [Arbeid] wordt gebruikt en 2) de eenheid [u/Uur]
			met internationale code 570410.
			*/
			
			CALCULATE(
			    SUM( 'Project kosten en geboekte uren'[Aantal] )
			    , 'Kostensoorten'[Categorie] = "Arbeid"
			    , 'Project kosten en geboekte uren'[Kostenbron] = "Inkoop"
			    --,'Kosten'[Kostenstatus] = "Definitief"
			    , 'Project kosten en geboekte uren'[internationale code] = "570410"
			)
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid

	measure 'Projectjournalisering werkresultaat opbrengsten' = ```
			
			VAR _credit =
			CALCULATE(
			    SUM('Project journaalregels'[Bedrag])
			    ,'Project journaalregels'[Debet/Credit] = "C"
			    ,Rubrieken[Type] = "W"
			    ,'Rubrieken'[Toepassing] = "Werkresultaat"
			    ,'Project journaalregels'[BoxNummer] = "2"
			)
			
			VAR _debet =
			CALCULATE(
			    SUM('Project journaalregels'[Bedrag])
			    ,'Project journaalregels'[Debet/Credit] = "D"
			
			    ,Rubrieken[Type] = "W"
			    ,'Rubrieken'[Toepassing] = "Werkresultaat"
			    ,'Project journaalregels'[BoxNummer] = "2" 
			)
			
			
			VAR Result = _credit-_debet
			
			RETURN
			Result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering

	measure 'Gerealiseerde uren eigen MPS monteurs' = ```
			
			/*
			Totaal gerealiseerde uren van medewerkers die tot de MPS functiegroe 'monteurs'
			behoren 
			
			*/
			
			CALCULATE(
			    SUM('Geboekte uren'[Aantal])
			    ,'Geboekte uren'[verlofsaldoboeking] = "Nee"
			    ,'NR - MPS functies DQ'[MPS omschrijving] IN { "Project monteurs", "S&O monteurs" }
			    ,'Bedrijfsmedewerkers'[Ingeleend (Ja/Nee)] = "Nee"
			)
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Gerealiseerde uren

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Montage uren eigen personeel' = ```
			
			VAR werkuren_urenstaat =
			    CALCULATE(
			    SUM('Project kosten en geboekte uren'[Aantal])
			    ,'NR - Taakgroepen DQ'[Taakgroep] = "Montage"
			    ,'Bedrijfsmedewerkers'[Ingeleend (Ja/Nee)] = "Nee"
			)
			
			VAR result = werkuren_urenstaat 
			
			RETURN
			result
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid

	measure 'Montage uren eigen MPS monteurs (projecten en S&O)' = ```
			
			VAR werkuren_urenstaat =
			    CALCULATE(
			    SUM('Project kosten en geboekte uren'[Aantal])
			    ,'NR - Taakgroepen DQ'[Taakgroep] = "Montage"
			    ,'NR - MPS functies DQ'[MPS omschrijving] IN { "Project monteurs", "S&O monteurs" }
			    ,'Bedrijfsmedewerkers'[Ingeleend (Ja/Nee)] = "Nee"
			)
			
			VAR result = werkuren_urenstaat 
			
			RETURN
			result
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid

	measure 'Montage uren niet eigen MPS monteurs (projecten en S&O)' =
			
			VAR werkuren_urenstaat =
			    CALCULATE(
			    SUM('Project kosten en geboekte uren'[Aantal])
			    ,'NR - Taakgroepen DQ'[Taakgroep] = "Montage"
			    ,NOT( 'NR - MPS functies DQ'[MPS omschrijving] )  IN { "Project monteurs", "S&O monteurs" }
			    ,'Bedrijfsmedewerkers'[Ingeleend (Ja/Nee)]= "Nee"
			)
			
			
			VAR result = werkuren_urenstaat
			
			RETURN
			result
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid

	measure 'Voortgang facturatie actuele projecten' =
			
			CALCULATE(
			    DIVIDE( [Project omzet], [Definitieve kostprijs] )
			    , Projecten[Hoofdprojectstatus] = "Actueel"
			)
		formatString: #,##0 %
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat

	measure Inkoopkorting = ```
			
			VAR result = 
			    CALCULATE(
			      sum(Journaalregels[Creditbedrag])  - sum(Journaalregels[Debetbedrag])
			      ,'NR - CoA schema'[Code]=102008
			      ,Rubrieken[Type] = "W"
			    )
			
			RETURN
			    result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA rekeningschema

	measure 'Inkoopkorting %' = DIVIDE([Inkoopkorting],[Directe kosten])
		formatString: #,##0.0 %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA rekeningschema

	measure 'Inleenuren via inkoop zonder datumfilter' =
			
			/*
			Werkuren vanuit de urenstaten plus werkuren van inleners die direct via inkoopfacturen op projecten worden geboekt.
			Voorwaarde voor inleners via inkoopfacturen is dat 1) er een kostensoort [Arbeid] wordt gebruikt en 2) de eenheid [u/Uur]
			met internationale code 570410.
			*/
			
			CALCULATE(
			    SUM( 'Project kosten en geboekte uren'[Aantal] )
			    , 'Kostensoorten'[Categorie] = "Arbeid"
			    , 'Project kosten en geboekte uren'[Kostenbron] = "Inkoop"
			    --,'Kosten'[Kostenstatus] = "Definitief"
			    , 'Project kosten en geboekte uren'[internationale code] = "570410"
			    ,ALL(kalender)
			)
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid

	measure 'Montage uren zonder datumfilter' = ```
			
			VAR werkuren_urenstaat =
			    CALCULATE(
			    SUM('Project kosten en geboekte uren'[Aantal])
			    ,'NR - Taakgroepen DQ'[Taakgroep] = "Montage"
			    ,ALL(kalender)
			)
			
			VAR result = werkuren_urenstaat 
			
			RETURN
			result
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid

	measure 'Montage en reis uren zonder datumfilter' = ```
			
			/*
			Werkuren vanuit de urenstaten plus werkuren van inleners die direct via inkoopfacturen op projecten worden geboekt.
			Voorwaarde voor inleners via inkoopfacturen is dat 1) er een kostensoort [Arbeid] wordt gebruikt en 2) de eenheid [u/Uur]
			met internationale code 570410.
			*/
			VAR werkuren_urenstaat =
			    CALCULATE(
			    SUM('Project kosten en geboekte uren'[Aantal])
			    ,'NR - Taakgroepen DQ'[Taakgroep] = "Montage"
			    ,ALL(kalender)
			)
			VAR inleenuren_via_inkoop =
			CALCULATE(
			    SUM('Project kosten en geboekte uren'[Aantal])
			    ,'Kostensoorten'[Categorie] = "Arbeid"
			    ,'Project kosten en geboekte uren'[Kostenbron] = "Inkoop"
			    --,'Kosten'[Kostenstatus] = "Definitief"
			    ,'Project kosten en geboekte uren'[internationale code] = "570410"
			    ,ALL(kalender)
			)
			VAR reisuren_op_projecten = 
			CALCULATE(
			    SUM('Project kosten en geboekte uren'[Aantal])
			    ,'NR - Taakgroepen DQ'[Taakgroep] = "Reizen"
			    ,ALL(kalender)
			)
			VAR result = werkuren_urenstaat + inleenuren_via_inkoop + reisuren_op_projecten
			
			RETURN
			result
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid

	measure 'minimale productiviteit' = 0
		formatString: #,##0 %
		displayFolder: 1. Semantisch model\1.02 HR\Ratios

	measure 'Norm productiviteit eigen monteurs' = MAX('Methode norm productiviteit monteurs'[Value])
		formatString: #,##0 %
		displayFolder: 1. Semantisch model\1.02 HR\Ratios

	measure 'Controle productiviteit t.o.v. norm eigen monteurs' = ```
			
			IF(
			    [Montage uren t.o.v. totale uren eigen MPS monteurs (projecten en S&O)]<[Norm productiviteit eigen monteurs]
			    ,0
			    ,1 
			)
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Ratios

	measure 'Calculatie projectgebonden uren' = ```
			
			          CALCULATE(
			            SUM('Calculatie kostenregels'[Aantal])
			            ,NOT(ISBLANK('Calculatie kostenregels'[TaakKey]))
			            ,'NR - Taakgroepen DQ'[Taakgroep] = "Projectgebonden"
			            ,'Calculatie kostenregels'[Calculatiestatus] = "Opdracht"
			            )         
			
			```
		formatString: #,##0.0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Project marge incl. omzetcorrectie' = ```
			
			/*
			MCH 20230917;
			Omzet correctie is nog niet beschikbaar in DWH. Met 'Omzet correctie app', die gelijk aan de projectwaardering app, de gebruiker de mogelijkheid moet bieden 
			om de omzet correctie vast te leggen is dit wel mogelijk. De omzetcorrectie kan dan als feitentabel worden opgehaald en onder de projecten worden gekoppeld.
			
			Ter info; de projectwaarderingen die via de projectwaardering app worden gemaakt hoeven niet als aparte tabel te worden gekoppeld. De projectwaarderingen kunnen in Syntess 
			als boeking per project via memoriaal worden ingeboekt. Dit verloopt hierdoor al via de journaalregels.
			
			LET OP; omdat omzet correctie in Professional niet op projectniveau kan worden ingevoerd is het gewenst om dit wel op administratie niveau te doen. Dit moet dan wel aansluiten met 
			de vastgelegde omzetcorrectieregels in de omzet correctie app! De gebruiker kan hier van afwijken (het totaal uit de omzet correctie app en de uiteindelijke ingeboekte 
			omzet correctie in Syntess) waardoor er geen aansluiting is. 
			
			*/
			
			DIVIDE([Project resultaat],[Project omzet])
			```
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Ratios

	measure FTE = ```
			
			var FTE_uren_per_week = MIN('Methode FTE'[Uren per week])
			
			VAR contractenuren = 
			IF(
			    MIN( 'Methode contracturen'[Bron] ) = "Medewerker"
			    ,SUM('Arbeidspatroon per medewerker per week'[contracturen op medewerker])
			    ,SUM('Arbeidspatroon per medewerker per week'[contracturen op arbeidspatroon])
			   )
			   
			VAR aantal_weken_in_selectie =
			    DISTINCTCOUNT('Kalender FTE'[Einddatum Week])
			   
			VAR contracturen_per_week = DIVIDE(contractenuren,aantal_weken_in_selectie)  
			   
			VAR result = 
			
			IF( MAX( 'Bedrijfsmedewerkers'[Ingeleend (Ja/Nee)] ) = "Nee"
			    ,DIVIDE( contracturen_per_week, FTE_uren_per_week )
			    ,BLANK()
			 )
			 
			RETURN
			   result
			```
		formatString: #,##0.0
		displayFolder: 1. Semantisch model\1.02 HR\FTE

	measure 'FTE monteurs' =
			
			CALCULATE (
			    [FTE]
			    ,'NR - MPS functies DQ'[MPS omschrijving] IN { "Project monteurs", "S&O monteurs" }
			    ,'Bedrijfsmedewerkers'[Ingeleend (Ja/Nee)] = "Nee"
			)
		formatString: #,##0.0
		displayFolder: 1. Semantisch model\1.02 HR\FTE

	measure 'FTE projectgebonden' =
			
			CALCULATE (
			    [FTE]
			    ,'NR - MPS functies DQ'[MPS omschrijving] IN { "Project gebonden personeel", "S&O gebonden personeel" }
			    ,'Bedrijfsmedewerkers'[Ingeleend (Ja/Nee)] = "Nee"
			)
		formatString: #,##0.0
		displayFolder: 1. Semantisch model\1.02 HR\FTE

	measure 'FTE Staf' =
			
			CALCULATE (
			    [FTE]
			    ,'NR - MPS functies DQ'[MPS omschrijving] IN { "Staf"}
			    ,'Bedrijfsmedewerkers'[Ingeleend (Ja/Nee)] = "Nee"
			)
		formatString: #,##0.0
		displayFolder: 1. Semantisch model\1.02 HR\FTE

	measure 'FTE monteurs t.o.v. totaal' = DIVIDE([FTE monteurs],[FTE])
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.02 HR\Ratios

	measure 'FTE eigen personeel' =
			
			CALCULATE (
			    [FTE]
			    ,'Bedrijfsmedewerkers'[Ingeleend (Ja/Nee)] = "Nee"
			)
		formatString: 0.0
		displayFolder: 1. Semantisch model\1.02 HR\FTE

	measure 'Gerealiseerde uren eigen personeel' = ```
			
			CALCULATE(
			    SUM('Geboekte uren'[Aantal])
			    ,'Geboekte uren'[verlofsaldoboeking] = "Nee"
			    ,'Bedrijfsmedewerkers'[Ingeleend (Ja/Nee)] = "Nee" 
			)
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Gerealiseerde uren

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Ziekte uren eigen personeel' = ```
			
			CALCULATE(
			    SUM('Geboekte uren'[Aantal])
			    ,'Geboekte uren'[verlofsaldoboeking] = "Nee"
			    ,'Bedrijfsmedewerkers'[Ingeleend (Ja/Nee)] = "Nee" 
			    ,'NR - Taakgroepen DQ'[Taakgroep] in { "Kort ziek", "Langdurig ziek" }
			)
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Gerealiseerde uren

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Ziekteverzuim eigen personeel' = DIVIDE([Ziekte uren eigen personeel],[Gerealiseerde uren eigen personeel])
		formatString: #,##0.0 %
		displayFolder: 1. Semantisch model\1.02 HR\Ratios

	measure 'Ziekte uren kort eigen personeel' = ```
			
			CALCULATE(
			    SUM('Geboekte uren'[Aantal])
			    ,'Geboekte uren'[verlofsaldoboeking] = "Nee"
			    ,'Bedrijfsmedewerkers'[Ingeleend (Ja/Nee)] = "Nee" 
			    ,'NR - Taakgroepen DQ'[Taakgroep] in { "Kort ziek" }
			)
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Gerealiseerde uren

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Ziekte uren langdurig eigen personeel' = ```
			
			CALCULATE(
			    SUM('Geboekte uren'[Aantal])
			    ,'Geboekte uren'[verlofsaldoboeking] = "Nee"
			    ,'Bedrijfsmedewerkers'[Ingeleend (Ja/Nee)] = "Nee" 
			    ,'NR - Taakgroepen DQ'[Taakgroep] in {"Langdurig ziek" }
			)
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Gerealiseerde uren

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Ziekteverzuim kort eigen personeel' = DIVIDE([Ziekte uren kort eigen personeel],[Gerealiseerde uren eigen personeel])
		formatString: #,##0.0 %
		displayFolder: 1. Semantisch model\1.02 HR\Ratios

	measure 'Productieve uren per eigen FTE MPS monteur' = ```
			
			var _FTE_uren_per_week = MIN('Methode FTE'[Uren per week])
			
			
			VAR _contractenuren_monteurs = 
			IF(
			    MIN( 'Methode contracturen'[Bron] ) = "Medewerker"
			    ,
			    CALCULATE(
			        SUM( 'Arbeidspatroon per medewerker per week'[contracturen op medewerker] )
			        ,'NR - MPS functies DQ'[MPS omschrijving] IN { "Project monteurs", "S&O monteurs" }
			        ,'Bedrijfsmedewerkers'[Ingeleend (Ja/Nee)] = "Nee"
			        , USERELATIONSHIP( 'Kalender'[Datum], 'Arbeidspatroon per medewerker per week'[Einddatum Week] )
			    )
			    ,
			    CALCULATE(
			        SUM( 'Arbeidspatroon per medewerker per week'[contracturen op arbeidspatroon] )
			        ,'NR - MPS functies DQ'[MPS omschrijving] IN { "Project monteurs", "S&O monteurs" }
			        ,'Bedrijfsmedewerkers'[Ingeleend (Ja/Nee)] = "Nee"
			        , USERELATIONSHIP( 'Kalender'[Datum], 'Arbeidspatroon per medewerker per week'[Einddatum Week] )
			    )
			)
			   
			VAR _aantal_weken_in_selectie =
			CALCULATE(
			    DISTINCTCOUNT( 'Kalender'[Einddatum Week] )
			    , USERELATIONSHIP( 'Kalender'[Datum], 'Arbeidspatroon per medewerker per week'[Einddatum Week] )
			)
			   
			VAR _contracturen_per_week = DIVIDE(_contractenuren_monteurs,_aantal_weken_in_selectie)  
			   
			VAR _FTE = 
			DIVIDE( _contracturen_per_week, _FTE_uren_per_week )
			  
			VAR result = DIVIDE( [Montage uren eigen MPS monteurs (projecten en S&O)], _FTE)
			
			
			RETURN
			  result
			```
		formatString: #,##0
		displayFolder: 1. Semantisch model\1.02 HR\Ratios

	measure 'Productieve uren per eigen FTE MPS projectgebonden' = ```
			
			var _FTE_uren_per_week = MIN('Methode FTE'[Uren per week])
			
			VAR _contractenuren_projectgebonden = 
			IF(
			    MIN( 'Methode contracturen'[Bron] ) = "Medewerker"
			    ,
			    CALCULATE(
			        SUM( 'Arbeidspatroon per medewerker per week'[contracturen op medewerker] )
			        ,'NR - MPS functies DQ'[MPS omschrijving] IN { "Project gebonden personeel", "S&O gebonden personeel" }
			        ,'Bedrijfsmedewerkers'[Ingeleend (Ja/Nee)] = "Nee"
			        , USERELATIONSHIP( 'Kalender'[Datum], 'Arbeidspatroon per medewerker per week'[Einddatum Week] )
			    )
			    ,
			    CALCULATE(
			        SUM( 'Arbeidspatroon per medewerker per week'[contracturen op arbeidspatroon] )
			        ,'NR - MPS functies DQ'[MPS omschrijving] IN {  "Project gebonden personeel", "S&O gebonden personeel"  }
			        ,'Bedrijfsmedewerkers'[Ingeleend (Ja/Nee)] = "Nee"
			        , USERELATIONSHIP( 'Kalender'[Datum], 'Arbeidspatroon per medewerker per week'[Einddatum Week] )
			    )
			)
			
			VAR _aantal_weken_in_selectie =
			CALCULATE(
			    DISTINCTCOUNT( 'Kalender'[Einddatum Week] )
			    , USERELATIONSHIP( 'Kalender'[Datum], 'Arbeidspatroon per medewerker per week'[Einddatum Week] )
			)
			   
			VAR _contracturen_per_week = DIVIDE( _contractenuren_projectgebonden,_aantal_weken_in_selectie)  
			   
			VAR _FTE = 
			DIVIDE( _contracturen_per_week, _FTE_uren_per_week )
			  
			VAR result = DIVIDE( [Montage uren eigen MPS projectgebonden personeel (projecten en S&O)], _FTE)
			
			
			RETURN
			  result
			```
		formatString: #,##0
		displayFolder: 1. Semantisch model\1.02 HR\Ratios

	measure 'Montage uren t.o.v. totale uren eigen projectgebonden personeel (projecten en S&O)' = DIVIDE([Montage uren eigen MPS monteurs (projecten en S&O)],[Gerealiseerde uren eigen MPS monteurs])
		formatString: #,##0 %
		displayFolder: 1. Semantisch model\1.02 HR\Ratios

	measure 'Montage uren eigen MPS projectgebonden personeel (projecten en S&O)' = ```
			
			VAR werkuren_urenstaat =
			    CALCULATE(
			    SUM('Project kosten en geboekte uren'[Aantal])
			    ,'NR - Taakgroepen DQ'[Taakgroep] = "Projectgebonden"
			    ,'NR - MPS functies DQ'[MPS omschrijving] IN { "Project gebonden personeel", "S&O gebonden personeel" }
			    ,'Bedrijfsmedewerkers'[Ingeleend (Ja/Nee)] = "Nee"
			)
			
			VAR result = werkuren_urenstaat 
			
			RETURN
			result
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid

	measure 'Ondergrens orderwaarde' = MIN('Methode budgetverzoek bewaking'[minimale orderwaarde])
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Algemeen

	measure 'Aantal budgetverzoeken met order filter' = ```
			
			VAR result =
			
			CALCULATE(
			    DISTINCTCOUNT('NR - Projectbudgetverzoeken DQ'[BudgetverzoekKey] )
			    , 'Projecten'[Hoofdproject soort] = "Eenmalig"
			    , 'Projecten'[Hoofdproject totaal orderbedrag] > MIN( 'Methode budgetverzoek bewaking'[minimale orderwaarde] )
			)
			
			 
			RETURN
			    result
			
			
			```
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectbewaking\Budgetverzoeken actuele projecten

	measure 'Aantal budgetverzoeken Aantal budgetverzoeken met order filter met 0' = ```
			
			VAR _aantal_budgetverzoeken =
			CALCULATE(
			    DISTINCTCOUNT('NR - Projectbudgetverzoeken DQ'[BudgetverzoekKey] )
			    , 'Projecten'[Hoofdproject soort] = "Eenmalig"
			    , 'Projecten'[Hoofdproject totaal orderbedrag] > MIN( 'Methode budgetverzoek bewaking'[minimale orderwaarde] )
			)
			
			VAR _aantal_hoofdprojecten =
			CALCULATE(
			    DISTINCTCOUNT('Projecten'[hoofdprojectkey] )
			    ,'Projecten'[Hoofdproject soort] = "Eenmalig"
			    ,'Projecten'[Hoofdproject totaal orderbedrag]  > MIN('Methode budgetverzoek bewaking'[minimale orderwaarde])
			)
			
			VAR result = 
			    IF(
			        NOT( ISBLANK( _aantal_hoofdprojecten ) )
			        , IF(
			            ISBLANK( _aantal_budgetverzoeken )
			            , 0
			            , _aantal_budgetverzoeken
			        )
			        
			    )
			 
			RETURN
			    result
			
			
			```
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectbewaking\Budgetverzoeken actuele projecten

	measure Productiviteit = ```
			
			VAR directe_uren = CALCULATE(SUM('Geboekte uren'[Aantal]),'NR - Taakgroepen DQ'[Type] = "Direct")
			VAR totale_uren = SUM('Geboekte uren'[Aantal])
			
			RETURN 
			DIVIDE(directe_uren,totale_uren)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 1. Semantisch model\1.02 HR\Ratios

	measure Omzet/kosten = DIVIDE( [Project omzet], [Definitieve kostprijs])
		formatString: #,##0.0 %
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Totaal budgetverzoek/Projectwaarde' = DIVIDE([Verzoek Kosten],[Orderbedrag])
		formatString: #,##0.0 %
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure OHW =
			
			CALCULATE(
			    SUM( Journaalregels[Creditbedrag] ) - SUM( Journaalregels[Debetbedrag] ),
			    'NR - CoA balans schema'[Code] = 104002
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA Balans

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Prognose vs budget' = DIVIDE([Prognose marge],[Project marge])
		formatString: #,##0.0 %
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Ratios

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Aantal werkbonnen' = DISTINCTCOUNT(Werkbonnen[WerkbonDocumentKey])
		formatString: #,##0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonnen

	measure 'Aantal hoofdwerkbonnen' = DISTINCTCOUNT(Werkbonnen[HoofdwerkbonDocumentKey])
		formatString: #,##0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonnen

	measure 'Aantal werkbonparagrafen onderhoud' =
			
			CALCULATE(
			    DISTINCTCOUNT( Werkbonparagrafen[WerkbonparagraafKey] )
			    , Werkbonparagrafen[type] = "Onderhoud"
			)
		formatString: #,##0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen

	measure 'Aantal unieke installaties op bestekparagraaf' = DISTINCTCOUNT(Bestekparagrafen[InstallatieKey])
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Installaties

	measure 'Aantal installaties op bestekparagraaf' = COUNT(Bestekparagrafen[InstallatieKey])
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Installaties

	measure 'Aantal unieke installaties op bestekparagraaf onderhoud' =
			
			CALCULATE(
			    DISTINCTCOUNT( Bestekparagrafen[InstallatieKey] )
			    , Bestekparagrafen[Bestekparagraaf type] = "Onderhoud" || Bestekparagrafen[Bestekparagraaf type] = "Onderhoud en Storing"
			)
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Installaties

	measure 'Aantal unieke installaties op bestekparagraaf storing' =
			
			CALCULATE(
			    DISTINCTCOUNT( Bestekparagrafen[InstallatieKey] )
			    , Bestekparagrafen[Bestekparagraaf type] = "Storing"
			)
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Installaties

	measure 'Aantal objecten op bestekparagraaf' = COUNT(Bestekparagrafen[ObjectKey])
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Objecten

	measure 'Aantal unieke objecten op bestekparagraaf' = DISTINCTCOUNT(Bestekparagrafen[ObjectKey])
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Objecten

	measure 'Aantal installaties in database' = DISTINCTCOUNT(Installaties[InstallatieKey])
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Installaties

	measure 'Aantal objecten' = DISTINCTCOUNT(Objecten[ObjectKey])
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Objecten

	measure 'Aantal unieke objecten op bestekparagraaf onderhoud' =
			
			CALCULATE(
			    DISTINCTCOUNT( Bestekparagrafen[ObjectKey] )
			    , Bestekparagrafen[Bestekparagraaf type] = "Onderhoud" || Bestekparagrafen[Bestekparagraaf type] = "Onderhoud en Storing"
			)
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Objecten

	measure 'Aantal unieke objecten op bestekparagraaf storing' =
			
			CALCULATE(
			    DISTINCTCOUNT( Bestekparagrafen[ObjectKey] )
			    , Bestekparagrafen[Bestekparagraaf type] = "Storing"
			)
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Objecten

	measure 'Aantal installaties' =
			
			/*
			Het aantal installaties voor het berekenen van de storingsgraad is afhankelijk van de definitie die de klant heeft.
			
			Zie hieronder een mogelijk uitgangspunt
			*/
			
			[Aantal unieke installaties op bestekparagraaf storing zonder einddatum of einddatum in toekomst]
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Installaties

	measure 'Aantal unieke installaties op bestekparagraaf storing zonder einddatum of einddatum in toekomst' =
			
			CALCULATE(
			    DISTINCTCOUNT( Bestekparagrafen[InstallatieKey] )
			    , Bestekparagrafen[Bestekparagraaf type] = "Storing"
			    , Bestekparagrafen[Bestekparagraaf einddatumstatus]= "Geen einddatum"
			    || Bestekparagrafen[Bestekparagraaf einddatumstatus]= "Einddatum in toekomst"
			)
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Installaties

	measure 'Aantal installaties met bouwjaar' =
			
			/*
			Het aantal installaties voor het berekenen van de storingsgraad is afhankelijk van de definitie die de klant heeft.
			
			Zie hieronder een mogelijk uitgangspunt
			*/
			
			CALCULATE(
			    [Aantal installaties]
			    ,NOT( ISBLANK( Bestekparagrafen[Installatie bouwjaar] ) )
			)
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Installaties

	measure '% urenstaat projectboekingen t.o.v. salaris' =
			
			DIVIDE([Urenstaat kosten op project],[Salarissen])
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.01 Financieel\Ratios en verschillen

	measure '% urenstaat totaal t.o.v. salaris' = DIVIDE([Urenstaat kosten op project]+[Urenstaat kosten niet op project],[Salarissen])
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Salarissen en uren

	measure 'Aantal openstaande documenten' = SUM('Openstaande documenten'[Aantal documenten])
		formatString: 0
		displayFolder: 1. Semantisch model\1.01 Financieel\Algemeen

	measure 'Achtergrond kleur melding geselecteerde rekeningschemas' = ```
			
			IF(
			    ISBLANK( SELECTEDVALUE( 'Rekeningschemas'[RekeningSchemaKey] ) ) 
			    ,"#E6E6E6"
			    , IF(
			        DISTINCTCOUNT( 'Rekeningschemas'[RekeningschemaKey] ) = 1
			        , "#FFFFFF00"
			        , "#E6E6E6"
			    )
			)
			```
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Meldingen

	measure 'Achtergrond kleur waarschuwing niet compleet rekeningschema balans' = ```
			
			IF(
			    [Controle niet gekoppelde balans rubrieken geselecteerd rekeningschema] < -1 || [Controle niet gekoppelde balans rubrieken geselecteerd rekeningschema] > 1 
			    ,"#E6E6E6"
			    ,"#FFFFFF00"
			)
			```
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Meldingen

		changedProperty = IsHidden

	measure 'Achtergrond kleur waarschuwing niet compleet rekeningschema W&V' = ```
			
			IF(
			    [Controle niet gekoppelde W&V rubrieken geselecteerd rekeningschema] < -1 || [Controle niet gekoppelde W&V rubrieken geselecteerd rekeningschema] > 1 
			    ,"#E6E6E6"
			    ,"#FFFFFF00"
			)
			```
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Meldingen

		changedProperty = IsHidden

	measure Bank = [Bank Debet]-[Bank Credit]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Cash flow\Bank

	measure 'Bank met voorfinanciering' = [Bank]+[Voorfinanciering]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Balans\Liquiditeit

	measure 'Boekdatum bijgewerkt tot' =
			
			IF(
			    MAX('Kalender'[Datum])>Today()
			    ,TODAY()-1
			    ,MAX('Kalender'[Datum])
			
			)
		formatString: Short Date
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Algemeen

		changedProperty = IsHidden

	measure 'Controle einddatum - type 1' = ```
			
			//Focus op vergelijking huidig jaar met vorig jaar. De einddatum mag hiervoor niet in de toekomst liggen. 
			    IF(
			        MAX('Kalender'[Datum])> today()
			        ,"LET OP; geselecteerde einddatum ligt in de toekomst! Huidig en vorig jaar kunnen niet worden vergeleken."
			        ,IF(
			            MONTH(MAX('Kalender'[Datum]))=MONTH(TODAY())
			            ,"LET OP: geselecteerde einddatum is in huidige maand. Deze periode is financieel nog niet definitief!"
			        , CONCATENATE("De geselecteerde einddatum is: ",FORMAT(MAX('Kalender'[Datum]),"dd-mm-yyyy"))
			        )
			    )
			        
			
			
			```
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Controle

		changedProperty = IsHidden

	measure 'Controle einddatum - type 3' = ```
			
			//Focus op vergelijking huidig jaar met vorig jaar. De einddatum mag hiervoor niet in de toekomst liggen. 
			//Tevens attentie wanneer einddatum in het verleden ligt.
			    IF(
			        MAX('Kalender'[Datum])> today()-1
			        ,"LET OP; geselecteerde einddatum ligt in de toekomst! Huidig en vorig jaar kunnen niet worden vergeleken. Selecteer de einddatum: " & FORMAT(TODAY()-1,"DD-MM-YYYY")
			        ,IF(
			            MAX('Kalender'[Datum])=TODAY()-1
			            ,""
			        , "LET OP: geselecteerde einddatum ligt in het verleden. Dit is niet de actuele stand. Selecteer einddatum: " & FORMAT(TODAY()-1,"DD-MM-YYYY")
			        )
			    )
			```
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Controle

		changedProperty = IsHidden

	measure 'Controle einddatum - type 4' =
			
			//Attentie wanneer einddatum in correct geselecteerd is.
			IF(
			    MAX('Kalender'[Datum])=TODAY()-1
			    ,"U heeft de meest actuele stand geselecteerd."
			    ,""
			    )
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Controle

		changedProperty = IsHidden

	measure 'Controle einddatum rekeningschema - goed' = ```
			
			//Focus of een periode financieel afgerond is. 
			    IF(
			        MAX('Kalender'[Datum])> today()
			        ,""
			        ,IF(
			            MONTH(MAX('Kalender'[Datum]))=MONTH(TODAY())
			            ,""
			        , CONCATENATE("De geselecteerde einddatum is: ",FORMAT(MAX('Kalender'[Datum]),"dd-mm-yyyy"))
			        )
			    )
			```
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Controle

		changedProperty = IsHidden

	measure 'Controle einddatum rekeningschema - slecht' = ```
			
			//Focus of een periode financieel afgerond is. 
			    IF(
			        MAX('Kalender'[Datum])> today()
			        ,"LET OP; geselecteerde einddatum ligt in de toekomst! De huidige maand is financieel nog niet definitief!"
			        ,IF(
			            MONTH(MAX('Kalender'[Datum]))=MONTH(TODAY())
			            ,"LET OP: geselecteerde einddatum is in huidige maand. Deze periode is financieel nog niet definitief!"
			        , ""
			        )
			    )
			```
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Controle

		changedProperty = IsHidden

	measure 'Controle einddatum rekeningschema - slecht - achtergrond' = ```
			
			//Focus of een periode financieel afgerond is. 
			    IF(
			        MAX('Kalender'[Datum])> today()
			        ,1
			        ,IF(
			            MONTH(MAX('Kalender'[Datum]))=MONTH(TODAY())
			            ,1
			        , 0
			        )
			    )
			```
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Controle

		changedProperty = IsHidden

	measure 'Controle niet gekoppelde balans rubrieken geselecteerd rekeningschema' = ```
			
			var controle =( [Credit balans] - [Credit Balans ongeacht rekeningschema] )+([Debet balans]-[Debet Balans ongeacht rekeningschema])
			var test =( [Credit balans]  )+([Debet balans])
			 
			VAR result = controle
			
			return
			    IF(
			        result >-1 && result <1
			        ,BLANK()
			        ,result
			    )
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Controle

		changedProperty = IsHidden

	measure 'Controle niet gekoppelde W&V rubrieken geselecteerd rekeningschema' = ```
			
			    var controle = [resultaat W&V] - [resultaat W&V ongeacht rekeningschema]
			    return
			    IF(
			        controle >-1 && controle <1
			        ,BLANK()
			        ,controle
			    )
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Controle

		changedProperty = IsHidden

	measure 'Credit Balans ongeacht rekeningschema' =
			
			CALCULATE(
			    [Credit balans]
			    ,ALL(Rekeningschemas)
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Overig

		changedProperty = IsHidden

	measure Crediteuren =
			calculate(
			    [Actual credit-YTD Balans]-[Actual debet-YTD Balans]
			    ,Rubrieken[Rubriek categorie]="Crediteuren"
			    )*-1
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Balans\Liquiditeit

	measure 'Crediteuren neg' =
			calculate(
			    [Actual credit-YTD Balans]-[Actual debet-YTD Balans]
			    ,Rubrieken[Rubriek categorie]="Crediteuren"
			    )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Balans\Liquiditeit

	measure 'Current ratio' = DIVIDE( ( [Debiteuren] + [Bank] + [Voorraad] ), [Crediteuren] )
		formatString: 0.00
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Balans\Liquiditeit

	measure 'Debet Balans ongeacht rekeningschema' =
			
			CALCULATE(
			    [Debet balans]
			    ,ALL(Rekeningschemas)
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Overig

		changedProperty = IsHidden

	measure Debiteuren =
			calculate(
			    [Actual debet-YTD Balans]-[Actual credit-YTD Balans]
			    ,Rubrieken[Rubriek categorie]="Debiteuren"
			    )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Balans\Liquiditeit

	measure 'Eerste datum afgesloten periode' = ```
			
			//Om het resultaat te tonen voor een afgesloten periode
			//Tot én met 10 dagen in de maand 2 maanden terug en na 10 dagen in de maand 1 maand terug (bijv. 8 aug; juni tonen en 11 aug.; juli tonen). 
			var periode_a =
			//Betreft einde maand van 2 maanden terug voor eerste 10 dagen.
			    CALCULATE(
			        MIN('Kalender'[Datum])
			        ,PREVIOUSMONTH(PREVIOUSMONTH('Kalender'[Datum]))
			        )
			//Betreft einde maand van vorige maand voor alles dagen na de 10e dag in de maand
			var periode_b =
			    CALCULATE(
			        MIN('Kalender'[Datum])
			        ,PREVIOUSMONTH('Kalender'[Datum])
			        )
			return
			IF(
			    DAY(MAX('Kalender'[Datum]))<=10
			    ,periode_a
			    ,periode_b
			)
			
			
			```
		formatString: d-m-yyyy
		isHidden
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Algemeen

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Goal Current ratio' = 1.5
		formatString: #,##0.00
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Balans\Liquiditeit

	measure 'Jaar bijgewerkt tot' = ```
			
			    YEAR([Boekdatum bijgewerkt tot])
			```
		formatString: 0
		isHidden
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Algemeen

		changedProperty = IsHidden

	measure 'Jaar en einddatum laatste afgesloten periode' = ```
			
			//Om het resultaat te tonen voor een afgesloten periode
			//Tot én met 10 dagen in de maand 2 maanden terug en na 10 dagen in de maand 1 maand terug (bijv. 8 aug; juni tonen en 11 aug.; juli tonen). 
			var periode_a =
			//Betreft einde maand van 2 maanden terug voor eerste 10 dagen.
			    CALCULATE(
			        MAX('Kalender'[Datum])
			        ,PREVIOUSMONTH(PREVIOUSMONTH('Kalender'[Datum]))
			        )
			//Betreft einde maand van vorige maand voor alles dagen na de 10e dag in de maand
			var periode_b =
			    CALCULATE(
			        MAX('Kalender'[Datum])
			        ,PREVIOUSMONTH('Kalender'[Datum])
			        )
			return
			IF(
			    DAY(MAX('Kalender'[Datum]))<=10
			    ,"Jaar: " & FORMAT(periode_a,"YYYY") & " tot en met " & FORMAT(periode_a,"DD-MM-YYYY")
			    ,"Jaar: " & FORMAT(periode_b,"YYYY") & " tot en met " & FORMAT(periode_b,"DD-MM-YYYY")
			)
			
			
			```
		isHidden
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Algemeen

		changedProperty = IsHidden

	measure 'Jaar LY en einddatum LY laatste afgesloten periode' = ```
			
			//Om het resultaat te tonen voor een afgesloten periode
			//Tot én met 10 dagen in de maand 2 maanden terug en na 10 dagen in de maand 1 maand terug (bijv. 8 aug; juni tonen en 11 aug.; juli tonen). 
			var periode_a =
			//Betreft einde maand van 2 maanden terug voor eerste 10 dagen.
			    CALCULATE(
			        MAX('Kalender'[Datum])
			        ,SAMEPERIODLASTYEAR(PREVIOUSMONTH(PREVIOUSMONTH('Kalender'[Datum])))
			        )
			//Betreft einde maand van vorige maand voor alles dagen na de 10e dag in de maand
			var periode_b =
			    CALCULATE(
			        MAX('Kalender'[Datum])
			        ,SAMEPERIODLASTYEAR(PREVIOUSMONTH('Kalender'[Datum]))
			        )
			return
			IF(
			    DAY(MAX('Kalender'[Datum]))<=10
			    ,"Jaar LY: " & FORMAT(periode_a,"YYYY") & " tot en met " & FORMAT(periode_a,"DD-MM-YYYY")
			    ,"Jaar LY: " & FORMAT(periode_a,"YYYY") & " tot en met " & FORMAT(periode_a,"DD-MM-YYYY")
			)
			
			```
		isHidden
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Algemeen

		changedProperty = IsHidden

	measure 'Laatste facturatie datum' = ```
			
			var laatstefacturatiedatum =
			CALCULATE(
			    MAX(Journaalregels[Boekdatum])
			    ,Rubrieken[Rubriek Code] = "8000" 
			    || Rubrieken[Rubriek Code] = "8100"
			    || Rubrieken[Rubriek Code] = "8110"
			    || Rubrieken[Rubriek Code] = "8200"
			    || Rubrieken[Rubriek Code] = "8700"
			    || Rubrieken[Rubriek Code] = "8710"   
			    || Rubrieken[Rubriek Code] = "8300" 
			    || Rubrieken[Rubriek Code] = "8500"
			    || Rubrieken[Rubriek Code] = "8510"
			    || Rubrieken[Rubriek Code] = "8600"
			    || Rubrieken[Rubriek Code] = "8610"
			    || Rubrieken[Rubriek Code] = "8620"
			    || Rubrieken[Rubriek Code] = "8800"
			    || Rubrieken[Rubriek Code] = "8803"
			    || Rubrieken[Rubriek Code] = "8880"
			    || Rubrieken[Rubriek Code] = "8881"
			    || Rubrieken[Rubriek Code] = "8883"
			    || Rubrieken[Rubriek Code] = "8990"
			    ,Journaalregels[Boekdatum]<TODAY()
			)
			return
			"Laatste Facturatiedatum: " & FORMAT(laatstefacturatiedatum,"DD-MM-YYYY")
			```
		isHidden
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Algemeen

		changedProperty = IsHidden

	measure 'Maand laatste afgesloten periode' = ```
			
			//Om het resultaat te tonen voor een afgesloten periode
			//Tot én met 10 dagen in de maand 2 maanden terug en na 10 dagen in de maand 1 maand terug (bijv. 8 aug; juni tonen en 11 aug.; juli tonen). 
			var periode_a =
			//Betreft einde maand van 2 maanden terug voor eerste 10 dagen.
			    CALCULATE(
			        MAX('Kalender'[Datum])
			        ,PREVIOUSMONTH(PREVIOUSMONTH('Kalender'[Datum]))
			        )
			//Betreft einde maand van vorige maand voor alles dagen na de 10e dag in de maand
			var periode_b =
			    CALCULATE(
			        MAX('Kalender'[Datum])
			        ,PREVIOUSMONTH('Kalender'[Datum])
			        )
			return
			IF(
			    DAY(MAX('Kalender'[Datum]))<=10
			    ,"Maand: " & FORMAT(periode_a,"MMMM YYYY")
			    ,"Maand: " & FORMAT(periode_b,"MMMM YYYY")
			)
			
			
			```
		isHidden
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Algemeen

		changedProperty = IsHidden

	measure 'Melding aantal geselecteerde rekeningschemas' = ```
			IF(
			    ISBLANK( SELECTEDVALUE( 'Rekeningschemas'[RekeningSchemaKey] ) ) 
			    ,"Selecteer één specifiek rekeningschema."
			    , IF(
			        DISTINCTCOUNT( 'Rekeningschemas'[RekeningschemaKey] ) = 1
			        , ""
			        , "Selecteer één rekeningschema."
			    )
			)
			```
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Meldingen

	measure 'Melding periode YTDLY' = ```
			
			
			"Periode: "
			&FORMAT(
			    CALCULATE(
			        MIN('Kalender'[Datum])
			        ,SAMEPERIODLASTYEAR('Kalender'[Datum])
			    )
			    ,"dd-mm-yyyy"
			)
			&" t/m "
			&FORMAT(
			    CALCULATE(
			        MAX('Kalender'[Datum])
			        ,SAMEPERIODLASTYEAR('Kalender'[Datum])
			    )
			    ,"dd-mm-yyyy"
			)
			
			
			```
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Meldingen

		changedProperty = IsHidden

	measure 'melding resultaat cumulatief' = ```
			
			"Resultaat cumulatief in periode: "
			&FORMAT(MIN('Kalender'[Datum]),"dd-mm-yyyy")
			&" t/m "
			&FORMAT(MAX('Kalender'[Datum]),"dd-mm-yyyy")
			
			```
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Meldingen

	measure 'melding resultaat cumulatief LY' = ```
			
			
			"Resultaat cumulatief in periode: "
			&FORMAT(
			    CALCULATE(
			        MIN('Kalender'[Datum])
			        ,SAMEPERIODLASTYEAR('Kalender'[Datum])
			    )
			    ,"dd-mm-yyyy"
			)
			&" t/m "
			&FORMAT(
			    CALCULATE(
			        MAX('Kalender'[Datum])
			        ,SAMEPERIODLASTYEAR('Kalender'[Datum])
			    )
			    ,"dd-mm-yyyy"
			)
			
			```
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Meldingen

	measure 'melding resultaat per boekingsperiode' =
			
			"Resultaat per boekingsperiode: "
			&FORMAT(MIN('Kalender'[Datum]),"dd-mm-yyyy")
			&" t/m "
			&FORMAT(MAX('Kalender'[Datum]),"dd-mm-yyyy")
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Meldingen

	measure 'melding resultaat per boekingsperiode LY' = ```
			
			
			"Resultaat per boekingsperiode: "
			&FORMAT(
			    CALCULATE(
			        MIN('Kalender'[Datum])
			        ,SAMEPERIODLASTYEAR('Kalender'[Datum])
			    )
			    ,"dd-mm-yyyy"
			)
			&" t/m "
			&FORMAT(
			    CALCULATE(
			        MAX('Kalender'[Datum])
			        ,SAMEPERIODLASTYEAR('Kalender'[Datum])
			    )
			    ,"dd-mm-yyyy"
			)
			
			```
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Meldingen

	measure 'Quick ratio' = DIVIDE( ( [Debiteuren] + [Bank] ), [Crediteuren neg] )
		formatString: 0.00
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Balans\Liquiditeit

	measure 'resultaat W&V ongeacht rekeningschema' =
			
			
			CALCULATE(
			    [Actual mutatie exploitatierekening]
			    ,ALL(Rekeningschemas)
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Overig

		changedProperty = IsHidden

	measure Salarissen =
			
			CALCULATE(
			    [Actual mutatie exploitatierekening]
			    ,'NR - CoA schema' [Code] IN {105001,105002,105003,105004}
			)*-1
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Salarissen en uren

	measure tussenkop_1 = ""
		displayFolder: 1. Semantisch model\1.99 Overig\Algemeen

		changedProperty = IsHidden

	measure tussenkop_2 = ""
		displayFolder: 1. Semantisch model\1.99 Overig\Algemeen

		changedProperty = IsHidden

	measure tussenkop_3 = ""
		displayFolder: 1. Semantisch model\1.99 Overig\Algemeen

		changedProperty = IsHidden

	measure 'Urenstaat kosten niet op project' =
			
			CALCULATE(
			    [Actual mutatie exploitatierekening]
			    ,'Journaalregels'[projectgerelateerd] = "Nee"
			    ,Rubrieken[Toepassing]="Kostenrekening"
			    ,'Documenten'[StandaardEntiteitKey]=175
			) *-1
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Salarissen en uren

	measure 'Urenstaat kosten op project' =
			
			CALCULATE(
			    [Actual mutatie exploitatierekening]
			   ,'Journaalregels'[projectgerelateerd] = "Ja"
			    ,Rubrieken[Toepassing]="Kostenrekening"
			    ,'Documenten'[StandaardEntiteitKey]=175
			) *-1
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Salarissen en uren

	measure 'Urenstaat tegenboeking' =
			
			CALCULATE(
			    [Actual mutatie exploitatierekening]
			    ,Rubrieken[Toepassing]="Dagboek"
			    ,'Documenten'[StandaardEntiteitKey]=175
			) *-1
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Salarissen en uren

	measure Voorfinanciering = [Openstaande inkoopfacturen per categorie] - [Openstaande verkoopfacturen per categorie]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Voorfinanciering

	measure Voorraad =
			calculate(
			    [Actual debet-YTD Balans]-[Actual credit-YTD Balans]
			    ,'Rubrieken'[Toepassing]= "Magazijn"
			    )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Balans\Liquiditeit

	measure 'Waarschuwing niet compleet rekeningschema Balans' = ```
			
			IF(
			    [Controle niet gekoppelde balans rubrieken geselecteerd rekeningschema] < -1 || [Controle niet gekoppelde balans rubrieken geselecteerd rekeningschema] > 1 
			    ,"LET OP: Niet alle rubrieken zijn gekoppeld in het rekeningschema!"
			    ,""
			)
			```
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Meldingen

		changedProperty = IsHidden

	measure 'Waarschuwing niet compleet rekeningschema W&V' = ```
			
			IF(
			    [Controle niet gekoppelde W&V rubrieken geselecteerd rekeningschema] < -1 || [Controle niet gekoppelde W&V rubrieken geselecteerd rekeningschema] > 1 
			    ,"LET OP: Niet alle rubrieken zijn gekoppeld in het rekeningschema!"
			    ,""
			)
			```
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Meldingen

		changedProperty = IsHidden

	measure 'Week bijgewerkt tot' = ```
			
			    WEEKNUM([Boekdatum bijgewerkt tot])
			```
		formatString: 0
		isHidden
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Algemeen

		changedProperty = IsHidden

	measure '% overuren' = DIVIDE( [Overuren],[Gerealiseerde uren excl. saldo-uren] ,blank())
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 1. Semantisch model\1.02 HR\Ratios

	measure '% reistijd direct' = ```
			 DIVIDE([Directe reisuren eigen personeel],[Directe uren eigen personeel],0)
			```
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.02 HR\Ratios

	measure '% reistijd indirect' = ```
			 DIVIDE([Indirecte reisuren eigen personeel],[Indirecte uren eigen personeel])
			```
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.02 HR\Ratios

	measure 'Bron contracturen' =
			
			MIN('Methode contracturen'[Bron])
		displayFolder: 1. Semantisch model\1.02 HR

		changedProperty = IsHidden

	measure 'Contracturen excl. saldo uren' =
			
			CALCULATE(
			    SUM('Geboekte uren'[Aantal])
			    ,'Geboekte uren'[Contracturen] = "Ja"
			    ,NOT(ISBLANK('Geboekte uren'[TaakKey]))
			    ,'Geboekte uren'[verlofsaldoboeking] = "Nee"
			)
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Realisatie

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Directe (productieve) uren totaal' =
			
			CALCULATE(
					SUM('Geboekte uren'[Aantal])
			        , 'Geboekte uren'[projectgerelateerd Ja/Nee]="Ja"
			        ,NOT(ISBLANK('Geboekte uren'[TaakKey]))
			        ,'Geboekte uren'[verlofsaldoboeking] = "Nee"
				)
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Realisatie

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Directe reisuren eigen personeel' =
			
			CALCULATE(
			        SUM('Geboekte uren'[Aantal])
			        , 'Geboekte uren'[projectgerelateerd Ja/Nee]="Ja"
			        ,'Bedrijfsmedewerkers'[Ingeleend (Ja/Nee)] = "Nee"
			        ,'Geboekte uren'[verlofsaldoboeking] = "Nee"
			        ,CONTAINSSTRING(Taken[Taak],"reis") || Taken[Type] = "Reizen"
			  )
		formatString: #,##0.0
		displayFolder: 1. Semantisch model\1.02 HR\Realisatie

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Directe uren eigen personeel' =
			
			CALCULATE(
			        SUM('Geboekte uren'[Aantal])
			        , 'Geboekte uren'[projectgerelateerd Ja/Nee]="Ja"
			       ,'Bedrijfsmedewerkers'[Ingeleend (Ja/Nee)] = "Nee"
			        ,'Geboekte uren'[verlofsaldoboeking] = "Nee"
			        ,NOT(ISBLANK('Geboekte uren'[TaakKey])
			    ))
		formatString: #,0
		displayFolder: 1. Semantisch model\1.02 HR\Realisatie

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Directe uren ingeleend personeel' =
			
			CALCULATE(
			        SUM('Geboekte uren'[Aantal])
			        , 'Geboekte uren'[projectgerelateerd Ja/Nee]="Ja"
			        ,'Bedrijfsmedewerkers'[Ingeleend (Ja/Nee)] = "Ja"
			        ,'Geboekte uren'[verlofsaldoboeking] = "Nee"
			        ,NOT(ISBLANK('Geboekte uren'[TaakKey]))
			    )
		formatString: #,0
		displayFolder: 1. Semantisch model\1.02 HR\Realisatie

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Directe werkuren zonder reizen eigen personeel' = ```
			
			CALCULATE(
			        SUM('Geboekte uren'[Aantal])
			        , 'Geboekte uren'[projectgerelateerd Ja/Nee]="Ja"
			       ,'Bedrijfsmedewerkers'[Ingeleend (Ja/Nee)] = "Nee"
			        ,'Geboekte uren'[verlofsaldoboeking] = "Nee"
			        ,NOT(CONTAINSSTRING(Taken[Taak],"reis")) 
			        , Taken[Type] <> "Verlof"
			    )
			```
		formatString: #,##0.0
		displayFolder: 1. Semantisch model\1.02 HR\Realisatie

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Doel ziekteverzuim' =
			IF(
									ISBLANK([Ziekteverzuim zonder blank])
									,BLANK()
									,0.04
			)
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.02 HR\Ratios

	measure Feestdagen =
			
			CALCULATE(
			    [Gerealiseerde uren excl. saldo-uren]
			    ,CONTAINSSTRING(Taken[Taak],"feest")
			)
		formatString: #,0
		displayFolder: 1. Semantisch model\1.02 HR\Realisatie

	measure 'FTE beginstand' = ```
			
			VAR begindatum = MIN(kalender[Datum])
			VAR contracturen = 
			IF(
			    MIN('Methode contracturen'[Bron]) = "Medewerker"
			   ,CALCULATE(
			       SUM('Arbeidspatroon per medewerker'[contracturen op medewerker])
			       ,CALCULATETABLE(
			        'Arbeidspatroon per medewerker'
			        ,'Arbeidspatroon per medewerker'[Ingangsdatum]<=begindatum
			        ,'Arbeidspatroon per medewerker'[Einddatum]>=begindatum || ISBLANK('Arbeidspatroon per medewerker'[Einddatum])
			        )
			    )
			    ,CALCULATE(
			        SUM('Arbeidspatroon per medewerker'[contracturen op arbeidspatroon])
			        ,CALCULATETABLE(
			        'Arbeidspatroon per medewerker'
			        ,'Arbeidspatroon per medewerker'[Ingangsdatum]<=begindatum
			        ,'Arbeidspatroon per medewerker'[Einddatum]>=begindatum || ISBLANK('Arbeidspatroon per medewerker'[Einddatum])
			        )
			    )
			)
			var FTE_uren = MIN('Methode FTE'[Uren per week])
			RETURN
			DIVIDE(contracturen,FTE_uren)
			```
		formatString: #,##0.0
		displayFolder: 2. Rapport Specifieke Objecten\2.02 Best practice HR

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FTE eindstand' = ```
			
			VAR einddatum = MAX(kalender[Datum])
			VAR contracturen = 
			IF(
			    MIN('Methode contracturen'[Bron]) = "Medewerker"
			   ,CALCULATE(
			       SUM('Arbeidspatroon per medewerker'[contracturen op medewerker])
			       ,CALCULATETABLE(
			        'Arbeidspatroon per medewerker'
			        ,'Arbeidspatroon per medewerker'[Ingangsdatum]<=einddatum
			        ,'Arbeidspatroon per medewerker'[Einddatum]>=einddatum || ISBLANK('Arbeidspatroon per medewerker'[Einddatum])
			        )
			    )
			    ,CALCULATE(
			        SUM('Arbeidspatroon per medewerker'[contracturen op arbeidspatroon])
			        ,CALCULATETABLE(
			        'Arbeidspatroon per medewerker'
			        ,'Arbeidspatroon per medewerker'[Ingangsdatum]<=einddatum
			        ,'Arbeidspatroon per medewerker'[Einddatum]>=einddatum || ISBLANK('Arbeidspatroon per medewerker'[Einddatum])
			        )
			    )
			)
			var FTE_uren = MIN('Methode FTE'[Uren per week])
			RETURN
			DIVIDE(contracturen,FTE_uren)
			```
		formatString: #,##0.0
		displayFolder: 2. Rapport Specifieke Objecten\2.02 Best practice HR

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FTE uren per week' =
			
			MIN('Methode FTE'[Uren per week])
		formatString: 0.0
		displayFolder: 2. Rapport Specifieke Objecten\2.02 Best practice HR

		changedProperty = IsHidden

	measure 'Gerealiseerde Contracturen' =
			
			CALCULATE(
					SUM('Geboekte uren'[Aantal]),
					ALL(Taken),
					'Geboekte uren'[Contracturen] = "Ja"
				)
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Realisatie

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Gerealiseerde uren excl. saldo-uren' =
			
			CALCULATE(
			    SUM('Geboekte uren'[Aantal])
			    ,NOT(ISBLANK('Geboekte uren'[TaakKey]))
			    ,'Geboekte uren'[verlofsaldoboeking] = "Nee"
			)
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Realisatie

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Gerealiseerde uren excl. saldo-uren eigen personeel' =
			
			CALCULATE(
			    SUM('Geboekte uren'[Aantal])
			    ,NOT(ISBLANK('Geboekte uren'[TaakKey]))
			   ,'Bedrijfsmedewerkers'[Ingeleend (Ja/Nee)] = "Nee"
			    ,'Geboekte uren'[verlofsaldoboeking] = "Nee"
			)
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Realisatie

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Gerealiseerde uren totaal incl. verlofsaldo uren' =
			
			CALCULATE(
			    SUM('Geboekte uren'[Aantal])
			    ,NOT(ISBLANK('Geboekte uren'[TaakKey]))
				)
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Realisatie

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Headcount beginstand' =
			
			SUMX(
			    SUMMARIZE(
			        Bedrijfsmedewerkers
			        ,Bedrijfsmedewerkers[Medewerker]
			        ,"headcount_per_medewerker",ROUNDUP([FTE beginstand],0)
			    )
			    ,[headcount_per_medewerker]
			)
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.02 Best practice HR

	measure 'Headcount eindstand' =
			
			SUMX(
			    SUMMARIZE(
			        Bedrijfsmedewerkers
			        ,Bedrijfsmedewerkers[Medewerker]
			        ,"headcount_per_medewerker",ROUNDUP([FTE eindstand],0)
			    )
			    ,[headcount_per_medewerker]
			)
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.02 Best practice HR

	measure 'Indirect % tov direct' = ```
			
			    DIVIDE([Indirecte uren eigen personeel],[Directe uren eigen personeel])
			```
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.02 HR\Ratios

	measure 'Indirecte reisuren eigen personeel' = ```
			
			CALCULATE(
			        SUM('Geboekte uren'[Aantal])
			        ,'Geboekte uren'[projectgerelateerd Ja/Nee]="Nee"
			       ,'Bedrijfsmedewerkers'[Ingeleend (Ja/Nee)] = "Nee"
			        ,'Geboekte uren'[verlofsaldoboeking] = "Nee"
			        ,CONTAINSSTRING(Taken[Taak],"reis") 
			  )
			```
		formatString: #,0
		displayFolder: 1. Semantisch model\1.02 HR\Realisatie

	measure 'Indirecte uren eigen personeel' =
			
			CALCULATE(
			        SUM('Geboekte uren'[Aantal])
			        ,'Geboekte uren'[projectgerelateerd Ja/Nee]="Nee"
			       ,'Bedrijfsmedewerkers'[Ingeleend (Ja/Nee)] = "Nee"
			        ,'Geboekte uren'[verlofsaldoboeking] = "Nee"
			        ,NOT(ISBLANK('Geboekte uren'[TaakKey])
			    ))
		formatString: #,0
		displayFolder: 1. Semantisch model\1.02 HR\Realisatie

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Indirecte uren ingeleend personeel' =
			
			CALCULATE(
			        SUM('Geboekte uren'[Aantal])
			        ,'Geboekte uren'[projectgerelateerd Ja/Nee]="Nee"
			        ,'Bedrijfsmedewerkers'[Ingeleend (Ja/Nee)] = "Ja"
			        ,'Geboekte uren'[verlofsaldoboeking] = "Nee"
			        ,NOT(ISBLANK('Geboekte uren'[TaakKey])
			    ))
		formatString: #,0
		displayFolder: 1. Semantisch model\1.02 HR\Realisatie

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Indirecte uren totaal' =
			
			CALCULATE(
			        SUM('Geboekte uren'[Aantal])
			        ,'Geboekte uren'[projectgerelateerd Ja/Nee]="Nee"
			        ,'Geboekte uren'[verlofsaldoboeking] = "Nee"
			        ,NOT(ISBLANK('Geboekte uren'[TaakKey])
			    ))
		formatString: #,0
		displayFolder: 1. Semantisch model\1.02 HR\Realisatie

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Medewerker mutatie' =
			
			[Medewerkers in dienst]+[Medewerkers uit dienst]
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Medewerkers

	measure 'Medewerkers in dienst' =
			
			CALCULATE(
			    COUNT(Bedrijfsmedewerkers[Volledige naam])
			    ,USERELATIONSHIP(kalender[Datum],Bedrijfsmedewerkers[Datum in dienst])
			    ,Bedrijfsmedewerkers[Ingeleend (Ja/Nee)] = "Nee"
			)
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Medewerkers

	measure 'Medewerkers uit dienst' =
			
			CALCULATE(
			    COUNT(Bedrijfsmedewerkers[Volledige naam])
			    ,USERELATIONSHIP(Kalender[Datum],Bedrijfsmedewerkers[Datum uit dienst])
			    ,Bedrijfsmedewerkers[Ingeleend (Ja/Nee)] = "Nee"
			)*-1
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Medewerkers

	measure 'Melding gerealiseerde uren' = "Gerealiseerde uren vanaf " &FORMAT(MIN(kalender[Datum]),"DD-MM-YYYY")& " tot en met "&FORMAT(MAX(kalender[Datum]),"DD-MM-YYYY")
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Meldingen

	measure 'Melding Headcount' =
			
			"Headcount en FTE met beginstand op: " &FORMAT(MIN(kalender[Datum]),"DD-MM-YYYY")
			& " en eindstand op: "&FORMAT(MAX(kalender[Datum]),"DD-MM-YYYY")
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Meldingen

	measure 'Melding ingeleend personeel niet geselecteerd' =
			
			var ingeleend =
			CALCULATE(
			    COUNT(Bedrijfsmedewerkers[MedewerkerKey])
			    ,FILTER(Bedrijfsmedewerkers
			        ,Bedrijfsmedewerkers[Ingeleend (Ja/Nee)] = "Ja"
			    )
			)
			return
			if(
			   ISBLANK(ingeleend)
			    ,"INFO: Ingeleend personeel is niet geselecteerd."
			  ,""
			)
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Meldingen

	measure 'Melding ingeleend personeel wel geselecteerd' =
			
			var ingeleend =
			CALCULATE(
			    COUNT(Bedrijfsmedewerkers[MedewerkerKey])
			    ,FILTER(Bedrijfsmedewerkers
			        ,Bedrijfsmedewerkers[Ingeleend (Ja/Nee)] = "Ja"
			    )
			)
			return
			if(
			   ISBLANK(ingeleend)
			    ,""
			  ,"INFO: Ingeleend personeel is geselecteerd."
			)
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Meldingen

	measure 'Melding medewerkers in en uit dienst' = "Medewerkers in- en uit dienst vanaf " &FORMAT(MIN(kalender[Datum]),"DD-MM-YYYY")& " tot en met "&FORMAT(MAX(kalender[Datum]),"DD-MM-YYYY")
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Meldingen

	measure 'Melding productiviteit eigen personeel' =
			
			"Productiviteit eigen personeel vanaf " &FORMAT(MIN(kalender[Datum]),"DD-MM-YYYY")
			&" tot en met "&FORMAT(MAX(kalender[Datum]),"DD-MM-YYYY")
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Meldingen

	measure 'Melding verlofsaldo' =
			
			"Verlofsaldo met beginstand op: " &FORMAT(MIN(kalender[Datum]),"DD-MM-YYYY")
			& " en eindstand op: "&FORMAT(MAX(kalender[Datum]),"DD-MM-YYYY")
			& " (Verlofsaldo is boekjaar gebonden. zie info)"
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Meldingen

	measure 'Melding ziekteverzuim' = "Ziekteverzuim vanaf " &FORMAT(MIN(kalender[Datum]),"DD-MM-YYYY")& " tot en met "&FORMAT(MAX(kalender[Datum]),"DD-MM-YYYY")
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Meldingen

	measure Overuren =
			
			CALCULATE(
			    SUM('Geboekte uren'[Aantal])
			    ,'Geboekte uren'[Contracturen] = "Nee"
			    ,NOT(ISBLANK('Geboekte uren'[TaakKey]))
			    ,'Geboekte uren'[verlofsaldoboeking] = "Nee"
			)
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Realisatie

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Productiviteit Eigen personeel' =
			
			DIVIDE([Directe uren eigen personeel],[Directe uren eigen personeel]+[Indirecte uren eigen personeel])
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.02 HR\Ratios

	measure 'Productiviteit totaal' = ```
			IF(
								ISBLANK([Directe (productieve) uren totaal]),
								BLANK(),
								DIVIDE([Directe (productieve) uren totaal],[Gerealiseerde uren excl. saldo-uren])
			)
								
			```
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.02 HR\Ratios

	measure 'Verlof %' =
			
			DIVIDE([Verlofuren],[Gerealiseerde uren excl. saldo-uren],0)
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.02 HR\Ratios

	measure Verlofsaldo = ```
			
			VAR _verlofsaldo =
			CALCULATE(
			    SUM('Geboekte uren'[Aantal])
			    ,NOT(ISBLANK('Geboekte uren'[TaakKey]))
			    ,Taken[Type] = "Verlof"
			)*-1
							
			
			
			VAR result = 
			    _verlofsaldo
			
			Return
			    result
			
			
			
			```
		formatString: #,##0.0
		displayFolder: 2. Rapport Specifieke Objecten\2.02 Best practice HR

	measure 'Verlofsaldo beginstand' = ```
			
			var geselecteerde_startdatum = MIN(kalender[Datum])
			var StartOfYear_geselecteerde_Startdatum = Date(YEAR(geselecteerde_startdatum),1,1)
			var saldo = 
			CALCULATE(
			    SUM('Geboekte uren'[Aantal])
			    ,NOT(ISBLANK('Geboekte uren'[TaakKey]))
			    ,Bedrijfsmedewerkers[Ingeleend (Ja/Nee)] = "Nee"
			    ,'Geboekte uren'[verlofsaldoboeking] = "Ja"
			    ,FILTER(
			        ALL(Kalender)
			        ,Kalender[Datum]>=StartOfYear_geselecteerde_Startdatum &&
			        Kalender[Datum]<=geselecteerde_startdatum
			    ) 
			)*-1
			
			var verlof_opname =
			CALCULATE(
			    SUM('Geboekte uren'[Aantal])
			    ,NOT(ISBLANK('Geboekte uren'[TaakKey]))
			    ,Bedrijfsmedewerkers[Ingeleend (Ja/Nee)] = "Nee"
			    ,Taken[Type] = "Verlof"
			    ,'Geboekte uren'[verlofsaldoboeking] = "Nee"
			    ,FILTER(
			        ALL(Kalender)
			        ,Kalender[Datum]>=StartOfYear_geselecteerde_Startdatum &&
			        Kalender[Datum]<=geselecteerde_startdatum
			    )
			)
			
			VAR result = saldo - verlof_opname
						
			
			RETURN
			    result
			```
		formatString: 0.00
		displayFolder: 2. Rapport Specifieke Objecten\2.02 Best practice HR

		changedProperty = FormatString

	measure 'Verlofsaldo beginstand variabel format' = ```
			
			var geselecteerde_startdatum = MIN(kalender[Datum])
			var StartOfYear_geselecteerde_Startdatum = Date(YEAR(geselecteerde_startdatum),1,1)
			var saldo = 
			CALCULATE(
			    SUM('Geboekte uren'[Aantal])
			    ,NOT(ISBLANK('Geboekte uren'[TaakKey]))
			    ,Bedrijfsmedewerkers[Ingeleend (Ja/Nee)] = "Nee"
			    ,'Geboekte uren'[verlofsaldoboeking] = "Ja"
			    ,FILTER(
			        ALL(Kalender)
			        ,Kalender[Datum]>=StartOfYear_geselecteerde_Startdatum &&
			        Kalender[Datum]<=geselecteerde_startdatum
			    ) 
			)*-1
			
			var verlof_opname =
			CALCULATE(
			    SUM('Geboekte uren'[Aantal])
			    ,NOT(ISBLANK('Geboekte uren'[TaakKey]))
			    ,Bedrijfsmedewerkers[Ingeleend (Ja/Nee)] = "Nee"
			    ,Taken[Type] = "Verlof"
			    ,'Geboekte uren'[verlofsaldoboeking] = "Nee"
			    ,FILTER(
			        ALL(Kalender)
			        ,Kalender[Datum]>=StartOfYear_geselecteerde_Startdatum &&
			        Kalender[Datum]<=geselecteerde_startdatum
			    )
			)
			
			VAR _verlofsaldo_beginstand = saldo - verlof_opname
							
			
			VAR result = 
			    IF(
			        isblank(_verlofsaldo_beginstand)
			        ,blank()
			        ,_verlofsaldo_beginstand
			    )
			
			RETURN
			    result
			```
		formatString: 0.00
		displayFolder: 2. Rapport Specifieke Objecten\2.02 Best practice HR

		changedProperty = FormatString

	measure 'Verlofsaldo eindstand' = ```
			
			var geselecteerde_eind = MAX(Kalender[Datum])
			var StartOfYear_geselecteerde_eind = DATE(YEAR(geselecteerde_eind),1,1)
			var saldo = 
			CALCULATE(
			    SUM('Geboekte uren'[Aantal])
			    ,NOT(ISBLANK('Geboekte uren'[TaakKey]))
			     ,Bedrijfsmedewerkers[Ingeleend (Ja/Nee)] = "Nee"
			    ,'Geboekte uren'[verlofsaldoboeking] = "Ja"
			    ,FILTER(
			        ALL(Kalender)
			        ,Kalender[Datum]>=StartOfYear_geselecteerde_eind &&
			        Kalender[Datum]<=geselecteerde_eind 
			    ) 
			)*-1
			
			var verlof_opname =
			CALCULATE(
			    SUM('Geboekte uren'[Aantal])
			    ,NOT(ISBLANK('Geboekte uren'[TaakKey]))
			    ,Bedrijfsmedewerkers[Ingeleend (Ja/Nee)] = "Nee"
			    ,Taken[Type] = "Verlof" 
			    ,'Geboekte uren'[verlofsaldoboeking]= "Nee"
			    ,FILTER(
			        ALL(Kalender)
			        ,Kalender[Datum]>=StartOfYear_geselecteerde_eind &&
			        Kalender[Datum]<=geselecteerde_eind 
			    )
			)
			
			VAR result = saldo - verlof_opname
							
			
			Return
			    result
			```
		formatString: 0.00
		displayFolder: 2. Rapport Specifieke Objecten\2.02 Best practice HR

	measure 'Verlofsaldo eindstand variabel format' = ```
			
			var geselecteerde_eind = MAX(Kalender[Datum])
			var StartOfYear_geselecteerde_eind = DATE(YEAR(geselecteerde_eind),1,1)
			var saldo = 
			CALCULATE(
			    SUM('Geboekte uren'[Aantal])
			    ,NOT(ISBLANK('Geboekte uren'[TaakKey]))
			    ,Bedrijfsmedewerkers[Ingeleend (Ja/Nee)] = "Nee"
			    ,'Geboekte uren'[verlofsaldoboeking]= "Ja"
			    ,FILTER(
			        ALL(Kalender)
			        ,Kalender[Datum]>=StartOfYear_geselecteerde_eind &&
			        Kalender[Datum]<=geselecteerde_eind 
			    ) 
			)*-1
			
			var verlof_opname =
			CALCULATE(
			    SUM('Geboekte uren'[Aantal])
			    ,NOT(ISBLANK('Geboekte uren'[TaakKey]))
			    ,Bedrijfsmedewerkers[Ingeleend (Ja/Nee)] = "Nee"
			    ,Taken[Type] = "Verlof" 
			    ,'Geboekte uren'[verlofsaldoboeking]= "Nee"
			    ,FILTER(
			        ALL(Kalender)
			        ,Kalender[Datum]>=StartOfYear_geselecteerde_eind &&
			        Kalender[Datum]<=geselecteerde_eind 
			    )
			)
			
			VAR _verlofsaldo_eindstand = saldo - verlof_opname
			
			VAR result = 
			    IF(
			        isblank(_verlofsaldo_eindstand)
			        ,blank()
			        ,_verlofsaldo_eindstand
			    )
			
			Return
			    result
			```
		formatString: 0.00
		displayFolder: 2. Rapport Specifieke Objecten\2.02 Best practice HR

		changedProperty = FormatString

	measure Verlofuren =
			
			CALCULATE(
			    [Gerealiseerde uren excl. saldo-uren]
			    ,Taken[Type] = "Verlof"
			)
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Realisatie

	measure 'Ziekte uren' =
			
			CALCULATE(
					[Gerealiseerde uren excl. saldo-uren]
			        ,Taken[Type] = "Verzuim"
				)
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Gerealiseerde uren

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Ziekte verzuim - Rolling Average 12 maanden' = ```
			
			var ziekte_uren_12_maand =
			    CALCULATE(
			        [Ziekte uren]
			        ,DATESINPERIOD(kalender[Datum]
			                    ,LASTDATE(kalender[Datum])
			                    ,-12
			                    ,MONTH
			        )
			    )
			var gerealiseerde_uren =
			    CALCULATE(
			        [Gerealiseerde uren excl. saldo-uren]
			        ,DATESINPERIOD(kalender[Datum]
			                    ,LASTDATE(kalender[Datum])
			                    ,-12
			                    ,MONTH
			        )
			    )
			return
			DIVIDE(ziekte_uren_12_maand,gerealiseerde_uren,0)
			
			
			```
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.02 HR\Ratios

		changedProperty = FormatString

		changedProperty = DisplayFolder

	measure Ziekteverzuim = ```
			
			DIVIDE([Ziekte uren],[Gerealiseerde uren excl. saldo-uren],0)
			
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 1. Semantisch model\1.02 HR\Ratios

		changedProperty = FormatString

	measure 'Ziekteverzuim zonder blank' =
			
			IF(
			    ISBLANK([Ziekte uren eigen personeel]),
			    0,
			    DIVIDE([Ziekte uren eigen personeel],[Gerealiseerde uren excl. saldo-uren eigen personeel],0)
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 1. Semantisch model\1.02 HR\Ratios

	measure 'openstaande bankmutaties' =
			
			//Betreft bankregels van openstaande bankafschriften
			    SUM('Bankregels openstaand'[Creditbedrag])-SUM('Bankregels openstaand'[Debetbedrag])
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Openstaande bankafschriften

	measure 'openstaande bankmutaties te betalen' =
			
			//Betreft bankregels van openstaande bankafschriften
			CALCULATE(
			    SUM('Bankregels openstaand'[Creditbedrag])
			    ,'Bankregels openstaand'[Status Bankafschrift] <> "Historisch"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Openstaande bankafschriften

	measure 'openstaande bankmutaties te ontvangen' =
			
			//Betreft bankregels van openstaande bankafschriften
			CALCULATE(
			    SUM('Bankregels openstaand'[Debetbedrag])
			    ,'Bankregels openstaand'[Status Bankafschrift] <> "Historisch"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Openstaande bankafschriften

	measure 'BTW af te dragen' = SUM('Prognose BTW'[BTW af te dragen])
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Cash flow\BTW

	measure 'BTW prognose (huidige inkoop- en verkoopfacturen)' = [BTW af te dragen]-[BTW te vorderen]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Cash flow\BTW

	measure 'BTW te vorderen' = sum('Prognose BTW'[BTW te vorderen])
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Cash flow\BTW

	measure 'Bank beginsaldo' = ```
			
			var beginsaldo =
			    CALCULATE(
			        [Bank]
			        ,FILTER(
			            ALL(Kalender[Datum])
			            ,Kalender[Datum]<MIN(Kalender[Datum])
			        )
			    )   
			return
			IF(
			    ISBLANK(beginsaldo)
			    , BLANK()
			    ,IF(
			        beginsaldo > -1000 && beginsaldo < 1000
			        ,BLANK()
			        ,beginsaldo)
			)
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Cash flow\Bank

	measure 'Bank Credit' =
			
			CALCULATE(
			    SUM(Journaalregels[Creditbedrag])
			    ,'Journaalregels'[Bankafschriftboeking type]="Bank"
			    ,'Journaalregels'[Bankafschriftboeking Ja/Nee] = "Ja"
			    )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Cash flow\Bank

	measure 'Bank Debet' =
			
			CALCULATE(
			    SUM(Journaalregels[Debetbedrag])
			    ,'Journaalregels'[Bankafschriftboeking type]="Bank"
			    ,'Journaalregels'[Bankafschriftboeking Ja/Nee] = "Ja"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Cash flow\Bank

	measure 'Bank eindsaldo' = ```
			
			var eindsaldo =
			    CALCULATE(
			        [Bank]
			        ,FILTER(
			            ALL(Kalender[Datum])
			            ,Kalender[Datum]<=MAX(Kalender[Datum])
			        )
			    )   
			return
			IF(
			    ISBLANK(eindsaldo)
			    , BLANK()
			    ,IF(
			        eindsaldo > -1000 && eindsaldo < 1000
			        ,BLANK()
			        ,eindsaldo)
			)
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Cash flow\Bank

	measure 'Mutatie totaal' = [Mutatie Credit - Debet]+[openstaande bankmutaties]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Cash flow\Mutatie op bank

	measure 'Mutatie Debet' = ```
			
			CALCULATE(
			    SUM(Journaalregels[Debetbedrag])
			    ,'Journaalregels'[Bankafschriftboeking type]="Tegenrekening"
			    ,'Journaalregels'[Bankafschriftboeking Ja/Nee] = "Ja"
			    
			    )
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Cash flow\Mutatie op bank

	measure 'Mutatie Credit - Debet' = [Mutatie Credit]-[Mutatie Debet]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Cash flow\Mutatie op bank

	measure 'Mutatie Credit' =
			
			CALCULATE(
			    SUM( Journaalregels[Creditbedrag] )
			    , 'Journaalregels'[Bankafschriftboeking type] = "Tegenrekening"
			    , 'Journaalregels'[Bankafschriftboeking Ja/Nee] = "Ja"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Cash flow\Mutatie op bank

	measure 'Laatst beschikbare standdatum' =
			
			CALCULATE(
			    LASTDATE(kalender[standdatum])
			    ,ALL(kalender)
			)
		formatString: General Date
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Meldingen

	measure 'Laatste standdatum geselecteerd' =
			
			IF(
			    LASTDATE(kalender[standdatum]) = [Laatst beschikbare standdatum]
			    ,""
			    ,"De meest recente stand is van " & FORMAT([Laatst beschikbare standdatum],"DD-MM-YYYY")
			)
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Meldingen

	measure Inkopen =
			
			CALCULATE(
					SUMX('Inkoopfactuur termijnen','Inkoopfactuur termijnen'[Bedrag])
						,'Inkoopfactuur termijnen'[Bedrag]>0)
		formatString: "€"\ #,0.###############;-"€"\ #,0.###############;"€"\ #,0.###############
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Inkoop

	measure 'openstaande inkoopfacturen' =
			
			var openstaand =
				CALCULATE(
					SUM('Inkoopfactuur termijnen'[Bedrag])
					,FILTER(
						ALL(Kalender),
							COUNTROWS
							(
							FILTER(Kalender,
							   EARLIER(Kalender[Standdatum])<=MAX(Kalender[Standdatum]))
						)>0
				)
			)
			return
			IF(openstaand >-1 && openstaand <1
			    ,BLANK()
			    ,openstaand
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Inkoop

	measure 'Openstaande inkoopfacturen niet vervallen' = ```
			
			var niet_vervallen =
				    CALCULATE([openstaande inkoopfacturen],
					    FILTER('Kalender vervaldatum',
			                    MAXX(Kalender,
							        MAX(Kalender[Standdatum])-EARLIER('Kalender vervaldatum'[Vervaldatum])
							    )<0
					    )
					)
			return 
			IF(niet_vervallen>-1 && niet_vervallen <1
			    ,BLANK()
			    ,niet_vervallen
			)
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Inkoop

	measure 'Openstaande inkoopfacturen per categorie' =
			
			IF([openstaande inkoopfacturen]>1,
			IF(COUNTROWS(Band)=1,
				CALCULATE([openstaande inkoopfacturen],
					FILTER('Kalender factuurdatum',
						MAXX('Kalender factuurdatum',
							MAX(Kalender[Standdatum])-EARLIER('Kalender factuurdatum'[Factuurdatum])
							)>=MAX(Band[From])
							&& MAXX(Kalender,
							MAX(Kalender[Standdatum])-EARLIER('Kalender factuurdatum'[Factuurdatum])
							)<=MAX(Band[To])
					)
					),
				[openstaande inkoopfacturen]
			))
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Inkoop

	measure 'Openstaande inkoopfacturen vervallen' = ```
			
			var vervallen=
			CALCULATE([Openstaande inkoopfacturen],
				FILTER('Kalender vervaldatum',
			        MAXX(Kalender,
						MAX(Kalender[Standdatum])-EARLIER('Kalender vervaldatum'[Vervaldatum])
					)>=0
				)
			)
			return 
			IF(vervallen >-1 && vervallen <1
			    ,BLANK()
			    ,vervallen
			)
			```
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Inkoop

	measure 'Openstaande inkoopfacturen vervallen  0-30' = ```
			
			var vervallen =
				    CALCULATE([Openstaande inkoopfacturen],
					    FILTER('Kalender vervaldatum',
			                    MAXX(Kalender,
							        MAX(Kalender[Standdatum])-EARLIER('Kalender vervaldatum'[Vervaldatum])
							    )>=0
			                    && MAXX(Kalender,
							    MAX(Kalender[Standdatum])-EARLIER('Kalender vervaldatum'[Vervaldatum])
							    )<=30
					    )
					)
			return 
			IF(vervallen >-1 && vervallen <1
			    ,BLANK()
			    ,vervallen
			)
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Inkoop

	measure 'Openstaande inkoopfacturen vervallen  31-60' = ```
			
			var vervallen =
				    CALCULATE([Openstaande inkoopfacturen],
					    FILTER('Kalender vervaldatum',
			                    MAXX(Kalender,
							        MAX(Kalender[Standdatum])-EARLIER('Kalender vervaldatum'[Vervaldatum])
							    )>=31
			                    && MAXX(Kalender,
							    MAX(Kalender[Standdatum])-EARLIER('Kalender vervaldatum'[Vervaldatum])
							    )<=60
					    )
					)
			return 
			IF(vervallen >-1 && vervallen <1
			    ,BLANK()
			    ,vervallen
			)
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Inkoop

	measure 'Openstaande inkoopfacturen vervallen  61-90' = ```
			
			var vervallen =
				    CALCULATE([openstaande inkoopfacturen],
					    FILTER('Kalender vervaldatum',
			                    MAXX(Kalender,
							        MAX(Kalender[Standdatum])-EARLIER('Kalender vervaldatum'[Vervaldatum])
							    )>=61
			                    && MAXX(Kalender,
							    MAX(Kalender[Standdatum])-EARLIER('Kalender vervaldatum'[Vervaldatum])
							    )<=90
					    )
					)
			return 
			IF(vervallen >-1 && vervallen <1
			    ,BLANK()
			    ,vervallen
			)
			```
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Inkoop

	measure 'Openstaande inkoopfacturen vervallen  91-120' = ```
			
			var vervallen =
				    CALCULATE([Openstaande inkoopfacturen],
					    FILTER('Kalender vervaldatum',
			                    MAXX(Kalender,
							        MAX(Kalender[Standdatum])-EARLIER('Kalender vervaldatum'[Vervaldatum])
							    )>=91
			                    && MAXX(Kalender,
							    MAX(Kalender[Standdatum])-EARLIER('Kalender vervaldatum'[Vervaldatum])
							    )<=120
					    )
					)
			return 
			IF(vervallen >-1 && vervallen <1
			    ,BLANK()
			    ,vervallen
			)
			```
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Inkoop

	measure 'Openstaande inkoopfacturen vervallen 120+' = ```
			
			var vervallen =
				    CALCULATE([openstaande inkoopfacturen],
					    FILTER('Kalender vervaldatum',
			                    MAXX(Kalender,
							        MAX(Kalender[Standdatum])-EARLIER('Kalender vervaldatum'[Vervaldatum])
							    )>=121
					    )
					)
			return 
			IF(vervallen >-1 && vervallen <1
			    ,BLANK()
			    ,vervallen
			)
			```
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Inkoop

	measure 'Openstaande verkoopfacturen' =
			
			var openstaand =
				CALCULATE(
					SUM('Verkoopfactuur termijnen'[Bedrag])
					,FILTER(
						ALL(Kalender),
							COUNTROWS
							(
							FILTER(Kalender,
							   EARLIER(Kalender[Standdatum])<=MAX(Kalender[Standdatum]))
						)>0
				)
			)
			return
			IF(openstaand >-1 && openstaand <1
			    ,BLANK()
			    ,openstaand
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Verkoop

	measure 'Openstaande verkoopfacturen niet vervallen' = ```
			
			var niet_vervallen =
				    CALCULATE([Openstaande verkoopfacturen],
					    FILTER('Kalender vervaldatum',
			                    MAXX(Kalender,
							        MAX(Kalender[Standdatum])-EARLIER('Kalender vervaldatum'[Vervaldatum])
							    )<0
					    )
					)
			return 
			IF(niet_vervallen>-1 && niet_vervallen <1
			    ,BLANK()
			    ,niet_vervallen
			)
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Verkoop

	measure 'Openstaande verkoopfacturen per categorie' =
			
			IF([Openstaande verkoopfacturen]>1,
			IF(COUNTROWS(Band)=1,
				CALCULATE([Openstaande verkoopfacturen],
					FILTER('Kalender factuurdatum',
						MAXX('Kalender factuurdatum',
							MAX(Kalender[Standdatum])-EARLIER('Kalender factuurdatum'[Factuurdatum])
							)>=MAX(Band[From])
							&& MAXX(Kalender,
							MAX(Kalender[Standdatum])-EARLIER('Kalender factuurdatum'[Factuurdatum])
							)<=MAX(Band[To])
					)
					),
				[Openstaande verkoopfacturen]
			))
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Verkoop

	measure 'Openstaande verkoopfacturen vervallen' = ```
			
			var vervallen=
			CALCULATE([Openstaande verkoopfacturen],
				FILTER('Kalender vervaldatum',
			        MAXX(Kalender,
						MAX(Kalender[Standdatum])-EARLIER('Kalender vervaldatum'[Vervaldatum])
					)>=0
				)
			)
			return 
			IF(vervallen >-1 && vervallen <1
			    ,BLANK()
			    ,vervallen
			)
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Verkoop

	measure 'Openstaande verkoopfacturen vervallen  0-30' = ```
			
			var vervallen =
				    CALCULATE([Openstaande verkoopfacturen],
					    FILTER('Kalender vervaldatum',
			                    MAXX(Kalender,
							        MAX(Kalender[Standdatum])-EARLIER('Kalender vervaldatum'[Vervaldatum])
							    )>=0
			                    && MAXX(Kalender,
							    MAX(Kalender[Standdatum])-EARLIER('Kalender vervaldatum'[Vervaldatum])
							    )<=30
					    )
					)
			return 
			IF(vervallen >-1 && vervallen <1
			    ,BLANK()
			    ,vervallen
			)
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Verkoop

	measure 'Openstaande verkoopfacturen vervallen  31-60' = ```
			
			var vervallen =
				    CALCULATE([Openstaande verkoopfacturen],
					    FILTER('Kalender vervaldatum',
			                    MAXX(Kalender,
							        MAX(Kalender[Standdatum])-EARLIER('Kalender vervaldatum'[Vervaldatum])
							    )>=31
			                    && MAXX(Kalender,
							    MAX(Kalender[Standdatum])-EARLIER('Kalender vervaldatum'[Vervaldatum])
							    )<=60
					    )
					)
			return 
			IF(vervallen >-1 && vervallen <1
			    ,BLANK()
			    ,vervallen
			)
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Verkoop

	measure 'Openstaande verkoopfacturen vervallen  61-90' = ```
			
			var vervallen =
				    CALCULATE([Openstaande verkoopfacturen],
					    FILTER('Kalender vervaldatum',
			                    MAXX(Kalender,
							        MAX(Kalender[Standdatum])-EARLIER('Kalender vervaldatum'[Vervaldatum])
							    )>=61
			                    && MAXX(Kalender,
							    MAX(Kalender[Standdatum])-EARLIER('Kalender vervaldatum'[Vervaldatum])
							    )<=90
					    )
					)
			return 
			IF(vervallen >-1 && vervallen <1
			    ,BLANK()
			    ,vervallen
			)
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Verkoop

	measure 'Openstaande verkoopfacturen vervallen  91-120' = ```
			
			var vervallen =
				    CALCULATE([Openstaande verkoopfacturen],
					    FILTER('Kalender vervaldatum',
			                    MAXX(Kalender,
							        MAX(Kalender[Standdatum])-EARLIER('Kalender vervaldatum'[Vervaldatum])
							    )>=91
			                    && MAXX(Kalender,
							    MAX(Kalender[Standdatum])-EARLIER('Kalender vervaldatum'[Vervaldatum])
							    )<=120
					    )
					)
			return 
			IF(vervallen >-1 && vervallen <1
			    ,BLANK()
			    ,vervallen
			)
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Verkoop

	measure 'Openstaande verkoopfacturen vervallen 120+' = ```
			
			var vervallen =
				    CALCULATE([Openstaande verkoopfacturen],
					    FILTER('Kalender vervaldatum',
			                    MAXX(Kalender,
							        MAX(Kalender[Standdatum])-EARLIER('Kalender vervaldatum'[Vervaldatum])
							    )>=121
					    )
					)
			return 
			IF(vervallen >-1 && vervallen <1
			    ,BLANK()
			    ,vervallen
			)
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Verkoop

	measure Verkopen =
			
			CALCULATE(
					SUMX('Verkoopfactuur termijnen','Verkoopfactuur termijnen'[Bedrag])
						,'Verkoopfactuur termijnen'[Bedrag]>0)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Verkoop

	measure 'Target voorfinanciering' = 0
		formatString: 0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Voorfinanciering

	measure 'voorfinanciering negatief' =
			
			IF(
			    [Voorfinanciering]<0
			    ,[Voorfinanciering]
			    ,blank()
			)
		formatString: "€"\ #,0.0;-"€"\ #,0.0;"€"\ #,0.0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Voorfinanciering

	measure 'voorfinanciering postitief' =
			
			IF(
			    [Voorfinanciering]>=0
			    ,[Voorfinanciering]
			    ,blank()
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Voorfinanciering

	measure 'Verzoek kosten  (Projectbudgetregels)' = SUM('Projectenbudgetregels (doorgerekend)'[Budget mutatie kosten])
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Syntess Projectbudget en opname regels\Budget verzoek (impliciet via Projectbudgetregels)

	/// Verzoek extra omzet aangevraagd via Budget Verzoek App.
	measure 'Verzoek omzet  (Projectbudgetregels)' = SUM('Projectenbudgetregels (doorgerekend)'[Budget mutatie omzet])
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Syntess Projectbudget en opname regels\Budget verzoek (impliciet via Projectbudgetregels)

	measure 'Verzoek uren (Projectbudgetregels)' = SUM('Projectenbudgetregels (doorgerekend)'[Budget mutatie uren])
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Syntess Projectbudget en opname regels\Budget verzoek (impliciet via Projectbudgetregels)

	measure 'Verzoek uren (Projectbudgetregels) NOT BLANK ' =
			
			IF(
			    ISBLANK([Verzoek uren (Projectbudgetregels)])
			    ,0
			    ,[Verzoek uren (Projectbudgetregels)]
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Syntess Projectbudget en opname regels\Budget verzoek (impliciet via Projectbudgetregels)

	measure 'Verzoek omzet (Projectbudgetregels) NOT BLANK ' =
			
			IF(
			    ISBLANK([Verzoek omzet  (Projectbudgetregels)])
			    ,0
			    ,[Verzoek omzet  (Projectbudgetregels)]
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Syntess Projectbudget en opname regels\Budget verzoek (impliciet via Projectbudgetregels)

	measure 'Verzoek kosten (Projectbudgetregels) NOT BLANK' =
			
			IF(
			    ISBLANK([Verzoek kosten  (Projectbudgetregels)])
			    ,0
			    ,[Verzoek kosten  (Projectbudgetregels)])
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Syntess Projectbudget en opname regels\Budget verzoek (impliciet via Projectbudgetregels)

	measure 'Budget kosten (Projectbudgetregels)' = SUM('Projectenbudgetregels (doorgerekend)'[Budget kosten])
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Syntess Projectbudget en opname regels\Budget (via projectbudgetregels)

	measure 'Budget kosten (Projectbudgetregels) NOT BLANK' =
			
			IF(
			    ISBLANK( [Budget kosten (Projectbudgetregels)] )
			    ,0
			    ,[Budget kosten (Projectbudgetregels)])
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Syntess Projectbudget en opname regels\Budget (via projectbudgetregels)

	measure 'Budget kosten inkoop (Projectbudgetregels)' =
			
			CALCULATE(
			    SUM('Projectenbudgetregels (doorgerekend)'[Budget omzet])
			    ,Kostensoorten[Categorie] <> "Arbeid"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Syntess Projectbudget en opname regels\Budget (via projectbudgetregels)

	measure 'Budget omzet (Projectbudgetregels)' = SUM('Projectenbudgetregels (doorgerekend)'[Budget omzet])
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Syntess Projectbudget en opname regels\Budget (via projectbudgetregels)

	measure 'Budget omzet (Projectbudgetregels) NOT BLANK' =
			
			IF(
			    ISBLANK([Budget omzet (Projectbudgetregels)])
			    ,0
			    ,[Budget omzet (Projectbudgetregels)])
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Syntess Projectbudget en opname regels\Budget (via projectbudgetregels)

	measure 'Budget uren (Projectbudgetregels)' = SUM('Projectenbudgetregels (doorgerekend)'[Budget uren])
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Syntess Projectbudget en opname regels\Budget (via projectbudgetregels)

	measure 'Budget uren (Projectbudgetregels) NOT BLANK' =
			
			IF(
			    ISBLANK([Budget uren (Projectbudgetregels)])
			    ,0
			    ,[Budget uren (Projectbudgetregels)])
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Syntess Projectbudget en opname regels\Budget (via projectbudgetregels)

	measure 'Prognose kosten (Projectbudgetregels)' = SUM('Projectenbudgetregels (doorgerekend)'[Prognose kosten])
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Syntess Projectbudget en opname regels\Prognose (via projectbudgetregels)

	/// [Budget omzet] + [Verzoek omzet]. 
	measure 'Prognose omzet (Projectbudgetregels)' = SUM('Projectenbudgetregels (doorgerekend)'[Prognose omzet])
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Syntess Projectbudget en opname regels\Prognose (via projectbudgetregels)

	measure 'Prognose uren (Projectbudgetregels)' = SUM('Projectenbudgetregels (doorgerekend)'[Prognose uren])
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Syntess Projectbudget en opname regels\Prognose (via projectbudgetregels)

	measure 'Prognose uren (Projectbudgetregels) NOT BLANK' =
			
			if(
			    ISBLANK([Prognose uren (Projectbudgetregels)])
			    ,0
			    ,[Prognose uren (Projectbudgetregels)])
		formatString: 0
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Syntess Projectbudget en opname regels\Prognose (via projectbudgetregels)

	measure 'Prognose omzet (Projectbudgetregels) NOT BLANK' =
			
			if(
			    ISBLANK( [Prognose omzet (Projectbudgetregels)] )
			    ,0
			    , [Prognose omzet (Projectbudgetregels)])
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Syntess Projectbudget en opname regels\Prognose (via projectbudgetregels)

	measure 'Prognose kosten (Projectbudgetregels) NOT BLANK' =
			
			if(
			    ISBLANK([Prognose kosten (Projectbudgetregels)])
			    ,0
			    ,[Prognose kosten (Projectbudgetregels)])
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Syntess Projectbudget en opname regels\Prognose (via projectbudgetregels)

	measure '% actual en forecast t.o.v. budget' = DIVIDE([CoA actual en forecast],[CoA mutatie budget])
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Ratio

	measure 'CoA actual en forecast' =
			
			var __geselec_maandindex = max('Kalender standdatums'[Maand index])
			
			var __maandindex  = max(Kalender[Maand index])
			
			VAR __coa_mutatie_tot_standdatum =
			CALCULATE(
			    [CoA mutatie]
			    , Kalender[Maand index] <= __geselec_maandindex
			)
			
			VAR __forecast_mutatie_na_standdatum =
			CALCULATE(
			    [CoA Forecast mutatie]
			    , Kalender[Maand index] > __geselec_maandindex
			)
			
			var result =
			If(
			    NOT(ISINSCOPE(Kalender[Maand]))
			    ,__coa_mutatie_tot_standdatum+__forecast_mutatie_na_standdatum
			    ,If(
			        __maandindex<=__geselec_maandindex
			        ,[CoA mutatie]
			        ,[CoA Forecast mutatie]
			    )
			)
			
			return
			    result
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema

	measure 'Controle Coa actual en forecast' =
			
			var __geselec_maandindex = max('Kalender standdatums'[Maand index])
			
			var __maandindex  = max(Kalender[Maand index])
			
			var result =
			if(
			    ISINSCOPE(Kalender[Maand kort])
			        ,If(
			                __maandindex<=__geselec_maandindex
			                ,0
			                ,1
			            )
			    ,blank()
			)
			
			
			return
			    result
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Ratio

	measure 'Delta actual en forecast - budget' = [CoA actual en forecast]-[CoA mutatie budget]
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Ratio

	measure 'CoA Forecast mutatie' = ```
			
			VAR _classification         = SELECTEDVALUE('NR - CoA schema'[Classificatie type])
			VAR _is_subtotaal           = _classification = "Subtotaal"
			VAR _is_geen_omzet          = _classification <> "Omzet" 
			VAR _correctSubtotalLevel   = _is_subtotaal                && ISINSCOPE('NR - CoA schema'[Niveau1]) && NOT(ISINSCOPE('NR - CoA schema'[Niveau2]))
			VAR _is_legeregel           = _classification = "Leeg"    && ISINSCOPE('NR - CoA schema'[Niveau1]) && NOT(ISINSCOPE('NR - CoA schema'[Niveau2]))
			 
			VAR _mutatie_forecast     = sum('NR - Resultaatrekening forecastregels DQ'[Waarde])
			//VAR _mutatie_forecast     = sum(Forecast[Value])*max('NR - CoA schema'[Teken])
			//VAR _mutatie_forecast     = sum(Forecast[Value])*-1
			
			
			VAR _subtotaalWaarde =
			    CALCULATE(
			        sum('NR - Resultaatrekening forecastregels DQ'[Waarde])
			        , FILTER(
			            ALL( 'NR - CoA schema' )
			            , 'NR - CoA schema'[Niveau2_sortering] <= MAX( 'NR - CoA schema'[Niveau2_sortering] )
			        )
			    )
			
			VAR result =
			    SWITCH(
			        TRUE
			        ,_is_legeregel,0
			        ,NOT(_is_subtotaal) && _is_geen_omzet,-_mutatie_forecast
			        ,NOT(_is_subtotaal),_mutatie_forecast
			        ,_correctSubtotalLevel,_subtotaalWaarde
			    )/1000
			    
			    
			RETURN
			  result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Forecast

	measure 'CoA mutatie notifica budget in de standmaand o.b.v. standdatum' = ```
			
			VAR _classification         = SELECTEDVALUE('NR - CoA schema'[Classificatie type])
			VAR _is_subtotaal           = _classification = "Subtotaal"
			VAR _is_geen_omzet          = _classification <> "Omzet" 
			VAR _correctSubtotalLevel   = _is_subtotaal                && ISINSCOPE('NR - CoA schema'[Niveau1]) && NOT(ISINSCOPE('NR - CoA schema'[Niveau2]))
			VAR _is_legeregel           = _classification = "Leeg"    && ISINSCOPE('NR - CoA schema'[Niveau1]) && NOT(ISINSCOPE('NR - CoA schema'[Niveau2]))
			VAR _einddatum_gesecteerde_standmaand = MAX('Kalender standdatums'[Einddatum Maand])
			VAR _begindatum_gesecteerde_standmaand = MIN('Kalender standdatums'[Begindatum Maand])
			 
			 
			VAR _budget    
			= CALCULATE(
			    SUM ('NR - Budgetregels DQ'[waarde])
			    ,Rubrieken[Type] = "W"
			    , FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			        && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			    )
			)
			
			
			VAR _subtotaalWaarde =
			    CALCULATE(
			        [Mutatie budget (notifica)]
			        , FILTER(
			            ALL( 'NR - CoA schema' )
			            , 'NR - CoA schema'[Niveau2_sortering] <= MAX( 'NR - CoA schema'[Niveau2_sortering] )
			        )
			        , FILTER(
			            ALL( Kalender )
			                , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			                && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			        )
			    )
			
			VAR result =
			    SWITCH(
			        TRUE
			        ,_is_legeregel,0
			        ,NOT(_is_subtotaal) && _is_geen_omzet,_budget*-1
			        ,NOT(_is_subtotaal),_budget
			        ,_correctSubtotalLevel,_subtotaalWaarde
			    )/1000
			    
			    
			RETURN
			   result
			```
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Notifica budget

	measure 'Budget YTD (notifica)' =
			
			var geselecteerde_einddatum = MAX('Kalender'[Datum])
			var StartOfYear_geselecteerde_einddatum = Date(YEAR(geselecteerde_einddatum),1,1)
			var _budget_notifica =
			CALCULATE(
			    SUM ('NR - Budgetregels DQ'[waarde])
			    ,FILTER(
			        ALL('Kalender')
			        ,'Kalender'[Datum]>=StartOfYear_geselecteerde_einddatum &&
			        'Kalender'[Datum]<=geselecteerde_einddatum
			    )
			)
			
			VAR result = _budget_notifica
			
			return
			    result
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Budget\Bron - Notifica

	measure 'Mutatie budget (notifica)' =
			
			var result = SUM ('NR - Budgetregels DQ'[waarde])
			
			return
			    result
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Budget\Bron - Notifica

	measure 'Delta actual - budget (notifica)' = [CoA mutatie]-[CoA mutatie notifica budget]
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Ratio

	measure 'Delta actual en forecast - budget (notifica)' = [CoA actual en forecast]-[CoA mutatie notifica budget]
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Ratio

	measure '% actual en forecast t.o.v. budget (notifica)' = DIVIDE([CoA actual en forecast],[CoA mutatie notifica budget])
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Ratio

	measure '% YTD t.o.v. YTD budget (notifica)' = DIVIDE([Delta actual - budget (notifica)],[CoA mutatie])
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Ratio

	measure 'CoA YTD rendement notifica budget' = ```
			
			VAR _classification         = SELECTEDVALUE('NR - CoA schema'[Classificatie type])
			VAR _is_subtotaal           = _classification = "Subtotaal"
			VAR _is_omzet               = _classification = "Omzet" 
			VAR _correctSubtotalLevel   = _is_subtotaal               && ISINSCOPE('NR - CoA schema'[Niveau1]) && NOT(ISINSCOPE('NR - CoA schema'[Niveau2]))
			VAR _is_legeregel           = _classification = "Leeg"    && ISINSCOPE('NR - CoA schema'[Niveau1]) && NOT(ISINSCOPE('NR - CoA schema'[Niveau2]))
			 
			VAR _omzetwaarde =
			    CALCULATE(
			        [Mutatie resultaat notifica budget]
			        ,FILTER(
			            ALL( 'NR - CoA schema' )
			            , 'NR - CoA schema'[Classificatie type] = "Omzet"
			        )
			    )
			    
			VAR _subtotaalWaarde =
			    CALCULATE(
			       [Mutatie resultaat notifica budget]
			        , FILTER(
			            ALL( 'NR - CoA schema' )
			            , 'NR - CoA schema'[Niveau2_sortering] <= MAX( 'NR - CoA schema'[Niveau2_sortering] )
			        )
			    )
			
			VAR result =
			    SWITCH(
			        TRUE
			        ,_is_legeregel,BLANK()
			        ,NOT(_is_subtotaal),BLANK()
			        ,_correctSubtotalLevel,DIVIDE( _subtotaalWaarde, _omzetwaarde )
			    )
			    
			    
			RETURN
			   result
			```
		formatString: 0%;-0%;
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Notifica budget

	measure 'Mutatie resultaat notifica budget' =
			
			var result = SUM ('NR - Budgetregels DQ'[waarde])
			
			return
			    result
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Notifica budget

	measure 'Controle project selectie' = ```
			
			/*
			Legenda codes;
			0 = er is één deelproject geselecteerd.
			1 = Er is een hoofdproject met alle deelprojecten geselecteerd.
			2 = Er is een hoofdproject zonder deelprojecten geselecteerd.
			3 = Niet alle deelprojecten zijn geselecteerd. (= niet goed)
			4 = Er zijn meerdere deelprojecten geselecteerd (= niet goed)
			5 = Geen correctie selectie (=niet goed)
			6 = Er zijn meerdere hoofdprojecten geselecteerd eventueel vanuit selectie meerdere deelprojecten.(=niet goed).
			
			*/
			
			VAR _aantal_projecten = 
			CALCULATE(
			    DISTINCTCOUNT(Projecten[Niveau 2 Project])
			    ,ALL('Projecten'[Niveau 2 Project])
			)
			
			VAR _aantal_geselecteerde_deelprojecten =
			COALESCE(
			    CALCULATE(
			        DISTINCTCOUNT(Projecten[Niveau 2 Project])
			        ,'Projecten'[Niveau] =2
			    )
			,0)    
			
			VAR _aantal_geselecteerde_hoofdprojecten =
			COALESCE(
			CALCULATE(
			    DISTINCTCOUNT(Projecten[Hoofdproject])
			    ,'Projecten'[Niveau] =1)
			,0) 
			
			VAR _aantal_geselecteerde_projecten = 
			DISTINCTCOUNT(Projecten[Niveau 2 Project])
			
			VAR _aantal_hoofdprojecten =
			COALESCE(DISTINCTCOUNT(Projecten[Hoofdproject]),0) 
			
			
			VAR result =
			IF(_aantal_hoofdprojecten>1
			    ,6
			    ,IF(
			        ISFILTERED('Projecten'[Niveau 2 Project] ) && _aantal_geselecteerde_hoofdprojecten=0 && _aantal_geselecteerde_deelprojecten =1
			        ,0
			        ,IF(
			            ISFILTERED( 'Projecten'[Hoofdproject] ) && _aantal_geselecteerde_projecten=_aantal_projecten && _aantal_geselecteerde_hoofdprojecten=1 
			            ,1
			            ,IF(
			                ISFILTERED( 'Projecten'[Hoofdproject] ) && _aantal_geselecteerde_deelprojecten= 0 && _aantal_geselecteerde_hoofdprojecten=1 
			                ,2
			                ,IF(
			                    ISFILTERED( 'Projecten'[Hoofdproject] ) && _aantal_geselecteerde_projecten<_aantal_projecten && _aantal_geselecteerde_hoofdprojecten=1 
			                    ,3
			                    ,IF(
			                        ISFILTERED( 'Projecten'[Hoofdproject] ) && _aantal_geselecteerde_projecten<_aantal_projecten && _aantal_geselecteerde_hoofdprojecten=0    
			                        ,4
			                        ,5  
			                    )
			                )
			            )
			        )
			    )
			)
			
			return
			result
			```
		formatString: 0
		isHidden
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectselectie

		changedProperty = IsHidden

	measure 'Gerealiseerde marge incl onverwerkte kosten' = ```
			 DIVIDE([Project resultaat incl. kosten in bestelling],[Project omzet])
			```
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat

		changedProperty = IsHidden

	measure 'Gerealiseerd project rendement' = ```
			 DIVIDE([Project resultaat],[Project omzet])
			```
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat

		changedProperty = IsHidden

	measure 'Geselecteerd project' = ```
			
			VAR _aantal_projecten = 
			CALCULATE(
			    DISTINCTCOUNT(Projecten[Niveau 2 Project])
			    ,ALL('Projecten'[Niveau 2 Project])
			)
			
			VAR _aantal_geselecteerde_deelprojecten =
			COALESCE(
			    CALCULATE(
			        DISTINCTCOUNT(Projecten[Niveau 2 Project])
			        ,'Projecten'[Niveau] =2
			    )
			,0)    
			
			VAR _aantal_geselecteerde_hoofdprojecten =
			COALESCE(
			CALCULATE(
			    DISTINCTCOUNT(Projecten[Hoofdproject])
			    ,'Projecten'[Niveau] =1)
			,0) 
			
			VAR _aantal_geselecteerde_projecten = 
			DISTINCTCOUNT(Projecten[Niveau 2 Project])
			
			VAR _aantal_hoofdprojecten =
			COALESCE(DISTINCTCOUNT(Projecten[Hoofdproject]),0) 
			
			
			VAR result =
			IF(_aantal_hoofdprojecten>1
			    ,"Selectie op basis van meerdere projecten" 
			    ,IF(
			        ISFILTERED('Projecten'[Niveau 2 Project] ) && _aantal_geselecteerde_hoofdprojecten=0 && _aantal_geselecteerde_deelprojecten =1
			        ,SELECTEDVALUE('Projecten'[Niveau 2 Project])
			        ,IF(
			            ISFILTERED( 'Projecten'[Hoofdproject] ) && _aantal_geselecteerde_projecten=_aantal_projecten && _aantal_geselecteerde_hoofdprojecten=1 
			            ,SELECTEDVALUE( 'Projecten'[hoofdproject] )
			            ,IF(
			                ISFILTERED( 'Projecten'[Hoofdproject] ) && _aantal_geselecteerde_deelprojecten= 0 && _aantal_geselecteerde_hoofdprojecten=1 
			                ,CONCATENATE( SELECTEDVALUE( 'Projecten'[hoofdproject] ), " (zonder deelprojecten)" )
			                ,IF(
			                    ISFILTERED( 'Projecten'[Hoofdproject] ) && _aantal_geselecteerde_projecten<_aantal_projecten && _aantal_geselecteerde_hoofdprojecten=1 
			                    ,"Selectie op basis van meerdere projecten" 
			                    ,IF(
			                        ISFILTERED( 'Projecten'[Hoofdproject] ) && _aantal_geselecteerde_projecten<_aantal_projecten && _aantal_geselecteerde_hoofdprojecten=0    
			                        ,"Selectie op basis van meerdere projecten" 
			                        ,"Selectie op basis van meerdere projecten"  
			                    )
			                )
			            )
			        )
			    )
			)
			
			return
			result
			```
		isHidden
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectselectie

		changedProperty = IsHidden

	measure KostenplaatsKey = ```
			
			IF(
			    [Controle project selectie] IN {0,2} //Er is slechts één hoofd- of deelproject geselecteerd.
			    ,SWITCH(
			        MIN('Projecten'[Niveau])
			        ,1,CALCULATE(MIN('Projecten'[KostenplaatsKey]) ,'Projecten'[Niveau] =1)
			        ,2,CALCULATE(MIN('Projecten'[KostenplaatsKey]) ,'Projecten'[Niveau] =2)
			    )
			    ,IF(
			         [Controle project selectie] = 1 // Er is één hoofdproject geselecteerd met mogelijk meerdere deelprojecten.
			         ,CALCULATE(MAX('Projecten'[KostenplaatsKey] ),'Projecten'[Niveau] =1)
			         ,BLANK() //Als de selectie niet gewenst is dan wordt er geen KostenplaatsKey bepaald. 
			    )
			)
			```
		formatString: ##0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectselectie\1. Naar PowerApp

	measure 'Melding geselecteerde budget omzet methode' =
			
			"Budget omzet op basis van ["&max('Methode budgetomzet'[Omschrijving])&"] en kostpijs op basis van [calculatie(s) in opdracht]."
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Meldingen

	measure Niveau = ```
			
			IF(
			    [Controle project selectie] IN {0,2} //Er is slechts één hoofd- of deelproject geselecteerd.
			    ,SWITCH(
			        MIN('Projecten'[Niveau])
			        ,1,CALCULATE(MIN('Projecten'[Niveau]) ,'Projecten'[Niveau] =1)
			        ,2,CALCULATE(MIN('Projecten'[Niveau]) ,'Projecten'[Niveau] =2)
			    )
			    ,IF(
			         [Controle project selectie] = 1 // Er is één hoofdproject geselecteerd met mogelijk meerdere deelprojecten.
			         ,CALCULATE(
			             MIN('Projecten'[Niveau])
			             ,'Projecten'[Niveau] =1
			         )
			         ,BLANK() //Als de selectie niet gewenst is dan wordt er geen niveau bepaald. 
			    )
			)
			```
		formatString: ##0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectselectie

	measure 'Orderbedrag Cumulative' = ```
			
			CALCULATE (
			    SUM('Project eenmalige orderregels'[TotaalRegelbedrag Excl. BTW])
			    ,FILTER (
			        ALL ( 'Kalender'),
			        'Kalender'[Maand index] <= MAX ( 'Kalender'[Maand index])
			    )
			    ,USERELATIONSHIP(Kalender[Datum],'Project eenmalige orderregels'[Invoerdatum]) 
			)
			
			```
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Eenmalige orders

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"currencyCulture":"nl-NL"}

	measure Project =
			
			IF(
			    [Controle project selectie] = 0 //Er is slechts één deelproject geselecteerd.
			    , CALCULATE(MAX( 'Projecten'[Project] ), 'Projecten'[Niveau] = 2)
			    , IF(
			        [Controle project selectie] = 2 //Er is alleen het hoofdproject geselecteerd zonder deelprojecten
			        , CONCATENATE( CALCULATE(MAX( 'Projecten'[Project] ), 'Projecten'[Niveau] = 1), " (zonder deelprojecten)" )
			        , IF(
			            [Controle project selectie] = 1 // Er is één hoofdproject geselecteerd met mogelijk meerdere deelprojecten.
			            , CALCULATE(MAX('Projecten'[Project]),'Projecten'[Niveau] = 1)
			            , BLANK() //Als de selectie niet gewenst is dan wordt er geen project bepaald.
			        )
			    )
			)
		formatString: #,##0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectselectie

	measure 'Project Percentage gereed' =
			
			IF(
			    MIN(Projecten[Niveau])=1
			    ,MAX('Projecten'[Hoofdproject Percentage Gereed])
			    ,IF(
			        MIN(Projecten[Niveau])=2
			        ,max('Projecten'[Niveau 2 Percentage Gereed])
			        ,blank()
			    )
			)/100
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectselectie

	measure ProjectKey = ```
			
			IF(
			    [Controle project selectie] IN {0,2} //Er is slechts één hoofd- of deelproject geselecteerd.
			    ,SWITCH(
			        MIN('Projecten'[Niveau])
			        ,1,CALCULATE(MIN('Projecten'[ProjectKey]) ,'Projecten'[Niveau] =1)
			        ,2,CALCULATE(MIN('Projecten'[ProjectKey]) ,'Projecten'[Niveau] =2)
			    )
			    ,IF(
			         [Controle project selectie] = 1 // Er is één hoofdproject geselecteerd met mogelijk meerdere deelprojecten.
			         ,CALCULATE(MAX('Projecten'[HoofdProjectKey]),'Projecten'[Niveau] =1)
			         ,BLANK() //Als de selectie niet gewenst is dan wordt er geen ProjectKey bepaald. 
			    )
			)
			```
		formatString: ##0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectselectie\1. Naar PowerApp

	measure 'Type selectie' = ```
			
			IF(
			    [Controle project selectie] = 0 //Er is slechts één deelproject geselecteerd.
			    ,"Deelproject"
			    , IF(
			        [Controle project selectie] = 2 //Er is alleen het hoofdproject geselecteerd zonder deelprojecten
			        ,"Hoofdproject zonder deelprojecten"
			        
			        , IF(
			            [Controle project selectie] = 1 // Er is één hoofdproject geselecteerd met mogelijk meerdere deelprojecten.
			            , "Hoofdproject met  deelprojecten"
			            , "Verkeerde selectie"//Als de selectie niet gewenst is dan wordt er geen administratieKey bepaald.
			        )
			    )
			)
			```
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectselectie

	measure 'Verschil budget - realisatie' =
			
			[Budget kostprijs] - [Definitieve kostprijs]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Ratios

		changedProperty = IsHidden

	measure 'Verschil budget - realisatie definitief' =
			
			[Budget kostprijs] - [Definitieve kostprijs]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Ratios

		changedProperty = IsHidden

	measure 'Verschil calculatie - realisatie definitief' =
			
			[Calculatie kostprijs] - [Definitieve kostprijs]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Ratios

		changedProperty = IsHidden

	measure 'Verschil calculatie aantal - realisatie aantal' = [Calculatie aantal]-[Aantal gerealiseerd]
		formatString: #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Ratios

	measure 'Verschil prognose - realisatie' =
			
			[Prognose kostprijs o.b.v. methode wachte marge] - [Definitieve kostprijs]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Ratios

		changedProperty = IsHidden

	measure 'Verschil prognose - realisatie definitief' =
			
			[Prognose kostprijs o.b.v. methode wachte marge] - [Definitieve kostprijs]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Ratios

		changedProperty = IsHidden

	measure 'Verschil prognose - realisatie uren' =
			
			[Prognose uren] - [Gerealiseerde uren]
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Ratios

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Verschil VC - NC prijs per eenheid' = [Calculatie gem. prijs per eenheid]-[Gem. prijs per eenheid]
		formatString: "€"\ #,0.00;-"€"\ #,0.00;"€"\ #,0.00
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Ratios

	measure WerkgroepKey = ```
			
			IF(
			    [Controle project selectie] IN {0,2} //Er is slechts één hoofd- of deelproject geselecteerd.
			    ,SWITCH(
			        MIN('Projecten'[Niveau])
			        ,1,CALCULATE(MIN('Projecten'[WerkgroepKey]) ,'Projecten'[Niveau] =1)
			        ,2,CALCULATE(MIN('Projecten'[WerkgroepKey]) ,'Projecten'[Niveau] =2)
			    )
			    ,IF(
			         [Controle project selectie] = 1 // Er is één hoofdproject geselecteerd met mogelijk meerdere deelprojecten.
			         ,CALCULATE(MAX('Projecten'[WerkgroepKey]),'Projecten'[Niveau] =1)
			         ,BLANK() //Als de selectie niet gewenst is dan wordt er geen WerkgroepKey bepaald. 
			    )
			)
			```
		formatString: ##0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectselectie\1. Naar PowerApp

	measure 'Budget omzet o.b.v. orderbedrag' = ```
			
			[Orderbedrag]
			
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budget o.b.v. calculatiekostprijs en order

	measure 'Budget omzet o.b.v. calculatie verkoopprijs' = [Calculatie verkoopprijs]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Budget

	measure 'Budget omzet o.b.v. geselecteerde generiek marge' = DIVIDE( [Definitieve kostprijs (t/m standdatum)], 1 - [Generieke marge geselecteerd] )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Budget

	measure 'Budget omzet o.b.v. methode budgetomzet' = ```
			
			VAR _budgetomzet =
			IF(
			    VALUE( MAX( 'Methode budgetomzet'[ID] ) ) = 1
			    ,[Orderbedrag]
			    ,[Calculatie verkoopprijs]
			)
			
			VAR _budgetomzet_generieke_marge =
			IF(
			    [Methode ID verwachte marge geselecteerd] = 3
			    , DIVIDE( [Definitieve kostprijs (t/m standdatum)], 1 - [Generieke marge geselecteerd] )
			    , IF(
			        ISBLANK( [Orderbedrag] )
			        , DIVIDE( [Definitieve kostprijs (t/m standdatum)], 1 - [Generieke marge geselecteerd] )
			        , [Orderbedrag]
			    )
			)
			
			VAR Result = 
			IF(
			   [Methode ID verwachte marge geselecteerd] = 1
			   ,_budgetomzet 
			   ,_budgetomzet_generieke_marge
			)
			
			
			return
			    _budgetomzet
			
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Budget

	measure 'laatste budgetverzoek' = ```
			
			
			VAR _laatste_budgetverzoek =
			    max('NR - Projectbudgetverzoeken DQ'[Aanmaakdatum])
			 
			   
			VAR result = 
			IF(
			    ISINSCOPE(Projecten[Hoofdproject])
			    ,_laatste_budgetverzoek 
			    ,blank()
			)    
			
			
			RETURN
			    result
			```
		formatString: dd-mm-yy
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectbewaking

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'POC kostprijs o.b.v. budget' = ```
			var _poc = 
			DIVIDE([Definitieve kostprijs],[Calculatie kostprijs])
			
			VAR result =
			IF(
			    ISFILTERED('Projecten'[Hoofdproject] ) || ISFILTERED('Projecten'[Niveau 2 Project]) || ISFILTERED(Projecten[Niveau 3 Project]) || ISFILTERED(Projecten[Project])
			    , _poc
			    , BLANK()
			)
			
			RETURN
			result
			```
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC

	measure 'POC montage uren o.b.v. budget' = ```
			
			var _poc = 
			DIVIDE([Montage uren],[Calculatie montage uren])
			
			
			VAR result =
			IF(
			    ISFILTERED('Projecten'[Hoofdproject] ) || ISFILTERED('Projecten'[Niveau 2 Project]) || ISFILTERED(Projecten[Niveau 3 Project]) || ISFILTERED(Projecten[Project])
			    , _poc
			    , BLANK()
			)
			
			RETURN
			result
			```
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC

	measure 'POC kostprijs o.b.v. prognose' = ```
			
			//Op basis van definitieve kosten.
			
			var _poc = 
			DIVIDE([Definitieve kostprijs],[Prognose kostprijs o.b.v. methode wachte marge])
			
			
			VAR result =
			IF(
			    ISFILTERED('Projecten'[Hoofdproject] ) || ISFILTERED('Projecten'[Niveau 2 Project]) || ISFILTERED(Projecten[Niveau 3 Project]) || ISFILTERED(Projecten[Project]) 
			    , _poc
			    , BLANK()
			)
			
			RETURN
			_poc
			
			
			
			
			
			
			```
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC

		changedProperty = FormatString

	measure 'POC montage uren o.b.v. prognose' = ```
			
			var _poc = 
			DIVIDE([Montage uren],[Prognose montage uren])
			
			
			VAR result =
			IF(
			    ISFILTERED('Projecten'[Hoofdproject] ) || ISFILTERED('Projecten'[Niveau 2 Project]) || ISFILTERED(Projecten[Niveau 3 Project]) || ISFILTERED(Projecten[Project])
			    , _poc
			    , BLANK()
			)
			
			RETURN
			_poc
			```
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC

	measure Voortgang = ```
			/*
			De voortgang wordt bepaald op basis van de geselecteerde voortgang methode. Deze formule kan ook klanten met alleen budget (maar zonder prognose) 
			worden gebruikt. voor 'budget' klanten is prognose gelijk aan budget. Er zijn immers geen verzoeken. 
			*/
			
			SWITCH(
			    MAX('Methode voortgang'[ID])
			    ,1,[Historische POC kostprijs o.b.v. prognose]
			    ,2,[Project percentage gereed]
			    ,3,[Historische POC uren o.b.v. prognose]
			    ,4,[Historische POC montage uren o.b.v. prognose]
			)
			```
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Ratios

	measure 'Historische POC kostprijs o.b.v. budget' = ```
			
			var _poc = 
			DIVIDE([Definitieve kostprijs (t/m standdatum)],[budget kostprijs])
			
			VAR result =
			IF(
			    ISFILTERED('Projecten'[Hoofdproject] ) || ISFILTERED('Projecten'[Niveau 2 Project]) || ISFILTERED(Projecten[Niveau 3 Project]) || ISFILTERED(Projecten[Project])
			    , _poc
			    , BLANK()
			)
			
			RETURN
			result
			```
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC

	measure 'Historische POC kostprijs o.b.v. prognose' =
			
			var _poc =
			DIVIDE([Definitieve kostprijs (t/m standdatum)],[Prognose kostprijs o.b.v. methode wachte marge])
			
			
			VAR result =
			IF(
			    ISFILTERED('Projecten'[Hoofdproject] ) || ISFILTERED('Projecten'[Niveau 2 Project]) || ISFILTERED(Projecten[Niveau 3 Project]) || ISFILTERED(Projecten[Project])
			    , _poc
			    , BLANK()
			)
			
			RETURN
			result
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC

	measure 'Historische POC montage uren o.b.v. budget' = ```
			
			var _poc = 
			DIVIDE([Montage uren historisch],[Calculatie montage uren])
			
			
			VAR result =
			IF(
			    ISFILTERED('Projecten'[Hoofdproject] ) || ISFILTERED('Projecten'[Niveau 2 Project]) || ISFILTERED(Projecten[Niveau 3 Project]) || ISFILTERED(Projecten[Project])
			    , _poc
			    , BLANK()
			)
			
			RETURN
			result
			```
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC

	measure 'Historische POC montage uren o.b.v. prognose' = ```
			
			var _poc = 
			DIVIDE([Montage uren historisch],[Prognose montage uren])
			
			
			VAR result =
			IF(
			    ISFILTERED('Projecten'[Hoofdproject] ) || ISFILTERED('Projecten'[Niveau 2 Project]) || ISFILTERED(Projecten[Niveau 3 Project]) || ISFILTERED(Projecten[Project])
			    , _poc
			    , BLANK()
			)
			
			RETURN
			_poc
			```
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC

	measure 'Historische POC uren o.b.v. budget' = ```
			
			var _poc = 
			DIVIDE([Gerealiseerde uren historisch projecten],[Budget uren])
			
			
			VAR result =
			IF(
			    ISFILTERED('Projecten'[Hoofdproject] ) || ISFILTERED('Projecten'[Niveau 2 Project]) || ISFILTERED(Projecten[Niveau 3 Project]) || ISFILTERED(Projecten[Project])
			    , _poc
			    , BLANK()
			)
			
			RETURN
			result
			```
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC

	measure 'Historische POC uren o.b.v. prognose' = ```
			
			var _poc = 
			DIVIDE([Gerealiseerde uren historisch projecten],[Prognose uren])
			
			
			VAR result =
			IF(
			    ISFILTERED('Projecten'[Hoofdproject] ) || ISFILTERED('Projecten'[Niveau 2 Project]) || ISFILTERED(Projecten[Niveau 3 Project]) || ISFILTERED(Projecten[Project])
			    , _poc
			    , BLANK()
			)
			
			RETURN
			_poc
			```
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC

	/// Voortgang facturatie t.o.v. [budget omzet]
	measure 'Historische POC omzet o.b.v. budget' = DIVIDE([Historische omzet (t/m standdatum)],[Budget omzet o.b.v. methode budgetomzet])
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC

	/// Voortgang facturatie t.o.v. prognose omzet
	measure 'Historische POC omzet o.b.v. prognose' = DIVIDE([Historische omzet (t/m standdatum)],[Prognose omzet o.b.v. methode verwachte marge])
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC

	/// Voortgang facturatie t.o.v. [budget omzet]
	measure 'POC omzet o.b.v. budget' = DIVIDE([Project omzet],[Budget omzet o.b.v. methode budgetomzet])
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC

	/// Voortgang facturatie t.o.v. prognose omzet
	measure 'POC omzet o.b.v. prognose' = DIVIDE([Project omzet],[Budget omzet o.b.v. methode budgetomzet])
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC

	measure 'POC uren o.b.v. budget' = ```
			
			var _poc = 
			DIVIDE([Gerealiseerde uren projecten],[Budget uren])
			
			
			VAR result =
			IF(
			    ISFILTERED('Projecten'[Hoofdproject] ) || ISFILTERED('Projecten'[Niveau 2 Project]) || ISFILTERED(Projecten[Niveau 3 Project]) || ISFILTERED(Projecten[Project])
			    , _poc
			    , BLANK()
			)
			
			RETURN
			result
			```
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC

	measure 'POC uren o.b.v. prognose' = ```
			
			var _poc = 
			DIVIDE([Gerealiseerde uren projecten],[Prognose uren])
			
			
			VAR result =
			IF(
			    ISFILTERED('Projecten'[Hoofdproject] ) || ISFILTERED('Projecten'[Niveau 2 Project]) || ISFILTERED(Projecten[Niveau 3 Project]) || ISFILTERED(Projecten[Project])
			    , _poc
			    , BLANK()
			)
			
			RETURN
			_poc
			```
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC

	measure 'POC projectgebonden uren o.b.v. prognose' = DIVIDE( [Projectgebonden uren], [Prognose projectgebonden uren] )
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC

	measure 'POC projectgebonden uren  o.b.v. budget' = DIVIDE( [Projectgebonden uren], [Budget projectgebonden uren] )
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC

	measure 'POC overig kostprijs o.b.v. prognose' = DIVIDE( [Definitieve kostprijs overig], [Prognose kostprijs overig] )
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC

	measure 'POC overig kostprijs o.b.v. budget' = DIVIDE( [Definitieve kostprijs overig], [Budget kostprijs overig] )
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC

	measure 'POC materieel kostprijs o.b.v. prognose' = DIVIDE( [Definitieve kostprijs materieel], [Prognose kostprijs materieel] )
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC

	measure 'POC materieel kostprijs o.b.v. budget' = DIVIDE( [Definitieve kostprijs materieel], [Budget kostprijs materieel] )
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC

	measure 'POC materiaal kostprijs o.b.v. prognose' = DIVIDE( [Definitieve kostprijs materiaal], [Prognose kostprijs materiaal] )
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC

	measure 'POC materiaal kostprijs o.b.v. budget' = DIVIDE( [Definitieve kostprijs materiaal], [Budget kostprijs materiaal] )
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC

	measure 'POC arbeid kostprijs o.b.v. budget' = DIVIDE( [Definitieve kostprijs arbeid], [Budget kostprijs arbeid] )
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC

	measure 'POC arbeid kostprijs o.b.v. prognose' = DIVIDE( [Definitieve kostprijs arbeid], [Prognose kostprijs arbeid] )
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC

	measure 'Historische projectwaardering o.b.v. budget' = ```
			
			/*
			Functie;
			Berekenen van de projectwaardering o.b.v. de voorgang * verwacht resultaat.
			
			
			Aanpassingen; 
			
			1. 2023-06-29;  Relatie tussen omzet SOLL en projectwaardering verwijderd. Projectwaardering werd berekend op basis van; omzet SOLL - gerealiseerde kosten. Dit lijkt echter niet meer 
			correct te zijn met de komst van de meerdere voortgang methodes (PG syntess, POC uren). Daarom Projectwaardering als zelfstandige berekening.
			
			Auteur: Mark Haring
			
			Datum: 2023-06-01
			
			*/
			
			VAR __pw_per_hoofdproject =
			SUMMARIZE(
			   Projecten
			   ,projecten[hoofdproject]
			   ,"_pw"
			    ,IF(
			        ISBLANK([Budget resultaat])||ISBLANK([Voortgang])
			        , BLANK()
			        , IF(
			            [Budget resultaat] < 0 --Als resultaat prognose negatief is dan het volledig resultaat Budget direct nemen.
			            , [Budget resultaat]
			            ,[Voortgang]*[Budget resultaat]
			        )
			    )
			)
			
			VAR result =
			SUMX(__pw_per_hoofdproject,[_pw])
			
			return
			result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectwaardering

	measure 'Historische projectwaardering o.b.v. prognose' = ```
			
			/*Functie;Berekenen van de projectwaardering o.b.v. de voorgang * verwacht resultaat.Aanpassingen; 1. 2023-06-29;  Relatie tussen omzet SOLL en projectwaardering verwijderd. Projectwaardering werd berekend op basis van; omzet SOLL - gerealiseerde kosten. Dit lijkt echter niet meer correct te zijn met de komst van de meerdere voortgang methodes (PG syntess, POC uren). Daarom Projectwaardering als zelfstandige berekening.Auteur: Mark HaringDatum: 2023-06-01*/VAR __pw_per_hoofdproject = 
			SUMMARIZE(
			   Projecten
			   ,projecten[hoofdproject]
			   ,"_pw"
			    ,IF(
			        ISBLANK([Prognose resultaat])||ISBLANK([Voortgang])
			        , BLANK()
			        , IF(
			            [Prognose resultaat] < 0 --Als resultaat prognose negatief is dan het volledig resultaat prognose direct nemen.
			            , [Prognose resultaat]
			            ,[Voortgang]*[Prognose resultaat]
			        )
			    )
			)
			
			VAR result =
			SUMX(__pw_per_hoofdproject,[_pw])
			
			return
			result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectwaardering

	measure 'Historische correctieboeking (berekend) projectwaardering o.b.v. prognose' =
			VAR __correctie_per_hoofdproject =
			   SUMMARIZE(
			       'Projecten'
			       ,'Projecten'[Hoofdproject]
			       ,"__corr"
			       ,[Historische projectwaardering o.b.v. prognose]-[Projectjournalisering projectwaarderingen (t/m standdatum)]
			   )
			
			VAR result =
			SUMX(
			    __correctie_per_hoofdproject
			    ,[__corr]
			)
			
			RETURN
			    result
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectwaardering

	measure 'Historische correctieboeking (berekend) projectwaardering o.b.v. budget' =
			VAR __correctie_per_hoofdproject =
			   SUMMARIZE(
			       'Projecten'
			       ,'Projecten'[Hoofdproject]
			       ,"__corr"
			       ,[Historische projectwaardering o.b.v. prognose]-[Projectjournalisering projectwaarderingen (t/m standdatum)]
			   )
			
			VAR result =
			SUMX(
			    __correctie_per_hoofdproject
			    ,[__corr]
			)
			
			RETURN
			    result
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectwaardering

	measure 'Historische omzetcorrectie o.b.v. budget' = ```
			
			/*
			Functie: Berekenen van de omzetcorrectie per hoofdproject op basis van de geselecteerde standdatum. 
			
			De omzetcorrectie in de basis;
			(budget omzet * Voortgang)-gerealiseerde omzet
			
			Overleg met Arthur (2022-12-28);
			-Wat als de POC > 1 is? 
			    >>Dan [__verwachte_omzet]-[__Gerealiseerde_omzet] 
			-Wat als de POC leeg is? 
			    >>Mogelijk signalering in visual op ontbrekende data.
			-Wat als het verwachte resultaat negatief is? 
			    >>Vooralsnog On Hold. Tevens bij projectwaardering On Hold zetten.
			    
			             , IF(
			                 [__verwacht_resultaat] < 0 --Als resultaat prognose negatief is dan het volledig resultaat prognose direct nemen.
			                 , [__verwacht_resultaat] 
			                 ,( [__verwachte_omzet] * [__POC] ) - [__Gerealiseerde_omzet]
			             )    
			    
			    
			-Toevoegen van optie om ook met POC montage uren de omzetcorrectie (en projectwaardering) te berekenen?
			    >>Op basis van ervaringen met gebruik door klanten. Vooralsnog On Hold.
			-Wat te doen met regie omzet en regie kosten? 
			    > Helemaal eruit halen in de realisatie (misschien wel apart tonen) maar niet meenemen in beoordeling gerealiseerde kosten en opbrengsten.
			    > Op basis van factureerwijze van project (= tricky omdat deze door klant aangepast kan worden. In principe Vaste prijs en Regie).
			    > Of op basis van omzet wel/niet vanuit order en kosten o.b.v. factureerstatus (niet/nooit factureren = vaste prijs. Nog te factureren en gefactureerd = regie). 
			    >>Op basis van ervaringen met gebruik door klanten. Vooralsnog On Hold.
			
			Aanpassingen:
			- 1. 18-6-2023; POC kostprijs is vervangen door voortgang. De voortgang is afhankelijk van de geselecteerde voortgang methode (POC kostprijs, PG syntess, POC uren of POC Montage uren)
			
			Auteur:     MCH
			Datum:      28-12-2022
			*/
			VAR _projecttabel =
			SUMMARIZE(
			    Projecten
			    , Projecten[Hoofdproject]
			    , "__Gerealiseerde_omzet"
			    ,[Historische omzet (t/m standdatum)]
			    , "__verwachte_omzet"
			    ,IF( [Historische omzet (t/m standdatum)] > [Budget omzet o.b.v. methode budgetomzet], [Historische omzet (t/m standdatum)], [Budget omzet o.b.v. methode budgetomzet] )
			    ,"__Voortgang"
			    ,[Voortgang]
			)
			 
			 VAR _omzetcorrectie =
			 SUMX(
			     _projecttabel
			     , IF(
			         [__Voortgang] > 1 --als Voortgang groter dan 100% is dan resultaat budget als waardering.
			         , [__verwachte_omzet]-[__Gerealiseerde_omzet] 
			         , IF(
			             ISBLANK( [__Voortgang] )
			             , BLANK()
			             ,( [__verwachte_omzet] * [__Voortgang] ) - [__Gerealiseerde_omzet]
			         )
			     )
			 )
			
			VAR result = _omzetcorrectie
			
			return
			result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Omzetcorrectie

	measure 'Historische omzet SOLL o.b.v. budget' = ```
			
			/*
			Functie: Berekenen van de omzet SOLL (=omzet zoals deze zou moeten zij) per hoofdproject op basis van de geselecteerde standdatum. 
			
			De omzet SOLL is in de basis;
			Budget omzet * Voortgang
			
			Overleg met Arthur (2022-12-28);
			-Wat als de POC > 1 is? 
			    >>Dan [__verwachte_omzet]-[__Gerealiseerde_omzet] 
			-Wat als de POC leeg is? 
			    >>Mogelijk signalering in visual op ontbrekende data.
			-Wat als het verwachte resultaat negatief is? 
			    >>Vooralsnog On Hold. Tevens bij projectwaardering On Hold zetten.
			    
			             , IF(
			                 [__verwacht_resultaat] < 0 --Als resultaat prognose negatief is dan het volledig resultaat prognose direct nemen.
			                 , [__verwacht_resultaat] 
			                 ,( [__verwachte_omzet] * [__POC] ) - [__Gerealiseerde_omzet]
			             )    
			    
			    
			-Toevoegen van optie om ook met POC montage uren de omzetcorrectie (en projectwaardering) te berekenen?
			    >>Op basis van ervaringen met gebruik door klanten. Vooralsnog On Hold.
			-Wat te doen met regie omzet en regie kosten? 
			    > Helemaal eruit halen in de realisatie (misschien wel apart tonen) maar niet meenemen in beoordeling gerealiseerde kosten en opbrengsten.
			    > Op basis van factureerwijze van project (= tricky omdat deze door klant aangepast kan worden. In principe Vaste prijs en Regie).
			    > Of op basis van omzet wel/niet vanuit order en kosten o.b.v. factureerstatus (niet/nooit factureren = vaste prijs. Nog te factureren en gefactureerd = regie). 
			    >>Op basis van ervaringen met gebruik door klanten. Vooralsnog On Hold.
			
			Aanpassingen:
			- 1. 18-6-2023; POC kostprijs is vervangen door voortgang. De voortgang is afhankelijk van de geselecteerde voortgang methode (POC kostprijs, PG syntess, POC uren of POC Montage uren)
			
			Auteur:     MCH
			Datum:      28-12-2022
			*/
			VAR _projecttabel =
			SUMMARIZE(
			    'Projecten'
			    , 'Projecten'[Hoofdproject]
			    , "__Gerealiseerde_omzet"
			    ,[Historische omzet (t/m standdatum)]
			    , "__verwachte_omzet"
			    ,IF( [Historische omzet (t/m standdatum)] > [Budget omzet o.b.v. methode budgetomzet], [Historische omzet (t/m standdatum)], [Budget omzet o.b.v. methode budgetomzet] )
			    ,"__Voortgang"
			    ,[Voortgang]
			)
			 
			 VAR _omzet_soll =
			 SUMX(
			     _projecttabel
			     , IF(
			         [__Voortgang] > 1 --als Voortgang groter dan 100% is dan resultaat prognose als waardering.
			         , [__verwachte_omzet]
			         , IF(
			             ISBLANK( [__Voortgang] )
			             , BLANK()
			             ,( [__verwachte_omzet] * [__Voortgang] )
			         )
			     )
			 )
			
			VAR result = _omzet_soll
			
			return
			result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Omzetcorrectie

	measure 'Historische omzet SOLL o.b.v. prognose' = ```
			
			/*
			Functie: Berekenen van de omzet SOLL (=omzet zoals deze zou moeten zij) per hoofdproject op basis van de geselecteerde standdatum. 
			
			De omzet SOLL is in de basis;
			Prognose omzet * Voortgang
			
			Overleg met Arthur (2022-12-28);
			-Wat als de POC > 1 is? 
			    >>Dan [__verwachte_omzet]-[__Gerealiseerde_omzet] 
			-Wat als de POC leeg is? 
			    >>Mogelijk signalering in visual op ontbrekende data.
			-Wat als het verwachte resultaat negatief is? 
			    >>Vooralsnog On Hold. Tevens bij projectwaardering On Hold zetten.
			    
			             , IF(
			                 [__verwacht_resultaat] < 0 --Als resultaat prognose negatief is dan het volledig resultaat prognose direct nemen.
			                 , [__verwacht_resultaat] 
			                 ,( [__verwachte_omzet] * [__POC] ) - [__Gerealiseerde_omzet]
			             )    
			    
			    
			-Toevoegen van optie om ook met POC montage uren de omzetcorrectie (en projectwaardering) te berekenen?
			    >>Op basis van ervaringen met gebruik door klanten. Vooralsnog On Hold.
			-Wat te doen met regie omzet en regie kosten? 
			    > Helemaal eruit halen in de realisatie (misschien wel apart tonen) maar niet meenemen in beoordeling gerealiseerde kosten en opbrengsten.
			    > Op basis van factureerwijze van project (= tricky omdat deze door klant aangepast kan worden. In principe Vaste prijs en Regie).
			    > Of op basis van omzet wel/niet vanuit order en kosten o.b.v. factureerstatus (niet/nooit factureren = vaste prijs. Nog te factureren en gefactureerd = regie). 
			    >>Op basis van ervaringen met gebruik door klanten. Vooralsnog On Hold.
			
			Aanpassingen:
			- 1. 18-6-2023; POC kostprijs is vervangen door voortgang. De voortgang is afhankelijk van de geselecteerde voortgang methode (POC kostprijs, PG syntess, POC uren of POC Montage uren)
			
			
			Auteur:     MCH
			Datum:      28-12-2022
			*/
			VAR _projecttabel =
			SUMMARIZE(
			    'Projecten'
			    , 'Projecten'[Hoofdproject]
			    , "__Gerealiseerde_omzet"
			    ,[Historische omzet (t/m standdatum)]
			    , "__verwachte_omzet"
			    ,IF( [Historische omzet (t/m standdatum)] > [Prognose omzet o.b.v. methode verwachte marge], [Historische omzet (t/m standdatum)], [Prognose omzet o.b.v. methode verwachte marge] )
			    ,"__Voortgang"
			    ,[Voortgang]
			)
			 
			 VAR _omzet_soll=
			 SUMX(
			     _projecttabel
			     , IF(
			         [__Voortgang] > 1 --als POC groter dan 100% is dan resultaat prognose als waardering.
			         , [__verwachte_omzet]
			         , IF(
			             ISBLANK( [__Voortgang] )
			             , BLANK()
			             ,( [__verwachte_omzet] * [__Voortgang] )
			         )
			     )
			 )
			
			VAR result = _omzet_soll
			
			return
			result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Omzetcorrectie

	measure 'Historische omzetcorrectie o.b.v. prognose' = ```
			
			/*
			Functie: Berekenen van de omzetcorrectie per hoofdproject op basis van de geselecteerde standdatum. 
			
			De omzetcorrectie in de basis;
			(prognose omzet * Voortgang)-gerealiseerde omzet
			
			Overleg met Arthur (2022-12-28);
			-Wat als de POC > 1 is? 
			    >>Dan [__verwachte_omzet]-[__Gerealiseerde_omzet] 
			-Wat als de POC leeg is? 
			    >>Mogelijk signalering in visual op ontbrekende data.
			-Wat als het verwachte resultaat negatief is? 
			    >>Vooralsnog On Hold. Tevens bij projectwaardering On Hold zetten.
			    
			             , IF(
			                 [__verwacht_resultaat] < 0 --Als resultaat prognose negatief is dan het volledig resultaat prognose direct nemen.
			                 , [__verwacht_resultaat] 
			                 ,( [__verwachte_omzet] * [__POC] ) - [__Gerealiseerde_omzet]
			             )    
			    
			    
			-Toevoegen van optie om ook met POC montage uren de omzetcorrectie (en projectwaardering) te berekenen?
			    >>Op basis van ervaringen met gebruik door klanten. Vooralsnog On Hold.
			-Wat te doen met regie omzet en regie kosten? 
			    > Helemaal eruit halen in de realisatie (misschien wel apart tonen) maar niet meenemen in beoordeling gerealiseerde kosten en opbrengsten.
			    > Op basis van factureerwijze van project (= tricky omdat deze door klant aangepast kan worden. In principe Vaste prijs en Regie).
			    > Of op basis van omzet wel/niet vanuit order en kosten o.b.v. factureerstatus (niet/nooit factureren = vaste prijs. Nog te factureren en gefactureerd = regie). 
			    >>Op basis van ervaringen met gebruik door klanten. Vooralsnog On Hold.
			
			Aanpassingen:
			- 1. 18-6-2023; POC kostprijs is vervangen door voortgang. De voortgang is afhankelijk van de geselecteerde voortgang methode (POC kostprijs, PG syntess, POC uren of POC Montage uren)
			
			
			Auteur:     MCH
			Datum:      28-12-2022
			*/
			VAR _projecttabel =
			SUMMARIZE(
			    Projecten
			    , Projecten[Hoofdproject]
			    , "__Gerealiseerde_omzet"
			    ,[Historische omzet (t/m standdatum)]
			    , "__verwachte_omzet"
			    ,IF( [Historische omzet (t/m standdatum)] > [Prognose omzet o.b.v. methode verwachte marge], [Historische omzet (t/m standdatum)], [Prognose omzet o.b.v. methode verwachte marge] )
			    ,"__Voortgang"
			    ,[Historische POC kostprijs o.b.v. prognose]
			)
			 
			 VAR _omzetcorrectie =
			 SUMX(
			     _projecttabel
			     , IF(
			         [__Voortgang] > 1 --als Voortgang groter dan 100% is dan resultaat prognose als waardering.
			         , [__verwachte_omzet]-[__Gerealiseerde_omzet] 
			         , IF(
			             ISBLANK( [__Voortgang] )
			             , BLANK()
			             ,( [__verwachte_omzet] * [__Voortgang] ) - [__Gerealiseerde_omzet]
			         )
			     )
			 )
			
			VAR result = _omzetcorrectie
			
			return
			result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Omzetcorrectie

	measure 'Opgeslagen omzetcorrectie' = ```
			
			0
			
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Omzetcorrectie

	measure 'Werkelijk rendement o.b.v. prognose' = DIVIDE([Historische projectwaardering o.b.v. prognose],[Historische omzet SOLL o.b.v. prognose])
		formatString: #,##0 %
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Ratios

	measure 'Werkelijk rendement o.b.v. budget' = DIVIDE([Historische projectwaardering o.b.v. budget],[Historische omzet SOLL o.b.v. budget])
		formatString: #,##0 %
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Ratios

	measure 'Methode ID voortgang geselecteerd' = MAX('Methode voortgang'[ID])
		formatString: #,##0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Methodes

	measure 'Methode ID verwachte marge geselecteerd' = MAX('Methode verwachte marge'[ID])
		formatString: #,##0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Methodes

	measure 'Generieke marge geselecteerd' = MAX('Methode generieke marge'[Value])
		formatString: #,##0.00 %
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Methodes

	measure 'Methode ID budget omzet geselecteerd' = MAX('Methode budgetomzet'[ID])
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Methodes

	measure 'Methode budget omzet geselecteerd' = MAX('Methode budgetomzet'[Omschrijving])
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Methodes

	measure 'Methode verwachte marge geselecteerd' = MAX('Methode verwachte marge'[Omschrijving])
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Methodes

	measure 'Methode voortgang geselecteerd' = MAX('Methode voortgang'[Omschrijving])
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Methodes

	measure 'Melding geselecteerde methode voortgang' = "Geselecteerde voortgang methode: "&[Methode voortgang geselecteerd]
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Meldingen

	measure 'Melding generieke marge' =
			
			IF(
			         [Methode ID verwachte marge geselecteerd]IN {2,3},
			         "Generieke marge", -- returns transparent if bulk marge is selected
			         "Generieke marge niet van toepassing"
			      )
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Meldingen

	measure 'Gemiddeld uurtarief projectgebonden uren' = DIVIDE([Projectgebonden arbeidskosten],[Projectgebonden uren])
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid

	measure 'Gemiddeld uurtarief montage uren' = DIVIDE([Montage arbeidskosten],[Montage uren])
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid

	measure 'Inleen via inkoop' = ```
			
			/*
			Werkuren vanuit de urenstaten plus werkuren van inleners die direct via inkoopfacturen op projecten worden geboekt.
			Voorwaarde voor inleners via inkoopfacturen is dat 1) er een kostensoort [Arbeid] wordt gebruikt en 2) de eenheid [u/Uur]
			met internationale code 570410.
			*/
			CALCULATE(
			    SUM('Project kosten en geboekte uren'[Aantal])
			    ,'Kostensoorten'[Categorie] = "Arbeid"
			    ,'Project kosten en geboekte uren'[Kostenbron] = "Inkoop"
			    ,'Project kosten en geboekte uren'[internationale code] = "570410"
			)
			
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid

		changedProperty = IsHidden

	measure 'inleen via inkoop cumulatief' = ```
			
			CALCULATE (
			    SUM('Project kosten en geboekte uren'[Aantal])
			    ,'Kostensoorten'[Categorie] = "Arbeid"
			    ,'Project kosten en geboekte uren'[Kostenbron] = "Inkoop"
			    ,'Project kosten en geboekte uren'[internationale code] = "570410"
			    ,FILTER (
			        ALL ('Kalender'[Datum]),
			        'Kalender'[Datum] <= MAX ('Kalender'[Datum])
			    )
			)
			
			
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Montage arbeidskosten' =
			
			CALCULATE(
			    SUM('Project kosten en geboekte uren'[Kostprijs])
			    ,'NR - Taakgroepen DQ'[Taakgroep] = "Montage"
			)
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid

	measure 'Projectgebonden arbeidskosten' =
			
			CALCULATE(
			     SUM('Project kosten en geboekte uren'[Kostprijs])
			    ,'NR - Taakgroepen DQ'[Taakgroep] = "Projectgebonden"
			)
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid

		changedProperty = IsHidden

	measure 'Montage uren NOT BLANK' = ```
			
			         
			    if(
			        ISBLANK([Montage uren]),
			        "-",
			        [Montage uren])  
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid

		changedProperty = IsHidden

	measure 'Gemiddeld uurtarief' = DIVIDE([Arbeidskosten],[Gerealiseerde uren projecten])
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid

	measure Arbeidskosten =
			
			CALCULATE(
			     SUM('Project kosten en geboekte uren'[Kostprijs])
			    ,NOT(ISBLANK('Project kosten en geboekte uren'[TaakKey]))
			)
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid

		changedProperty = IsHidden

	measure 'Betaald bedrag via orderregel' = ```
			
			var BetaaldBedrag = 
			SUM('Betalingen per opbrengstregel (alleen orderregels)'[BetaaldExclBTW])
			
			return
			IF(
			    ISBLANK(BetaaldBedrag),
			    IF(
			        NOT(ISBLANK([Orderbedrag])),
			        0,
			        BLANK()),
			    BetaaldBedrag
			)
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Betalingen\Via orderregels vanuit project

		changedProperty = IsHidden

	measure 'Betalingen en openstaand' = ```
			
			    [Betalingen op inkoopregels]+[Openstaand op inkoopregels]
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Betalingen\Inkoopfactuur betalingen vanuit project

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Betalingen op inkoopregels' =
			
			//Exclusief BTW. Op basis van werkelijke inkoopprijs (=verrekenprijs).
			    SUM('Betalingen per inkoopregel'[BetaaldExclBTW])
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Betalingen\Inkoopfactuur betalingen vanuit project

		changedProperty = IsHidden

	measure 'Cash in' = ```
			
			SUM('Betalingen per opbrengstregel'[BetaaldExclBTW])
			
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Betalingen\Verkoopfactuur betalingen vanuit project

		changedProperty = IsHidden

	measure 'Cash in via order' = ```
			
			 CALCULATE(
			    SUM('Betalingen per opbrengstregel'[BetaaldExclBTW])
			    ,NOT(ISBLANK('Betalingen per opbrengstregel'[OrderregelKey]))
			)
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Betalingen\Verkoopfactuur betalingen vanuit project

		changedProperty = IsHidden

	measure 'Openstaand bedrag' = ```
			
			    SUM('Betalingen per opbrengstregel'[OpenstaandExclBTW])
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Betalingen\Verkoopfactuur betalingen vanuit project

		changedProperty = IsHidden

	measure 'Openstaand bedrag via orderregel' = ```
			
			var OpenstaandBedrag = 
			SUM('Betalingen per opbrengstregel (alleen orderregels)'[OpenstaandExclBTW])
			
			return
			IF(
			    ISBLANK(OpenstaandBedrag),
			    IF(
			        NOT(ISBLANK([Orderbedrag])),
			        0,
			        BLANK()),
			    OpenstaandBedrag
			)
			    
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Betalingen\Via orderregels vanuit project

		changedProperty = IsHidden

	measure 'Openstaand op inkoopregels' =
			
			//Exclusief BTW. Op basis van werkelijke inkoopprijs (=verrekenprijs).
			    SUM('Betalingen per inkoopregel'[OpenstaandExclBTW])
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Betalingen\Inkoopfactuur betalingen vanuit project

		changedProperty = IsHidden

	measure 'Vervallen betalingstermijnen' = ```
			
			var telaat=
			        CALCULATE(
			            SUM('Betalingen per opbrengstregel'[OpenstaandExclBTW]),
			            FILTER( 
			                'Betalingen per opbrengstregel' ,
			                'Betalingen per opbrengstregel'[Vervaldatum] < TODAY())
			        )
			return
			IF(
			    ISBLANK(telaat),
			    IF(
			        NOT(ISBLANK([Cash in via order])),
			        0,
			        blank()
			    ),
			    telaat
			)
			
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Betalingen\Verkoopfactuur betalingen vanuit project

		changedProperty = IsHidden

	measure 'Vervallen betalingstermijnen via orderregel' = ```
			
			var vervallen = 
			       CALCULATE(
			            SUM('Betalingen per opbrengstregel (alleen orderregels)'[OpenstaandExclBTW])
			            ,'Betalingen per opbrengstregel (alleen orderregels)'[Vervallen] = "Ja"
			       )
			return
			IF(
			    ISBLANK(vervallen),
			    IF(
			        NOT(ISBLANK([Orderbedrag])),
			        0,
			        BLANK()
			    ),
			    vervallen
			)
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Betalingen\Via orderregels vanuit project

		changedProperty = IsHidden

	measure 'Aantal gerealiseerd' = ```
			
			SUM('Project kosten en geboekte uren'[Aantal])
			
			```
		formatString: #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

		changedProperty = IsHidden

	measure 'Definitieve kostprijs cum.' = ```
			
			CALCULATE (
			    [Definitieve kostprijs]
			    ,FILTER (
			        ALL ( 'Kalender'),
			        'Kalender'[Maand index] <= MAX ( 'Kalender'[Maand index] )
			    )
			)
			
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

		changedProperty = FormatString

	measure 'Gem. prijs per eenheid' = DIVIDE( [Verrekenprijs inkoop], [Aantal gerealiseerd] )
		formatString: "€"\ #,0.00;-"€"\ #,0.00;"€"\ #,0.00
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

	measure 'Onverwerkte kostprijs inkoop' = ```
			
			CALCULATE(
			    SUM('Project kosten en geboekte uren'[Kostprijs])
			    ,'Project kosten en geboekte uren'[Kostenbron] = "Inkoop" ||'Project kosten en geboekte uren'[Kostenbron] = "Pakbon" 
			    ,'Project kosten en geboekte uren'[Kostenstatus] = "Nog te verwachten"
			)
			
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

		changedProperty = IsHidden

	measure 'Totaal kosten cum. (verrekenprijs onverwerkt, kostprijs definitief)' = ```
			
			CALCULATE (
			    SUM ( 'Project kosten en geboekte uren'[Verrekenprijs] )
			    ,'Project kosten en geboekte uren'[Kostenstatus] = "Nog te verwachten"
			    ,FILTER (
			        ALL ( 'Kalender'),
			        Kalender[datum] <= MAX ( 'Kalender'[datum])
			    )
			    
			)
			
			+
			CALCULATE (
			    SUM ( 'Project kosten en geboekte uren'[Kostprijs] )
			    ,'Project kosten en geboekte uren'[Kostenstatus] = "Definitief"
			    ,FILTER (
			        ALL ( 'Kalender'),
			        'Kalender'[datum] <= MAX ( 'Kalender'[datum] )
			    )
			)
			
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

		changedProperty = IsHidden

	measure 'Totaal kosten inkoop (verrekenprijs onverwerkt, kostprijs definitief)' = ```
			
			 [Onverwerkte verrekenprijs inkoop] + [Definitieve kostprijs inkoop]
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

		changedProperty = IsHidden

	measure 'Verrekenprijs inkoop' = ```
			
			    CALCULATE(
			        SUM('Project kosten en geboekte uren'[Verrekenprijs]),
			        Kostensoorten[Categorie] <> "Arbeid"
			        )
			
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

		changedProperty = IsHidden

	measure 'Verschil kostprijs tov verrekenprijs' = [Definitieve kostprijs]-[Definitieve verrekenprijs]
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

	measure 'Nog niet betaald van orderregel' = ```
			
			    [Orderbedrag]-[Betaald bedrag via orderregel]
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Betalingen\Via orderregels vanuit project

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Waardering =
			
			CALCULATE(
			    [Debet]-[Credit]
			    ,Rubrieken[Toepassing] = "Projectwaardering"
			    ,Rubrieken[type] = "B"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.02 HR\Realisatie

		changedProperty = IsHidden

	measure Vrijval/Werkresultaat =
			
			CALCULATE(
			    [Credit]-[Debet],
			    Rubrieken[Toepassing]= "Werkresultaat"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.02 HR\Realisatie

		changedProperty = IsHidden

	measure 'Onderhanden werk' = ```
			
			 CALCULATE(
			    [Credit]-[Debet],
			    Rubrieken[Toepassing] = "Onderhanden Werk"
			)
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.02 HR\Realisatie

		changedProperty = IsHidden

	measure 'Calculatie montage uren cum.' =
			
			CALCULATE (
			    [Calculatie montage uren]
			    ,FILTER (
			        ALL ( 'Kalender'[Datum]),
			        'Kalender'[Datum] <= MAX ('Kalender'[Datum])
			    )
			)
		formatString: #,##0.0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Calculatie gem. prijs per eenheid' = DIVIDE([Calculatie kostprijs],[Calculatie aantal])
		formatString: "€"\ #,0.00;-"€"\ #,0.00;"€"\ #,0.00
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie

		changedProperty = FormatString

	measure 'Calculatie aantal' =
			
			CALCULATE(
			    SUM('Calculatie kostenregels'[Aantal])
			    ,'Calculatie kostenregels'[Calculatiestatus] = "Opdracht"
			)
		formatString: #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie

		changedProperty = IsHidden

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'POC montage uren  o.b.v. budget' = ```
			
			DIVIDE( [Montage uren], [Budget montage uren] )
			
			```
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC

		changedProperty = IsHidden

	measure 'POC uren o.b.v. calculatie' = ```
			    DIVIDE([Gerealiseerde uren projecten],[Calculatie uren])
			```
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC

		changedProperty = IsHidden

	measure 'POC kostprijs o.b.v. calculatie' = ```
			    DIVIDE([Definitieve kostprijs],[Calculatie kostprijs])
			```
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC

		changedProperty = IsHidden

	measure 'Verzoek omzet NOT BLANK ' =
			
			IF(
			    ISBLANK([Verzoek omzet])
			    ,0
			    ,[Verzoek omzet]
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budgetverzoek o.b.v. Budget Verzoek App

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Verzoek kosten NOT BLANK' =
			
			IF(
			    ISBLANK([Verzoek Kosten])
			    ,0
			    ,[Verzoek Kosten])
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budgetverzoek o.b.v. Budget Verzoek App

		changedProperty = FormatString

	measure 'Prognose omzet o.b.v. orderbedrag' = ```
			
			VAR Result = 
			[Budget omzet o.b.v. orderbedrag] + [Verzoek omzet]
			
			return
			   Result 
			
			
			
			
			
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Prognose o.b.v. calculatiekostprijs en order

	measure 'Prognose omzet o.b.v. calculatie verkoopprijs' = ```
			
			VAR Result = 
			    [Budget omzet o.b.v. calculatie verkoopprijs] + [Verzoek omzet]
			
			return
			   result
			
			
			
			
			
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Prognose

	measure 'Prognose kostprijs' = ```
			
			VAR Result = 
			[Budget kostprijs] + [Verzoek Kosten]
			
			
			return
			    result
			
			
			
			
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Prognose o.b.v. calculatiekostprijs en order

	measure 'Budget kostprijs' = ```
			
			VAR Result = 
			[Calculatie kostprijs]
			
			return
			   result
			
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budget o.b.v. calculatiekostprijs en order

	measure 'Definitieve kostprijs arbeid (regie)' = ```
			
			CALCULATE( 
			    SUM('Werkbonparagraaf kosten en geboekte uren'[Kostprijs])
			    ,'Werkbonparagraaf kosten en geboekte uren'[Kostenstatus] = "Definitief"
			    ,'Werkbonparagraaf kosten en geboekte uren'[Factureerstatus] <> "Niet factureren"
			    ,'Kostensoorten'[Categorie] = "Arbeid"
			)
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

		changedProperty = FormatString

	measure Boekjaar =
			IF(
			        HASONEVALUE(Kalender[Jaar])
			        ,MAX(Kalender[Jaar])
			        ,"! --GEEN-- !"
			    )
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.04 Best practice Service

	measure 'Controle kosten verdeeld' = ```
			
			[Definitieve kosten via werkbon]-
			([Definitieve Kosten via onderhoud (in contract)] 
			    + [Definitieve kosten via onderhoud (regie)] 
			    + [Definitieve Kosten via Regiebon] 
			    + [Definitieve Kosten via storing (in contract)] 
			    + [Definitieve Kosten via storing (regie)]
			)
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.04 Best practice Service

	measure 'Definitieve kostprijs niet via werkbon' = ```
			
			CALCULATE( 
			    SUM('Project kosten en geboekte uren'[Kostprijs])
			    ,'Project kosten en geboekte uren'[Kostenstatus] = "Definitief"
			    ,'Project kosten en geboekte uren'[Via werkbon Ja/Nee] = "Nee"
			)
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

		changedProperty = DisplayFolder

	measure 'Definitieve kostprijs niet via werkbon NOT BLANK' = ```
			
			IF(
			    ISBLANK([Definitieve kostprijs niet via werkbon]) 
			    ,0
			    ,[Definitieve kostprijs niet via werkbon])
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

		changedProperty = DisplayFolder

	measure 'Definitieve kostprijs NOT BLANK' = ```
			
			IF(
			    ISBLANK([Definitieve kostprijs]) 
			    ,0
			    ,[Definitieve kostprijs])
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

		changedProperty = DisplayFolder

	measure 'Definitieve Kosten via onderhoud (in contract)' =
			
			CALCULATE(
			    SUM('Werkbonparagraaf kosten en geboekte uren'[Kostprijs])
			    ,'Werkbonparagraaf kosten en geboekte uren'[Kostenstatus] = "Definitief"
			    ,'Werkbonparagraaf kosten en geboekte uren'[Factureerstatus] = "Niet Factureren"
			    ,Werkbonparagrafen[type] = "Onderhoud"
			    )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen

	measure 'Definitieve Kosten via onderhoud (in contract) NOT BLANK' =
			
			IF(
			    ISBLANK([Definitieve Kosten via onderhoud (in contract)])
			    ,0
			    ,[Definitieve Kosten via onderhoud (in contract)]
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen

	measure 'Definitieve kosten via onderhoud (regie)' =
			
			CALCULATE(
			    SUM('Werkbonparagraaf kosten en geboekte uren'[Kostprijs])
			    ,'Werkbonparagraaf kosten en geboekte uren'[Kostenstatus] = "Definitief"
			    ,'Werkbonparagraaf kosten en geboekte uren'[Factureerstatus] <> "Niet Factureren"
			    ,Werkbonparagrafen[type] = "Onderhoud"
			    )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen

	measure 'Definitieve kosten via onderhoud (regie) NOT BLANK' =
			
			IF(
			    ISBLANK([Definitieve kosten via onderhoud (regie)])
			    ,0
			    ,[Definitieve kosten via onderhoud (regie)]
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen

	measure 'Definitieve Kosten via Regiebon' =
			
			CALCULATE(
			        SUM('Werkbonparagraaf kosten en geboekte uren'[Kostprijs])
			        ,'Werkbonparagraaf kosten en geboekte uren'[Kostenstatus] = "Definitief"
			        ,Werkbonparagrafen[type] = "Onbekend (regie/project)"
			    )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen

	measure 'Definitieve Kosten via Regiebon NOT BLANK' =
			
			IF(
			    ISBLANK([Definitieve Kosten via Regiebon])
			    ,0
			    ,[Definitieve Kosten via Regiebon]
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen

	measure 'Definitieve Kosten via storing (in contract)' =
			
			CALCULATE(
			    SUM('Werkbonparagraaf kosten en geboekte uren'[Kostprijs])
			    ,'Werkbonparagraaf kosten en geboekte uren'[Kostenstatus] = "Definitief"
			    ,'Werkbonparagraaf kosten en geboekte uren'[Factureerstatus] = "Niet Factureren"
			    ,Werkbonparagrafen[type] = "Storing"
			    )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen

	measure 'Definitieve Kosten via storing (in contract) NOT BLANK' =
			
			IF(
			    ISBLANK([Definitieve Kosten via storing (in contract)])
			    ,0
			    ,[Definitieve Kosten via storing (in contract)]
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen

	measure 'Definitieve Kosten via storing (regie)' =
			
			CALCULATE(
			    SUM('Werkbonparagraaf kosten en geboekte uren'[Kostprijs])
			    ,'Werkbonparagraaf kosten en geboekte uren'[Kostenstatus] = "Definitief"
			    ,'Werkbonparagraaf kosten en geboekte uren'[Factureerstatus] <> "Niet Factureren"
			    ,Werkbonparagrafen[type] = "Storing"
			    )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen

	measure 'Definitieve Kosten via storing (regie) NOT BLANK' =
			
			IF(
			    ISBLANK([Definitieve Kosten via storing (regie)])
			    ,0
			    ,[Definitieve Kosten via storing (regie)]
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen

	measure 'Definitieve kosten via werkbon' =
			
			CALCULATE(
			        SUM('Werkbonparagraaf kosten en geboekte uren'[Kostprijs])
			        ,'Werkbonparagraaf kosten en geboekte uren'[Kostenstatus] = "Definitief"
			    )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen

	measure 'Project omzet o.b.v. onderdelen' =
			
			[Project omzet (regie)]
			+ [Project omzet (order)]
			+ [Project omzet (voorschot op termijn)]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.04 Best practice Service\Gefactureerd

		changedProperty = DisplayFolder

	measure 'Project omzet (niet via order)' =
			
			CALCULATE(
			        SUM('Project omzet'[Bedrag])
			        ,'Project omzet'[Vanuit order Ja/Nee] = "Nee"
			        ,'Project omzet'[Opbrengststatus] = "Definitief"
			    )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project omzet

		changedProperty = DisplayFolder

	measure 'Project omzet o.b.v. onderdelen NOT BLANK' = ```
			
			IF(
			    ISBLANK([Project omzet o.b.v. onderdelen]) 
			    ,0
			    ,[Project omzet o.b.v. onderdelen])
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.04 Best practice Service\Gefactureerd

		changedProperty = DisplayFolder

	measure 'Project omzet (regie) NOT BLANK' =
			
			IF(
			    ISBLANK([Project omzet (regie)])
			    ,0
			    ,[Project omzet (regie)]
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project omzet

		changedProperty = DisplayFolder

	measure 'Project omzet (order) NOT BLANK' = ```
			
			IF(
			    ISBLANK([Project omzet (order)])   
			    ,0
			    ,[Project omzet (order)])
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project omzet

		changedProperty = DisplayFolder

	measure 'Project omzet creditnotas' =
			
			var creditbedrag =
			   CALCULATE(
			        SUM('Project omzet'[Bedrag])
			        ,'Project omzet'[Type] = "Creditbedrag"
			    )
			return
			IF(
			    ISBLANK(creditbedrag)
			    //,0
			    ,BLANK()
			    ,creditbedrag)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project omzet

		changedProperty = DisplayFolder

	measure 'Project omzet (voorschot op termijn)' =
			
			CALCULATE(
			        SUM('Project omzet'[Bedrag])
			        ,'Project omzet'[Vanuit order Ja/Nee] = "Nee"
			        ,'Project omzet'[Type] = "Voorschot termijn"
			        ,'Project omzet'[Opbrengststatus] = "Definitief"
			    )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project omzet

		changedProperty = DisplayFolder

	measure 'Project omzet (voorschot op termijn) NOT BLANK' = ```
			
			IF(
			    ISBLANK([Project omzet (voorschot op termijn)]) 
			    ,0
			    ,[Project omzet (voorschot op termijn)])
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project omzet

		changedProperty = DisplayFolder

	measure 'Marge % VC resultaat Projecten' =
			var marge = DIVIDE([VC resultaat projecten],[Orderbedrag])
			
			return
			
			IF(
			    isblank(marge)
			    ,blank()
			    ,if(
			        marge>3
			        ,blank()
			        ,if(
			            marge<-3
			            ,blank()
			            ,marge
			        )
			    )
			)
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat

	measure 'Definitieve kostprijs materiaal (regie)' = ```
			
			CALCULATE( 
			    SUM('Werkbonparagraaf kosten en geboekte uren'[Kostprijs])
			    ,'Werkbonparagraaf kosten en geboekte uren'[Kostenstatus] = "Definitief"
			    ,'Kostensoorten'[Categorie] = "Materiaal"
			    ,'Werkbonparagraaf kosten en geboekte uren'[Factureerstatus] <> "Niet factureren"
			)
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

		changedProperty = FormatString

	measure 'Melding alle kosten verdeeld' =
			
			IF(
			        [Controle kosten verdeeld]> -1 &&  [Controle kosten verdeeld] < 1
			        ,"Alle kosten zijn verdeeld"
			        ,""
			    )
		displayFolder: 2. Rapport Specifieke Objecten\2.04 Best practice Service

	measure 'Melding niet alle kosten verdeeld' =
			
			IF(
			        [Controle kosten verdeeld]<-1 || [Controle kosten verdeeld] >1
			        ,"LET OP: Niet alle kosten zijn verdeeld ("& FORMAT([Controle kosten verdeeld],"€###") &"). Zie tabblad [controle kostenverdeling]"
			        ,""
			    )
		displayFolder: 2. Rapport Specifieke Objecten\2.04 Best practice Service

	measure 'Nog te factureren' = ```
			
			SUM('Project service orders prognose'[Factureerbedrag excl. BTW]) 
			+ SUM('Project eenmalige orderregels'[Nog te factureren excl. BTW])
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\nog te verwachten

		changedProperty = DisplayFolder

	measure 'Nog te verwachten kosten via werkbon' =
			
			CALCULATE(
			        SUM('Werkbonparagraaf kosten en geboekte uren'[Kostprijs])
			        ,'Werkbonparagraaf kosten en geboekte uren'[Kostenstatus] = "Nog te verwachten"
			    )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen

	measure 'onverwerkte opbrengsten' =
			
			CALCULATE(
			        SUM('Werkbonparagraaf opbrengsten'[Bedrag])
			        ,'Werkbonparagraaf opbrengsten'[Opbrengststatus] <> "Definitief"
			    )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project omzet

	measure 'onverwerkte opbrengsten contract' =
			
			var opb_via_werkbon_vasteprijs=
			CALCULATE(
			    SUM('Werkbonparagraaf opbrengsten'[Bedrag])
			    ,'Werkbonparagraaf opbrengsten'[Opbrengststatus] <> "Definitief"
			    ,Werkbonparagrafen[factureerwijze] = "Vaste prijs"
			    ,'Werkbonparagraaf opbrengsten'[Vanuit order Ja/Nee] = "Nee"
			    )
			var opb_via_order=
			CALCULATE(
			    SUM('Project omzet'[Bedrag])
			    ,'Project omzet'[Opbrengststatus] <> "Definitief"
			    ,'Project omzet'[Vanuit order Ja/Nee] = "Ja"
			    ,'Project omzet'[Vanuit werkbon Ja/Nee] = "Nee"
			    )
			return
			opb_via_werkbon_vasteprijs+opb_via_order
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.04 Best practice Service

		changedProperty = FormatString

		changedProperty = DisplayFolder

	measure 'onverwerkte opbrengsten niet uitgevoerde werkbonnen' =
			
			CALCULATE(
			        SUM('Werkbonparagraaf opbrengsten'[Bedrag])
			        ,'Werkbonnen'[status] <> "Uitgevoerd"
			        ,'Werkbonparagraaf opbrengsten'[Opbrengststatus] <> "Definitief"
			    )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project omzet

	measure 'onverwerkte opbrengsten NOT BLANK' =
			
			var onverwerkt =
			   CALCULATE(
			        SUM('Project omzet'[Bedrag])
			        ,'Project omzet'[Opbrengststatus] <> "Definitief"
			    )
			return
			IF(
			    ISBLANK(onverwerkt)
			    ,0
			    ,onverwerkt
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project omzet

	measure 'onverwerkte opbrengsten uitgevoerde werkbonnen' =
			
			CALCULATE(
			        SUM('Werkbonparagraaf opbrengsten'[Bedrag])
			        ,'Werkbonnen'[status] = "Uitgevoerd"
			        ,'Werkbonparagraaf opbrengsten'[Opbrengststatus] <> "Definitief"
			    )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project omzet

	measure 'Project omzet (regie)' =
			
			CALCULATE(
			    SUM('Project omzet'[Bedrag])
			    ,'Project omzet'[Vanuit order Ja/Nee] = "Nee"
			    ,'Project omzet'[Opbrengststatus] = "Definitief"
			    ,'Project omzet'[Type] = "Regie" || 'Project omzet'[Type] = "Vrij"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project omzet

		changedProperty = FormatString

	measure 'opbrengsten via werkbon' = ```
			
			SUM('Werkbonparagraaf opbrengsten'[Bedrag])
			
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen

	measure Opdrachtdatum =
			
			IF(
			    ISINSCOPE(Projecten[niveau 2 project])
			    ,MAX(Projecten[niveau 2 opdrachtdatum])
			    ,IF(
			        ISINSCOPE(Projecten[Hoofdproject])
			        ,MAX(Projecten[Hoofdproject opdrachtdatum])
			        ,blank()
			    )
			)
		formatString: dd-mm-yy
		displayFolder: 2. Rapport Specifieke Objecten\2.04 Best practice Service

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Openstaand over vervaldatum' = ```
			
			var openstaand_vervallen =
			CALCULATE(
			    SUM('Betalingen per opbrengstregel'[OpenstaandExclBTW])
			    ,'Betalingen per opbrengstregel'[Vervaldatum]<=TODAY()
			)
			return
			if(
			    openstaand_vervallen <-1 || openstaand_vervallen >1 
			    ,openstaand_vervallen
			    ,blank()
			)
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten

		changedProperty = DisplayFolder

	measure 'POC contract op basis van uren' = DIVIDE([Uren contract gerealiseerd],[Uren contract gerealiseerd]+[Te verwachten uren arbeid (onderhoud)])
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering

		changedProperty = FormatString

		changedProperty = DisplayFolder

	measure Rendement = DIVIDE([Project resultaat],[Project omzet])
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat

		changedProperty = DisplayFolder

	measure 'Rendement NOT BLANK' = ```
			IF(
			    ISBLANK([Rendement]) 
			    ,0
			    ,[Rendement])
			```
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat

		changedProperty = DisplayFolder

	measure 'Rendement op service contract' =
			//Verwacht resultaat t.o.v. de orderwaarde
			DIVIDE([Project resultaat op service contract],[Orderbedrag])
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat

		changedProperty = DisplayFolder

		changedProperty = FormatString

	measure 'Restant te verwachten onverwerkte kosten niet factureren (contract)' = ```
			
			/*
			De onverwerkte kosten op werkbonnen die de status [aanmaak] en [in uitvoering] hebben zijn reeds onderdeel van de [Nog te verwachten kosten]. Deze kosten worden samen met de WvB-kosten samen berekend (de hoogste van beide is leidend). 
			Daarom hierbij alleen de onverwerkte kosten van werkbonnen die [uitgevoerd] en [vervallen] zijn.
			*/
			
			CALCULATE(
			    SUM('Werkbonparagraaf kosten en geboekte uren'[Kostprijs])
			    ,'Werkbonparagraaf kosten en geboekte uren'[Kostenstatus] = "Nog te verwachten"
			    ,'Werkbonparagraaf kosten en geboekte uren'[Factureerstatus] = "Niet Factureren"
			    ,'Werkbonnen'[status] IN { "Uitgevoerd", "Vervallen" }
			    ,'Werkbonparagrafen'[type] = "Onderhoud"
			    )
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\nog te verwachten

		changedProperty = FormatString

		changedProperty = DisplayFolder

	measure 'Resultaat op contract NOT BLANK' = ```
			
			IF(
			    ISBLANK([Resultaat op contract via werkbon]) 
			    ,0
			    ,[Resultaat op contract via werkbon])
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.04 Best practice Service

		changedProperty = DisplayFolder

	measure 'Resultaat op contract via werkbon' =
			
			[Project omzet (order)]
			-[Definitieve Kosten via storing (in contract)]
			-[Definitieve Kosten via onderhoud (in contract)]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.04 Best practice Service

		changedProperty = DisplayFolder

	measure 'Resultaat op regiewerkzaamheden' = ```
			
			[Project omzet (regie)]
			- [Definitieve Kosten via storing (regie)] 
			- [Definitieve kosten via onderhoud (regie)] 
			- [Definitieve Kosten via Regiebon]
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat

		changedProperty = DisplayFolder

	measure 'Resultaat op regiewerkzaamheden NOT BLANK' = ```
			IF(
			    ISBLANK([Resultaat op regiewerkzaamheden]) 
			    ,0
			    ,[Resultaat op regiewerkzaamheden])
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat

		changedProperty = DisplayFolder

	measure 'Project resultaat op service contract' = [Project omzet (order)]-[Definitieve kostprijs (contract)]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat

		changedProperty = DisplayFolder

		changedProperty = FormatString

	measure 'Resultaat tot heden regie' =
			
			[Project omzet (regie)]
			    -[Definitieve kostprijs arbeid (regie)]
			    -[Definitieve kostprijs materiaal (regie)]
			    -[Definitieve kostprijs overig (regie)]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

		changedProperty = FormatString

	measure 'Te verwachten kosten (storingen)' =
			
			var TeVerwachtenKosten =
			CALCULATE(
			    [Totale kosten via storing LY (in contract)]-[Definitieve Kosten via storing (in contract)]
			)
			return
			IF(
			    TeVerwachtenKosten > 0
			    ,TeVerwachtenKosten
			    ,BLANK()
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\nog te verwachten

	measure 'Te verwachten kosten arbeid (onderhoud)' = ```
			
			VAR _kostencategorie = "Arbeid"
			
			VAR _nog_verwachten_WB_niet_klaar 
			= CALCULATE(  
			        SUM('Onderhoudsplanning en te verwachten kosten'[nog te verwachten kostprijs])
			        ,'Kostensoorten'[Categorie] = _kostencategorie
			        )
			        
			VAR _nog_verwachten_WB_klaar
			= CALCULATE(
			    SUM('Werkbonparagraaf kosten en geboekte uren'[Kostprijs])
			    ,'Werkbonparagraaf kosten en geboekte uren'[Kostenstatus] = "Nog te verwachten"
			    ,'Werkbonparagraaf kosten en geboekte uren'[Factureerstatus] = "Niet Factureren"
			    ,'Kostensoorten'[Categorie] = _kostencategorie
			    ,'Werkbonnen'[status] IN { "Uitgevoerd", "Vervallen" }
			    ,'Werkbonparagrafen'[type] = "Onderhoud"
			    ) 
			        
			VAR result = _nog_verwachten_WB_niet_klaar + _nog_verwachten_WB_klaar
			
			RETURN
			    result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\nog te verwachten

	measure 'Te verwachten kosten contract' =
			
			[Te verwachten kosten arbeid (onderhoud)]
			+[Te verwachten kosten materiaal (onderhoud)]
			+[Te verwachten kosten materieel (onderhoud)]
			+[Te verwachten kosten onderaanneming (onderhoud)]
			+[Restant te verwachten onverwerkte kosten niet factureren (contract)]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\nog te verwachten

		changedProperty = DisplayFolder

		changedProperty = FormatString

	measure 'Te verwachten kosten materiaal (onderhoud)' = ```
			
			VAR _kostencategorie = "Materiaal"
			
			VAR _nog_verwachten_WB_niet_klaar 
			= CALCULATE(  
			        SUM('Onderhoudsplanning en te verwachten kosten'[nog te verwachten kostprijs])
			        ,'Kostensoorten'[Categorie] = _kostencategorie
			        )
			        
			VAR _nog_verwachten_WB_klaar
			= CALCULATE(
			    SUM('Werkbonparagraaf kosten en geboekte uren'[Kostprijs])
			    ,'Werkbonparagraaf kosten en geboekte uren'[Kostenstatus] = "Nog te verwachten"
			    ,'Werkbonparagraaf kosten en geboekte uren'[Factureerstatus] = "Niet Factureren"
			    ,'Kostensoorten'[Categorie] = _kostencategorie
			    ,'Werkbonnen'[status] IN { "Uitgevoerd", "Vervallen" }
			    ,'Werkbonparagrafen'[type] = "Onderhoud"
			    ) 
			        
			VAR result = _nog_verwachten_WB_niet_klaar + _nog_verwachten_WB_klaar
			
			RETURN
			    result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\nog te verwachten

	measure 'Te verwachten kosten materieel (onderhoud)' = ```
			
			VAR _kostencategorie = "Materieel"
			
			VAR _nog_verwachten_WB_niet_klaar 
			= CALCULATE(  
			        SUM('Onderhoudsplanning en te verwachten kosten'[nog te verwachten kostprijs])
			        ,'Kostensoorten'[Categorie] = _kostencategorie
			        )
			        
			VAR _nog_verwachten_WB_klaar
			= CALCULATE(
			    SUM('Werkbonparagraaf kosten en geboekte uren'[Kostprijs])
			    ,'Werkbonparagraaf kosten en geboekte uren'[Kostenstatus] = "Nog te verwachten"
			    ,'Werkbonparagraaf kosten en geboekte uren'[Factureerstatus] = "Niet Factureren"
			    ,'Kostensoorten'[Categorie] = _kostencategorie
			    ,'Werkbonnen'[status] IN { "Uitgevoerd", "Vervallen" }
			    ,'Werkbonparagrafen'[type] = "Onderhoud"
			    ) 
			        
			VAR result = _nog_verwachten_WB_niet_klaar + _nog_verwachten_WB_klaar
			
			RETURN
			    result
			```
		formatString: "€"\ #,0.###############;#,0.###############\ -"€";"€"\ #,0.###############
		displayFolder: 1. Semantisch model\1.04 Service\nog te verwachten

		annotation PBI_FormatHint = {"currencyCulture":"nl-NL"}

	measure 'Te verwachten kosten onderaanneming (onderhoud)' = ```
			
			VAR _kostencategorie = "Overig"
			
			VAR _nog_verwachten_WB_niet_klaar 
			= CALCULATE(  
			        SUM('Onderhoudsplanning en te verwachten kosten'[nog te verwachten kostprijs])
			        ,'Kostensoorten'[Categorie] = _kostencategorie
			        )
			        
			VAR _nog_verwachten_WB_klaar
			= CALCULATE(
			    SUM('Werkbonparagraaf kosten en geboekte uren'[Kostprijs])
			    ,'Werkbonparagraaf kosten en geboekte uren'[Kostenstatus] = "Nog te verwachten"
			    ,'Werkbonparagraaf kosten en geboekte uren'[Factureerstatus] = "Niet Factureren"
			    ,'Kostensoorten'[Categorie] = _kostencategorie
			    ,'Werkbonnen'[status] IN { "Uitgevoerd", "Vervallen" }
			    ,'Werkbonparagrafen'[type] = "Onderhoud"
			    ) 
			        
			VAR result = _nog_verwachten_WB_niet_klaar + _nog_verwachten_WB_klaar
			
			RETURN
			    result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\nog te verwachten

	measure 'Te verwachten onverwerkte kosten' = ```
			
			CALCULATE( 
			    SUM('Project kosten en geboekte uren'[Kostprijs])
			    ,'Project kosten en geboekte uren'[Kostenstatus] = "Nog te verwachten"
			)
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

	measure 'Te verwachten Opbrengst contract' = [Nog te factureren]+[onverwerkte opbrengsten contract]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\nog te verwachten

		changedProperty = FormatString

	measure 'Te verwachten uren arbeid (onderhoud)' = ```
			
			VAR _kostencategorie = "Arbeid"
			
			VAR _nog_verwachten_WB_niet_klaar 
			= CALCULATE(  
			        SUM('Onderhoudsplanning en te verwachten kosten'[nog te verwachten aantal])
			        ,'Kostensoorten'[Categorie] = _kostencategorie
			        )
			        
			VAR _nog_verwachten_WB_klaar
			= CALCULATE(
			    SUM('Werkbonparagraaf kosten en geboekte uren'[Aantal])
			    ,'Werkbonparagraaf kosten en geboekte uren'[Kostenstatus] = "Nog te verwachten"
			    ,'Werkbonparagraaf kosten en geboekte uren'[Factureerstatus] = "Niet Factureren"
			    ,'Kostensoorten'[Categorie] = _kostencategorie
			    ,'Werkbonnen'[status] IN { "Uitgevoerd", "Vervallen" }
			    ,'Werkbonparagrafen'[type] = "Onderhoud"
			    ) 
			        
			VAR result = _nog_verwachten_WB_niet_klaar + _nog_verwachten_WB_klaar
			
			RETURN
			    result
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\nog te verwachten

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Totale kosten' = [Definitieve kostprijs]+[Te verwachten onverwerkte kosten]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

		changedProperty = DisplayFolder

	measure 'Totale kosten niet via werkbon' = [Totale kosten] - [Totale kosten via werkbon]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

		changedProperty = DisplayFolder

	measure 'Totale kosten via storing LY (in contract)' =
			
			CALCULATE(
			     [Definitieve Kosten via storing (in contract)]
			     ,SAMEPERIODLASTYEAR(Kalender[Datum])
			 )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen

	measure 'Totale kosten via werkbon' = [Definitieve kosten via werkbon]+[Nog te verwachten kosten via werkbon]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen

	measure 'Uren contract gerealiseerd' = ```
			
			CALCULATE( 
			    SUM('Project kosten en geboekte uren'[Aantal])
			    ,'Project kosten en geboekte uren'[Kostenstatus] = "Definitief"
			    ,'Kostensoorten'[Categorie] = "Arbeid"
			    ,'Project kosten en geboekte uren'[Arbeidregel Ja/Nee] = "Ja"
			)
			```
		formatString: #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

		changedProperty = FormatString

		changedProperty = DisplayFolder

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Uren contract gerealiseerd tekst' = round([Uren contract gerealiseerd],0)&" uur"
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

		changedProperty = DisplayFolder

	measure 'Uren contract te verwachten tekst' = round([Te verwachten uren arbeid (onderhoud)],0)&" uur"
		displayFolder: 1. Semantisch model\1.04 Service\nog te verwachten

		changedProperty = DisplayFolder

	measure 'VC resultaat projecten' = [Orderbedrag]-[Calculatie kostprijs]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat

	measure 'Verwacht rendement service project' =
			
			//Verwacht resultaat t.o.v. de orderwaarde
			DIVIDE([Verwacht resultaat service project],[Orderbedrag])
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat

		changedProperty = DisplayFolder

	measure 'Verwacht rendement service project (contract)' =
			//Verwacht resultaat t.o.v. de orderwaarde
			DIVIDE([Verwacht resultaat service project (contract)],[Orderbedrag])
		formatString: #,0%;-#,0%;#,0%
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat

		changedProperty = FormatString

		changedProperty = DisplayFolder

	measure 'Verwacht resultaat service project' =
			
			[Project resultaat service project]
			-[Te verwachten kosten arbeid (onderhoud)]
			-[Te verwachten kosten materiaal (onderhoud)]
			-[Te verwachten kosten onderaanneming (onderhoud)]
			-[Te verwachten onverwerkte kosten]
			-[Te verwachten kosten materieel (onderhoud)]
			+[Nog te factureren]+[onverwerkte opbrengsten]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat

		changedProperty = DisplayFolder

	measure 'Verwacht resultaat service project (contract)' = ```
			
			[Project resultaat op service contract]
			-[Te verwachten kosten arbeid (onderhoud)]
			-[Te verwachten kosten materiaal (onderhoud)]
			-[Te verwachten kosten onderaanneming (onderhoud)]
			-[Te verwachten kosten materieel (onderhoud)]
			-[Restant te verwachten onverwerkte kosten niet factureren (contract)] 
			+[Nog te factureren]
			+[onverwerkte opbrengsten contract]
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat

		changedProperty = FormatString

		changedProperty = DisplayFolder

	measure 'Definitieve kostprijs overig (regie)' = ```
			
			CALCULATE( 
			    SUM('Werkbonparagraaf kosten en geboekte uren'[Kostprijs])
			    ,'Werkbonparagraaf kosten en geboekte uren'[Kostenstatus] = "Definitief"
			    ,'Kostensoorten'[Categorie] = "Overig"
			    ,'Werkbonparagraaf kosten en geboekte uren'[Factureerstatus] <> "Niet factureren"
			)
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

		changedProperty = FormatString

	measure 'Definitieve kostprijs overig (contract)' = ```
			
			CALCULATE( 
			    SUM('Project kosten en geboekte uren'[Kostprijs])
			    ,'Project kosten en geboekte uren'[Kostenstatus] = "Definitief"
			    ,'Kostensoorten'[Categorie] = "Overig"
			    ,'Project kosten en geboekte uren'[Factureerstatus] = "Niet factureren"
			)
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

		changedProperty = FormatString

		changedProperty = DisplayFolder

	measure 'Definitieve kostprijs materiaal (contract)' = ```
			
			CALCULATE( 
			    SUM('Project kosten en geboekte uren'[Kostprijs])
			    ,'Project kosten en geboekte uren'[Kostenstatus] = "Definitief"
			    ,'Kostensoorten'[Categorie] = "Materiaal"
			    ,'Project kosten en geboekte uren'[Factureerstatus] = "Niet factureren"
			)
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

		changedProperty = FormatString

		changedProperty = DisplayFolder

	measure 'Definitieve kostprijs arbeid (contract)' = ```
			
			CALCULATE( 
			    SUM('Project kosten en geboekte uren'[Kostprijs])
			    ,'Project kosten en geboekte uren'[Kostenstatus] = "Definitief"
			    ,'Kostensoorten'[Categorie] = "Arbeid"
			    ,'Project kosten en geboekte uren'[Factureerstatus] = "Niet factureren"
			)
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

		changedProperty = FormatString

		changedProperty = DisplayFolder

	measure 'Definitieve kostprijs (contract)' = ```
			
			CALCULATE( 
			    SUM('Project kosten en geboekte uren'[Kostprijs])
			    ,'Project kosten en geboekte uren'[Kostenstatus] = "Definitief"
			    ,'Project kosten en geboekte uren'[Factureerstatus] = "Niet factureren"
			)
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

		changedProperty = FormatString

		changedProperty = DisplayFolder

	measure 'Project resultaat NOT BLANK' = ```
			
			IF(
			    ISBLANK([Project resultaat]) 
			    ,0
			    ,[Project resultaat])
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat

	measure 'Project resultaat service project' =
			
			CALCULATE(
			    [Project omzet] - [Definitieve kostprijs]
			    , 'Projecten'[Soort] = "Periodiek"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat

	measure 'Definitieve kostprijs (regie)' = ```
			
			CALCULATE( 
			    SUM('Project kosten en geboekte uren'[Kostprijs])
			    ,'Project kosten en geboekte uren'[Kostenstatus] = "Definitief"
			    ,'Project kosten en geboekte uren'[Factureerstatus] <> "Niet factureren"
			)
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

		changedProperty = FormatString

		changedProperty = DisplayFolder

	measure 'Project omzet (order)' =
			
			//Vanuit order
			CALCULATE(
			    SUM('Project omzet'[Bedrag])
			    ,'Project omzet'[Vanuit order Ja/Nee] = "Ja"
			    ,'Project omzet'[Opbrengststatus] = "Definitief"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project omzet

		changedProperty = FormatString

	measure 'Projectjournalisering kosten' = ```
			
			/*
			LET OP; dit is op basis van de verrekenprijs. De dekkingen worden apart geboekt (Credit) maar zonder projectkey. Daarom niet te matchen met definitieve kostprijs uit de subadministratie.
			Wel met de [Definitieve verrekenprijs]
			*/
			VAR _projectkosten =
			CALCULATE(
			    SUM('Project journaalregels'[Bedrag])
			    ,'Project journaalregels'[Debet/Credit] = "D"
			    ,Rubrieken[Type] = "W"
			    ,'Project journaalregels'[BoxNummer] = "1" 
			)
			
			
			RETURN
			    _projectkosten
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering

	measure 'Projectjournalisering opbrengsten' = ```
			
			VAR _projectopbrengsten =
			CALCULATE(
			    SUM('Project journaalregels'[Bedrag])
			    ,'Project journaalregels'[Debet/Credit] = "C"
			    ,Rubrieken[Type] = "W"
			    ,'Project journaalregels'[BoxNummer] = "1" 
			)
			
			
			RETURN
			    _projectopbrengsten
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering

	measure 'Projectjournalisering project resultaat' =
			
			/*
			LET OP; De [Projectjournalisering kosten!] is op basis van de verrekenprijs. De dekkingen worden apart geboekt (Credit) maar zonder projectkey. Daarom niet te matchen met definitieve kostprijs uit de subadministratie.
			Wel met de [Definitieve verrekenprijs]
			*/
			
			[Projectjournalisering opbrengsten]-[Projectjournalisering kosten]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering

	measure 'Projectjournalisering projectwaarderingen regulierer boeking' = ```
			
			VAR _credit =
			CALCULATE(
			    SUM('Project journaalregels'[Bedrag])
			    ,'Project journaalregels'[Debet/Credit] = "C"
			    ,Rubrieken[Type] = "W"
			    ,'Rubrieken'[Toepassing] = "Projectwaardering"
			    ,'Project journaalregels'[tegenboeking projectwaardering bij vrijval] = "Nee"
			    ,'Project journaalregels'[BoxNummer] = "2" 
			)
			
			VAR _debet =
			CALCULATE(
			    SUM( 'Project journaalregels'[Bedrag] )
			    , 'Project journaalregels'[Debet/Credit] = "D"
			    , Rubrieken[Type] = "W"
			    , 'Rubrieken'[Toepassing] = "Projectwaardering"
			    ,'Project journaalregels'[tegenboeking projectwaardering bij vrijval] = "Nee"
			    ,'Project journaalregels'[BoxNummer] = "2"
			)
			
			
			VAR Result = _credit-_debet
			
			RETURN
			Result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering

	measure 'Projectjournalisering projectwaarderingen tegenboeking bij vrijval' = ```
			
			VAR _credit =
			CALCULATE(
			    SUM('Project journaalregels'[Bedrag])
			    ,'Project journaalregels'[Debet/Credit] = "C"
			    ,Rubrieken[Type] = "W"
			    ,'Rubrieken'[Toepassing] = "Projectwaardering"
			    ,'Project journaalregels'[tegenboeking projectwaardering bij vrijval] = "Ja"
			    ,'Project journaalregels'[BoxNummer] = "2" 
			)
			
			VAR _debet =
			CALCULATE(
			    SUM( 'Project journaalregels'[Bedrag] )
			    , 'Project journaalregels'[Debet/Credit] = "D"
			    , Rubrieken[Type] = "W"
			    , 'Rubrieken'[Toepassing] = "Projectwaardering"
			    ,'Project journaalregels'[tegenboeking projectwaardering bij vrijval] = "Ja"
			    , 'Project journaalregels'[BoxNummer] = "2"
			)
			
			
			VAR Result = _credit-_debet
			
			RETURN
			Result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering

	/// Projectopbrengsten - projectkosten. Geeft inzicht in het effect van elk project op het resultaat in de exploitatierekening in de geselecteerde periode. Exclusief dekkingen.
	measure 'OHW mutatie in exploitatie' = ```
			
			VAR _credit = 
			CALCULATE(
			    SUM('Project journaalregels'[bedrag] )
			    ,'Project journaalregels'[Debet/Credit] = "C"
			    ,Rubrieken[Type] = "W"
			    ,'Rubrieken'[Toepassing]="Doorbelasting OHW"
			    ,'Journaalregels'[BoxNummer] = "2"
			    ,Journaalregels[TypePeriode]<>"Openingsperiode"
			)
			
			VAR _debet = 
			CALCULATE(
			    SUM('Project journaalregels'[bedrag] )
			    ,'Project journaalregels'[Debet/Credit] = "D"
			    ,Rubrieken[Type] = "W"
			    ,'Rubrieken'[Toepassing]="Doorbelasting OHW"
			    ,'Journaalregels'[BoxNummer] = "2"
			    ,Journaalregels[TypePeriode]<>"Openingsperiode"
			
			)
			
			VAR result = _credit-_debet
			
			
			RETURN
			result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering

	measure 'Aantal definitieve inkoopfacturen' = ```
			
			    CALCULATE(
			        DISTINCTCOUNT('Werkbonparagraaf kosten en geboekte uren'[Document code])
			        ,'Werkbonparagraaf kosten en geboekte uren'[Kostenbron] = "Inkoop"
			        ,'Werkbonparagraaf kosten en geboekte uren'[Kostenstatus] = "Definitief"
			    )
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen

	measure 'Aantal inkoopfacturen' =
			
			CALCULATE(
			    DISTINCTCOUNT('Werkbonparagraaf kosten en geboekte uren'[Document code])
			    ,'Werkbonparagraaf kosten en geboekte uren'[Kostenbron] = "Inkoop"
			)
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen

	measure 'Aantal openstaande inkoopfacturen' = ```
			
			    CALCULATE(
			        DISTINCTCOUNT('Werkbonparagraaf kosten en geboekte uren'[Document code])
			        ,'Werkbonparagraaf kosten en geboekte uren'[Kostenbron] = "Inkoop"
			        ,'Werkbonparagraaf kosten en geboekte uren'[Kostenstatus] <> "Definitief"
			    )
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen

	measure 'Aantal pakbonnen' = ```
			
			 CALCULATE(
			    DISTINCTCOUNT('Werkbonparagraaf kosten en geboekte uren'[Document code])
			    ,'Werkbonparagraaf kosten en geboekte uren'[Kostenbron] = "Pakbon"
			)
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen

	measure 'Aantal uren' = ```
			
			CALCULATE(
			    SUM('Werkbonparagraaf kosten en geboekte uren'[Aantal])
			    ,'Werkbonparagraaf kosten en geboekte uren'[Arbeidregel Ja/Nee] = "Ja"
			)
			         
			       
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Kosten niet factureren (contract)' =
			
			CALCULATE(
			    SUM('Werkbonparagraaf kosten en geboekte uren'[Kostprijs])
			    ,'Werkbonparagraaf kosten en geboekte uren'[Factureerstatus]= "Niet Factureren"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen

		changedProperty = FormatString

	measure Crediteur =
			
			//if(
			//    HASONEVALUE('Crediteuren per kostendocument'[Crediteuren])
			//    ,MAX('Crediteuren per kostendocument'[Crediteuren])
			//    ,"Betreft urenstaat - heeft geen crediteur"
			//)
			
			0
		isHidden
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen

	measure 'Kosten inkoopfactuur' = ```
			
			    CALCULATE(
			        SUM('Werkbonparagraaf kosten en geboekte uren'[Kostprijs])
			        ,'Werkbonparagraaf kosten en geboekte uren'[Kostenbron] = "Inkoop"
			    )
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen

	measure 'Kosten Overig' =
			
			CALCULATE(
			    SUM('Werkbonparagraaf kosten en geboekte uren'[Kostprijs])
			    ,NOT( 'Werkbonparagraaf kosten en geboekte uren'[Kostenbron] ) IN { "Inkoop", "Urenstaat", "Pakbon" }
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen

	measure 'Kosten pakbon' =
			
			CALCULATE(
			    SUM('Werkbonparagraaf kosten en geboekte uren'[Kostprijs])
			    ,'Werkbonparagraaf kosten en geboekte uren'[Kostenbron] = "Pakbon"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen

	measure 'Kosten totaal' = ```
			
			    [Kosten inkoopfactuur]+[Kosten pakbon]+[kosten uren]+[Kosten Overig]
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen

	measure 'kosten uren' =
			
			CALCULATE(
			    SUM('Werkbonparagraaf kosten en geboekte uren'[Kostprijs])
			    ,'Werkbonparagraaf kosten en geboekte uren'[Kostenbron] = "Urenstaat"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen

	measure 'Periode openstaand (gemiddeld)' = AVERAGEX(Werkbonnen,today()-Werkbonnen[Aanmaakdatum])
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonnen

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Regie kosten' =
			
			CALCULATE(
			    SUM('Werkbonparagraaf kosten en geboekte uren'[Kostprijs])
			    ,'Werkbonparagraaf kosten en geboekte uren'[Factureerstatus] <> "Niet Factureren"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen

		changedProperty = FormatString

	measure 'Melding verschil op dekking' = ```
			IF(
			    [Dekkingen]-[Dekkingen op projecten (berekend)]>1 || [Dekkingen]-[Dekkingen op projecten (berekend)]<-1
			    ,"LET OP; De dekking op projectniveau is niet compleet. Verschil: "&FORMAT( ROUND( [Verschil dekking berekeningen]+1000, 0 ), "€#,##0;(€#.##0)")    
			    ,""  
			)
			```
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Meldingen

	/// Het percentage van de totale projectkosten dat via doorbelasting op de balans wordt geactiveerd als OHW.
	measure 'Ratio doorbelasting van projectkosten' = DIVIDE([Doorbelasting projectkosten],[Projectjournalisering kosten])
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering

	/// Het percentage van de totale projectkosten dat via doorbelasting op de balans wordt geactiveerd als OHW.
	measure 'Ratio doorbelasting van projectopbrengsten' = DIVIDE([Doorbelasting projectopbrengsten],[Projectjournalisering opbrengsten])
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering

	measure Boekingsbedrag =
			
			IF([BrowseDepth]>[MaxNodeDepth],
			BLANK(),
			CALCULATE (
			    SUM (Journaalregels[Creditbedrag])+SUM (Journaalregels[Debetbedrag]),
			    CROSSFILTER ( Rubrieken[RubriekKey], Grootboekrekeningen[RubriekKey], BOTH )
			))
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Overig

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Omzet van totaal' =
			
			IF(
			    [Geselecteerde methode resultaat bepaling]=2
			    ,[% Omzet van totaal (benchmark schema)]
			    ,[% Omzet van totaal (standaard)]
			)
		formatString: #,##0 %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd

	measure 'Bruto rendement' =
			
			IF(
			    [Geselecteerde methode resultaat bepaling]=2
			    ,[Bruto rendement (benchmark schema)]
			    ,[Bruto rendement (standaard)]
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd

	measure 'Bruto rendement LY' =
			
			IF(
			    [Geselecteerde methode resultaat bepaling]=2
			    ,[Bruto rendement LY (benchmark schema)]
			    ,[Bruto rendement LY (standaard)]
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd

	measure 'Bruto rendement YTD LY' =
			
			IF(
			    [Geselecteerde methode resultaat bepaling]=2
			    ,[Bruto rendement YTD LY (benchmark schema)]
			    ,[Bruto rendement YTD LY (standaard)]
			)
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd

	measure Brutowinst =
			
			IF(
			    [Geselecteerde methode resultaat bepaling]=2
			    ,[Brutowinst (benchmark schema)]
			    ,[Brutowinst (standaard)]
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd

	measure 'Brutowinst LY' =
			
			IF(
			    [Geselecteerde methode resultaat bepaling]=2
			    ,[Brutowinst LY (benchmark schema)]
			    ,[Brutowinst LY (standaard)]
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd

	measure 'Brutowinst YTD' =
			
			IF(
			    [Geselecteerde methode resultaat bepaling]=2
			    ,[Brutowinst YTD (benchmark schema)]
			    ,[Brutowinst YTD (standaard)]
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd

	measure 'Brutowinst YTDLY' =
			
			IF(
			    [Geselecteerde methode resultaat bepaling]=2
			    ,[Brutowinst YTDLY (benchmark schema)]
			    ,[Brutowinst YTDLY (standaard)]
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd

	/// Zie [Directe kosten]. Betreft directe kosten over dezelfde periode vorig jaar.
	measure 'Directe kosten LY' =
			
			IF(
			    [Geselecteerde methode resultaat bepaling]=2
			    ,[Directe kosten LY (benchmark schema)]
			    ,[Directe kosten LY (standaard)]
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd

	measure 'Directe kosten neg' =
			
			IF(
			    [Geselecteerde methode resultaat bepaling]=2
			    ,[Directe kosten neg (benchmark schema)]
			    ,[Directe kosten neg (standaard)]
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		isHidden
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd

	/// Directe kosten cumulatief tot einde geselecteerde einddatum.
	measure 'Directe kosten YTD' =
			
			IF(
			    [Geselecteerde methode resultaat bepaling]=2
			    ,[Directe kosten YTD (benchmark schema)]
			    ,[Directe kosten YTD (standaard)]
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd

	/// Zie [Directe kosten YTD]. Betreft directe kosten cumulaief over dezelfde periode vorig jaar.
	measure 'Directe kosten YTDLY' =
			
			IF(
			    [Geselecteerde methode resultaat bepaling]=2
			    ,[Directe kosten YTDLY (benchmark schema)]
			    ,[Directe kosten YTDLY (standaard)]
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd

	measure 'Indirecte kosten' =
			
			IF(
			    [Geselecteerde methode resultaat bepaling]=2
			    ,[Indirecte kosten (benchmark schema)]
			    ,[Indirecte kosten (standaard)]
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd

	measure 'Indirecte kosten LY' =
			
			IF(
			    [Geselecteerde methode resultaat bepaling]=2
			    ,[Indirecte kosten LY (benchmark schema)]
			    ,[Indirecte kosten LY (standaard)]
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd

	measure 'Indirecte kosten neg' =
			
			IF(
			    [Geselecteerde methode resultaat bepaling]=2
			    ,[Indirecte kosten neg (benchmark schema)]
			    ,[Indirecte kosten neg (standaard)]
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd

	measure 'Indirecte kosten YTD' =
			
			IF(
			    [Geselecteerde methode resultaat bepaling]=2
			    ,[Indirecte kosten YTD (benchmark schema)]
			    ,[Indirecte kosten YTD (standaard)]
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd

	measure 'Indirecte kosten YTDLY' =
			
			IF(
			    [Geselecteerde methode resultaat bepaling]=2
			    ,[Directe kosten YTDLY (benchmark schema)]
			    ,[Directe kosten YTDLY (standaard)]
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd

	measure 'Netto rendement' =
			
			IF(
			    [Geselecteerde methode resultaat bepaling]=2
			    ,[Netto rendement (benchmark schema)]
			    ,[Netto rendement (standaard)]
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd

	measure 'Netto rendement 12 maanden' =
			
			IF(
			    [Geselecteerde methode resultaat bepaling]=2
			    ,[Netto rendement 12 maanden (benchmark schema)]
			    ,[Netto rendement 12 maanden (standaard)]
			)
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd

	measure 'Netto rendement LY' =
			
			IF(
			    [Geselecteerde methode resultaat bepaling]=2
			    ,[Netto rendement LY (benchmark schema)]
			    ,[Netto rendement LY (standaard)]
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd

	measure 'Netto rendement YTD' =
			
			IF(
			    [Geselecteerde methode resultaat bepaling]=2
			    ,[Netto rendement YTD (benchmark schema)]
			    ,[Netto rendement YTD (standaard)]
			)
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd

	measure 'Netto rendement YTD LY' =
			
			IF(
			    [Geselecteerde methode resultaat bepaling]=2
			    ,[Netto rendement YTD LY (benchmark schema)]
			    ,[Netto rendement YTD LY (standaard)]
			)
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd

	measure Nettowinst =
			
			IF(
			    [Geselecteerde methode resultaat bepaling]=2
			    ,[Nettowinst (benchmark schema)]
			    ,[Nettowinst (standaard)]
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd

	measure 'nettowinst 12 maanden' =
			
			IF(
			    [Geselecteerde methode resultaat bepaling]=2
			    ,[nettowinst 12 maanden (benchmark schema)]
			    ,[nettowinst 12 maanden (standaard)]
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd

	measure 'Nettowinst LY' =
			
			IF(
			    [Geselecteerde methode resultaat bepaling]=2
			    ,[Nettowinst LY (benchmark schema)]
			    ,[Nettowinst LY (standaard)]
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd

	measure 'Nettowinst YTD' =
			
			IF(
			    [Geselecteerde methode resultaat bepaling]=2
			    ,[Nettowinst YTD (benchmark schema)]
			    ,[Nettowinst YTD (standaard)]
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd

	measure 'Nettowinst YTDLY' =
			
			IF(
			    [Geselecteerde methode resultaat bepaling]=2
			    ,[Nettowinst YTDLY (benchmark schema)]
			    ,[Nettowinst YTDLY (standaard)]
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd

	measure 'Omzet 12 maanden' =
			
			IF(
			    [Geselecteerde methode resultaat bepaling]=2
			    ,[Omzet 12 maanden (benchmark schema)]
			    ,[Omzet 12 maanden (standaard)]
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd

	measure 'Omzet LY' =
			
			IF(
			    [Geselecteerde methode resultaat bepaling]=2
			    ,[Omzet LY (benchmark schema)]
			    ,[Omzet LY (standaard)]
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd

	measure 'Omzet YTD' =
			
			IF(
			    [Geselecteerde methode resultaat bepaling]=2
			    ,[Omzet YTD (benchmark schema)]
			    ,[Omzet YTD (standaard)]
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd

	measure 'Omzet YTDLY' =
			
			IF(
			    [Geselecteerde methode resultaat bepaling]=2
			    ,[Omzet YTDLY (benchmark schema)]
			    ,[Omzet YTDLY (standaard)]
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd

		changedProperty = FormatString

	measure '% Directe kosten van totaal' =
			
			IF(
			    [Geselecteerde methode resultaat bepaling]=2
			    ,[% Directe kosten van totaal (benchmark schema)]
			    ,[% Directe kosten van totaal (standaard)]
			)
		formatString: #,##0 %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd

	measure '% Indirecte kosten van totaal' =
			
			IF(
			    [Geselecteerde methode resultaat bepaling]=2
			    ,[% Indirecte kosten van totaal (benchmark schema)]
			    ,[% Indirecte kosten van totaal (standaard)]
			)
		formatString: #,##0 %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd

	measure '% Omzet van totaal (benchmark schema)' =
			
			VAR _Totaal_omzet = CALCULATE([Omzet (benchmark schema)], ALL('Rubrieken'))
			
			return
			DIVIDE([Omzet (benchmark schema)],_Totaal_omzet)
		formatString: #,##0 %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)

	measure 'Bruto rendement (benchmark schema)' = Divide([Brutowinst (benchmark schema)],[Omzet (benchmark schema)])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)

	measure 'Bruto rendement LY (benchmark schema)' = Divide([Brutowinst LY (benchmark schema)],[Omzet LY (benchmark schema)])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)

	measure 'Bruto rendement YTD LY (benchmark schema)' = divide([Brutowinst YTDLY (benchmark schema)],[Omzet YTDLY (benchmark schema)])
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)

	measure 'Brutowinst (benchmark schema)' = [Omzet (benchmark schema)]-[Directe kosten (benchmark schema)]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)

	measure 'Brutowinst LY (benchmark schema)' = ```
			
			CALCULATE(
			    [Brutowinst (benchmark schema)]   
			    ,sameperiodlastyear('Kalender'[Datum])
			    )
			    
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)

	measure 'Brutowinst YTD (benchmark schema)' = [Omzet YTD (benchmark schema)] - [Directe kosten YTD (benchmark schema)]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)

	measure 'Brutowinst YTDLY (benchmark schema)' = [Omzet YTDLY (benchmark schema)] - [Directe kosten YTDLY (benchmark schema)]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)

	measure '% Directe kosten van totaal (benchmark schema)' =
			
			VAR _Totaal_directe_kosten = CALCULATE([Directe kosten (benchmark schema)], ALL('Rubrieken'))
			
			return
			DIVIDE([Directe kosten (benchmark schema)],_Totaal_directe_kosten)
		formatString: #,##0 %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)

	measure '% Indirecte kosten van totaal (benchmark schema)' = ```
			VAR _startdatum_volledige_selectie = MIN( Kalender[Datum] ) 
			VAR _einddatum_volledige_selectie = MAX( Kalender[Datum] ) 
			VAR _Totaal_indirecte_kosten = 
			    CALCULATE(
			        [Indirecte kosten (benchmark schema)]
			        , ALL( 'Rubrieken' )
			    )
			    
			
			return
			DIVIDE([Indirecte kosten (benchmark schema)],_Totaal_indirecte_kosten)
			```
		formatString: #,##0.00 %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)

	measure '% Omzet van totaal (standaard)' =
			
			VAR _Totaal_omzet= CALCULATE([Omzet (standaard)], ALL('Rubrieken'))
			
			return
			DIVIDE([Omzet (standaard)],_Totaal_omzet)
		formatString: #,##0 %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)

	measure 'Bruto rendement (standaard)' = Divide([Brutowinst (standaard)], [Omzet (standaard)])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)

	measure 'Bruto rendement LY (standaard)' = Divide([Brutowinst LY (standaard)], [Omzet LY (standaard)])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)

	measure 'Bruto rendement YTD LY (standaard)' = divide([Brutowinst YTDLY (standaard)],[Omzet YTDLY (standaard)])
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)

	measure 'Brutowinst (standaard)' = [Omzet (standaard)]-[Directe kosten (standaard)]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)

	measure 'Brutowinst LY (standaard)' =
			
			CALCULATE(
			    [Brutowinst (standaard)]
			    ,sameperiodlastyear('Kalender'[Datum])
			    )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)

	measure 'Brutowinst YTD (standaard)' = [Omzet YTD (standaard)] - [Directe kosten YTD (standaard)]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)

	measure 'Brutowinst YTDLY (standaard)' = [Omzet YTDLY (standaard)] - [Directe kosten YTDLY (standaard)]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)

	measure 'Omzet (standaard)' =
			
			CALCULATE([Credit] - [Debet]
			    ,Rubrieken[Type]="W"
			    ,Rubrieken[Toepassing]="Omzetrekening"
			    //,Journaalregels[BoxNummer]="1"
			    )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)

	measure 'Omzet 12 maanden (standaard)' =
			
			CALCULATE(
			    [Omzet (standaard)]
			    ,FILTER(
			        ALL('Kalender')
			        ,'Kalender'[Datum]<=MAX('Kalender'[Datum])
			        &&'Kalender'[Datum]>date(year(MAX('Kalender'[Datum]))-1,MONTH(max('Kalender'[Datum])),DAY(max('Kalender'[Datum])))
			        )
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)

	measure 'Omzet LY (standaard)' =
			
			CALCULATE(
			    [Omzet (standaard)]
			    ,sameperiodlastyear('Kalender'[Datum])
			    )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)

	measure 'Omzet YTD (standaard)' =
			
			totalytd(
			    [Omzet (standaard)]
			    ,'Kalender'[Datum]
			    )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)

	measure 'Omzet YTDLY (standaard)' =
			
			totalytd(
			    [Omzet YTD (standaard)]
			    ,SAMEPERIODLASTYEAR('Kalender'[Datum])
			    )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)

	measure '% Directe kosten van totaal (standaard)' =
			
			VAR _Totaal_directe_kosten = CALCULATE([Directe kosten (standaard)], ALL('Rubrieken'))
			
			return
			DIVIDE([Directe kosten (standaard)],_Totaal_directe_kosten)
		formatString: #,##0 %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)

	measure '% Indirecte kosten van totaal (standaard)' =
			
			VAR _Totaal_indirecte_kosten = CALCULATE([Indirecte kosten (standaard)], ALL('Rubrieken'),ALL(Kalender[Maand]))
			
			return
			DIVIDE([Indirecte kosten (standaard)],_Totaal_indirecte_kosten)
		formatString: #,##0 %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)

	measure 'Geselecteerde methode resultaat bepaling' = VALUE(MAX('Methode resultaat bepaling'[ID]))
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen

	measure 'jaar resultaat LY' = ```
			
			 CALCULATE(
			    [resultaat W&V]
			    ,SAMEPERIODLASTYEAR(
			        FILTER(
			        ALL('Kalender'[Datum])
			            ,'Kalender'[Datum] <=today()
			            && YEAR('Kalender'[Datum]) = YEAR(TODAY())
			        )
			    )    
			 )
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Overig

	measure 'resultaat W&V' = ```
			[Actual mutatie exploitatierekening]
			
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Overig

	measure BrowseDepth =
			
			ISFILTERED (Projecten[Hoofdproject] )
			    + ISFILTERED ( Projecten[Niveau 2 Project]  )
			    + ISFILTERED ( Projecten[Niveau 3 Project]  )
		formatString: 0
		isHidden
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten

		changedProperty = IsHidden

	measure 'Niveau 3 tonen' = ```
			
			    IF(
			        ISFILTERED(Projecten[Niveau 3 Project]),
			        MAX(Projecten[Niveau 3 Project]),
			        "Selectie is op een hoger niveau gemaakt"
			        )
			```
		isHidden
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten

		changedProperty = IsHidden

	measure 'Niveau 2 tonen' = ```
			
			    IF(
			        ISFILTERED(Projecten[Niveau 2 Project]),
			        MAX(Projecten[Niveau 2 Project]),
			        "Selectie is op een hoger niveau gemaakt"
			        )
			```
		isHidden
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten

		changedProperty = IsHidden

	measure MaxNodeDepth = MAX ( Projecten[Niveau] )
		formatString: 0
		isHidden
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten

		changedProperty = IsHidden

	measure '% onderhouds paragrafen met WvB Arbeid' =
			
			VAR _aantal_paragrafen =
			COUNT('Onderhoudsplanning en te verwachten kosten'[BestekparagraafKey])
			
			VAR _aantal_paragrafen_met_WvB =
			CALCULATE(
			    COUNT('Onderhoudsplanning en te verwachten kosten'[BestekparagraafKey])
			    ,'Onderhoudsplanning en te verwachten kosten'[nog te verwachten aantal]
			    ,NOT( ISBLANK( 'Onderhoudsplanning en te verwachten kosten'[TaakKey] ) )
			)
			
			VAR result = DIVIDE(_aantal_paragrafen_met_WvB,_aantal_paragrafen)
			
			RETURN
			    result
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.04 Best practice Service\Onderhoudsplanning

	measure 'Aantal onderhoud werkbonparagrafen' = ```
			
			    CALCULATE(
			        COUNT('Werkbonparagrafen'[WerkbonparagraafKey])
			        ,Werkbonparagrafen[Type] = "Onderhoud"
			        ,Werkbonparagrafen[Uitvoeringstatus] = "Uitgevoerd"
			    )
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen

	measure 'Aantal uur nog te doen' = ```
			
			VAR _NTD_obv_WvB = 
			 CALCULATE(
			        SUM('Onderhoudsplanning en te verwachten kosten'[nog te verwachten aantal])
			        ,NOT( ISBLANK( 'Onderhoudsplanning en te verwachten kosten'[TaakKey] ) )
			    )
			
			VAR _NTD_obv_gemiddelde_uitvoertijd =
			    COUNT( 'Onderhoudsplanning en te verwachten kosten'[BestekparagraafKey])*[Geselecteerd gemiddelde uitvoertijd onderhoud]
			
			VAR result = 
			        IF(
			           [Geselecteerde methode uitvoertijd onderhoud] = "1"
			           ,_NTD_obv_WvB
			           ,_NTD_obv_gemiddelde_uitvoertijd
			        )
			
			RETURN 
			    result
			    
			```
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.04 Best practice Service\Onderhoudsplanning\Werkvoorraad

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'geselecteerde methode' =
			
			max('Methode afwijking berekening'[ID])
		displayFolder: 2. Rapport Specifieke Objecten\2.04 Best practice Service\Onderhoudsplanning

	measure 'Onbekend (regie/project) % van totaal' =
			
			var onbekend_uren =
			    CALCULATE(
			        [Aantal uren werkbonparagraaf o.b.v. boekdatum urenregel]
			        ,Werkbonparagrafen[Type] = "Onbekend (regie/project)"
			    )
			return
			    DIVIDE(onbekend_uren,[Aantal uren werkbonparagraaf o.b.v. boekdatum urenregel])
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.04 Best practice Service\Onderhoudsplanning

	measure 'onderhoud % van totaal' = ```
			
			var _onderhoudsuren =
			    CALCULATE(
			        [Aantal uren werkbonparagraaf o.b.v. boekdatum urenregel]
			        ,Werkbonparagrafen[Type] = "Onderhoud"
			    )
			return 
			    DIVIDE(_onderhoudsuren,[Aantal uren werkbonparagraaf o.b.v. boekdatum urenregel])
			```
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.04 Best practice Service\Onderhoudsplanning

	measure 'Onderhoud uitgevoerd (reisuren)' = ```
			
			    CALCULATE(
			        SUM('Werkbonparagraaf kosten en geboekte uren'[Aantal])
			        ,Werkbonparagrafen[Type] = "Onderhoud"
			        ,Werkbonparagrafen[Uitvoeringstatus] = "Uitgevoerd"
			        ,'Werkbonparagraaf kosten en geboekte uren'[Arbeidregel Ja/Nee] = "Ja"
			        ,'NR - Taakgroepen DQ'[Taakgroep]="Reizen"
			    )
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen

		changedProperty = FormatString

		changedProperty = DisplayFolder

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Onderhoud uitgevoerd (werkelijke uren)' = ```
			
			    CALCULATE(
			        SUM('Werkbonparagraaf kosten en geboekte uren'[Aantal])
			        ,Werkbonparagrafen[Type] = "Onderhoud"
			        ,Werkbonparagrafen[Uitvoeringstatus] = "Uitgevoerd"
			        ,'Werkbonparagraaf kosten en geboekte uren'[Arbeidregel Ja/Nee] = "Ja"
			    )
			
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen

	measure 'Onderhoud uitgevoerd (werkuren)' =
			
			CALCULATE(
			    SUM('Werkbonparagraaf kosten en geboekte uren'[Aantal])
			    ,Werkbonparagrafen[Type] = "Onderhoud"
			    ,Werkbonparagrafen[Uitvoeringstatus] = "Uitgevoerd"
			    ,'Werkbonparagraaf kosten en geboekte uren'[Arbeidregel Ja/Nee] = "Ja"
			    ,'NR - Taakgroepen DQ'[Taakgroep] = "Montage"
			)
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen

		changedProperty = FormatString

		changedProperty = DisplayFolder

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Betreft de uren op de werkvoorbereiding van de werkbonparagrafen van het type Onderhoud en status Uitgevoerd.  
	measure 'Onderhoud uitgevoerd (WvB uren)' =
			
			//De status van de werkbon is reeds gefilterd in de tabel 'Werkbon werkvoorbereiding (arbeid)' op "uitgevoerd".
			    CALCULATE(
			        SUM('Werkbonparagraaf WvB arbeid'[Aantal])
			        ,Werkbonparagrafen[Type] = "Onderhoud"
			        ,Werkbonparagrafen[Uitvoeringstatus] = "Uitgevoerd"
			    )
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Onderhoud uitgevoerd gemiddeld (reisuren)' = DIVIDE([Onderhoud uitgevoerd (reisuren)],[Aantal onderhoud werkbonparagrafen])
		formatString: 0.00
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen

		changedProperty = FormatString

		changedProperty = DisplayFolder

	measure 'Onderhoud uitgevoerd gemiddeld (werkelijke uren)' = DIVIDE([Onderhoud uitgevoerd (werkelijke uren)],[Aantal onderhoud werkbonparagrafen])
		formatString: 0.00
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen

	measure 'Onderhoud uitgevoerd gemiddeld (werkuren)' = DIVIDE([Onderhoud uitgevoerd (werkuren)],[Aantal onderhoud werkbonparagrafen])
		formatString: 0.00
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen

		changedProperty = FormatString

		changedProperty = DisplayFolder

	measure 'storing % van totaal' =
			
			var _storingsuren =
			    CALCULATE(
			        [Aantal uren werkbonparagraaf o.b.v. boekdatum urenregel]
			        ,Werkbonparagrafen[Type] = "Storing"
			    )
			return
			    DIVIDE(_storingsuren,[Aantal uren werkbonparagraaf o.b.v. boekdatum urenregel])
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.04 Best practice Service\Onderhoudsplanning

	measure 'Totaal onderhoud' = ```
			
			    [Aantal uur nog te doen]+[Onderhoud uitgevoerd (WvB uren)]
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Werkelijk onderhoud % van WvB' =
			
			var afwijking_methode_werkuren =
			divide([Onderhoud uitgevoerd (werkuren)]-[Onderhoud uitgevoerd (WvB uren)],[Onderhoud uitgevoerd (WvB uren)])
			
			var afwijking_methode_werk_en_reisuren =
			divide(([Onderhoud uitgevoerd (werkuren)]+[Onderhoud uitgevoerd (reisuren)])-[Onderhoud uitgevoerd (WvB uren)],[Onderhoud uitgevoerd (WvB uren)])
			
			var geselecteerde_methode = MAX('Methode afwijking berekening'[ID])
			//methode 1 = alleen werkuren, methode 2= werk- en reisuren.
			return
			IF(
			    geselecteerde_methode = "1"
			    ,afwijking_methode_werkuren
			    ,afwijking_methode_werk_en_reisuren
			)
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.04 Best practice Service\Onderhoudsplanning

	measure 'Beschikbare uren' =
			
			[Contracturen] - [Geplande uren indirect]
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Planning

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Contracturen =
			CALCULATE(
							SUM('Geplande en contracturen medewerkers'[Aantal Uur])
							,'Geplande en contracturen medewerkers'[Type] = "Contracturen"
			)
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Planning

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Geplande uren' =
			CALCULATE(
							SUM('Geplande en contracturen medewerkers'[Aantal Uur])
							,'Geplande en contracturen medewerkers'[Type] = "Indirecte taak" || 'Geplande en contracturen medewerkers'[Type] = "Werkbon" || 'Geplande en contracturen medewerkers'[Type] = "Project"
			)
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Planning

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Geplande uren direct' =
			
			CALCULATE(
				SUM('Geplande en contracturen medewerkers'[Aantal Uur])
				,'Geplande en contracturen medewerkers'[Type] = "Werkbon" || 'Geplande en contracturen medewerkers'[Type] = "Project"
			)
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Planning

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Geplande uren indirect' = ```
			CALCULATE(
							SUM('Geplande en contracturen medewerkers'[Aantal Uur])
							,'Geplande en contracturen medewerkers'[Type] = "Indirecte taak" 
			)
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Planning

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Geplande uren indirect (-)' = ```
			CALCULATE(
							SUM('Geplande en contracturen medewerkers'[Aantal Uur])*-1
							,'Geplande en contracturen medewerkers'[Type] = "Indirecte taak" 
			)
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Planning

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Geselecteerd gemiddelde uitvoertijd onderhoud' = MAX('Methode gemiddelde uitvoertijd onderhoud'[Value])
		formatString: 0.00
		displayFolder: 1. Semantisch model\1.02 HR\Planning

	measure 'Geselecteerde methode uitvoertijd onderhoud' = MAX('Methode bepalen uitvoertijd onderhoud'[ID])
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Planning

	measure 'Ongeplande uren' =
			CALCULATE(
							SUM('Geplande en contracturen medewerkers'[Aantal Uur])
							,'Geplande en contracturen medewerkers'[Type] = "Ongepland"
			)
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Planning

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Periode afgesloten' =
			
			CALCULATE(
			    count(Boekingperiodes[BoekingsperiodeKey])
			    ,Boekingperiodes[Status] = "Afgesloten"
			)
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Controle

		changedProperty = IsHidden

	measure 'Periode Invoer afgesloten' =
			
			CALCULATE(
			    count(Boekingperiodes[BoekingsperiodeKey])
			    ,Boekingperiodes[Status] = "Invoer afgesloten"
			)
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Controle

		changedProperty = IsHidden

	measure 'Periode Openstaand' =
			
			CALCULATE(
			    count(Boekingperiodes[BoekingsperiodeKey])
			    ,Boekingperiodes[Status] = "Openstaand"
			)
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Overig

		changedProperty = IsHidden

	measure 'Aantal aangemaakte calculaties' =
			
			calculate(
			    DISTINCTCOUNT('Calculaties met verkoopprijzen'[CalculatieDocumentKey])
			    ,USERELATIONSHIP('Kalender aanmaakdatum'[Aanmaakdatum],'Calculaties met verkoopprijzen'[Aanmaakdatum])
			    ,ALL(Projecten)
			)
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.05 Best practice Commercieel

	measure 'Aantal dagen offerte uitstaand' = ```
			
			IF(
			    ISINSCOPE(Offertes[Document])
			    ,CALCULATE(
			        DATEDIFF(MAX(offertes[Offertedatum]),today(),DAY)
			        ,offertes[Offerte status] = "Uitstaand")
			    ,blank()
			)    
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.05 Commercieel

	measure 'Aantal offertes uitstaand' = ```
			VAR _aantal_uitstaand =
			CALCULATE(
			    COUNT('Offertes'[OfferteDocumentKey])
			    ,FILTER(
			        ALL( 'Offertes'[Offerte status] )
			        , 'Offertes'[Offerte status] = "Uitstaand"
			    )
			)
			
			VAR result = 
			IF(
			    ISBLANK( _aantal_uitstaand )
			    , 0
			    , _aantal_uitstaand
			)
			
			
			RETURN
			
			result
			```
		formatString: #,##0
		displayFolder: 1. Semantisch model\1.05 Commercieel

	measure 'Budget facturatie' =
			
			var debet =
			CALCULATE(
			    SUM ('Budget per dag'[Bedrag per dag])
			    ,'Budget per dag'[Debet/Credit] = "D"
			    ,Rubrieken[Type] = "W"
			    ,Rubrieken[Toepassing] = "Omzetrekening"
			)
			var credit =
			CALCULATE(
			    SUM ('Budget per dag'[Bedrag per dag])
			    ,'Budget per dag'[Debet/Credit] = "C"
			    ,Rubrieken[Type] = "W"
			    ,Rubrieken[Toepassing] = "Omzetrekening"
			)
			
			return
			credit-debet
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Budget\Bron - Syntess

	measure 'Budget facturatie cumulatief' = ```
			
			    TOTALYTD(
			        [Budget facturatie]
			        ,Kalender[Datum]
			    )
			```
		formatString: "€"\ #,0.0;-"€"\ #,0.0;"€"\ #,0.0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Budget\Bron - Syntess

	measure 'Calculatie aantal dagen uitstaand' =
			
			IF(
			    ISINSCOPE('Calculaties met verkoopprijzen'[Calculatie])
			    , CALCULATE(
			        SUM( 'Calculaties met verkoopprijzen'[Aantal dagen sinds aanmaak] )
			        , 'Calculaties met verkoopprijzen'[Calculatiestatus] = "Uitstaand"
			    )
			    ,blank()
			)
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.05 Best practice Commercieel

	measure 'Calculatie kostprijs tbv offertes' = ```
			
			sum('Calculatiekosten onder offertes'[calculatie kostprijs])
			
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.05 Commercieel

	measure 'Calculatie project einddatum' =
			
			IF(
			    ISINSCOPE('Calculaties met verkoopprijzen'[Calculatie])
			    ,MAX( 'Calculaties met verkoopprijzen'[Project einddatum])
			    ,blank()
			)
		formatString: dd-mm-yy
		displayFolder: 2. Rapport Specifieke Objecten\2.05 Best practice Commercieel

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Calculatie project startdatum' =
			
			IF(
			    ISINSCOPE('Calculaties met verkoopprijzen'[Calculatie])
			    ,MAX('Calculaties met verkoopprijzen'[Project startdatum])
			    ,blank()
			)
		formatString: dd-mm-yy
		displayFolder: 2. Rapport Specifieke Objecten\2.05 Best practice Commercieel

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Calculatie uren montage tbv offertes' =
			
			CALCULATE(
			    SUM('Calculatiekosten onder offertes'[calculatie aantal])
			    ,NOT ( ISBLANK('Calculatiekosten onder offertes'[TaakKey] ) )
			    ,'NR - Taakgroepen DQ'[Taakgroep] = "Montage"
			)
		formatString: 0
		displayFolder: 1. Semantisch model\1.05 Commercieel

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Calculatie uren projectgebonden tbv offertes' =
			
			CALCULATE(
			    SUM('Calculatiekosten onder offertes'[calculatie aantal])
			    ,NOT(ISBLANK('Calculatiekosten onder offertes'[TaakKey]))
			    ,'NR - Taakgroepen DQ'[Taakgroep] = "Projectgebonden"
			)
		formatString: 0
		displayFolder: 1. Semantisch model\1.05 Commercieel

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Conversie naar opdracht' = ```
			
			var offertes_opdracht 
			=CALCULATE(
			    DISTINCTCOUNT(offertes[OfferteDocumentKey])
			    ,offertes[Offerte status] = "Opdracht"
			    ,'Offertes'[Niveau]=1)
			
			var offertes_geen_opdracht
			=CALCULATE(
			    DISTINCTCOUNT(offertes[OfferteDocumentKey])
			    ,offertes[Offerte status] = "Geen opdracht"
			    ,'Offertes'[Niveau]=1)
			
			var totaal_van_beide =
			    offertes_opdracht + offertes_geen_opdracht
			var conversie = DIVIDE(offertes_opdracht,totaal_van_beide,0)
			
			return
			IF(
			    ISBLANK(offertes_geen_opdracht)
			    ,0
			        ,IF(
			         ISBLANK(conversie)
			            ,0
			            ,conversie
			        )
			)
			```
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.05 Best practice Commercieel

	measure Gefactureerd =
			
			var debet =
			CALCULATE(
			    SUM ('Journaalregels'[Debetbedrag])
			    ,Rubrieken[Type] = "W"
			    ,Rubrieken[Toepassing] = "Omzetrekening"
			    ,Journaalregels[BoxNummer] = "1"
			)
			var credit =
			CALCULATE(
			    SUM ('Journaalregels'[Creditbedrag])
			    ,Rubrieken[Type] = "W"
			    ,Rubrieken[Toepassing] = "Omzetrekening"
			    ,Journaalregels[BoxNummer] = "1"
			)
			
			return
			credit-debet
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Exploitatie

	measure 'Gefactureerd % budget per dag' =
			
			var verschil =
			    [Gefactureerd]-[Budget facturatie]
			return
			DIVIDE(verschil,[Budget facturatie])
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Exploitatie

	measure 'Gefactureerd % tov vorig jaar' =
			
			var verschil =
			    [Gefactureerd]-[Gefactureerd vorig jaar]
			return
			DIVIDE(verschil,[Gefactureerd vorig jaar])
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Exploitatie

	measure 'Gefactureerd cumulatief' = ```
			
			    TOTALYTD(
			        [Gefactureerd],
			        'Kalender'[Datum]
			    )
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Exploitatie

	measure 'Gefactureerd cumulatief vorig jaar' =
			
			CALCULATE(
			        [Gefactureerd cumulatief],
			        SAMEPERIODLASTYEAR(Kalender[Datum])
			    )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Exploitatie

	measure 'Gefactureerd vorig jaar' = ```
			
				CALCULATE(
					[Gefactureerd],
					SAMEPERIODLASTYEAR(Kalender[Datum])
					)
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Exploitatie

	measure 'Melding conversie naar opdracht' = ```
			
			var offertes_opdracht 
			=CALCULATE(
			    DISTINCTCOUNT(offertes[OfferteDocumentKey])
			    ,offertes[Offerte status] = "Opdracht")
			
			var offertes_geen_opdracht
			=CALCULATE(
			    DISTINCTCOUNT(offertes[OfferteDocumentKey])
			    ,offertes[Offerte status] = "Geen opdracht")
			
			var totaal_van_beide =
			    offertes_opdracht + offertes_geen_opdracht
			var conversie = DIVIDE(offertes_opdracht,totaal_van_beide,0)
			
			return
			IF(
			    ISBLANK(offertes_geen_opdracht)
			    ,"Geen data"
			        ,IF(
			         ISBLANK(conversie)
			            ,"Geen data"
			            ,conversie
			        )
			)
			```
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.05 Best practice Commercieel

	measure 'Melding offerte met  aantal uitstaand' = "Offertes (Aantal uitstaand: "& [Aantal offertes uitstaand]  & " )"
		displayFolder: 2. Rapport Specifieke Objecten\2.05 Best practice Commercieel

	measure 'Offerte project einddatum' =
			
			IF(
			    ISINSCOPE('Offertes'[Document])
			    ,MAX( Offertes[Project einddatum] )
			    ,blank()
			)
		formatString: dd-mm-yy
		displayFolder: 2. Rapport Specifieke Objecten\2.05 Best practice Commercieel

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Offerte project startdatum' =
			
			IF(
			    ISINSCOPE('Offertes'[Document])
			    ,MAX( 'Offertes'[project startdatum] )
			    ,blank()
			)
		formatString: dd-mm-yy
		displayFolder: 2. Rapport Specifieke Objecten\2.05 Best practice Commercieel

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure Offertebedrag =
			
			SUM(offerteregels[Offertebedrag incl korting excl BTW])
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.05 Commercieel

	measure 'Offertebedrag alleen met VC kostprijs' = ```
			SUMX(
			    ADDCOLUMNS(
			    SUMMARIZE(
			        'Offertes'
			        , 'Offertes'[Document]
			        , "__offertebedrag"
			        , [Offertebedrag]
			    )
			    , "__VC_kostprijs"
			    , [Calculatie kostprijs tbv offertes]
			    ,"__offertebedrag_aangepast"
			    , IF(
			        ISBLANK( [Calculatie kostprijs tbv offertes] )
			        , BLANK()
			        ,IF(
			            ISBLANK([__offertebedrag])
			            ,BLANK()
			        , [__offertebedrag]            
			            )
			        )
			    )
			   ,[__offertebedrag_aangepast]
			)
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.05 Best practice Commercieel

		changedProperty = FormatString

	measure 'Offertebedrag uitstaand' =
			
			CALCULATE(
			    [Offertebedrag]
			    ,Offertes[Offerte status] = "Uitstaand"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.05 Commercieel

	measure 'Orderintake eenmalig' =
			
			var boekdatum =
			CALCULATE(
			SUM('Project eenmalige orderregels'[TotaalRegelbedrag Excl. BTW])
			,USERELATIONSHIP(Kalender[Datum],'Project eenmalige orderregels'[Boekdatum])
			)
			var aanmaakdatum =
			CALCULATE(
			SUM('Project eenmalige orderregels'[TotaalRegelbedrag Excl. BTW])
			,USERELATIONSHIP(Kalender[Datum],'Project eenmalige orderregels'[Aanmaakdatum])
			)
			
			var invoerdatum =
			CALCULATE(
			SUM('Project eenmalige orderregels'[TotaalRegelbedrag Excl. BTW])
			,USERELATIONSHIP(Kalender[Datum],'Project eenmalige orderregels'[Invoerdatum])
			)
			
			return
			SWITCH(
			    MAX('Methode datum orderintake eenmalig'[DatummethodeKey])
			    ,101,boekdatum
			    ,102,aanmaakdatum
			    ,103,invoerdatum
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.05 Best practice Commercieel

	measure 'Orderintake service' = SUM('Service order intake'[Jaarbedrag zonder einddatum])
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.05 Best practice Commercieel

	measure 'Scoringskans offertes' =
			
			IF(
			    ISINSCOPE(offertes[document])
			        ,CALCULATE(
			            MAX(offertes[Scoringskans])/100
			        )
			    ,blank()
			)
		formatString: #,##0.0 %
		displayFolder: 2. Rapport Specifieke Objecten\2.05 Best practice Commercieel

		changedProperty = DisplayFolder

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Scoringskans uitstaande offertes' =
			
			IF(
			    ISINSCOPE(offertes[document])
			        ,CALCULATE(
			            MAX(offertes[Scoringskans])/100
			            ,offertes[Offerte status] = "Uitstaand"
			        )
			    ,blank()
			)
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.05 Best practice Commercieel

	measure 'Winst %' = DIVIDE([Winst alleen met VC kostprijs],[Offertebedrag alleen met VC kostprijs])
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: 2. Rapport Specifieke Objecten\2.05 Best practice Commercieel

		changedProperty = FormatString

	measure 'Winst alleen met VC kostprijs' = ```
			SUMX(
			    ADDCOLUMNS(
			    SUMMARIZE(
			        'Offertes'
			        , 'Offertes'[Document]
			        , "__offertebedrag"
			        , [Offertebedrag]
			    )
			    , "__VC_kostprijs"
			    , [Calculatie kostprijs tbv offertes]
			    , "__resultaat"
			    , IF(
			        ISBLANK( [Calculatie kostprijs tbv offertes] )
			        , BLANK()
			        ,IF(
			            ISBLANK([__offertebedrag])
			            ,BLANK()
			        , [__offertebedrag] - [Calculatie kostprijs tbv offertes]                
			            )
			        )
			    )
			   ,[__resultaat]
			)
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.05 Best practice Commercieel

		changedProperty = FormatString

	measure 'Calculatie winst %' = DIVIDE([Calculatie winst],[Calculatie verkoopprijs])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie

		changedProperty = FormatString

	measure 'Calculatie winst' = [Calculatie verkoopprijs]-[Calculatie kostprijs]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie

	measure 'Calculatie kostprijs' =
			
			CALCULATE(
			    SUM('Calculatie kostenregels'[Kostprijs])
			    ,'Calculatie kostenregels'[Calculatiestatus] = "Opdracht"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie

	measure 'Aantal calculaties' =
			
			CALCULATE(
			    COUNT('Calculaties met verkoopprijzen'[CalculatieDocumentKey])
			    --,ALL(Projecten)
			)
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie

	measure 'Aantal actuele projecten' =
			
			CALCULATE(
			    DISTINCTCOUNT(Projecten[ProjectKey])
			    ,Projecten[Hoofdprojectstatus] = "Actueel")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectselectie

		changedProperty = IsHidden

	measure 'Aantal historische projecten' =
			
			CALCULATE(
			    DISTINCTCOUNT(Projecten[ProjectKey])
			    ,Projecten[Hoofdprojectstatus] = "Historisch")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectselectie

		changedProperty = IsHidden

	measure 'Aantal openstaande facturen met dispuut' =
			
			var openstaand =
			CALCULATE(
			    DISTINCTCOUNT('Betalingen per opbrengstregel'[VerkoopfactuurDocumentKey])
			    ,NOT(ISBLANK('Betalingen per opbrengstregel'[DispuutKey]))
			    ,FILTER(
			        ALL('Betalingen per opbrengstregel'[OpenstaandExclBTW])
			        ,'Betalingen per opbrengstregel'[OpenstaandExclBTW]>0)
			)
			return
			if(
			    ISBLANK(openstaand)
			    ,0
			    ,openstaand
			)
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.05 Best practice Commercieel

		changedProperty = IsHidden

	measure 'Aantal uitstaande offertes' =
			
			CALCULATE(
			    DISTINCTCOUNT(offertes[OfferteDocumentKey])
			    ,offertes[Offerte status] = "Uitstaand"
			)
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.05 Best practice Commercieel

		changedProperty = IsHidden

	measure 'Controle 1 relatie geselecteerd' =
			
			IF(
			    ISBLANK(SELECTEDVALUE(Relaties[Relatie]))
			    ,1
			    ,0
			    )
		formatString: 0
		isHidden
		displayFolder: 2. Rapport Specifieke Objecten\2.05 Best practice Commercieel

		changedProperty = IsHidden

		changedProperty = DisplayFolder

	measure 'Directe omzet' =
			
			var debet =
			CALCULATE(
			    SUM ('Journaalregels'[Debetbedrag])
			    ,Rubrieken[Type] = "W"
			    ,Rubrieken[Toepassing] = "Omzetrekening"
			    ,Journaalregels[BoxNummer] = "1"
			    ,Journaalregels[projectgerelateerd] = "Nee"
			)
			var credit =
			CALCULATE(
			    SUM ('Journaalregels'[Creditbedrag])
			    ,Rubrieken[Type] = "W"
			    ,Rubrieken[Toepassing] = "Omzetrekening"
			    ,Journaalregels[BoxNummer] = "1"
			    ,Journaalregels[projectgerelateerd] = "Nee"
			)
			
			return
			credit-debet
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.05 Commercieel

		changedProperty = IsHidden

	measure 'Openstaande bedragen met dispuut' =
			
			CALCULATE(
			    SUM('Betalingen per opbrengstregel'[OpenstaandExclBTW])
			    ,NOT(ISBLANK('Betalingen per opbrengstregel'[DispuutKey]))
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.05 Commercieel

		changedProperty = IsHidden

	measure 'Project van offerte' =
			
			IF(
			    ISFILTERED(offertes[document])
				,MAX(projecten[project])
				,""
			)
		displayFolder: 2. Rapport Specifieke Objecten\2.05 Best practice Commercieel

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "FilteredMeasure"
				}

		changedProperty = IsHidden

	measure 'Indirecte kosten YTDLY (standaard)' =
			
			totalytd(
			    [Indirecte kosten YTD (standaard)]
			    ,SAMEPERIODLASTYEAR('Kalender'[Datum])
			    )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)

	measure 'Indirecte kosten YTD (standaard)' =
			
			totalytd(
			    [Indirecte kosten (standaard)]
			    ,'Kalender'[Datum]
			    )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)

	measure 'Indirecte kosten LY (standaard)' =
			
			CALCULATE(
			    [Indirecte kosten (standaard)]
			    ,sameperiodlastyear('Kalender'[Datum])
			    )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)

	measure 'Indirecte kosten neg (standaard)' = [Indirecte kosten (standaard)]*-1
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		isHidden
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)

	measure 'Indirecte kosten (standaard)' =
			
			CALCULATE(
				[Debet]-[Credit]
				,Rubrieken[Toepassing]<>"Omzetrekening"
			    ,Rubrieken[Type] = "W"
			    //,Journaalregels[BoxNummer]="1"
			    ,'Journaalregels'[projectgerelateerd] = "Nee"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)

	/// Zie [Directe kosten YTD]. Betreft directe kosten cumulaief over dezelfde periode vorig jaar.
	measure 'Directe kosten YTDLY (standaard)' =
			
			totalytd(
			    [Directe kosten YTD (standaard)]
			    ,SAMEPERIODLASTYEAR('Kalender'[Datum])
			    )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)

	/// Directe kosten cumulatief tot einde geselecteerde einddatum.
	measure 'Directe kosten YTD (standaard)' =
			
			totalytd(
			    [Directe kosten (standaard)]
			    ,'Kalender'[Datum]
			    )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)

	measure 'Directe kosten neg (standaard)' = [Directe kosten (standaard)]*-1
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		isHidden
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)

	/// Zie [Directe kosten]. Betreft directe kosten over dezelfde periode vorig jaar.
	measure 'Directe kosten LY (standaard)' =
			
			CALCULATE(
			    [Directe kosten (standaard)]
			    ,sameperiodlastyear('Kalender'[Datum])
			    )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)

	/// [Debet]-[Credit] op exploitatie rubrieken die niet de toepassing "omzetrekening" hebben. Betreft niet de projectjournalisering boekingen (alleen boxnummer 1 boekingen). Alleen de journaalregels die aan een project zijn gekoppeld. 
	measure 'Directe kosten (standaard)' =
			
			CALCULATE(
				[Debet]-[Credit]
				,Rubrieken[Toepassing]<>"Omzetrekening"
			    ,Rubrieken[Type] = "W"
			    //,Journaalregels[BoxNummer]="1"
			   ,'Journaalregels'[projectgerelateerd] = "Ja"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)

	measure 'Directe kosten LY (benchmark schema)' = ```
			CALCULATE(
			    [Directe kosten (benchmark schema)]
			    ,sameperiodlastyear('Kalender'[Datum])
			    )
			    
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)

	measure 'Directe kosten (benchmark schema)' =
			CALCULATE(
			    [Mutatie resultaat]*-1
			    ,'NR - CoA schema'[Niveau1] = "Directe kosten"
			
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)

	/// Directe kosten cumulatief tot einde geselecteerde einddatum.
	measure 'Directe kosten YTD (benchmark schema)' =
			
			totalytd(
			    [Directe kosten (benchmark schema)]
			    ,'Kalender'[Datum]
			    )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)

	/// Zie [Directe kosten YTD]. Betreft directe kosten cumulaief over dezelfde periode vorig jaar.
	measure 'Directe kosten YTDLY (benchmark schema)' =
			
			totalytd(
			    [Directe kosten YTD (benchmark schema)]
			    ,SAMEPERIODLASTYEAR('Kalender'[Datum])
			    )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)

	measure 'Indirecte kosten (benchmark schema)' =
			CALCULATE(
			    [Mutatie resultaat]*-1
			    ,NOT ( 'NR - CoA schema'[Niveau1] )  IN  { "Directe kosten", "omzet" }
			
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)

	measure 'Indirecte kosten LY (benchmark schema)' =
			CALCULATE(
			    [Indirecte kosten (benchmark schema)]
			    ,sameperiodlastyear('Kalender'[Datum])
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)

	measure 'Indirecte kosten YTD (benchmark schema)' =
			
			totalytd(
			    [Indirecte kosten (benchmark schema)]
			    ,'Kalender'[Datum]
			    )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)

	measure 'Indirecte kosten YTDLY (benchmark schema)' =
			
			totalytd(
			    [Indirecte kosten YTD (benchmark schema)]
			    ,SAMEPERIODLASTYEAR('Kalender'[Datum])
			    )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)

	measure 'Omzet YTDLY (benchmark schema)' =
			
			totalytd(
			    [Omzet YTD (benchmark schema)]
			    ,SAMEPERIODLASTYEAR('Kalender'[Datum])
			    )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)

	measure 'Omzet YTD (benchmark schema)' =
			
			totalytd(
			    [Omzet (benchmark schema)]
			    ,'Kalender'[Datum]
			    )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)

	measure 'Omzet LY (benchmark schema)' = ```
			CALCULATE(
			    [Omzet (benchmark schema)]
			    ,sameperiodlastyear('Kalender'[Datum])
			    )
			    
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)

	measure 'Omzet 12 maanden (benchmark schema)' =
			
			CALCULATE(
			    [Omzet (benchmark schema)]
			    ,FILTER(
			        ALL('Kalender')
			        ,'Kalender'[Datum]<=MAX('Kalender'[Datum])
			        &&'Kalender'[Datum]>date(year(MAX('Kalender'[Datum]))-1,MONTH(max('Kalender'[Datum])),DAY(max('Kalender'[Datum])))
			        )
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)

	measure 'Omzet (benchmark schema)' =
			CALCULATE(
			    [Mutatie resultaat]
			    ,'NR - CoA schema'[Niveau1] = "Omzet"
			
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)

	measure 'Nettowinst YTDLY (benchmark schema)' = [Omzet YTDLY (benchmark schema)] - [Directe kosten YTDLY (benchmark schema)] - [Indirecte kosten YTDLY (benchmark schema)]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)

	measure 'Nettowinst YTD (benchmark schema)' = [Omzet YTD (benchmark schema)] - [Directe kosten YTD (benchmark schema)] - [Indirecte kosten YTD (benchmark schema)]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)

	measure 'Nettowinst LY (benchmark schema)' = ```
			CALCULATE(
			    [Nettowinst (benchmark schema)]    
			    ,sameperiodlastyear('Kalender'[Datum])
			    )
			    
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)

	measure 'nettowinst 12 maanden (benchmark schema)' =
			
			CALCULATE(
			    [Nettowinst (benchmark schema)]
			    ,FILTER(
			        ALL('Kalender')
			        ,'Kalender'[Datum]<=MAX('Kalender'[Datum])
			        &&'Kalender'[Datum]>date(year(MAX('Kalender'[Datum]))-1,MONTH(max('Kalender'[Datum])),DAY(max('Kalender'[Datum])))
			        )
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)

	measure 'Nettowinst (benchmark schema)' = [Omzet (benchmark schema)] - [Directe kosten (benchmark schema)] - [Indirecte kosten (benchmark schema)]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)

	measure 'Netto rendement YTD LY (benchmark schema)' = divide([Nettowinst YTDLY (benchmark schema)],[Omzet YTDLY (benchmark schema)])
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)

	measure 'Netto rendement YTD (benchmark schema)' = divide([Nettowinst YTD (benchmark schema)],[Omzet YTD (benchmark schema)])
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)

	measure 'Netto rendement LY (benchmark schema)' = divide([Nettowinst LY (benchmark schema)],[Omzet LY (benchmark schema)])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)

	measure 'Netto rendement 12 maanden (benchmark schema)' = divide([nettowinst 12 maanden (benchmark schema)],[Omzet 12 maanden (benchmark schema)])
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)

	measure 'Netto rendement (benchmark schema)' = divide([Nettowinst (benchmark schema)],[Omzet (benchmark schema)])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)

	measure 'Nettowinst YTDLY (standaard)' = [Omzet YTDLY (standaard)] - [Directe kosten YTDLY (standaard)] - [Indirecte kosten YTDLY (standaard)]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)

	measure 'Nettowinst YTD (standaard)' = [Omzet YTD (standaard)] - [Directe kosten YTD (standaard)] - [Indirecte kosten YTD (standaard)]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)

	measure 'Nettowinst LY (standaard)' =
			
			CALCULATE(
			    [Nettowinst (standaard)]
			    ,sameperiodlastyear('Kalender'[Datum])
			    )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)

	measure 'nettowinst 12 maanden (standaard)' =
			
			CALCULATE(
			    [Nettowinst (standaard)]
			    ,FILTER(
			        ALL('Kalender')
			        ,'Kalender'[Datum]<=MAX('Kalender'[Datum])
			        &&'Kalender'[Datum]>date(year(MAX('Kalender'[Datum]))-1,MONTH(max('Kalender'[Datum])),DAY(max('Kalender'[Datum])))
			        )
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)

	measure 'Nettowinst (standaard)' = [Omzet (standaard)] - [Directe kosten (standaard)] - [Indirecte kosten (standaard)]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)

	measure 'Netto rendement YTD LY (standaard)' = divide([Nettowinst YTDLY (standaard)],[Omzet YTDLY (standaard)])
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)

	measure 'Netto rendement YTD (standaard)' = divide([Nettowinst YTD (standaard)],[Omzet YTD (standaard)])
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)

	measure 'Netto rendement LY (standaard)' = divide([Nettowinst LY (standaard)],[Omzet LY (standaard)])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)

	measure 'Netto rendement 12 maanden (standaard)' = divide([nettowinst 12 maanden (standaard)],[Omzet 12 maanden (standaard)])
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)

	measure 'Netto rendement (standaard)' = divide([Nettowinst (standaard)],[Omzet (standaard)])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)

	measure 'Directe kosten neg (benchmark schema)' = [Directe kosten]*-1
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)

	measure 'Indirecte kosten neg (benchmark schema)' = [Indirecte kosten (benchmark schema)]*-1
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)

	measure Omzet =
			
			IF(
			    [Geselecteerde methode resultaat bepaling]=2
			    ,[Omzet (benchmark schema)]
			    ,[Omzet (standaard)]
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd

	/// Resultaat (credit - debet) van het geboekte werkresultaat in de exploitatierekening. Werkresultaat is het definitieve resultaat bij vrijval van een project. 
	measure Werkresultaat = ```
			
			VAR _credit =
			CALCULATE(
			    SUM('Project journaalregels'[bedrag] )
			    ,'Project journaalregels'[Debet/Credit] = "C"
			    ,CROSSFILTER ( Rubrieken[RubriekKey], Grootboekrekeningen[RubriekKey], BOTH )
			    ,Rubrieken[Type] = "W"
			    ,'Rubrieken'[Toepassing] = "Werkresultaat"
			    ,'Journaalregels'[BoxNummer] = "2" 
			)
			
			VAR _debet =
			CALCULATE(
			    SUM('Project journaalregels'[bedrag] )
			    ,'Project journaalregels'[Debet/Credit] = "D"
			    ,CROSSFILTER ( Rubrieken[RubriekKey], Grootboekrekeningen[RubriekKey], BOTH )
			    ,Rubrieken[Type] = "W"
			    ,'Rubrieken'[Toepassing] = "Werkresultaat"
			    ,'Journaalregels'[BoxNummer] = "2" 
			)
			
			
			VAR Result = _credit-_debet
			
			RETURN
			Result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering

	/// Resultaat (credit - debet) van de geboekte projectwaarderingen in de exploitatierekening. Projectwaardering tonen de tussentijdse respresentatie van het verwachte resultaat. 
	measure Waarderingen = ```
			
			VAR _credit =
			CALCULATE(
			    SUM('Project journaalregels'[bedrag] )
			    ,'Project journaalregels'[Debet/Credit] = "C"
			    ,CROSSFILTER ( Rubrieken[RubriekKey], Grootboekrekeningen[RubriekKey], BOTH )
			    ,Rubrieken[Type] = "W"
			    ,'Rubrieken'[Toepassing] = "Projectwaardering"
			    ,'Journaalregels'[BoxNummer] = "2" 
			)
			
			VAR _debet =
			CALCULATE(
			    SUM('Project journaalregels'[bedrag] )
			    ,'Project journaalregels'[Debet/Credit] = "D"
			    , CROSSFILTER( Rubrieken[RubriekKey], Grootboekrekeningen[RubriekKey], Both )
			    , Rubrieken[Type] = "W"
			    , 'Rubrieken'[Toepassing] = "Projectwaardering"
			    , 'Journaalregels'[BoxNummer] = "2"
			)
			
			
			VAR Result = _credit-_debet
			
			RETURN
			Result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering

	/// Verschil tussen 2 manieren van de dekkingen bepaling. Moet altijd €0 zijn.
	measure 'Verschil dekking berekeningen' = [Dekkingen]-[Dekkingen op projecten (berekend)]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Projectjournalisering zonder projectrelatie\Enterprise

	/// [Projectwaarderingen resultaat]+[Resultaat tegenboeken projectwaarderingen]+[Werkresultaat]
	measure 'Totaal projectwaardering + werkresultaat' = [Waarderingen]+[Werkresultaat]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering

	measure 'Projectkosten incl dekkingen op projecten' = [Projectjournalisering kosten]+( [Dekkingen op projecten (berekend)] * - 1 )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering

	/// [OHW mutatie in balans]+[Werkresultaat]
	measure 'Netto resultaat via OHW' = [OHW mutatie in balans]+[Werkresultaat]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering

	/// [OHW mutatie in exploitatie]+[Dekkingen op projecten]
	measure 'Netto resultaat via exploitatie' = [OHW mutatie in exploitatie]+[Dekkingen op projecten (berekend)]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering

	/// [OHW mutatie in exploitatie]-[OHW mutatie in balans]-[Werkresultaat]. Betreft een berekende waarde t.b.v. bepaling dekking op projectniveau.
	measure 'Dekkingen op projecten (berekend)' = ```
			
			//Dekkingen worden niet geboekt met projectkey. Hierdoor is niet bekend wat de dekking is per project. Een alternatief is door de dekking te berekenen 
			IF(
			   Isblank(  [OHW mutatie in balans])
			   ,blank()
			   ,( [OHW mutatie in balans] + [Werkresultaat])-[OHW mutatie in exploitatie]
			)
			
			
			
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering

	measure 'Omzet CoA' = CALCULATE(SUM( Journaalregels[Creditbedrag] )-SUM(Journaalregels[Debetbedrag]), 'NR - CoA schema'[Niveau1] = "Omzet")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\KPI

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Omloopsnelheid debiteuren per maand' = DIVIDE([Gemiddeld debiteuren saldo],[Omzet CoA]) * 30
		formatString: #,##0.0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\KPI

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Omloopsnelheid debiteuren per jaar' = DIVIDE([Gemiddeld debiteuren saldo],[Omzet CoA]) * 365
		formatString: #,##0.0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\KPI

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Omloopsnelheid crediteuren per maand' = DIVIDE([Gemiddeld crediteuren saldo],[Bedrijfskosten CoA]) * 30
		formatString: #,##0.0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\KPI

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Omloopsnelheid crediteuren per jaar' = DIVIDE([Gemiddeld crediteuren saldo],[Bedrijfskosten CoA]) * 365
		formatString: #,##0.0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\KPI

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gemiddeld debiteuren saldo' = DIVIDE( ( [Debiteurensaldo einde periode] + [Debiteurensaldo begin periode] ), 2 )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\KPI

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gemiddeld crediteuren saldo' = DIVIDE( ( [Crediteurensaldo einde periode] + [Crediteurensaldo begin periode] ), 2 )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\KPI

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Debiteurensaldo einde periode' =
			
			var openstaand =
				CALCULATE(
					SUM('Verkoopfactuur termijnen'[Bedrag])
					,FILTER(
						ALL(kalender),
							COUNTROWS
							(
							FILTER(kalender,
							   EARLIER(Kalender[Standdatum])<=MAX(Kalender[Standdatum]))
						)>0
				)
			)
			return
			IF(openstaand >-1 && openstaand <1
			    ,blank()
			    ,openstaand
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\KPI

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Debiteurensaldo begin periode' =
			
			var openstaand =
				CALCULATE(
					SUM('Verkoopfactuur termijnen'[Bedrag])
					,FILTER(
						ALL(kalender),
							COUNTROWS
							(
							FILTER(kalender,
							   EARLIER(Kalender[Standdatum])<MIN(Kalender[Standdatum]))
						)>0
				)
			)
			return
			IF(openstaand >-1 && openstaand <1
			    ,blank()
			    ,openstaand
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\KPI

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Crediteurensaldo einde periode' =
			
			var openstaand =
				CALCULATE(
					SUM('Inkoopfactuur termijnen'[Bedrag])
					,FILTER(
						ALL(kalender),
							COUNTROWS
							(
							FILTER(kalender,
							   EARLIER(Kalender[Standdatum])<=MAX(Kalender[Standdatum]))
						)>0
				)
			)
			
			return
			IF(openstaand >-1 && openstaand <1
			    ,BLANK()
			    ,openstaand
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\KPI

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Crediteurensaldo begin periode' =
			
			var openstaand =
				CALCULATE(
					SUM('Inkoopfactuur termijnen'[Bedrag])
					,FILTER(
						ALL(kalender),
							COUNTROWS
							(
							FILTER(kalender,
							   EARLIER(Kalender[Standdatum])<MIN(Kalender[Standdatum]))
						)>0
				)
			)
			
			return
			IF(openstaand >-1 && openstaand <1
			    ,BLANK()
			    ,openstaand
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\KPI

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bedrijfskosten CoA' =
			
			CALCULATE(
			    SUM( Journaalregels[Debetbedrag] ) - SUM( Journaalregels[Creditbedrag] ),
			    'NR - CoA schema'[Classificatie type] = "Indirecte kosten"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\KPI

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Directe kosten' =
			
			IF(
			    [Geselecteerde methode resultaat bepaling]=2
			    ,[Directe kosten (benchmark schema)]
			    ,[Directe kosten (standaard)]
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd

	measure 'Montage uren TW' =
			
			VAR werkuren_urenstaat =
			    CALCULATE(
			    SUM('project kosten en geboekte Uren'[Aantal])
			    ,NOT(ISBLANK('Geboekte uren'[TaakKey]))
			    ,'NR - Taakgroepen DQ'[Taakgroep]="Montage"
			)
			VAR inleenuren_via_inkoop =
			CALCULATE(
			    SUM('Project kosten en geboekte uren'[Aantal])
			    ,'Kostensoorten'[Categorie] = "Arbeid"
			    ,'Project kosten en geboekte uren'[Kostenbron] = "Inkoop"
			    ,'Project kosten en geboekte uren'[internationale code] = "570410"
			)
			
			VAR result = werkuren_urenstaat + inleenuren_via_inkoop
			
			RETURN
			result
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Toegevoegde waarde

	measure 'Montage uren via inkoopfacturen' = ```
			
			VAR inleenuren_via_inkoop =
			CALCULATE(
			    SUM('Project kosten en geboekte uren'[Aantal])
			    ,'Kostensoorten'[Categorie] = "Arbeid"
			    ,'Project kosten en geboekte uren'[Kostenbron] = "Inkoop"
			    ,'Project kosten en geboekte uren'[internationale code] = "570410"
			)
			
			VAR result = 
			    inleenuren_via_inkoop
			
			RETURN
			result
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Toegevoegde waarde

	measure 'montage uren via urenstaten TW' =
			
			VAR werkuren_urenstaat =
			    CALCULATE(
			    SUM('Project kosten en geboekte uren'[Aantal])
			    ,NOT(ISBLANK('Geboekte uren'[TaakKey]))
			    ,'NR - Taakgroepen DQ'[Taakgroep]="Montage"
			)
			
			VAR result = werkuren_urenstaat
			
			RETURN
			result
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Toegevoegde waarde

	measure 'Toegevoegde Waarde op realisatie per uur (TWR\u)' = ```
			
			VAR result = DIVIDE( [Toegevoegde Waarde op Realisatie (TWR)],[Montage uren TW]  )
			
			RETURN 
			result
			```
		formatString: """"€""""\ #,0;-""""€""""\ #,0;""""€""""\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Toegevoegde waarde

	measure 'Toegevoegde Waarde op Realisatie (TWR, zonder datumfilter)' = ```
			
			CALCULATE(
			    [Project omzet] - [Verrekenprijs exclusief arbeid]
			    , ALL( Kalender )
			    --,Projecten[Hoofdprojectstatus] = "Historisch"
			)
			
			
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Toegevoegde waarde\Zonder datumfilter

	measure 'Melding bankrubrieken dubbel gekoppeld' =
			
			//controle of bank rubrieken aan meerdere dagboeken zijn gekoppeld. Dit kan leiden tot dubbeltellingen als het actuele dagboeken betreft.
			IF(
			    ISBLANK(DISTINCTCOUNT('Bank rubrieken meerdere keren gekoppeld'[DagboekRubriekKey]))
			    ,""
			    ,"Dezelfde bankrubriek(en) is(/zijn) aan meerdere dagboeken gekoppeld!")
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Meldingen

	measure 'Melding Geen openstaande bankafschriften' =
			
			IF(
			    ISBLANK([openstaande bankmutaties])
			    ,"Er zijn geen openstaande bankafschriften."
			    ,""
			)
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Meldingen

	measure 'Melding geselecteerde CF categorie' = "Specificatie van categorie ["&MAX('NR - Cashflow categorien DQ'[Categorie])&"] per rubriek"
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Meldingen

	measure 'Bank incl. openstaande bankregels' =
			
			[Bank Debet]-[Bank Credit]
			    + [openstaande bankmutaties]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Cash flow\Bank\New folder

	measure 'Bank eindsaldo incl. openstaande bankregels' = ```
			
			var eindsaldo =
			    CALCULATE(
			        [Bank incl. openstaande bankregels]
			        ,FILTER(
			            ALL(Kalender[Datum])
			            ,Kalender[Datum]<=MAX(Kalender[Datum])
			        )
			    )   
			return
			IF(
			    ISBLANK(eindsaldo)
			    , BLANK()
			    ,IF(
			        eindsaldo > -1000 && eindsaldo < 1000
			        ,BLANK()
			        ,eindsaldo)
			)
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Cash flow\Bank\New folder

	measure 'Bank beginsaldo incl. openstaande bankregels' = ```
			
			var beginsaldo =
			    CALCULATE(
			        [Bank incl. openstaande bankregels]
			        ,FILTER(
			            ALL(Kalender[Datum])
			            ,Kalender[Datum]<MIN(Kalender[Datum])
			        )
			    )   
			return
			IF(
			    ISBLANK(beginsaldo)
			    , BLANK()
			    ,IF(
			        beginsaldo > -1000 && beginsaldo < 1000
			        ,BLANK()
			        ,beginsaldo)
			)
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Cash flow\Bank\New folder

	measure 'Nog te verwachten kosten via werkbon inkoop' = ```
			
			CALCULATE(
			        SUM('Werkbonparagraaf kosten en geboekte uren'[Kostprijs])
			        ,'Werkbonparagraaf kosten en geboekte uren'[Kostenstatus] = "Nog te verwachten"
			        ,'Werkbonparagraaf kosten en geboekte uren'[Kostenbron] = "Inkoop" ||'Werkbonparagraaf kosten en geboekte uren'[Kostenbron] = "Pakbon" 
			    )
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen

	measure 'Budget resultaat (Projectbeheer)' = [Budget omzet (Projectbeheer)]-[Calculatie kostprijs]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Budget

	/// Basis: Orderbedrag. Indien specifiek geselecteerd;calculatie verkoopprijs
	measure 'budget omzet (Projectbeheer)' =
			
			IF(
			    VALUE( MAX( 'Methode Budgetomzet'[ID] ) ) = 2
			    ,[Calculatie verkoopprijs]
			    ,[Orderbedrag]
			)
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Budget

	/// (Budget omzet - budgetkosten) /budgetomzet
	measure 'Budget marge (Projectbeheer)' = DIVIDE([Budget resultaat (Projectbeheer)],[budget omzet (Projectbeheer)],0)
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Budget

		changedProperty = IsHidden

	measure 'Gerealiseerde rendement (Projectbeheer)' = ```
			
			 DIVIDE([Resultaat (Projectbeheer)],[Gefactureerd])
			```
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Ratios

		changedProperty = IsHidden

	measure 'Resultaat (Projectbeheer)' = [Gefactureerd]-[Definitieve kostprijs]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Ratios

		changedProperty = IsHidden

	measure AdministratieKey = ```
			
			IF(
			    [Controle project selectie] IN {0,2} //Er is slechts één hoofd- of deelproject geselecteerd.
			    ,SWITCH(
			        MIN('Projecten'[Niveau])
			        ,1,CALCULATE(MIN('Projecten'[AdministratieKey]) ,'Projecten'[Niveau] =1)
			        ,2,CALCULATE(MIN('Projecten'[AdministratieKey]) ,'Projecten'[Niveau] =2)
			    )
			    ,IF(
			         [Controle project selectie] = 1 // Er is één hoofdproject geselecteerd met mogelijk meerdere deelprojecten.
			         ,CALCULATE(
			             MAX('Projecten'[AdministratieKey])
			             ,'Projecten'[Niveau] =1
			         )
			         ,BLANK() //Als de selectie niet gewenst is dan wordt er geen administratieKey bepaald.
			    )
			)
			
			```
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectselectie\1. Naar PowerApp

	measure 'Mutatie actual CoCFC' = ```
			
			VAR _mutatie_selected                       = SELECTEDVALUE('NR - Cashflow categorien DQ'[Classificatie])   = "Mutatie"
			VAR _beginsaldo_selected                    = SELECTEDVALUE('NR - Cashflow categorien DQ'[Categorie])       = "Beginsaldo"
			VAR _eindsaldo_selected                     = SELECTEDVALUE('NR - Cashflow categorien DQ'[Categorie])       = "Eindsaldo"
			VAR _subtotaal_mutatie_selected             = SELECTEDVALUE('NR - Cashflow categorien DQ'[Categorie])       = "Mutatie op bank"
			VAR _openstaand_selected                    = SELECTEDVALUE('NR - Cashflow categorien DQ'[Categorie])       = "Openstaande bankafschriften*"
			var _geselec_maandindex                     = max('Kalender standdatums'[Maand index])
			VAR _geselecteerde_einddatum                = MAX( 'Kalender standdatums'[Einddatum Maand] )
			var _StartOfYear_geselecteerde_einddatum    = Date(YEAR(_geselecteerde_einddatum),1,1)
			VAR _einddatum_beginsaldo                   =
			      IF(
			          MIN( Kalender[Datum] )=_StartOfYear_geselecteerde_einddatum 
			          ,DATE(YEAR(MIN( Kalender[Datum] )),1,2)
			          ,MIN( Kalender[Datum] )
			      )
			VAR _credit_mutatie =        
			IF(
			    MAX( Kalender[Datum] ) <= MAX( 'Kalender standdatums'[Einddatum Maand] )
			    ,CALCULATE(
			        SUM( Journaalregels[Creditbedrag] )
			        , 'Journaalregels'[Bankafschriftboeking type] = "Tegenrekening"
			        , 'Journaalregels'[Bankafschriftboeking Ja/Nee] = "Ja"
			    ) 
			    , BLANK()
			)
			
			VAR _debet_mutatie =
			IF(
			    MAX( Kalender[Datum] ) <= MAX( 'Kalender standdatums'[Einddatum Maand] )
			    ,CALCULATE(
			        SUM(Journaalregels[Debetbedrag])
			        ,'Journaalregels'[Bankafschriftboeking type]="Tegenrekening"
			        ,'Journaalregels'[Bankafschriftboeking Ja/Nee] = "Ja"
			    )
			    , BLANK()
			)
			
			VAR _credit_mutatie_subtotaal = 
			IF(
			    MAX( Kalender[Datum] ) <= MAX( 'Kalender standdatums'[Einddatum Maand] )
			    , CALCULATE(
			        SUM( Journaalregels[Creditbedrag] )
			        , 'Journaalregels'[Bankafschriftboeking type] = "Tegenrekening"
			        , 'Journaalregels'[Bankafschriftboeking Ja/Nee] = "Ja"
			        ,ALL('NR - Cashflow categorien DQ')
			    )    
			    , BLANK()
			)
			
			VAR _debet_mutatie_subtotaal  =
			IF(
			    MAX( Kalender[Datum] ) <= MAX( 'Kalender standdatums'[Einddatum Maand] )
			    ,CALCULATE(
			        SUM(Journaalregels[Debetbedrag])
			        ,'Journaalregels'[Bankafschriftboeking type]="Tegenrekening"
			        ,'Journaalregels'[Bankafschriftboeking Ja/Nee] = "Ja"
			        ,ALL('NR - Cashflow categorien DQ')
			    ) 
			    , BLANK()
			)
			
			
			VAR _debet_bank_beginsaldo_tot_standdatum =
			 CALCULATE(
			        SUM( Journaalregels[Debetbedrag] )
			        , 'Journaalregels'[Bankafschriftboeking type] = "Bank"
			        , ALL( 'NR - cashflow categorien DQ' )
			        , FILTER(
			            ALL( Kalender )
			            , Kalender[Datum] < _einddatum_beginsaldo
			            && 'Kalender'[Datum]>=_StartOfYear_geselecteerde_einddatum
			            && Kalender[Maand index]  <= _geselec_maandindex
			        )
			        , FILTER(
			            ALL( 'Kalender standdatums' )
			            , 'Kalender standdatums'[Maand index] <= _geselec_maandindex
			        )
			    )
			    
			VAR _credit_bank_beginsaldo_tot_standdatum =
			CALCULATE(
			        SUM( Journaalregels[Creditbedrag] )
			        , 'Journaalregels'[Bankafschriftboeking type] = "Bank"
			        , ALL( 'NR - cashflow categorien DQ' )
			        , FILTER(
			            ALL( Kalender )
			            , Kalender[Datum] < _einddatum_beginsaldo
			            && 'Kalender'[Datum]>=_StartOfYear_geselecteerde_einddatum
			            && Kalender[Maand index]  <= _geselec_maandindex
			        )
			        , FILTER(
			            ALL( 'Kalender standdatums' )
			            , 'Kalender standdatums'[Maand index] <= _geselec_maandindex
			        )
			    )  
			
			VAR _debet_bank_eindsaldo_tot_standdatum =
			CALCULATE(
			    SUM( Journaalregels[Debetbedrag] )
			    , 'Journaalregels'[Bankafschriftboeking type] = "Bank"
			    , ALL( 'NR - cashflow categorien DQ' )
			    , FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] <= MAX( Kalender[Datum] )
			        && 'Kalender'[Datum]>=_StartOfYear_geselecteerde_einddatum
			        &&  Kalender[Maand index]  <= _geselec_maandindex
			    )
			    , FILTER(
			        ALL( 'Kalender standdatums' )
			        , 'Kalender standdatums'[Maand index] <= _geselec_maandindex
			    )
			)
			
			VAR _credit_bank_eindsaldo_tot_standdatum =
			CALCULATE(
			    SUM( Journaalregels[Creditbedrag] )
			    , 'Journaalregels'[Bankafschriftboeking type] = "Bank"
			    , ALL( 'NR - cashflow categorien DQ' )
			    , FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] <= MAX( Kalender[Datum] )
			        && 'Kalender'[Datum]>=_StartOfYear_geselecteerde_einddatum
			        && Kalender[Maand index]  <= _geselec_maandindex
			    )
			    , FILTER(
			        ALL( 'Kalender standdatums' )
			        , 'Kalender standdatums'[Maand index] <= _geselec_maandindex
			    )
			) 
			
			VAR _openstaand_bankafschrift_credit =
			CALCULATE(
			    SUM( 'Bankregels openstaand'[Creditbedrag] )
			    , ALL( 'NR - Cashflow categorien DQ' )
			)
			
			VAR _openstaand_bankafschrift_debet =
			CALCULATE(
			    SUM( 'Bankregels openstaand'[Debetbedrag] )
			    , ALL( 'NR - Cashflow categorien DQ')
			)
			
			VAR result =
			    SWITCH(
			        TRUE
			        ,_beginsaldo_selected,_debet_bank_beginsaldo_tot_standdatum-_credit_bank_beginsaldo_tot_standdatum
			        ,_eindsaldo_selected,_debet_bank_eindsaldo_tot_standdatum-_credit_bank_eindsaldo_tot_standdatum
			        ,_openstaand_selected,_openstaand_bankafschrift_credit-_openstaand_bankafschrift_debet
			        ,_mutatie_selected,_credit_mutatie - _debet_mutatie
			        ,_subtotaal_mutatie_selected,_credit_mutatie_subtotaal - _debet_mutatie_subtotaal
			    )
			    
			    
			RETURN
			 result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Cashflow forecast

	measure 'Mutatie actual en forecast CoCFC' = ```
			
			VAR _mutatie_selected                       = SELECTEDVALUE('NR - cashflow categorien DQ'[Classificatie]) = "Mutatie"
			VAR _beginsaldo_selected                    = SELECTEDVALUE('NR - cashflow categorien DQ'[Categorie]) = "Beginsaldo"
			VAR _eindsaldo_selected                     = SELECTEDVALUE('NR - cashflow categorien DQ'[Categorie]) = "Eindsaldo"
			VAR _subtotaal_mutatie_selected             = SELECTEDVALUE('NR - cashflow categorien DQ'[Categorie]) = "Mutatie op bank"
			VAR _openstaand_selected                    = SELECTEDVALUE('NR - cashflow categorien DQ'[Categorie]) = "Openstaande bankafschriften*"
			var _geselec_maandindex                     = max('Kalender standdatums'[Maand index])
			VAR _geselecteerde_einddatum                = MAX( 'Kalender standdatums'[Einddatum Maand] )
			var _StartOfYear_geselecteerde_einddatum    = Date(YEAR(_geselecteerde_einddatum),1,1)
			VAR _einddatum_beginsaldo                   =
			      IF(
			          MIN( Kalender[Datum] )=_StartOfYear_geselecteerde_einddatum 
			          ,DATE(YEAR(MIN( Kalender[Datum] )),1,2)
			          ,MIN( Kalender[Datum] )
			      )
			VAR _credit_mutatie_tot_standdatum = 
			CALCULATE(
			    SUM( Journaalregels[Creditbedrag] )
			    , 'Journaalregels'[Bankafschriftboeking type] = "Tegenrekening"
			    , 'Journaalregels'[Bankafschriftboeking Ja/Nee] = "Ja"
			    ,Kalender[Maand index]  <= _geselec_maandindex
			)
			
			VAR _debet_mutatie_tot_standdatum =
			CALCULATE(
			    SUM( Journaalregels[Debetbedrag] )
			    , 'Journaalregels'[Bankafschriftboeking type] = "Tegenrekening"
			    , 'Journaalregels'[Bankafschriftboeking Ja/Nee] = "Ja"
			    ,Kalender[Maand index]  <= _geselec_maandindex
			)
			
			VAR _forecast_mutatie_na_standdatum =
			CALCULATE(
			    SUM( 'NR - Cashflow forecastregels DQ'[waarde] )
			    ,Kalender[Maand index]  > _geselec_maandindex
			)
			
			VAR _credit_mutatie_subtotaal_tot_standdatum =
			CALCULATE(
			    SUM( Journaalregels[Creditbedrag] )
			    , 'Journaalregels'[Bankafschriftboeking type] = "Tegenrekening"
			    , 'Journaalregels'[Bankafschriftboeking Ja/Nee] = "Ja"
			    , ALL( 'NR - cashflow categorien DQ' )
			    , Kalender[Maand index]  <= _geselec_maandindex
			)
			
			VAR _debet_mutatie_subtotaal_tot_standdatum  =
			CALCULATE(
			    SUM( Journaalregels[Debetbedrag] )
			    , 'Journaalregels'[Bankafschriftboeking type] = "Tegenrekening"
			    , 'Journaalregels'[Bankafschriftboeking Ja/Nee] = "Ja"
			    , ALL( 'NR - cashflow categorien DQ' )
			    , Kalender[Maand index]  <= _geselec_maandindex
			)
			    
			VAR _forecast_mutatie_subtotaal_na_standdatum =
			CALCULATE(
			    SUM( 'NR - Cashflow forecastregels DQ'[waarde] )
			    , ALL( 'NR - cashflow categorien DQ' )
			    ,Kalender[Maand index]  > _geselec_maandindex
			)
			
			VAR _debet_bank_beginsaldo_tot_standdatum =
			 CALCULATE(
			        SUM( Journaalregels[Debetbedrag] )
			        , 'Journaalregels'[Bankafschriftboeking type] = "Bank"
			        , ALL( 'NR - cashflow categorien DQ' )
			        , FILTER(
			            ALL( Kalender )
			            , Kalender[Datum] < _einddatum_beginsaldo 
			            && 'Kalender'[Datum]>=_StartOfYear_geselecteerde_einddatum
			            && Kalender[Maand index]  <= _geselec_maandindex
			        )
			        , FILTER(
			            ALL( 'Kalender standdatums' )
			            , 'Kalender standdatums'[Maand index] <= _geselec_maandindex
			        )
			    )
			    
			VAR _credit_bank_beginsaldo_tot_standdatum =
			CALCULATE(
			        SUM( Journaalregels[Creditbedrag] )
			        , 'Journaalregels'[Bankafschriftboeking type] = "Bank"
			        , ALL( 'NR - cashflow categorien DQ' )
			        , FILTER(
			            ALL( Kalender )
			            , Kalender[Datum] < _einddatum_beginsaldo
			            && 'Kalender'[Datum]>=_StartOfYear_geselecteerde_einddatum
			            && Kalender[Maand index]  <= _geselec_maandindex
			        )
			        , FILTER(
			            ALL( 'Kalender standdatums' )
			            , 'Kalender standdatums'[Maand index] <= _geselec_maandindex
			        )
			    )
			
			VAR Forecast_beginsaldo_na_standdatum =
			CALCULATE(
			    SUM( 'NR - Cashflow forecastregels DQ'[waarde] )
			    , ALL( 'NR - cashflow categorien DQ' )
			    , FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] < MIN( Kalender[Datum] )
			        && Kalender[Maand index]  > _geselec_maandindex
			    )
			)
			
			VAR _debet_bank_eindsaldo_tot_standdatum =
			CALCULATE(
			    SUM( Journaalregels[Debetbedrag] )
			    , 'Journaalregels'[Bankafschriftboeking type] = "Bank"
			    , ALL( 'NR - cashflow categorien DQ' )
			    , FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] <= MAX( Kalender[Datum] )
			        && 'Kalender'[Datum]>=_StartOfYear_geselecteerde_einddatum
			        &&  Kalender[Maand index]  <= _geselec_maandindex
			    )
			    , FILTER(
			        ALL( 'Kalender standdatums' )
			        , 'Kalender standdatums'[Maand index] <= _geselec_maandindex
			    )
			)
			
			VAR _credit_bank_eindsaldo_tot_standdatum =
			CALCULATE(
			    SUM( Journaalregels[Creditbedrag] )
			    , 'Journaalregels'[Bankafschriftboeking type] = "Bank"
			    , ALL( 'NR - cashflow categorien DQ' )
			    , FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] <= MAX( Kalender[Datum] )
			        && 'Kalender'[Datum]>=_StartOfYear_geselecteerde_einddatum
			        && Kalender[Maand index]  <= _geselec_maandindex
			    )
			    , FILTER(
			        ALL( 'Kalender standdatums' )
			        , 'Kalender standdatums'[Maand index] <= _geselec_maandindex
			    )
			)
			
			VAR Forecast_eindsaldo_na_standdatum =
			 CALCULATE(
			    SUM( 'NR - Cashflow forecastregels DQ'[waarde] )
			    , ALL( 'NR - cashflow categorien DQ' )
			    , FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] <= MAX( Kalender[Datum] )
			        && Kalender[Maand index] > _geselec_maandindex
			    )
			)
			
			VAR _openstaand_bankafschrift_credit =
			CALCULATE(
			    SUM( 'Bankregels openstaand'[Creditbedrag] )
			    , ALL( 'NR - cashflow categorien DQ' )
			)
			
			VAR _openstaand_bankafschrift_debet =
			CALCULATE(
			    SUM( 'Bankregels openstaand'[Debetbedrag] )
			    , ALL( 'NR - cashflow categorien DQ')
			)
			
			VAR result =
			    SWITCH(
			        TRUE
			        ,_beginsaldo_selected,_debet_bank_beginsaldo_tot_standdatum-_credit_bank_beginsaldo_tot_standdatum + Forecast_beginsaldo_na_standdatum
			        ,_eindsaldo_selected,_debet_bank_eindsaldo_tot_standdatum-_credit_bank_eindsaldo_tot_standdatum  +Forecast_eindsaldo_na_standdatum
			        ,_openstaand_selected,_openstaand_bankafschrift_credit-_openstaand_bankafschrift_debet
			        ,_mutatie_selected,_credit_mutatie_tot_standdatum - _debet_mutatie_tot_standdatum + _forecast_mutatie_na_standdatum
			        ,_subtotaal_mutatie_selected,_credit_mutatie_subtotaal_tot_standdatum - _debet_mutatie_subtotaal_tot_standdatum +_forecast_mutatie_subtotaal_na_standdatum
			    )
			
			    
			RETURN
			 result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Cashflow forecast

	measure 'Subtotaal codering mutatie actual CoCFC' = ```
			
			VAR _subtotaal_mutatie_selected     = SELECTEDVALUE('NR - cashflow categorien DQ'[Categorie]) = "Mutatie op bank"
			
			VAR _credit_mutatie_subtotaal =        
			CALCULATE(
			    SUM( Journaalregels[Creditbedrag] )
			    , 'Journaalregels'[Bankafschriftboeking type] = "Tegenrekening"
			    , 'Journaalregels'[Bankafschriftboeking Ja/Nee] = "Ja"
			    ,ALL('NR - Cashflow categorien DQ')
			)    
			
			
			VAR _debet_mutatie_subtotaal  =
			CALCULATE(
			    SUM( Journaalregels[Debetbedrag] )
			    , 'Journaalregels'[Bankafschriftboeking type] = "Tegenrekening"
			    , 'Journaalregels'[Bankafschriftboeking Ja/Nee] = "Ja"
			    ,ALL('NR - Cashflow categorien DQ')
			) 
			
			  
			VAR _forecast_mutatie_subtotaal =
			IF(
			    MAX( Kalender[Datum] ) <= MAX( 'Kalender standdatums'[Einddatum Maand]  )
			    , CALCULATE(
			        SUM('NR - Cashflow forecastregels DQ'[waarde])
			        , ALL( 'NR - Cashflow categorien DQ' )
			    )
			    ,BLANK()
			 ) 
			
			VAR result =
			    IF(
			        _subtotaal_mutatie_selected
			        ,IF(
			            _credit_mutatie_subtotaal - _debet_mutatie_subtotaal>0
			            ,1
			            ,IF(
			                _credit_mutatie_subtotaal - _debet_mutatie_subtotaal<0
			                ,0
			                ,BLANK()
			            )
			        )
			        ,BLANK()
			    )
			    
			RETURN
			  result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Cashflow forecast

	measure 'Subtotaal codering mutatie actual en forecast CoCFC' = ```
			
			VAR _subtotaal_mutatie_selected     = SELECTEDVALUE('NR - cashflow categorien DQ'[Categorie]) = "Mutatie op bank"
			var __geselec_maandindex = max('Kalender standdatums'[Maand index])
			VAR _credit_mutatie_subtotaal_tot_standdatum =
			CALCULATE(
			    SUM( Journaalregels[Creditbedrag] )
			    , 'Journaalregels'[Bankafschriftboeking type] = "Tegenrekening"
			    , 'Journaalregels'[Bankafschriftboeking Ja/Nee] = "Ja"
			    ,ALL('NR - Cashflow categorien DQ')
			    , Kalender[Maand index]  <= __geselec_maandindex
			)
			
			
			VAR _debet_mutatie_subtotaal_tot_standdatum  =
			 CALCULATE(
			     SUM( Journaalregels[Debetbedrag] )
			    , 'Journaalregels'[Bankafschriftboeking type] = "Tegenrekening"
			    , 'Journaalregels'[Bankafschriftboeking Ja/Nee] = "Ja"
			    , ALL( 'NR - Cashflow categorien DQ' )
			    , Kalender[Maand index]  <= __geselec_maandindex
			)
			
			
			VAR _forecast_mutatie_subtotaal_na_standdatum =
			CALCULATE(
			    SUM( 'NR - Cashflow forecastregels DQ'[waarde])
			    , ALL( 'NR - Cashflow categorien DQ')
			    , Kalender[Maand index]  > __geselec_maandindex
			)
			
			
			VAR result =
			    IF(
			        _subtotaal_mutatie_selected
			        ,IF(
			            _credit_mutatie_subtotaal_tot_standdatum - _debet_mutatie_subtotaal_tot_standdatum + _forecast_mutatie_subtotaal_na_standdatum  >0
			            ,1
			            ,IF(
			                _credit_mutatie_subtotaal_tot_standdatum - _debet_mutatie_subtotaal_tot_standdatum + _forecast_mutatie_subtotaal_na_standdatum<0
			                ,0
			                ,BLANK()
			            )
			        )
			        ,BLANK()
			    )
			    
			RETURN
			  result
			```
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Cashflow forecast

	measure 'Actual beginsaldo' = ```
			
			VAR _debet_bank_beginsaldo =
			CALCULATE(
			    SUM( Journaalregels[Debetbedrag] )
			    , 'Journaalregels'[Bankafschriftboeking type] = "Bank"
			    , 'Journaalregels'[Bankafschriftboeking Ja/Nee] = "Ja"
			        , ALL( 'NR - Cashflow categorien DQ')
			        , FILTER(
			            ALL( Kalender[Datum] )
			            , Kalender[Datum] < MIN( Kalender[Datum] )
			            && Kalender[Datum] <= MAX( 'Kalender standdatums'[Einddatum Maand] )
			        )
			    , FILTER(
			        ALL(  'Kalender standdatums')
			        , 'Kalender standdatums'[Einddatum Maand] <= MAX( 'Kalender standdatums'[Einddatum Maand] )
			    )
			)
			        
			        
			    VAR _credit_bank_beginsaldo =
			CALCULATE(
			    SUM( Journaalregels[Creditbedrag] )
			    , 'Journaalregels'[Bankafschriftboeking type] = "Bank"
			    , 'Journaalregels'[Bankafschriftboeking Ja/Nee] = "Ja"
			        , ALL( 'NR - Cashflow categorien DQ')
			        , FILTER(
			            ALL( Kalender[Datum] )
			            , Kalender[Datum] < MIN( Kalender[Datum] )
			            && Kalender[Datum] <= MAX( 'Kalender standdatums'[Einddatum Maand] )
			        )
			    , FILTER(
			        ALL(  'Kalender standdatums')
			        , 'Kalender standdatums'[Einddatum Maand] <= MAX( 'Kalender standdatums'[Einddatum Maand] )
			    )
			)
			    
			    VAR Result = _debet_bank_beginsaldo- _credit_bank_beginsaldo
			    
			    
			    
			    RETURN  
			        result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Cashflow forecast

	measure 'Actual eindsaldo' = ```
			
			VAR _debet_bank_eindsaldo =
			CALCULATE(
			SUM( Journaalregels[Debetbedrag] )
			, 'Journaalregels'[Bankafschriftboeking type] = "Bank"
			, 'Journaalregels'[Bankafschriftboeking Ja/Nee] = "Ja"
			    , ALL( 'NR - Cashflow categorien DQ' )
			    , FILTER(
			        ALL(Kalender[Datum])
			        ,Kalender[Datum]<=MAX(Kalender[Datum])
			        && Kalender[Datum]<=MAX( 'Kalender standdatums'[Einddatum Maand]  )
			    )
			, FILTER(
			    ALL(  'Kalender standdatums')
			    , 'Kalender standdatums'[Einddatum Maand] < MAX( 'Kalender standdatums'[Einddatum Maand] )
			)
			)
			    
			    
			VAR _credit_bank_eindsaldo =
			CALCULATE(
			SUM( Journaalregels[Creditbedrag] )
			, 'Journaalregels'[Bankafschriftboeking type] = "Bank"
			, 'Journaalregels'[Bankafschriftboeking Ja/Nee] = "Ja"
			    ,ALL('NR - Cashflow categorien DQ' )
			    ,FILTER(
			        ALL(Kalender[Datum])
			        ,Kalender[Datum]<=MAX(Kalender[Datum])
			        && Kalender[Datum]<=MAX( 'Kalender standdatums'[Einddatum Maand] )
			    )
			    , FILTER(
			        ALL('Kalender standdatums')
			        , 'Kalender standdatums'[Einddatum Maand]  < MAX( 'Kalender standdatums'[Einddatum Maand]  )        
			   )
			)
			
			VAR Result = _debet_bank_eindsaldo- _credit_bank_eindsaldo
			
			
			
			RETURN  
			    result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Cashflow forecast

	measure 'Forecast beginsaldo' =
			
			IF(
			    MAX( Kalender[Datum]  ) > MAX( 'Kalender standdatums'[Einddatum Maand] )
			    , CALCULATE(
			        SUM(  'NR - Cashflow forecastregels DQ'[waarde] )
			        , FILTER(
			            ALL(  Kalender[Datum])
			            ,  Kalender[Datum] < MIN(  Kalender[Datum] )
			            &&  Kalender[Datum] > MAX( 'Kalender standdatums'[Einddatum Maand] )
			        )
			        , ALL('NR - Cashflow categorien DQ' )
			    )
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Cashflow forecast

	measure 'Forecast eindsaldo' =
			
			IF(
			    MAX( Kalender[Datum]  ) > MAX( 'Kalender standdatums'[Einddatum Maand] )
			    , CALCULATE(
			        SUM(  'NR - Cashflow forecastregels DQ'[waarde] )
			        , FILTER(
			            ALL( Kalender[Datum] )
			            ,Kalender[Datum] <= MAX(Kalender[Datum])
			            && Kalender[Datum]> MAX( 'Kalender standdatums'[Einddatum Maand] )
			        )
			        , ALL('NR - Cashflow categorien DQ')
			    )
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Cashflow forecast

	measure 'Actual en forecast beginsaldo' = [Actual beginsaldo]+[Forecast beginsaldo]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Cashflow forecast

	measure 'Actual en forecast eindsaldo' = [Actual eindsaldo]+[Forecast eindsaldo]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Cashflow forecast

	measure 'Actual mutatie' =
			
			VAR _credit_mutatie_subtotaal =
			CALCULATE(
			    SUM( Journaalregels[Creditbedrag] )
			    , 'Journaalregels'[Bankafschriftboeking type] = "Tegenrekening"
			    , 'Journaalregels'[Bankafschriftboeking Ja/Nee] = "Ja"
			    , ALL( 'NR - Cashflow categorien DQ')
			)
			
			VAR _debet_mutatie_subtotaal  =
			CALCULATE(
			SUM( Journaalregels[Debetbedrag] )
			, 'Journaalregels'[Bankafschriftboeking type] = "Tegenrekening"
			, 'Journaalregels'[Bankafschriftboeking Ja/Nee] = "Ja"
			    , ALL( 'NR - Cashflow categorien DQ' )
			)
			
			VAR result = _credit_mutatie_subtotaal - _debet_mutatie_subtotaal
			
			RETURN
			    result
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Cashflow forecast

	measure 'Actual mutatie tot en met standdatum' = ```
			
			VAR _credit_mutatie_subtotaal =
			IF(
			    MAX( Kalender[Datum] ) <= MAX( 'Kalender standdatums'[Einddatum Maand] )
			    , CALCULATE(
			        SUM( Journaalregels[Creditbedrag] )
			        , 'Journaalregels'[Bankafschriftboeking type] = "Tegenrekening"
			        , 'Journaalregels'[Bankafschriftboeking Ja/Nee] = "Ja"
			        , ALL( 'NR - Cashflow categorien DQ' )
			    )
			    , BLANK()
			)
			
			
			VAR _debet_mutatie_subtotaal  =
			IF(
			    MAX( Kalender[Datum] ) <= MAX( 'Kalender standdatums'[Einddatum Maand] )
			    , CALCULATE(
			        SUM( Journaalregels[Debetbedrag] )
			        , 'Journaalregels'[Bankafschriftboeking type] = "Tegenrekening"
			        , 'Journaalregels'[Bankafschriftboeking Ja/Nee] = "Ja"  
			        , ALL('NR - Cashflow categorien DQ')
			    )
			    , BLANK()
			)
			
			VAR result = _credit_mutatie_subtotaal - _debet_mutatie_subtotaal
			
			RETURN
			    result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Cashflow forecast

	measure 'Forecast mutatie cashflow' =
			
			CALCULATE(
			    SUM(  'NR - Cashflow forecastregels DQ'[waarde] )
			    , ALL( 'NR - Cashflow categorien DQ' )
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Cashflow forecast

	measure 'Forecast mutatie vanaf standdatum' =
			
			IF(
			    MAX(  Kalender[Datum]  ) > MAX( 'Kalender standdatums'[Einddatum Maand]  )
			    , CALCULATE(
			        SUM(  'NR - Cashflow forecastregels DQ'[waarde] )
			        , ALL( 'NR - Cashflow categorien DQ' )
			    )
			    ,BLANK()
			 )
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Cashflow forecast

	measure 'laatste standdatum' = MAX( 'Kalender standdatums'[Standdatum] )
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Cashflow forecast

	measure 'Codering voor achtergrond' = ```
			
			VAR _mutatie_selected               = SELECTEDVALUE('NR - cashflow categorien DQ'[Classificatie]) = "Mutatie"
			VAR _beginsaldo_selected            = SELECTEDVALUE('NR - cashflow categorien DQ'[Categorie]) = "Beginsaldo"
			VAR _eindsaldo_selected             = SELECTEDVALUE('NR - cashflow categorien DQ'[Categorie]) = "Eindsaldo"
			VAR _subtotaal_mutatie_selected     = SELECTEDVALUE('NR - cashflow categorien DQ'[Categorie]) = "Mutatie op bank"
			VAR _openstaand_selected  = SELECTEDVALUE('NR - cashflow categorien DQ'[Categorie]) = "Openstaande bankafschriften*"
			
			VAR _actual_vs_forecast_codering = 
			IF(
			    MAX(Kalender[Datum])<=MAX( 'Kalender standdatums'[Standdatum])
			    ,10
			    ,11
			)
			
			
			VAR result =
			    SWITCH(
			        TRUE
			        ,_beginsaldo_selected,MAX('NR - Cashflow categorien DQ'[Classificatie nummer])
			        ,_eindsaldo_selected,MAX('NR - Cashflow categorien DQ'[Classificatie nummer])
			        ,_openstaand_selected,MAX('NR - Cashflow categorien DQ'[Classificatie nummer])
			        ,_mutatie_selected,_actual_vs_forecast_codering
			        ,_subtotaal_mutatie_selected,MAX('NR - Cashflow categorien DQ'[Classificatie nummer])
			    )
			    
			    
			RETURN
			 result
			```
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Cashflow forecast

	measure 'Geselecteerde standdatum projecten' = ```
			 "standdatum:"&FORMAT(MAX(Kalender[Datum]),"dd-mm-yyyy")
			```
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Algemeen

	measure 'Definitieve kostprijs (t/m standdatum)' =
			
			CALCULATE(
			    SUM('Project kosten en geboekte uren'[Kostprijs]),
			    'Project kosten en geboekte uren'[Kostenstatus] = "Definitief"
			    , FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] <= MAX(Kalender[Datum])
			    )
			)
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectwaardering

		annotation PBI_FormatHint = {"currencyCulture":"nl-NL"}

	measure 'Definitieve kostprijs regie (t/m standdatum)' =
			
			CALCULATE(
			    SUM('Project kosten en geboekte uren'[Kostprijs]),
			    'Project kosten en geboekte uren'[Kostenstatus] = "Definitief"
			    ,'Project kosten en geboekte uren'[Factureerstatus] IN {"Nog te factureren","Gefactureerd"}
			    , FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] <= MAX(Kalender[Datum])
			    )
			)
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectwaardering

		annotation PBI_FormatHint = {"currencyCulture":"nl-NL"}

	measure 'Definitieve kostprijs vaste prijs (t/m standdatum)' =
			
			CALCULATE(
			    SUM('Project kosten en geboekte uren'[Kostprijs]),
			    'Project kosten en geboekte uren'[Kostenstatus] = "Definitief"
			    ,NOT ( 'Project kosten en geboekte uren'[Factureerstatus] ) IN { "Nog te factureren", "Gefactureerd" }
			    , FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] <= MAX(Kalender[Datum])
			    )
			)
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectwaardering

		annotation PBI_FormatHint = {"currencyCulture":"nl-NL"}

	measure 'Historische omzet (t/m standdatum)' =
			
			CALCULATE(
			    SUM('Project omzet'[Bedrag])
			    ,'Project omzet'[Opbrengststatus] = "Definitief"
			    , FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] <= MAX(Kalender[Datum])
			    )
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectwaardering

	measure 'Historische omzet order (t/m standdatum)' =
			
			CALCULATE(
			    SUM('Project omzet'[Bedrag])
			    ,'Project omzet'[Opbrengststatus] = "Definitief"
			     ,'Project omzet'[Vanuit order Ja/Nee] = "Ja"
			    , FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] <= MAX(Kalender[Datum])
			    )
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectwaardering

	measure 'Historische omzet regie (t/m standdatum)' =
			
			CALCULATE(
			    SUM('Project omzet'[Bedrag])
			    ,'Project omzet'[Opbrengststatus] = "Definitief"
			    ,'Project omzet'[Vanuit order Ja/Nee] = "Nee"
			    , FILTER(
			        ALL( Kalender )
			       , Kalender[Datum] <= MAX(Kalender[Datum])
			    )
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectwaardering

	measure 'Projectjournalisering kosten (t/m standdatum)' =
			
			/*
			LET OP; De [Projectjournalisering kosten!] is op basis van de verrekenprijs. De dekkingen worden apart geboekt (Credit) maar zonder projectkey. Daarom niet te matchen met definitieve kostprijs uit de subadministratie.
			Wel met de [Definitieve verrekenprijs]
			*/
			
			VAR _projectkosten =
			CALCULATE(
			    SUM('Project journaalregels'[Bedrag])
			    ,'Project journaalregels'[Debet/Credit] = "D"
			    ,Rubrieken[Type] = "W"
			    ,'Project journaalregels'[BoxNummer] = "1"
			    , FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] <= MAX(Kalender[Datum])
			    )
			)
			
			
			RETURN
			    _projectkosten
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectwaardering

	measure 'Projectjournalisering opbrengsten (t/m standdatum)' =
			
			VAR _projectopbrengsten =
			CALCULATE(
			    SUM('Project journaalregels'[Bedrag])
			    ,'Project journaalregels'[Debet/Credit] = "C"
			    ,Rubrieken[Type] = "W"
			    , FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] <= MAX(Kalender[Datum])
			    )
			)
			
			
			RETURN
			    _projectopbrengsten
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectwaardering

	measure 'Projectjournalisering projectwaarderingen (t/m standdatum)' =
			
			CALCULATE(
			        [Projectjournalisering projectwaarderingen]
			    , FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] <= MAX(Kalender[Datum])
			    )
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectwaardering

	measure 'Melding projectstand Professional' = "Projectstand Professional per "&FORMAT( MAX( Kalender[Datum]), "dd-MM-yyyy" )&" ("&DISTINCTCOUNT(Projecten[project])&" projecten)"
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Algemeen

	measure 'Melding projectstand Enterprise' = "Projectstand Enterprise per "&FORMAT( MAX( Kalender[Datum]), "dd-MM-yyyy" )&" ("&DISTINCTCOUNT(Projecten[project])&" projecten)"
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Algemeen

	measure 'Melding projectstand' = "Projectstand per "&FORMAT( MAX( Kalender[Datum] ), "dd-MM-yyyy" )&" ("&DISTINCTCOUNT(Projecten[project])&" projecten)"
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Algemeen

	measure 'Melding projecten' = DISTINCTCOUNT(Projecten[HoofdProjectKey])&" hoofdprojecten met datumselectie: "&FORMAT(MIN(Kalender[Datum]), "dd-MM-yyyy" )&" t/m "&FORMAT(MAX( Kalender[Datum] ), "dd-MM-yyyy" )
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Algemeen

	/// --Omschrijving--
	/// Gerealiseerde uren tot en met geselecteerde standdatum. 
	/// 
	/// LET OP; kan in combinatie met kalender tabel/filter ook gefilterd zijn.
	/// 
	/// 
	/// --DAX--
	/// CALCULATE(
	///     SUM('Geboekte Uren'[Aantal])
	///     ,NOT(ISBLANK('Geboekte Uren'[TaakKey]))
	///     ,'Geboekte Uren'[Uitvoeringsdatum]<=MAX('Standdatums'[standdatum])
	/// )
	measure 'Gerealiseerde uren historisch' =
			
			CALCULATE(
			    SUM('Geboekte uren'[Aantal])
			    ,'Geboekte uren'[verlofsaldoboeking] = "Nee"
			    ,'Geboekte uren'[Uitvoeringsdatum]<=MAX(kalender[standdatum])
			)
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Gerealiseerde uren

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Gerealiseerde uren' =
			
			CALCULATE(
			    SUM('Geboekte uren'[Aantal])
			    ,'Geboekte uren'[verlofsaldoboeking] = "Nee"
			)
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Gerealiseerde uren

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Gerealiseerde uren projecten' = ```
			
			CALCULATE(
			    SUM( 'Project kosten en geboekte uren'[Aantal] )
			    ,NOT(ISBLANK('Project kosten en geboekte uren'[TaakKey]))
			)
			
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid

		annotation PBI_FormatHint = {"isDecimal":true}

	/// --Omschrijving--
	/// Gerealiseerde uren tot en met geselecteerde standdatum. 
	/// 
	/// LET OP; kan in combinatie met kalender tabel/filter ook gefilterd zijn.
	/// 
	/// 
	/// --DAX--
	/// CALCULATE(
	///     SUM('Geboekte Uren'[Aantal])
	///     ,NOT(ISBLANK('Geboekte Uren'[TaakKey]))
	///     ,'Geboekte Uren'[Uitvoeringsdatum]<=MAX('Standdatums'[standdatum])
	/// )
	measure 'Gerealiseerde uren historisch projecten' = ```
			
			CALCULATE(
			    SUM( 'Project kosten en geboekte uren'[Aantal] )
			    ,NOT(ISBLANK('Project kosten en geboekte uren'[TaakKey]))
			    , Projecten[Status] = "Historisch"
			)
			
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Calculatie kostprijs arbeid montage' =
			
			CALCULATE(
			    SUM('Calculatie kostenregels'[Kostprijs])
			    ,Kostensoorten[Categorie] = "Arbeid"
			    ,'Calculatie kostenregels'[Calculatiestatus] = "Opdracht"
			    ,'NR - Taakgroepen DQ'[Taakgroep] = "Montage"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie

	measure 'Calculatie kostprijs arbeid projectgebonden' =
			
			CALCULATE(
			    SUM('Calculatie kostenregels'[Kostprijs])
			    ,Kostensoorten[Categorie] = "Arbeid"
			    ,'Calculatie kostenregels'[Calculatiestatus] = "Opdracht"
			    ,'NR - Taakgroepen DQ'[Taakgroep] = "Projectgebonden"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie

	measure 'Calculatie verrekenprijs inkoop' =
			
			CALCULATE(
			    SUM( 'Calculatie kostenregels'[Verrekenprijs] )
			    ,Kostensoorten[Categorie] <> "Arbeid"
			    ,'Calculatie kostenregels'[Calculatiestatus] = "Opdracht"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie

	measure 'Calculatie verrekenprijs arbeid montage' =
			
			CALCULATE(
			    SUM( 'Calculatie kostenregels'[Verrekenprijs] )
			    ,Kostensoorten[Categorie] = "Arbeid"
			    ,'Calculatie kostenregels'[Calculatiestatus] = "Opdracht"
			    ,'NR - Taakgroepen DQ'[Taakgroep] = "Montage"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie

	measure 'Calculatie verrekenprijs arbeid projectgebonden' =
			
			CALCULATE(
			    SUM( 'Calculatie kostenregels'[Verrekenprijs] )
			    ,Kostensoorten[Categorie] = "Arbeid"
			    ,'Calculatie kostenregels'[Calculatiestatus] = "Opdracht"
			    ,'NR - Taakgroepen DQ'[Taakgroep] = "Projectgebonden"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie

	measure 'Definitieve kostprijs arbeid montage' =
			
			CALCULATE(
			    SUM('Project kosten en geboekte uren'[Kostprijs])
			    ,'Project kosten en geboekte uren'[Kostenstatus] = "Definitief"
			    ,Kostensoorten[Categorie] = "Arbeid"
			    ,'NR - Taakgroepen DQ'[Taakgroep] = "Montage"
			)
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

		annotation PBI_FormatHint = {"currencyCulture":"nl-NL"}

	measure 'Definitieve kostprijs arbeid projectgebonden' =
			
			CALCULATE(
			    SUM('Project kosten en geboekte uren'[Kostprijs])
			    ,'Project kosten en geboekte uren'[Kostenstatus] = "Definitief"
			    ,Kostensoorten[Categorie] = "Arbeid"
			    ,'NR - Taakgroepen DQ'[Taakgroep] = "Projectgebonden"
			)
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

		annotation PBI_FormatHint = {"currencyCulture":"nl-NL"}

	measure 'Onverwerkte verrekenprijs arbeid montage' = ```
			
			CALCULATE(
			    SUM('Project kosten en geboekte uren'[Verrekenprijs])
			    ,'Project kosten en geboekte uren'[Kostenstatus] = "Nog te verwachten"
			    ,Kostensoorten[Categorie] = "Arbeid"
			    ,'NR - Taakgroepen DQ'[Taakgroep] = "Montage"
			)
			
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

	measure 'Onverwerkte verrekenprijs arbeid projectgebonden' = ```
			
			CALCULATE(
			    SUM('Project kosten en geboekte uren'[Verrekenprijs])
			    ,'Project kosten en geboekte uren'[Kostenstatus] = "Nog te verwachten"
			    ,Kostensoorten[Categorie] = "Arbeid"
			    ,'NR - Taakgroepen DQ'[Taakgroep] = "Projectgebonden"
			)
			
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

	measure 'Einde boekdatum' = ```
			
			    // einddatum op basis van laatste kosten en/of opbrengsten
			   MAX(Kalender[Datum])
			
			```
		formatString: Short Date
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Meldingen

	measure 'Start boekdatum' = ```
			
			    // einddatum op basis van laatste kosten en/of opbrengsten
			   MIN(Kalender[Datum])
			
			```
		formatString: Short Date
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Meldingen

	measure 'Verzoek Kosten arbeid montage' = ```
			
			VAR result = 
			CALCULATE(
			     SUM('NR - Projectbudgetverzoekregels DQ'[Kostprijs])
			    ,'NR - Projectbudgetverzoekregels DQ'[Categorie] = "Arbeid"
			    ,'NR - Taakgroepen DQ'[Taakgroep] = "Montage"
			    
			) 
			    
			RETURN
			    result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budgetverzoek o.b.v. Budget Verzoek App

	measure 'Verzoek Kosten arbeid projectgebonden' = ```
			
			VAR result = 
			CALCULATE(
			     SUM('NR - Projectbudgetverzoekregels DQ'[Kostprijs])
			    ,'NR - Projectbudgetverzoekregels DQ'[Categorie] = "Arbeid"
			    ,'NR - Taakgroepen DQ'[Taakgroep] = "Projectgebonden"
			) 
			    
			RETURN
			    result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budgetverzoek o.b.v. Budget Verzoek App

	measure 'Definitieve verrekenprijs inkoop' = ```
			
			CALCULATE(
			    SUM('Project kosten en geboekte uren'[Verrekenprijs])
			    ,'Project kosten en geboekte uren'[Kostenstatus] = "Definitief"
			    , Kostensoorten[Categorie] <> "Arbeid"
			)
			
			```
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

		annotation PBI_FormatHint = {"currencyCulture":"nl-NL"}

	measure 'Definitieve verrekenprijs arbeid montage' = ```
			
			CALCULATE(
			    SUM('Project kosten en geboekte uren'[Verrekenprijs])
			    ,'Project kosten en geboekte uren'[Kostenstatus] = "Definitief"
			    ,Kostensoorten[Categorie] = "Arbeid"
			    ,'NR - Taakgroepen DQ'[Taakgroep] = "Montage"
			)
			
			```
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

		annotation PBI_FormatHint = {"currencyCulture":"nl-NL"}

	measure 'Definitieve verrekenprijs arbeid projectgebonden' = ```
			
			CALCULATE(
			    SUM('Project kosten en geboekte uren'[Verrekenprijs])
			    ,'Project kosten en geboekte uren'[Kostenstatus] = "Definitief"
			    ,Kostensoorten[Categorie] = "Arbeid"
			    ,'NR - Taakgroepen DQ'[Taakgroep] = "Projectgebonden"
			)
			
			```
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten

		annotation PBI_FormatHint = {"currencyCulture":"nl-NL"}

	measure 'Projectgebonden uren definitief' =
			
			CALCULATE(
			    SUM('Project kosten en geboekte uren'[Aantal])
			    ,'Project kosten en geboekte uren'[Kostenstatus] = "Definitief"
			    ,'NR - Taakgroepen DQ'[Taakgroep] = "Projectgebonden"
			)
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid

	measure 'Montage uren definitief' = ```
			
			CALCULATE(
			    SUM('Project kosten en geboekte uren'[Aantal])
			    ,'Project kosten en geboekte uren'[Kostenstatus] = "Definitief"
			    ,'NR - Taakgroepen DQ'[Taakgroep] = "Montage"
			)
			
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid

	measure 'Projectgebonden uren onverwerkt' = ```
			
			CALCULATE(
			    SUM('Project kosten en geboekte uren'[Aantal])
			    ,'Project kosten en geboekte uren'[Kostenstatus] = "Nog te verwachten"
			    ,'NR - Taakgroepen DQ'[Taakgroep] = "Projectgebonden"
			     
			)
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid

	measure 'Montage uren onverwerkt' = ```
			
			CALCULATE(
			    SUM('Project kosten en geboekte uren'[Aantal])
			    ,'Project kosten en geboekte uren'[Kostenstatus] = "Nog te verwachten"
			    ,'NR - Taakgroepen DQ'[Taakgroep] = "Montage"
			)
			
			
			```
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid

	measure 'Start boekdatum projectvoortgang app' =
			
			IF(
			     MAX( 'Bestekparagrafen'[Eerste bestekparagraafKey hoofdproject] ) = "Ja" || MAX('Bestekparagrafen'[Eerste bestekparagraafKey project niveau 2] ) = "Ja"
			    , MIN('kalender'[Datum])
			    , BLANK()
			)
		formatString: dd-mm-yyyy
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectvoortgang App

	measure 'Eind boekdatum projectvoortgang app' =
			
			IF(
			    MAX( 'Bestekparagrafen'[Eerste bestekparagraafKey hoofdproject] ) = "Ja" || MAX('Bestekparagrafen'[Eerste bestekparagraafKey project niveau 2] ) = "Ja"
			    , MAX('kalender'[Datum])
			    , BLANK()
			)
		formatString: dd-mm-yyyy
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectvoortgang App

	measure 'Klantnummer projectvoortgang app' =
			
			IF(
			     MAX( 'Bestekparagrafen'[Eerste bestekparagraafKey hoofdproject] ) = "Ja" || MAX('Bestekparagrafen'[Eerste bestekparagraafKey project niveau 2] ) = "Ja"
			    , [KlantnummerDWH]
			    , BLANK()
			)
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectvoortgang App

	measure 'Hoogste projectniveau voortgang app' =
			
			IF(
			    MAX( 'Bestekparagrafen'[Eerste bestekparagraafKey hoofdproject] ) = "Ja" || MAX('Bestekparagrafen'[Eerste bestekparagraafKey project niveau 2] ) = "Ja"
			    , MIN(Projecten[Niveau])
			    , BLANK()
			)
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectvoortgang App

	measure 'Geselecteerde maandindex standdatum kalender' = MAX('Kalender standdatums'[Maand index])
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Algemeen

	measure 'Melding periode cumulatief LY o.b.v. standdatum' =
			
			"Periode: "
			&FORMAT(DATE(YEAR(MIN('Kalender standdatums'[Begindatum Maand]))-1,MONTH(MIN('Kalender standdatums'[Begindatum Maand])),DAY(MIN('Kalender standdatums'[Begindatum Maand]))),"dd-mm-yyyy")
			&" t/m "
			&FORMAT(DATE(YEAR(MAX('Kalender standdatums'[Einddatum Maand]))-1,MONTH(MAX('Kalender standdatums'[Einddatum Maand])),DAY(MAX('Kalender standdatums'[Einddatum Maand]))),"dd-mm-yyyy")
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Algemeen

	measure 'Melding periode cumulatief o.b.v. standdatum' =
			
			"Periode: "
			&FORMAT(DATE( YEAR( MIN( 'Kalender standdatums'[Begindatum Maand] ) ), 1, 1 ),"dd-mm-yyyy")
			&" t/m "
			&FORMAT(MAX('Kalender standdatums'[Einddatum Maand]),"dd-mm-yyyy")
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Algemeen

	measure 'Melding resultaat cumulatief o.b.v. standdatum' =
			
			"Resultaat cumulatief in periode: "
			&FORMAT(MIN('Kalender'[Datum]),"dd-mm-yyyy")
			&" t/m "
			&FORMAT(MAX('Kalender standdatums'[Einddatum Maand]),"dd-mm-yyyy")
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Algemeen

	measure 'Melding resultaat geselecteerde maand o.b.v. standdatum' =
			
			"Resultaat in maand: "
			&FORMAT(MIN('Kalender standdatums'[Begindatum Maand]),"dd-mm-yyyy")
			&" t/m "
			&FORMAT(MAX('Kalender standdatums'[Einddatum Maand]),"dd-mm-yyyy")
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Algemeen

	measure 'Verschil debet-credit balans CoA o.b.v. standdatum' = [Actual debet-YTD Balans CoA o.b.v. standdatum]-[Actual credit-YTD Balans CoA o.b.v. standdatum]
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA Balans

	measure 'Verschil credit-debet balans CoA o.b.v. standdatum' = [Actual credit-YTD Balans CoA o.b.v. standdatum]-[Actual debet-YTD Balans CoA o.b.v. standdatum]
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA Balans

	measure 'CoA balans YTD o.b.v. standdatum' = ```
			
			VAR _classification      = SELECTEDVALUE('NR - CoA balans schema'[Classificatie_type])
			VAR _Is_subtotaal        = _classification = "Subtotaal"
			VAR _is_activa           = _classification = "Activa"
			VAR _is_passiva          = _classification = "Passiva"
			
			VAR _correctSubtotalLevel_activa   = SELECTEDVALUE('NR - CoA balans schema'[Niveau1]) = "Activa" && ISINSCOPE('NR - CoA balans schema'[Niveau1]) && NOT(ISINSCOPE('NR - CoA balans schema'[Niveau2]))
			VAR _correctSubtotalLevel_passiva  = SELECTEDVALUE('NR - CoA balans schema'[Niveau1]) = "Passiva" && ISINSCOPE('NR - CoA balans schema'[Niveau1]) && NOT(ISINSCOPE('NR - CoA balans schema'[Niveau2]))
			
			VAR _is_legeregel           = _classification  = "Leeg" && ISINSCOPE('NR - CoA balans schema'[Niveau1]) && NOT(ISINSCOPE('NR - CoA balans schema'[Niveau2]))
			 
			VAR _stand_Balans         = [Verschil debet-credit balans CoA o.b.v. standdatum] -- Reguliere mutaties op rubriek--
			
			VAR _subtotaalWaarde_activa =
			    CALCULATE(
			       [Verschil debet-credit balans CoA o.b.v. standdatum]
			        , FILTER(
			            ALL( 'NR - CoA balans schema' )
			            , 'NR - CoA balans schema'[Classificatie_type] = "Activa"
			        )
			    )
			 
			VAR _subtotaalWaarde_passiva =
			    CALCULATE(
			        [Verschil credit-debet balans CoA o.b.v. standdatum]
			        , FILTER(
			            ALL( 'NR - CoA balans schema' )
			            , 'NR - CoA balans schema'[Classificatie_type] = "Passiva"
			        )
			    ) 
			
			VAR result =   
			SWITCH(
			        TRUE
			        ,_is_legeregel,0
			        ,NOT ( _is_subtotaal ) && _is_activa,[Verschil debet-credit balans CoA o.b.v. standdatum]
			        ,NOT ( _is_subtotaal ) && _is_passiva,[Verschil credit-debet balans CoA o.b.v. standdatum]
			        ,_correctSubtotalLevel_activa ,_subtotaalWaarde_activa
			        ,_correctSubtotalLevel_passiva,_subtotaalWaarde_passiva 
			    )
			
			VAR result2 =   
			IF(
			    _is_legeregel
			    , 0
			    , IF(
			        NOT ( _is_subtotaal )
			        , _stand_Balans
			        , IF(
			            _correctSubtotalLevel_activa
			            , _subtotaalWaarde_activa
			            , IF(
			                _correctSubtotalLevel_passiva
			                , _subtotaalWaarde_passiva
			            )
			        )
			    )
			)
			
			RETURN
			    result
			```
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA Balans

	measure 'Actual debet-YTD Balans CoA o.b.v. standdatum' =
			
			var geselecteerde_einddatum = MAX('Kalender standdatums'[Einddatum Maand])
			var StartOfYear_geselecteerde_einddatum = Date(YEAR(geselecteerde_einddatum),1,1)
			return
			CALCULATE(
			    SUM('Journaalregels'[Debetbedrag])
			    ,CROSSFILTER ( Rubrieken[RubriekKey], Grootboekrekeningen[RubriekKey], BOTH )
			    ,FILTER(
			        ALL('Kalender')
			        ,'Kalender'[Datum]>=StartOfYear_geselecteerde_einddatum &&
			        'Kalender'[Datum]<=geselecteerde_einddatum
			    )
			    ,Rubrieken[Type] = "B"
			)
			-[Debet eliminatie Balans]
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA Balans

	measure 'Actual credit-YTD Balans CoA o.b.v. standdatum' =
			
			var geselecteerde_einddatum = MAX('Kalender standdatums'[Einddatum Maand])
			var StartOfYear_geselecteerde_einddatum = Date(YEAR(geselecteerde_einddatum),1,1)
			VAR credit_YTD =
			CALCULATE(
			    SUM('Journaalregels'[Creditbedrag])
			    ,FILTER(
			        ALL('Kalender')
			        ,'Kalender'[Datum]>=StartOfYear_geselecteerde_einddatum &&
			        'Kalender'[Datum]<=geselecteerde_einddatum
			    )
			    ,Rubrieken[Type] = "B"
			)
			VAR credit_YTD_eliminatie =
			CALCULATE(
			    SUM( 'Eliminatie journaalregels'[Credit] )
			    ,FILTER(
			        ALL('Kalender')
			        ,'Kalender'[Datum]>=StartOfYear_geselecteerde_einddatum &&
			        'Kalender'[Datum]<=geselecteerde_einddatum
			    )
			    , 'Eliminatie journaalregels'[Rubriektype] = "B"
			)
			
			VAR result = credit_YTD - credit_YTD_eliminatie
			
			
			
			RETURN
			    result
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA Balans

	measure '% standmaand t.o.v. standmaand LY' = DIVIDE([Delta standmaand - standmaand LY],[CoA mutatie in de standmaand o.b.v. standdatum])
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Ratio

	measure 'CoA actual LY in standmaand o.b.v. standdatum' = ```
			
			VAR _classification         = SELECTEDVALUE('NR - CoA schema'[Classificatie type])
			VAR _is_subtotaal           = _classification = "Subtotaal"
			VAR _is_geen_omzet          = _classification <> "Omzet" 
			VAR _correctSubtotalLevel   = _is_subtotaal                && ISINSCOPE('NR - CoA schema'[Niveau1]) && NOT(ISINSCOPE('NR - CoA schema'[Niveau2]))
			VAR _is_legeregel           = _classification = "Leeg"    && ISINSCOPE('NR - CoA schema'[Niveau1]) && NOT(ISINSCOPE('NR - CoA schema'[Niveau2]))
			VAR _einddatum_gesecteerde_standmaand = DATE(YEAR(MAX('Kalender standdatums'[Einddatum Maand]))-1,MONTH(MAX('Kalender standdatums'[Einddatum Maand])),DAY(MAX('Kalender standdatums'[Einddatum Maand])))
			VAR _begindatum_gesecteerde_standmaand = DATE(YEAR(MIN('Kalender standdatums'[Begindatum Maand]))-1,MONTH(MIN('Kalender standdatums'[Begindatum Maand])),DAY(MIN('Kalender standdatums'[Begindatum Maand])))
			
			
			VAR _eerste_kalenderdatum =
			CALCULATE(
			    MIN(Kalender[Datum])
			    ,ALL('Kalender standdatums')
			    , FILTER(
			        ALL( Kalender[Datum] )
			        , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			        && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			    )
			)
			
			VAR _credit_eliminatie_Resultaatrekening = 
			CALCULATE(
			    SUM( 'Eliminatie journaalregels'[Credit] )
			    , 'Eliminatie journaalregels'[Rubriektype] = "W"
			    ,NOT ( ISBLANK('NR - CoA mapping DQ'[CoA_code] ) )
			    ,FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			        && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			    )
			) 
			
			
			VAR _credit_exploitatie     = 
			CALCULATE(
			    SUM( 'Journaalregels'[Creditbedrag] )
			    ,'Rubrieken'[Type] = "W"
			    ,NOT ( ISBLANK('NR - CoA mapping DQ'[CoA_code] ) )
			    ,ALL('Kalender standdatums')
			    ,FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			        && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			    )
			) - _credit_eliminatie_Resultaatrekening
			
			VAR _debet_eliminatie_Resultaatrekening = 
			CALCULATE(
			    SUM( 'Eliminatie journaalregels'[Debet] )
			    , 'Eliminatie journaalregels'[Rubriektype] = "W"
			    ,NOT ( ISBLANK('NR - CoA mapping DQ'[CoA_code] ) )
			    ,FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			        && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			    )
			)
			 
			VAR _debet_exploitatie      = 
			CALCULATE(
			    SUM( 'Journaalregels'[Debetbedrag] )
			    , 'Rubrieken'[Type] = "W"
			    ,NOT ( ISBLANK('NR - CoA mapping DQ'[CoA_code]  ) )
			    ,ALL('Kalender standdatums')
			    ,FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			        && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			    )
			)  - _debet_eliminatie_Resultaatrekening
			
			
			VAR _mutatie_eploitatie     = _credit_exploitatie - _debet_exploitatie -- Reguliere mutaties op rubriek--
			
			VAR _subtotaalWaarde =
			    CALCULATE(
			        [Mutatie resultaat met mapping in standmaand LY o.b.v. standdatum]
			        , FILTER(
			            ALL( 'NR - CoA schema' )
			            , 'NR - CoA schema'[Niveau2_sortering] <= MAX( 'NR - CoA schema'[Niveau2_sortering] )
			        )
			    )
			
			VAR result =
			    SWITCH(
			        TRUE
			        ,_is_legeregel,0
			        ,NOT(_is_subtotaal) && _is_geen_omzet,-_mutatie_eploitatie
			        ,NOT(_is_subtotaal),_mutatie_eploitatie
			        ,_correctSubtotalLevel,_subtotaalWaarde
			    )/1000
			    
			    
			RETURN
			    result
			```
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Actual

	measure 'CoA mutatie budget in de standmaand o.b.v. standdatum' = ```
			
			VAR _classification         = SELECTEDVALUE('NR - CoA schema'[Classificatie type])
			VAR _is_subtotaal           = _classification = "Subtotaal"
			VAR _is_geen_omzet          = _classification <> "Omzet" 
			VAR _correctSubtotalLevel   = _is_subtotaal                && ISINSCOPE('NR - CoA schema'[Niveau1]) && NOT(ISINSCOPE('NR - CoA schema'[Niveau2]))
			VAR _is_legeregel           = _classification = "Leeg"    && ISINSCOPE('NR - CoA schema'[Niveau1]) && NOT(ISINSCOPE('NR - CoA schema'[Niveau2]))
			VAR _einddatum_gesecteerde_standmaand = MAX('Kalender standdatums'[Einddatum Maand])
			VAR _begindatum_gesecteerde_standmaand = MIN('Kalender standdatums'[Begindatum Maand])
			 
			VAR _credit_exploitatie     
			= CALCULATE(
			    SUM ('Budget per dag'[Bedrag per dag])
			    ,'Budget per dag'[Debet/Credit] = "C"
			    ,CROSSFILTER ( Rubrieken[RubriekKey], Grootboekrekeningen[RubriekKey], BOTH )
			    ,Rubrieken[Type] = "W"
			    , FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			        && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			    )
			)
			VAR _debet_exploitatie      
			= CALCULATE(
			    SUM ('Budget per dag'[Bedrag per dag])
			    ,'Budget per dag'[Debet/Credit] = "D"
			    ,CROSSFILTER (Rubrieken[RubriekKey], Grootboekrekeningen[RubriekKey],BOTH)
			    ,Rubrieken[Type] = "W"
			    , FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			        && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			    )
			)
			
			VAR _mutatie_eploitatie     
			= _credit_exploitatie - _debet_exploitatie -- Reguliere mutaties op rubriek--
			
			VAR _subtotaalWaarde =
			CALCULATE(
			    [Mutatie budget per dag]
			    , FILTER(
			        ALL( 'NR - CoA schema' )
			        , 'NR - CoA schema'[Niveau2_sortering] <= MAX( 'NR - CoA schema'[Niveau2_sortering] )
			    )
			    , FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			        && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			    )
			)
			
			VAR result =
			    SWITCH(
			        TRUE
			        ,_is_legeregel,0
			        ,NOT(_is_subtotaal) && _is_geen_omzet,-_mutatie_eploitatie
			        ,NOT(_is_subtotaal),_mutatie_eploitatie
			        ,_correctSubtotalLevel,_subtotaalWaarde
			    )/1000
			    
			    
			RETURN
			   result
			```
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Syntess budget

	measure 'CoA mutatie in de standmaand o.b.v. standdatum' = ```
			
			VAR _classification         = SELECTEDVALUE('NR - CoA schema'[Classificatie type])
			VAR _is_subtotaal           = _classification = "Subtotaal"
			VAR _is_geen_omzet          = _classification <> "Omzet" 
			VAR _correctSubtotalLevel   = _is_subtotaal                && ISINSCOPE('NR - CoA schema'[Niveau1]) && NOT(ISINSCOPE('NR - CoA schema'[Niveau2]))
			VAR _is_legeregel           = _classification = "Leeg"    && ISINSCOPE('NR - CoA schema'[Niveau1]) && NOT(ISINSCOPE('NR - CoA schema'[Niveau2]))
			VAR _einddatum_gesecteerde_standmaand = MAX('Kalender standdatums'[Einddatum Maand])
			VAR _begindatum_gesecteerde_standmaand = MIN('Kalender standdatums'[Begindatum Maand])
			
			
			VAR _credit_eliminatie_Resultaatrekening = 
			CALCULATE(
			    SUM( 'Eliminatie journaalregels'[Credit] )
			    , 'Eliminatie journaalregels'[Rubriektype] = "W"
			    ,NOT ( ISBLANK('NR - CoA mapping DQ'[CoA_code] ) )
			    ,FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			        && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			    )
			)
			
			VAR _credit_exploitatie     = 
			CALCULATE(
			    SUM( 'Journaalregels'[Creditbedrag] )
			    ,'Rubrieken'[Type] = "W"
			    ,NOT ( ISBLANK('NR - CoA mapping DQ'[CoA_code]  ) )
			    ,FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			        && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			    )
			) - _credit_eliminatie_Resultaatrekening
			
			
			VAR _debet_eliminatie_Resultaatrekening = 
			CALCULATE(
			    SUM( 'Eliminatie journaalregels'[Debet] )
			    , 'Eliminatie journaalregels'[Rubriektype] = "W"
			    ,NOT ( ISBLANK('NR - CoA mapping DQ'[CoA_code] ) )
			    ,FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			        && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			    )
			)
			 
			VAR _debet_exploitatie      = 
			CALCULATE(
			    SUM( 'Journaalregels'[Debetbedrag] )
			    , 'Rubrieken'[Type] = "W"
			    ,NOT ( ISBLANK('NR - CoA mapping DQ'[CoA_code] ) )
			    ,FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			        && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			    )
			)  - _debet_eliminatie_Resultaatrekening
			
			
			VAR _mutatie_eploitatie     = _credit_exploitatie - _debet_exploitatie -- Reguliere mutaties op rubriek--
			
			VAR _subtotaalWaarde =
			    CALCULATE(
			        [Mutatie resultaat met mapping in standmaand o.b.v. standdatum]
			        , FILTER(
			            ALL( 'NR - CoA schema' )
			            , 'NR - CoA schema'[Niveau2_sortering] <= MAX( 'NR - CoA schema'[Niveau2_sortering] )
			        )
			    )
			
			VAR result =
			    SWITCH(
			        TRUE
			        ,_is_legeregel,0
			        ,NOT(_is_subtotaal) && _is_geen_omzet,-_mutatie_eploitatie
			        ,NOT(_is_subtotaal),_mutatie_eploitatie
			        ,_correctSubtotalLevel,_subtotaalWaarde
			    )/1000
			    
			    
			RETURN
			   result
			```
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Actual

	measure 'CoA YTD rendement budget in standmaand o.b.v. standdatum' = ```
			
			VAR _classification         = SELECTEDVALUE('NR - CoA schema'[Classificatie type])
			VAR _is_subtotaal           = _classification = "Subtotaal"
			VAR _is_omzet               = _classification = "Omzet" 
			VAR _correctSubtotalLevel   = _is_subtotaal               && ISINSCOPE('NR - CoA schema'[Niveau1]) && NOT(ISINSCOPE('NR - CoA schema'[Niveau2]))
			VAR _is_legeregel           = _classification = "Leeg"    && ISINSCOPE('NR - CoA schema'[Niveau1]) && NOT(ISINSCOPE('NR - CoA schema'[Niveau2]))
			 
			VAR _omzetwaarde =
			    CALCULATE(
			        [Mutatie resultaat budget in standmaand o.b.v. standmaand]
			        ,FILTER(
			            ALL( 'NR - CoA schema' )
			            , 'NR - CoA schema'[Classificatie type] = "Omzet"
			        )
			    )
			    
			VAR _subtotaalWaarde =
			    CALCULATE(
			          [Mutatie resultaat budget in standmaand o.b.v. standmaand]
			        , FILTER(
			            ALL( 'NR - CoA schema' )
			            , 'NR - CoA schema'[Niveau2_sortering] <= MAX( 'NR - CoA schema'[Niveau2_sortering] )
			        )
			    )
			
			VAR result =
			    SWITCH(
			        TRUE
			        ,_is_legeregel,BLANK()
			        ,NOT(_is_subtotaal),BLANK()
			        ,_correctSubtotalLevel,DIVIDE( _subtotaalWaarde, _omzetwaarde )
			    )
			    
			    
			RETURN
			   result
			```
		formatString: 0%;-0%;
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Syntess budget

	measure 'CoA YTD rendement in standmaand o.b.v. standdatum' = ```
			
			VAR _classification         = SELECTEDVALUE('NR - CoA schema'[Classificatie type])
			VAR _is_subtotaal           = _classification = "Subtotaal"
			VAR _is_omzet               = _classification = "Omzet" 
			VAR _correctSubtotalLevel   = _is_subtotaal               && ISINSCOPE('NR - CoA schema'[Niveau1]) && NOT(ISINSCOPE('NR - CoA schema'[Niveau2]))
			VAR _is_legeregel           = _classification = "Leeg"    && ISINSCOPE('NR - CoA schema'[Niveau1]) && NOT(ISINSCOPE('NR - CoA schema'[Niveau2]))
			 
			VAR _omzetwaarde =
			    CALCULATE(
			        [Mutatie resultaat in standmaand o.b.v. standdatum]
			        ,FILTER(
			            ALL( 'NR - CoA schema' )
			            , 'NR - CoA schema'[Classificatie type] = "Omzet"
			        )
			    )
			    
			VAR _subtotaalWaarde =
			    CALCULATE(
			        [Mutatie resultaat in standmaand o.b.v. standdatum]
			        , FILTER(
			            ALL( 'NR - CoA schema' )
			            , 'NR - CoA schema'[Niveau2_sortering] <= MAX( 'NR - CoA schema'[Niveau2_sortering] )
			        )
			    )
			
			VAR result =
			    SWITCH(
			        TRUE
			        ,_is_legeregel,BLANK()
			        ,NOT(_is_subtotaal),BLANK()
			        ,_correctSubtotalLevel,DIVIDE( _subtotaalWaarde, _omzetwaarde )
			    )
			    
			    
			RETURN
			   result
			```
		formatString: 0%;-0%;
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Actual

	measure 'Delta standmaand - standmaand LY' = [CoA mutatie in de standmaand o.b.v. standdatum] - [CoA actual LY in standmaand o.b.v. standdatum]
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Actual

	measure 'Mutatie resultaat budget in standmaand o.b.v. standmaand' = ```
			
			var _einddatum_gesecteerde_standmaand = MAX('Kalender standdatums'[Einddatum Maand])
			var _begindatum_gesecteerde_standmaand = MIN('Kalender standdatums'[Begindatum Maand])
			
			VAR _credit = 
			CALCULATE(
			    SUM ('Budget per dag'[Bedrag per dag])
			    ,'Budget per dag'[Debet/Credit] = "C"
			    ,CROSSFILTER (Rubrieken[RubriekKey], Grootboekrekeningen[RubriekKey],BOTH)
			    ,Rubrieken[Type] = "W"
			    ,FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			        && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			    )
			)
			
			VAR _debet = 
			CALCULATE(
			    SUM ('Budget per dag'[Bedrag per dag])
			    ,'Budget per dag'[Debet/Credit] = "D"
			    ,CROSSFILTER (Rubrieken[RubriekKey], Grootboekrekeningen[RubriekKey],BOTH)
			    ,Rubrieken[Type] = "W"
			    ,FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			        && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			    )
			)
			
			VAR result = _credit - _debet
			
			RETURN
			    result
			```
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Syntess budget

	measure 'Mutatie resultaat in standmaand o.b.v. standdatum' = ```
			
			var _einddatum_gesecteerde_standmaand = MAX('Kalender standdatums'[Einddatum Maand])
			var _begindatum_gesecteerde_standmaand = MIN('Kalender standdatums'[Begindatum Maand])
			
			VAR _credit_eliminatie_resultaatrekening =
			CALCULATE(
			    SUM( 'Eliminatie journaalregels'[Credit] )
			    , 'Eliminatie journaalregels'[Rubriektype] = "W"
			    ,FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			        && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			    )
			)    
			
			VAR _credit = 
			CALCULATE(
			    SUM( 'Journaalregels'[Creditbedrag] )
			    ,'Rubrieken'[Type] = "W"
			    ,FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			        && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			    )
			)-_credit_eliminatie_resultaatrekening
			
			  
			VAR _debet_eliminatie_resultaatrekening =
			CALCULATE(
			    SUM( 'Eliminatie journaalregels'[Debet] )
			    , 'Eliminatie journaalregels'[Rubriektype] = "W"
			    ,FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			        && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			    )
			)    
			
			VAR _debet = 
			CALCULATE(
			    SUM( 'Journaalregels'[Debetbedrag] )
			    , 'Rubrieken'[Type] = "W"
			    ,FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			        && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			    )
			)-_debet_eliminatie_resultaatrekening
			
			
			VAR result = _credit - _debet
			
			RETURN
			    result
			```
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Actual

	measure 'Mutatie resultaat LY o.b.v. standdatum' = ```
			
			VAR _einddatum_gesecteerde_standmaand = DATE(YEAR(MAX('Kalender standdatums'[Einddatum Maand]))-1,MONTH(MAX('Kalender standdatums'[Einddatum Maand])),DAY(MAX('Kalender standdatums'[Einddatum Maand])))
			VAR _begindatum_gesecteerde_standmaand = DATE(YEAR(MIN('Kalender standdatums'[Begindatum Maand]))-1,MONTH(MIN('Kalender standdatums'[Begindatum Maand])),DAY(MIN('Kalender standdatums'[Begindatum Maand])))
			
			VAR _credit_eliminatie_resultaatrekening =
			CALCULATE(
			    SUM( 'Eliminatie journaalregels'[Credit] )
			    , 'Eliminatie journaalregels'[Rubriektype] = "W"
			    ,ALL('Kalender standdatums')
			    ,FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			        && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			    )
			)    
			
			VAR _credit = 
			CALCULATE(
			    SUM( 'Journaalregels'[Creditbedrag] )
			    ,'Rubrieken'[Type] = "W"
			    ,ALL('Kalender standdatums')
			    ,FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			        && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			    )
			)-_credit_eliminatie_resultaatrekening
			
			  
			VAR _debet_eliminatie_resultaatrekening =
			CALCULATE(
			    SUM( 'Eliminatie journaalregels'[Debet] )
			    , 'Eliminatie journaalregels'[Rubriektype] = "W"
			    ,ALL('Kalender standdatums')
			    ,FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			        && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			    )
			)    
			
			VAR _debet = 
			CALCULATE(
			    SUM( 'Journaalregels'[Debetbedrag] )
			    , 'Rubrieken'[Type] = "W"
			    ,ALL('Kalender standdatums')
			    ,FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			        && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			    )
			)-_debet_eliminatie_resultaatrekening
			
			
			VAR result = _credit - _debet
			
			RETURN
			    result
			```
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Actual

	measure 'Mutatie resultaat met mapping in standmaand LY o.b.v. standdatum' = ```
			
			var _einddatum_gesecteerde_standmaand = DATE(YEAR(MAX('Kalender standdatums'[Einddatum Maand]))-1,MONTH(MAX('Kalender standdatums'[Einddatum Maand])),DAY(MAX('Kalender standdatums'[Einddatum Maand])))
			var _begindatum_gesecteerde_standmaand = DATE(YEAR(MIN('Kalender standdatums'[Begindatum Maand]))-1,MONTH(MIN('Kalender standdatums'[Begindatum Maand])),DAY(MIN('Kalender standdatums'[Begindatum Maand])))
			
			VAR _credit = 
			CALCULATE(
			    SUM( 'Journaalregels'[Creditbedrag] )
			    ,'Rubrieken'[Type] = "W"
			    ,NOT ( ISBLANK( 'NR - CoA mapping DQ'[CoA_code] ) )
			    ,ALL('Kalender standdatums')
			    ,FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			        && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			    )
			)
			
			VAR _debet = 
			CALCULATE(
			    SUM( 'Journaalregels'[Debetbedrag] )
			    , 'Rubrieken'[Type] = "W"
			    ,NOT ( ISBLANK('NR - CoA mapping DQ'[CoA_code]  ) )
			    ,ALL('Kalender standdatums')
			    ,FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			        && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			    )
			)
			
			
			VAR result = _credit - _debet 
			
			RETURN
			    result
			```
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Actual

	measure 'Mutatie resultaat met mapping in standmaand o.b.v. standdatum' = ```
			
			var _einddatum_gesecteerde_standmaand = MAX('Kalender standdatums'[Einddatum Maand])
			var _begindatum_gesecteerde_standmaand = MIN('Kalender standdatums'[Begindatum Maand])
			
			VAR _credit = 
			CALCULATE(
			    SUM( 'Journaalregels'[Creditbedrag] )
			    ,'Rubrieken'[Type] = "W"
			    ,NOT ( ISBLANK( 'NR - CoA mapping DQ'[CoA_code]  ) )
			    ,FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			        && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			    )
			)
			
			
			VAR _debet = 
			CALCULATE(
			    SUM( 'Journaalregels'[Debetbedrag] )
			    , 'Rubrieken'[Type] = "W"
			    ,NOT ( ISBLANK('NR - CoA mapping DQ'[CoA_code] ) )
			    ,FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			        && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			    )
			)
			
			
			VAR result = _credit  - _debet
			
			RETURN
			    result
			```
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Actual

	measure 'Mutatie resultaat o.b.v. standdatum' = ```
			
			var _einddatum_gesecteerde_standmaand = MAX('Kalender standdatums'[Einddatum Maand])
			var _begindatum_gesecteerde_standmaand = MIN('Kalender standdatums'[Begindatum Maand])
			
			VAR _credit_eliminatie_resultaatrekening =
			CALCULATE(
			    SUM( 'Eliminatie journaalregels'[Credit] )
			    , 'Eliminatie journaalregels'[Rubriektype] = "W"
			    ,FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			        && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			    )
			)    
			
			VAR _credit = 
			CALCULATE(
			    SUM( 'Journaalregels'[Creditbedrag] )
			    ,'Rubrieken'[Type] = "W"
			    ,FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			        && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			    )
			)-_credit_eliminatie_resultaatrekening
			
			  
			VAR _debet_eliminatie_resultaatrekening =
			CALCULATE(
			    SUM( 'Eliminatie journaalregels'[Debet] )
			    , 'Eliminatie journaalregels'[Rubriektype] = "W"
			    ,FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			        && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			    )
			)    
			
			VAR _debet = 
			CALCULATE(
			    SUM( 'Journaalregels'[Debetbedrag] )
			    , 'Rubrieken'[Type] = "W"
			    ,FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			        && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			    )
			)-_debet_eliminatie_resultaatrekening
			
			
			VAR result = _credit - _debet
			
			RETURN
			    result
			```
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Actual

	measure 'Mutatie resultaat YTD LY o.b.v. standdatum' = ```
			
			VAR _einddatum_gesecteerde_standmaand = DATE(YEAR(MAX('Kalender standdatums'[Einddatum Maand]))-1,MONTH(MAX('Kalender standdatums'[Einddatum Maand])),DAY(MAX('Kalender standdatums'[Einddatum Maand])))
			VAR _begindatum_gesecteerde_standmaand = DATE(YEAR(MIN('Kalender standdatums'[Begindatum Maand]))-1,1,1)
			
			VAR _credit_eliminatie_resultaatrekening =
			CALCULATE(
			    SUM( 'Eliminatie journaalregels'[Credit] )
			    , 'Eliminatie journaalregels'[Rubriektype] = "W"
			    ,ALL('Kalender standdatums')
			    ,FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			        && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			    )
			)    
			
			VAR _credit = 
			CALCULATE(
			    SUM( 'Journaalregels'[Creditbedrag] )
			    ,'Rubrieken'[Type] = "W"
			    ,ALL('Kalender standdatums')
			    ,FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			        && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			    )
			)-_credit_eliminatie_resultaatrekening
			
			  
			VAR _debet_eliminatie_resultaatrekening =
			CALCULATE(
			    SUM( 'Eliminatie journaalregels'[Debet] )
			    , 'Eliminatie journaalregels'[Rubriektype] = "W"
			    ,ALL('Kalender standdatums')
			    ,FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			        && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			    )
			)    
			
			VAR _debet = 
			CALCULATE(
			    SUM( 'Journaalregels'[Debetbedrag] )
			    , 'Rubrieken'[Type] = "W"
			    ,ALL('Kalender standdatums')
			    ,FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			        && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			    )
			)-_debet_eliminatie_resultaatrekening
			
			
			VAR result = _credit - _debet
			
			RETURN
			    result
			```
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Actual

	measure 'Mutatie resultaat YTD o.b.v. standdatum' = ```
			
			var _einddatum_gesecteerde_standmaand = MAX('Kalender standdatums'[Einddatum Maand])
			var _begindatum_gesecteerde_standmaand = DATE( YEAR( MIN( 'Kalender standdatums'[Begindatum Maand] ) ), 1, 1 )
			
			VAR _credit_eliminatie_resultaatrekening =
			CALCULATE(
			    SUM( 'Eliminatie journaalregels'[Credit] )
			    , 'Eliminatie journaalregels'[Rubriektype] = "W"
			    ,FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			        && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			    )
			)    
			
			VAR _credit = 
			CALCULATE(
			    SUM( 'Journaalregels'[Creditbedrag] )
			    ,'Rubrieken'[Type] = "W"
			    ,FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			        && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			    )
			)-_credit_eliminatie_resultaatrekening
			
			  
			VAR _debet_eliminatie_resultaatrekening =
			CALCULATE(
			    SUM( 'Eliminatie journaalregels'[Debet] )
			    , 'Eliminatie journaalregels'[Rubriektype] = "W"
			    ,FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			        && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			    )
			)    
			
			VAR _debet = 
			CALCULATE(
			    SUM( 'Journaalregels'[Debetbedrag] )
			    , 'Rubrieken'[Type] = "W"
			    ,FILTER(
			        ALL( Kalender )
			        , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			        && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			    )
			)-_debet_eliminatie_resultaatrekening
			
			
			VAR result = _credit - _debet
			
			RETURN
			    result
			```
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Actual

	measure Kolombreedte7 = "1234567"
		displayFolder: 1. Semantisch model\1.99 Overig\Algemeen

	measure Kolombreedte6 = "123456"
		displayFolder: 1. Semantisch model\1.99 Overig\Algemeen

	measure Kolombreedte8 = "12345678"
		displayFolder: 1. Semantisch model\1.99 Overig\Algemeen

	measure Kolombreedte9 = "123456789"
		displayFolder: 1. Semantisch model\1.99 Overig\Algemeen

	measure Kolombreedte5 = "12345"
		displayFolder: 1. Semantisch model\1.99 Overig\Algemeen

	measure 'CoA mutatie notifica budget' = ```
			
			VAR _classification         = SELECTEDVALUE('NR - CoA schema'[Classificatie type])
			VAR _is_subtotaal           = _classification = "Subtotaal"
			VAR _is_geen_omzet          = _classification <> "Omzet" 
			VAR _correctSubtotalLevel   = _is_subtotaal                && ISINSCOPE('NR - CoA schema'[Niveau1]) && NOT(ISINSCOPE('NR - CoA schema'[Niveau2]))
			VAR _is_legeregel           = _classification = "Leeg"    && ISINSCOPE('NR - CoA schema'[Niveau1]) && NOT(ISINSCOPE('NR - CoA schema'[Niveau2]))
			 
			VAR _budget    
			= CALCULATE(
			    SUM ('NR - Budgetregels DQ'[waarde])
			    ,Rubrieken[Type] = "W"
			)
			
			
			VAR _subtotaalWaarde =
			    CALCULATE(
			        [Mutatie budget (notifica)]
			        , FILTER(
			            ALL( 'NR - CoA schema' )
			            , 'NR - CoA schema'[Niveau2_sortering] <= MAX( 'NR - CoA schema'[Niveau2_sortering] )
			        )
			    )
			
			VAR result =
			    SWITCH(
			        TRUE
			        ,_is_legeregel,0
			        ,NOT(_is_subtotaal) && _is_geen_omzet,_budget*-1
			        ,NOT(_is_subtotaal),_budget
			        ,_correctSubtotalLevel,_subtotaalWaarde
			    )/1000
			    
			    
			RETURN
			   result
			```
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Notifica budget

	measure 'CoA YTD rendement notifica budget in standmaand o.b.v. standdatum' = ```
			
			VAR _classification         = SELECTEDVALUE('NR - CoA schema'[Classificatie type])
			VAR _is_subtotaal           = _classification = "Subtotaal"
			VAR _is_omzet               = _classification = "Omzet" 
			VAR _correctSubtotalLevel   = _is_subtotaal               && ISINSCOPE('NR - CoA schema'[Niveau1]) && NOT(ISINSCOPE('NR - CoA schema'[Niveau2]))
			VAR _is_legeregel           = _classification = "Leeg"    && ISINSCOPE('NR - CoA schema'[Niveau1]) && NOT(ISINSCOPE('NR - CoA schema'[Niveau2]))
			VAR _einddatum_gesecteerde_standmaand = MAX('Kalender standdatums'[Einddatum Maand])
			VAR _begindatum_gesecteerde_standmaand = MIN('Kalender standdatums'[Begindatum Maand])
			 
			VAR _omzetwaarde =
			    CALCULATE(
			        [Mutatie resultaat notifica budget]
			        ,FILTER(
			            ALL( 'NR - CoA schema' )
			            , 'NR - CoA schema'[Classificatie type] = "Omzet"
			        )
			        , FILTER(
			            ALL( Kalender )
			            , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			            && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			        )
			    )
			    
			VAR _subtotaalWaarde =
			    CALCULATE(
			       [Mutatie resultaat notifica budget]
			        , FILTER(
			            ALL( 'NR - CoA schema' )
			            , 'NR - CoA schema'[Niveau2_sortering] <= MAX( 'NR - CoA schema'[Niveau2_sortering] )
			        )
			        , FILTER(
			            ALL( Kalender )
			            , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			            && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			        )
			    )
			
			VAR result =
			    SWITCH(
			        TRUE
			        ,_is_legeregel,BLANK()
			        ,NOT(_is_subtotaal),BLANK()
			        ,_correctSubtotalLevel,DIVIDE( _subtotaalWaarde, _omzetwaarde )
			    )
			    
			    
			RETURN
			   result
			```
		formatString: 0%;-0%;
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Notifica budget

	measure 'CoA Forecast mutatie in de standmaand o.b.v. standdatum' = ```
			
			VAR _classification         = SELECTEDVALUE('NR - CoA schema'[Classificatie type])
			VAR _is_subtotaal           = _classification = "Subtotaal"
			VAR _is_geen_omzet          = _classification <> "Omzet" 
			VAR _correctSubtotalLevel   = _is_subtotaal                && ISINSCOPE('NR - CoA schema'[Niveau1]) && NOT(ISINSCOPE('NR - CoA schema'[Niveau2]))
			VAR _is_legeregel           = _classification = "Leeg"    && ISINSCOPE('NR - CoA schema'[Niveau1]) && NOT(ISINSCOPE('NR - CoA schema'[Niveau2]))
			VAR _einddatum_gesecteerde_standmaand = MAX('Kalender standdatums'[Einddatum Maand])
			VAR _begindatum_gesecteerde_standmaand = MIN('Kalender standdatums'[Begindatum Maand])
			 
			VAR _mutatie_forecast     = sum('NR - Resultaatrekening forecastregels DQ'[Waarde])
			//VAR _mutatie_forecast     = sum(Forecast[Value])*max('NR - CoA schema'[Teken])
			//VAR _mutatie_forecast     = sum(Forecast[Value])*-1
			
			
			VAR _subtotaalWaarde =
			    CALCULATE(
			        sum('NR - Resultaatrekening forecastregels DQ'[Waarde])
			        , FILTER(
			            ALL( 'NR - CoA schema' )
			            , 'NR - CoA schema'[Niveau2_sortering] <= MAX( 'NR - CoA schema'[Niveau2_sortering] )
			        )
			        , FILTER(
			            ALL( Kalender )
			                , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			                && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			        )
			    )
			
			VAR result =
			    SWITCH(
			        TRUE
			        ,_is_legeregel,0
			        ,NOT(_is_subtotaal) && _is_geen_omzet,-_mutatie_forecast
			        ,NOT(_is_subtotaal),_mutatie_forecast
			        ,_correctSubtotalLevel,_subtotaalWaarde
			    )/1000
			    
			    
			RETURN
			  result
			```
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Forecast

	measure 'CoA YTD rendement notifica forecast in standmaand o.b.v. standdatum' = ```
			
			VAR _classification         = SELECTEDVALUE('NR - CoA schema'[Classificatie type])
			VAR _is_subtotaal           = _classification = "Subtotaal"
			VAR _is_omzet               = _classification = "Omzet" 
			VAR _correctSubtotalLevel   = _is_subtotaal               && ISINSCOPE('NR - CoA schema'[Niveau1]) && NOT(ISINSCOPE('NR - CoA schema'[Niveau2]))
			VAR _is_legeregel           = _classification = "Leeg"    && ISINSCOPE('NR - CoA schema'[Niveau1]) && NOT(ISINSCOPE('NR - CoA schema'[Niveau2]))
			VAR _einddatum_gesecteerde_standmaand = MAX('Kalender standdatums'[Einddatum Maand])
			VAR _begindatum_gesecteerde_standmaand = MIN('Kalender standdatums'[Begindatum Maand])
			 
			VAR _omzetwaarde =
			    CALCULATE(
			        [Mutatie resultaat notifica forecast]
			        ,FILTER(
			            ALL( 'NR - CoA schema' )
			            , 'NR - CoA schema'[Classificatie type] = "Omzet"
			        )
			        , FILTER(
			            ALL( Kalender )
			            , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			            && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			        )
			    )
			    
			VAR _subtotaalWaarde =
			    CALCULATE(
			       [Mutatie resultaat notifica forecast]
			        , FILTER(
			            ALL( 'NR - CoA schema' )
			            , 'NR - CoA schema'[Niveau2_sortering] <= MAX( 'NR - CoA schema'[Niveau2_sortering] )
			        )
			        , FILTER(
			            ALL( Kalender )
			            , Kalender[Datum] >= _begindatum_gesecteerde_standmaand
			            && Kalender[Datum] <= _einddatum_gesecteerde_standmaand
			        )
			    )
			
			VAR result =
			    SWITCH(
			        TRUE
			        ,_is_legeregel,BLANK()
			        ,NOT(_is_subtotaal),BLANK()
			        ,_correctSubtotalLevel,DIVIDE( _subtotaalWaarde, _omzetwaarde )
			    )
			    
			    
			RETURN
			   result
			```
		formatString: 0%;-0%;
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Forecast

	measure 'Mutatie resultaat notifica forecast' =
			
			var result = SUM ('NR - Resultaatrekening forecastregels DQ'[waarde])
			
			return
			    result
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Forecast

	measure 'Melding geselecteerd boekjaar' = "Boekjaar: "&MAX(Kalender[Jaar])
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Algemeen

	measure 'Melding stand balans per einde standdatum' =
			
			"Balansstand per: "
			&FORMAT(MAX('Kalender standdatums'[Einddatum Maand]),"dd-mm-yyyy")
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Algemeen

	measure 'Montage uren incl inleen via inkoop cumulatief' = [Montage uren cumulatief]+[inleen via inkoop cumulatief]
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Montage uren incl inleen via inkoop' = [Montage uren]+[inleen via inkoop]
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Bruto rendement YTD (benchmark schema o.b.v. standdatum)' = Divide([Brutowinst YTD (benchmark schema o.b.v. standdatum)],[Omzet YTD (benchmark schema o.b.v. standdatum)])
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Resultaat topsheet

	measure 'Bruto rendement YTDLY (benchmark schema o.b.v. standdatum)' = Divide([Brutowinst YTDLY (benchmark schema o.b.v. standdatum)],[Omzet YTDLY (benchmark schema o.b.v. standdatum)])
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Resultaat topsheet

	measure 'Brutowinst YTD (benchmark schema o.b.v. standdatum)' = [Omzet YTD (benchmark schema o.b.v. standdatum)]-[Directe kosten YTD (benchmark schema o.b.v. standdatum)]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Resultaat topsheet

	measure 'Brutowinst YTDLY (benchmark schema o.b.v. standdatum)' = [Omzet YTDLY (benchmark schema o.b.v. standdatum)]-[Directe kosten YTDLY (benchmark schema o.b.v. standdatum)]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Resultaat topsheet

	/// Directe kosten cumulatief tot einde geselecteerde einddatum.
	measure 'Directe kosten (benchmark schema o.b.v. standdatum)' =
			
			CALCULATE(
			    [Mutatie resultaat in standmaand o.b.v. standdatum]*-1
			    ,'NR - CoA schema'[Niveau1] = "Directe kosten"
			
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Resultaat topsheet

	measure 'Directe kosten t/m standdatum (benchmark schema)' =
			
			CALCULATE(
			    [Mutatie resultaat]*-1
			    ,'NR - CoA schema'[Niveau1] = "Directe kosten"
			    ,Kalender[Maand index]<=MAX('Kalender standdatums'[Maand index])
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Resultaat topsheet

	/// Directe kosten cumulatief tot einde geselecteerde einddatum.
	measure 'Directe kosten YTD (benchmark schema o.b.v. standdatum)' =
			
			CALCULATE(
			    [Mutatie resultaat YTD o.b.v. standdatum]*-1
			    ,'NR - CoA schema'[Niveau1] = "Directe kosten"
			
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Resultaat topsheet

	/// Zie [Directe kosten YTD]. Betreft directe kosten cumulaief over dezelfde periode vorig jaar.
	measure 'Directe kosten YTDLY (benchmark schema o.b.v. standdatum)' =
			
			CALCULATE(
			    [Mutatie resultaat YTD LY o.b.v. standdatum]*-1
			    ,'NR - CoA schema'[Niveau1] = "Directe kosten"
			
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Resultaat topsheet

	measure 'Indirecte kosten t/m standdatum (benchmark schema)' =
			
			CALCULATE(
			    [Mutatie resultaat]*-1
			    ,NOT ( 'NR - CoA schema'[Niveau1] )  IN  { "Directe kosten", "omzet" }
			    ,Kalender[Maand index]<=MAX('Kalender standdatums'[Maand index])
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Resultaat topsheet

	measure 'Indirecte kosten YTD (benchmark schema o.b.v. standdatum)' =
			
			CALCULATE(
			    [Mutatie resultaat YTD o.b.v. standdatum]*-1
			    ,NOT ( 'NR - CoA schema'[Niveau1] )  IN  { "Directe kosten", "omzet" }
			
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Resultaat topsheet

	measure 'Indirecte kosten YTDLY (benchmark schema o.b.v. standdatum)' =
			
			CALCULATE(
			    [Mutatie resultaat YTD LY o.b.v. standdatum]*-1
			    ,NOT ( 'NR - CoA schema'[Niveau1] )  IN  { "Directe kosten", "omzet" }
			
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Resultaat topsheet

	measure 'Netto rendement YTD (benchmark schema o.b.v. standdatum)' = divide([Nettowinst YTD (benchmark schema o.b.v. standdatum)],[Omzet YTD (benchmark schema o.b.v. standdatum)])
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Resultaat topsheet

	measure 'Netto rendement YTDLY (benchmark schema o.b.v. standdatum)' = divide([Nettowinst YTDLY (benchmark schema o.b.v. standdatum)],[Omzet YTDLY (benchmark schema o.b.v. standdatum)])
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Resultaat topsheet

	measure 'Nettowinst YTD (benchmark schema o.b.v. standdatum)' =
			
			[Omzet YTD (benchmark schema o.b.v. standdatum)]
			- [Directe kosten YTD (benchmark schema o.b.v. standdatum)]
			- [Indirecte kosten YTD (benchmark schema o.b.v. standdatum)]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Resultaat topsheet

	measure 'Nettowinst YTDLY (benchmark schema o.b.v. standdatum)' =
			
			[Omzet YTDLY (benchmark schema o.b.v. standdatum)]
			- [Directe kosten YTDLY (benchmark schema o.b.v. standdatum)]
			- [Indirecte kosten YTDLY (benchmark schema o.b.v. standdatum)]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Resultaat topsheet

	measure 'Omzet YTD (benchmark schema o.b.v. standdatum)' =
			
			CALCULATE(
			    [Mutatie resultaat YTD o.b.v. standdatum]
			    ,'NR - CoA schema'[Niveau1] = "Omzet"
			
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Resultaat topsheet

	measure 'Omzet YTDLY (benchmark schema o.b.v. standdatum)' =
			
			CALCULATE(
			    [Mutatie resultaat YTD LY o.b.v. standdatum]
			    ,'NR - CoA schema'[Niveau1] = "Omzet"
			
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Resultaat topsheet

	measure 'Aantal uren werkbonparagraaf o.b.v. boekdatum urenregel' =
			CALCULATE(
			    SUM('Werkbonparagraaf kosten en geboekte uren'[Aantal])
			    ,'Werkbonparagraaf kosten en geboekte uren'[Arbeidregel Ja/Nee] = "Ja"
			)
		formatString: #,##0
		displayFolder: 2. Rapport Specifieke Objecten\2.04 Best practice Service\Onderhoudsplanning

	measure 'Aantal uren werkbonparagraaf o.b.v. boekdatum werkbon' =
			CALCULATE(
			    SUM('Werkbonparagraaf kosten en geboekte uren'[Aantal])
			    ,'Werkbonparagraaf kosten en geboekte uren'[Arbeidregel Ja/Nee] = "Ja"
			    ,USERELATIONSHIP(Kalender[Datum],Werkbonnen[Hoofdwerkbon boekdatum])
			)
		formatString: #,##0
		displayFolder: 2. Rapport Specifieke Objecten\2.04 Best practice Service\Onderhoudsplanning

	measure 'onderhoud en storing % van totaal' = ```
			var _onderhoudsuren =
			    CALCULATE(
			        [Aantal uren werkbonparagraaf o.b.v. boekdatum urenregel]
			        ,Werkbonparagrafen[Type] = "Onderhoud en Storing"
			    )
			return 
			    DIVIDE(_onderhoudsuren,[Aantal uren werkbonparagraaf o.b.v. boekdatum urenregel])
			```
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.04 Best practice Service\Onderhoudsplanning

	column NietGebruiken
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: NietGebruiken

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Formules-f526b6c0-4018-4c9c-9db9-d23bb25b68ec = m
		mode: import
		queryGroup: Algemeen
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [NietGebruiken = _t])
				in
				    Source

	annotation PBI_Id = 26fd8aea-f504-4cfc-bb0c-22d0ce2945ae

	annotation LinkedQueryName = Formules

	annotation PBI_QueryRelationships = {"columnCount":0,"keyColumnNames":[],"queryRelationships":[],"columnIdentities":[],"ColumnCount":0,"KeyColumnNames":[],"ColumnIdentities":[],"RelationshipInfo":[]}

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

