table 'Methode WvB'

	column Methode
		dataType: string
		summarizeBy: none
		sourceColumn: Methode

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: string
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	partition 'Methode WvB' = m
		mode: import
		queryGroup: Methodes
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCi9zUihILEpML0pMTFPSUTJUitWJVnJPzc1MSUnNSUlVACkoycxKAcoZKcXGAgA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Methode = _t, ID = _t])
				in
				    Source

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

