table 'Methode budgetomzet'

	column ID
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Omschrijving
		dataType: string
		summarizeBy: none
		sourceColumn: Omschrijving

		annotation SummarizationSetBy = Automatic

	partition 'Methode budgetomzet' = m
		mode: import
		queryGroup: Methodes
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUTLUU/AvSkktSkpNKUpMV4rViVYyAgob6Sk4J+Ykl+YklmSmKpSlFmXn5xcUFGVmFSvFxgIA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ID = _t, Omschrijving = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ID", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

