table 'Methode resultaat bepaling'

	column ID
		dataType: string
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Omschrijving
		dataType: string
		summarizeBy: none
		sourceColumn: Omschrijving

		annotation SummarizationSetBy = Automatic

	partition 'Methode resultaat bepaling' = m
		mode: import
		queryGroup: Methodes
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUQouScxLSUwsSlGK1YlWMgKKOKXmJWfkJhZlKxQnZ6TmJirFxgIA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ID = _t, Omschrijving = _t])
				in
				    Source

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

