table 'Methode omzet TWC'

	column ID
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Omschrijving
		dataType: string
		summarizeBy: none
		sourceColumn: Omschrijving

		annotation SummarizationSetBy = Automatic

	partition 'Methode omzet TWC' = m
		mode: import
		queryGroup: Methodes
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("HcpBCoMwEAXQqwyzlpToEXqACl0GF9F8RI2ZMCaF3t7g9vGcY8sdW0MfDdAZQf3KU+e4b9wbevu41OjLBvpBD5GcdduvpwytDIZGlR1LmWtYUV6Skz9Bp4QaQd9/Krhan24=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ID = _t, Omschrijving = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ID", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

