table 'NR - CoA schema'

	column Code
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: Code

		annotation SummarizationSetBy = Automatic

	column Niveau1
		dataType: string
		summarizeBy: none
		sourceColumn: Niveau1
		sortByColumn: Niveau1_sortering

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Niveau2
		dataType: string
		summarizeBy: none
		sourceColumn: Niveau2
		sortByColumn: Code

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Niveau1_sortering
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: Niveau1_sortering

		annotation SummarizationSetBy = Automatic

	column Niveau2_sortering
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: Niveau2_sortering

		annotation SummarizationSetBy = Automatic

	column 'Classificatie type'
		dataType: string
		summarizeBy: none
		sourceColumn: Classificatie type

		annotation SummarizationSetBy = Automatic

	column 'Rapportage type'
		dataType: string
		summarizeBy: none
		sourceColumn: Rapportage type

		annotation SummarizationSetBy = Automatic

	column Teken
		dataType: string
		summarizeBy: none
		sourceColumn: Teken

		annotation SummarizationSetBy = Automatic

	partition 'NR - CoA schema' = m
		mode: import
		queryGroup: NotificaRAAS
		source =
				let
				    Source = Sql.Database(#"7_serverAppdata", #"8_databaseAppdata"),
				    #"RAAS_CoA schema" = Source{[Schema="RAAS",Item="CoA schema"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(#"RAAS_CoA schema",{{"Niveau1_sortering", Int64.Type}, {"Niveau2_sortering", Int64.Type}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([Classificatie type] <> "Leeg"))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

