# --- Notifica AI Chat: START (PS 5.1 safe; no $args; fixed child launcher) ---
[CmdletBinding()]
param(
  [string]$ProjectDir   = "C:\Projects\DataNavigator\ai_chat",
  [string]$VenvActivate = "C:\Projects\DataNavigator\venv\Scripts\Activate.ps1",
  [string]$EnvFile      = "C:\Projects\DataNavigator\ai_chat\.env.dev",

  [string]$BindAddress  = "0.0.0.0",
  [int]$Port            = 8000,

  [switch]$Https,
  [string]$CertFile     = "C:\Projects\DataNavigator\ai_chat\ssl\notifica-local.pem",
  [string]$KeyFile      = "C:\Projects\DataNavigator\ai_chat\ssl\notifica-local-key.pem",

  [switch]$InPlace,
  [switch]$NoOpenBrowser
)

# --- Validatie ---
if (-not (Test-Path $ProjectDir)) { Write-Host "[ERROR] ProjectDir niet gevonden: $ProjectDir" -ForegroundColor Red; exit 1 }
if (-not (Test-Path (Join-Path $ProjectDir 'app.py'))) { Write-Host "[ERROR] app.py niet gevonden in $ProjectDir" -ForegroundColor Red; exit 1 }
if (-not (Test-Path $VenvActivate)) { Write-Host "[ERROR] venv Activate.ps1 niet gevonden: $VenvActivate" -ForegroundColor Red; exit 1 }

$PythonExe = Join-Path (Split-Path $VenvActivate -Parent) "python.exe"
if (-not (Test-Path $PythonExe)) { Write-Host "[ERROR] venv python.exe niet gevonden: $PythonExe" -ForegroundColor Red; exit 1 }

# --- ENV_FILE doorgeven ---
if (Test-Path $EnvFile) {
  $env:ENV_FILE = (Resolve-Path $EnvFile).Path
  Write-Host ("ENV_FILE -> {0}" -f $env:ENV_FILE) -ForegroundColor DarkGray
} else {
  Remove-Item Env:\ENV_FILE -ErrorAction SilentlyContinue
  Write-Host "ENV_FILE niet gevonden; start zonder expliciet .env" -ForegroundColor Yellow
}

# --- TLS / Poort ---
$scheme = "http"
if ($Https) {
  $scheme = "https"
  if ($Port -eq 8000) { $Port = 8443 }
  if (-not (Test-Path $CertFile)) { Write-Host "[ERROR] CertFile niet gevonden: $CertFile" -ForegroundColor Red; exit 1 }
  if (-not (Test-Path $KeyFile))  { Write-Host "[ERROR] KeyFile niet gevonden:  $KeyFile"  -ForegroundColor Red; exit 1 }
}
$url = ("{0}://localhost:{1}" -f $scheme, $Port)

# --- InPlace (debug in huidig venster) ---
if ($InPlace) {
  Set-Location $ProjectDir
  . $VenvActivate
  $env:PYTHONPATH = ""
  try { $host.UI.RawUI.WindowTitle = "Notifica AI Chat ($scheme $Port)" } catch {}

  $uvArgs = @("-m","uvicorn","app:app","--host",$BindAddress,"--port",$Port.ToString())
  if ($Https) { $uvArgs += @("--ssl-certfile",$CertFile,"--ssl-keyfile",$KeyFile) }
  $uvArgs += "--reload"

  Write-Host ("Starting Notifica AI Chat op {0} ..." -f $url) -ForegroundColor Cyan
  Write-Host ("Exe:  {0}" -f $PythonExe) -ForegroundColor DarkGray
  Write-Host ("Args: {0}" -f ($uvArgs -join ' ')) -ForegroundColor DarkGray
  & $PythonExe @uvArgs
  exit $LASTEXITCODE
}

# --- Child PowerShell launcher (blijft open) ---
$tmpLauncher = Join-Path $env:TEMP "Run-NotificaAIChat-Launch.ps1"
$useHttpsLiteral = if ($Https) { '$true' } else { '$false' }

$launcher = @"
# Auto-generated by Start-NotificaAIChat.ps1
Set-Location '$ProjectDir'
. '$VenvActivate'
`$env:ENV_FILE = '$($env:ENV_FILE)'
`$env:PYTHONPATH = ''
try { `$host.UI.RawUI.WindowTitle = 'Notifica AI Chat ($scheme $Port)' } catch {}

`$PythonExe   = '$PythonExe'
`$BindAddress = '$BindAddress'
`$Port        = $Port
`$UseHttps    = $useHttpsLiteral
`$CertFile    = '$CertFile'
`$KeyFile     = '$KeyFile'

`$uvArgs = @('-m','uvicorn','app:app','--host',`$BindAddress,'--port',(`$Port.ToString()))
if (`$UseHttps) {
  `$uvArgs += @('--ssl-certfile',`$CertFile,'--ssl-keyfile',`$KeyFile)
}
`$uvArgs += '--reload'

Write-Host ('Exe:  {0}' -f `$PythonExe) -ForegroundColor DarkGray
Write-Host ('Args: {0}' -f (`$uvArgs -join ' ')) -ForegroundColor DarkGray
Write-Host ('Starting Notifica AI Chat op {0}://localhost:{1} ...' -f '$scheme', `$Port) -ForegroundColor Cyan

# Start zonder splatting-gedoe; houdt venster open en toont output
Start-Process -FilePath `$PythonExe -ArgumentList `$uvArgs -NoNewWindow
"@

Set-Content -Path $tmpLauncher -Value $launcher -Encoding UTF8

Start-Process -FilePath "powershell.exe" -ArgumentList @(
  "-NoLogo","-NoProfile","-ExecutionPolicy","Bypass","-NoExit",
  "-File",$tmpLauncher
) -WorkingDirectory $ProjectDir

Start-Sleep -Seconds 2
if (-not $NoOpenBrowser) { Start-Process $url }

